Repository moonbeam-foundation/moonbeam, pull requests merged in 2020-12, with the labels that each got.

#132 Adds test for polkadot transfer
  tests/package-lock.json
  tests/package.json
  tests/tests/test-balance.ts
Labels: A0-pleasereview, B0-silent, C1-low

#134 Remove unused longest chain rule from parachain node
  node/parachain/src/service.rs
Labels: A6-seemsok, C1-low

#135 Adds support for moon-key binary
  tools/moon-key.ts
  tools/package-lock.json
  tools/package.json
Labels: A0-pleasereview, B0-silent, C1-low, I5-documentation 📄

#102 Update to Substrate master and Parachains V1
  Cargo.lock
  docker/polkadot-relay.Dockerfile
  launch-notes.md
  node/parachain/Cargo.toml
  node/parachain/src/cli.rs
  node/parachain/src/command.rs
  node/parachain/src/service.rs
  node/rpc/Cargo.toml
  node/rpc/src/lib.rs
  node/rpc/src/pubsub_hotfixes.rs
  node/rpc/src/server_hotfixes.rs
  node/standalone/Cargo.lock
  node/standalone/Cargo.toml
  node/standalone/src/command.rs
  node/standalone/src/service.rs
  pallets/ethereum-chain-id/Cargo.toml
  pallets/ethereum-chain-id/src/lib.rs
  pallets/mb-core/Cargo.toml
  pallets/mb-session/Cargo.toml
  pallets/parachain-info/Cargo.toml
  pallets/parachain-info/src/lib.rs
  pallets/token-dealer/Cargo.toml
  polkadot-js/alphanet-relay-types.json
  polkadot-js/alphanet-types.json
  polkadot-js/standalone-types.json
  runtime/Cargo.toml
  runtime/account/Cargo.toml
  runtime/build.rs
  runtime/precompiles/Cargo.toml
  runtime/precompiles/src/lib.rs
  runtime/src/lib.rs
  runtime/src/parachain.rs
  runtime/src/standalone.rs
  rust-toolchain
  scripts/README.md
  scripts/build-alphanet-relay-image.sh
  scripts/generate-relay-specs.sh
  scripts/register-alphanet-parachain.sh
  scripts/run-alphanet-relay.sh
  specs/rococo-alphanet-specs-template.json
  tests/tests/test-block.ts
  tests/tests/test-revert-receipt.ts
  tests/tests/test-subscription.ts
Labels: A6-seemsok, B7-runtimenoteworthy, C7-high

#124 Security testing: block limits and infinite loop
  tests/package.json
  tests/tests/constants/index.ts
  tests/tests/constants/testContracts.ts
  tests/tests/constants/transactionConfigs.ts
  tests/tests/test-balance.ts
  tests/tests/test-block.ts
  tests/tests/test-contract-loops.ts
  tests/tests/test-contract-methods.ts
  tests/tests/test-contract-precompiled.ts
  tests/tests/test-contract.ts
  tests/tests/test-existential-deposit.ts
  tests/tests/test-gas.ts
  tests/tests/test-nonce.ts
  tests/tests/test-precompiles.ts
  tests/tests/test-revert-receipt.ts
  tests/tests/test-subscription.ts
  tests/tests/util/fillBlockWithTx.ts
  tests/tests/util/index.ts
  tests/tests/util/polkadotApiRequests.ts
  tests/tests/util/testWithMoonbeam.ts
  tests/tests/util/web3Requests.ts
Labels: A6-seemsok, B0-silent, C1-low

#149 Update Cumulus and friends
  Cargo.lock
  node/parachain/src/chain_spec.rs
  node/parachain/src/command.rs
  node/parachain/src/service.rs
  node/standalone/Cargo.lock
  runtime/precompiles/src/lib.rs
  runtime/src/lib.rs
  runtime/src/parachain.rs
  runtime/src/standalone.rs
  specs/rococo-alphanet-specs-template.json
  tests/package-lock.json
  tests/package.json
  tests/tests/test-web3api.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low, dependencies
