Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-01, with the labels that each got.

#153 Antoine clean tests
  tests/README.md
  tests/package.json
  tests/tests/util/fillBlockWithTx.ts
  tests/tests/util/testWithMoonbeam.ts
Labels: A0-pleasereview, B0-silent, C1-low

#150 Create moonbeam-types-bundle npm package and added it to tests
  moonbeam-types-bundle/.gitignore
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
  moonbeam-types-bundle/tsconfig.json
  tests/package-lock.json
  tests/package.json
  tests/tests/util/testWithMoonbeam.ts
Labels: A0-pleasereview, B0-silent, C1-low

#161 Clean .gitignore
  .gitignore
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#164 Remove unused file
  runtime/account/src/signer.rs
Labels: A0-pleasereview, B0-silent, C1-low

#165 Runtime requires <= 1/2 second block execution.
  runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium

#163 De-alias dependencies
  Cargo.lock
  node/parachain/Cargo.toml
  node/parachain/src/command.rs
  node/parachain/src/service.rs
  node/rpc/Cargo.toml
  node/rpc/src/lib.rs
  node/rpc/src/pubsub_hotfixes.rs
  node/rpc/src/server_hotfixes.rs
  node/standalone/Cargo.lock
  node/standalone/Cargo.toml
  node/standalone/src/service.rs
  pallets/ethereum-chain-id/Cargo.toml
  pallets/parachain-info/Cargo.toml
  runtime/Cargo.toml
  runtime/account/Cargo.toml
  runtime/account/src/lib.rs
  runtime/src/lib.rs
  runtime/src/parachain.rs
  runtime/src/standalone.rs
  tests/tests/test-web3api.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low

#173 test staking
  Cargo.lock
  Cargo.toml
  moonbeam-types-bundle/package-lock.json
  node/parachain/Cargo.toml
  node/parachain/src/chain_spec.rs
  node/parachain/src/cli.rs
  node/parachain/src/command.rs
  node/parachain/src/service.rs
  node/standalone/Cargo.lock
  node/standalone/Cargo.toml
  node/standalone/src/chain_spec.rs
  node/standalone/src/cli.rs
  node/standalone/src/command.rs
  node/standalone/src/service.rs
  pallets/author-inherent/Cargo.toml
  pallets/author-inherent/src/lib.rs
  pallets/stake/Cargo.toml
  pallets/stake/src/lib.rs
  pallets/stake/src/mock.rs
  pallets/stake/src/tests.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachain.rs
  runtime/src/standalone.rs
  tests/moonbeam-test-specs/templates/simple-specs-template.json
  tests/tests/test-balance.ts
  tests/tests/test-stake.ts
  tests/tests/util/fillBlockWithTx.ts
  tests/tests/util/testWithMoonbeam.ts
Labels: A0-pleasereview

#171 txpool module support
  Cargo.lock
  Cargo.toml
  client/rpc-core/txpool/Cargo.toml
  client/rpc-core/txpool/src/lib.rs
  client/rpc-core/txpool/src/types/content.rs
  client/rpc-core/txpool/src/types/inspect.rs
  client/rpc-core/txpool/src/types/mod.rs
  client/rpc/txpool/Cargo.toml
  client/rpc/txpool/src/lib.rs
  node/rpc/Cargo.toml
  node/rpc/src/lib.rs
  node/standalone/Cargo.lock
  primitives/rpc/txpool/Cargo.toml
  primitives/rpc/txpool/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachain.rs
  runtime/src/standalone.rs
  tests/tests/constants/testContracts.ts
  tests/tests/test-txpool.ts
Labels: A0-pleasereview, B3-apinoteworthy

#188 Only require author id on CLI when node is authoring
  Cargo.lock
  node/parachain/src/cli.rs
  node/parachain/src/command.rs
  node/parachain/src/service.rs
  node/standalone/src/cli.rs
  node/standalone/src/command.rs
  node/standalone/src/service.rs
  scripts/run-alphanet-parachain.sh
  scripts/run-moonbase-standalone.sh
  tests/tests/util/testWithMoonbeam.ts
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium

#216 Prune irrelevant block gas limit adjustment tests.
  tests/tests/test-gas.ts
Labels: A0-pleasereview, B0-silent, C1-low

#214 Remove redundant author requirement
  Cargo.lock
  pallets/author-inherent/Cargo.toml
  pallets/author-inherent/src/lib.rs
  runtime/src/parachain.rs
  runtime/src/standalone.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low
