Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-12, with the labels that each got.

#1034 Add proxy tests ts balance author mapping
  moonbeam-types-bundle/index.ts
  tests/package.json
  tests/tests/test-proxy.ts
  tests/tests/test-proxy/test-proxy-author-mapping.ts
  tests/tests/test-proxy/test-proxy-balance.ts
  tests/tests/test-proxy/test-proxy-governance.ts
  tests/tests/test-proxy/test-proxy.ts
  tests/util/balances.ts
  tests/util/constants.ts
  tests/util/transactions.ts
Labels: A0-pleasereview, B0-silent, C1-low

#1041 Enable force default xcm version in polkadotXcm
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
Labels: B7-runtimenoteworthy

#1040 Add tests for each type of transaction
  tests/package-lock.json
  tests/package.json
  tests/tests/test-balance/test-balance-extrinsics.ts
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-block/test-block-gas.ts
  tests/tests/test-contract/test-contract-creation.ts
  tests/tests/test-contract/test-contract-error.ts
  tests/tests/test-contract/test-contract-incr-loop.ts
  tests/tests/test-contract/test-contract-loop-cost.ts
  tests/tests/test-contract/test-contract-methods.ts
  tests/tests/test-contract/test-contract-variables.ts
  tests/tests/test-deal-fees.ts
  tests/tests/test-ethpool/test-ethpool-multiple.ts
  tests/tests/test-ethpool/test-ethpool-nonce-future.ts
  tests/tests/test-event.ts
  tests/tests/test-existential-deposit.ts
  tests/tests/test-fibonacci.ts
  tests/tests/test-filter/test-filter-api-creation.ts
  tests/tests/test-filter/test-filter-api-polling.ts
  tests/tests/test-fork-chain.ts
  tests/tests/test-gas/test-gas-estimation.ts
  tests/tests/test-gas/test-gas-estimation2.ts
  tests/tests/test-log-filtering.ts
  tests/tests/test-nonce.ts
  tests/tests/test-precompile-assets-erc20.ts
  tests/tests/test-precompile-blake2.ts
  tests/tests/test-precompile/test-precompile-bn128add.ts
  tests/tests/test-precompile/test-precompile-bn128mul.ts
  tests/tests/test-precompile/test-precompile-bn128pairing.ts
  tests/tests/test-precompile/test-precompile-dummy-bytecode.ts
  tests/tests/test-precompile/test-precompile-erc20.ts
  tests/tests/test-precompile/test-precompile-modexp.ts
  tests/tests/test-precompile/test-precompile-relay-encoder.ts
  tests/tests/test-precompile/test-precompile-revert-attack.ts
  tests/tests/test-precompile/test-precompile-ripemd160.ts
  tests/tests/test-precompile/test-precompile-sha3fips.ts
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/tests/test-precompile/test-precompile-xcm-transactor.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
  tests/tests/test-receipt/test-receipt-revert.ts
  tests/tests/test-receipt/test-receipt.ts
  tests/tests/test-resubmit-txn.ts
  tests/tests/test-subscription/test-subscription-logs.ts
  tests/tests/test-subscription/test-subscription-past-events.ts
  tests/tests/test-subscription/test-subscription.ts
  tests/tests/test-txpool/test-txpool-future.ts
  tests/tests/test-txpool/test-txpool-pending.ts
  tests/tests/test-txpool/test-txpool-reset.ts
  tests/tracing-tests/test-trace-concurrency.ts
  tests/tracing-tests/test-trace-filter-reorg.ts
  tests/tracing-tests/test-trace-filter.ts
  tests/tracing-tests/test-trace-gas.ts
  tests/tracing-tests/test-trace.ts
  tests/util/setup-dev-tests.ts
  tests/util/transactions.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1031 Girazoki xcm queues to maintenance mode
  Cargo.lock
  pallets/maintenance-mode/Cargo.toml
  pallets/maintenance-mode/src/lib.rs
  pallets/maintenance-mode/src/mock.rs
  pallets/maintenance-mode/src/tests.rs
  pallets/maintenance-mode/src/types.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  tests/para-tests-no-ci/test-xcm-para.ts
Labels: B7-runtimenoteworthy

#1044 [Staking] Remove delays for bond_more
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#1048 Add crowdloan rewards to non-transfer proxy
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  tests/tests/test-crowdloan.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#1046 Fix genesis chain specs
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  pallets/parachain-staking/src/inflation.rs
  pallets/parachain-staking/src/lib.rs
  tests/tests/test-staking.ts
Labels: A8-mergeoncegreen, B0-silent

#1036 Deposit xcm fees to treasury
  primitives/xcm/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/para-tests-no-ci/test-xcm-para.ts
Labels: B7-runtimenoteworthy, C3-medium

#1045 Include democracy `voted` and `seconded` events
  Cargo.lock
  precompiles/pallet-democracy/src/tests.rs
  tests/tests/test-democracy.ts
  tests/tests/test-proxy/test-proxy-governance.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#1030 Increases staking delays
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  pallets/parachain-staking/src/inflation.rs
  pallets/parachain-staking/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-staking.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D1-runtime-migration

#1051 upgrade runtime to 1001
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1054 AccountId20 must impl Debug
  primitives/account/src/lib.rs
Labels: B7-runtimenoteworthy

#1055 Adds github token to generate runtime script
  .github/workflows/publish-runtime.yml
Labels: A8-mergeoncegreen, B0-silent

#1056 Fix staking try runtime (attempt #2)
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
Labels: A8-mergeoncegreen, B0-silent

#1047 Add CI workflow "Create client release ticket"
  .github/workflows/client-release-issue.yml
  tools/github/print-client-release-issue.ts
  tools/package.json
Labels: A8-mergeoncegreen, B0-silent

#1062 Add CI workflow "Create runtime release ticket"
  .github/workflows/runtime-release-issue.yml
  tools/github/print-runtime-release-issue.ts
  tools/package.json
Labels: A8-mergeoncegreen, B0-silent

#1053 add feature force-debug for all runtimes
  .github/workflows/client-release-issue.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/runtime-release-issue.yml
  Cargo.lock
  node/cli/src/command.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  primitives/account/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
  specs/moonbeam/parachain-embedded-specs.json
  tools/github/print-client-release-issue.ts
  tools/github/print-runtime-release-issue.ts
  tools/package.json
Labels: A8-mergeoncegreen, B0-silent

#1064 Restore Proxy/Staking requirements for Moonbeam Phase 2
  runtime/moonbeam/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high

#1018 Add types bundle build to post install script (in CI)
  .github/workflows/build.yml
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
  tests/package-lock.json
  tests/package.json
  tests/tests/test-pallet-evm-transfer.ts
Labels: A0-pleasereview, B0-silent, C1-low

#1067 Fix typo in bootnode in spec file
  specs/moonbeam/parachain-embedded-specs.json
Labels: A8-mergeoncegreen, B0-silent

#1069 Add test for mocked relaychain number
  tests/tests/test-block/test-block-mocked-relay.ts
Labels: A0-pleasereview, B0-silent, C1-low

#1074 Increase client version to v0.16.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: B5-clientnoteworthy

#1073 Solve at runtime level wrong UI AccountID32 matching
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy

#1007 Girazoki xtokens fee with extrinsic
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/tests.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/contracts/compiled/XtokensInstance.json
  tests/contracts/sources.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#1079 Bump tx-wrapper deps
  tests/package-lock.json
  tests/package.json
Labels: A0-pleasereview, B0-silent, C1-low

#1078 CI: improve check cargo toml files error
  scripts/check-cargo-toml-files-format.sh
  scripts/toml-sort.sh
Labels: B0-silent

#1083 remove `proposal(setcode)` from runtime release note
  tools/github/generate-runtimes-body.ts
Labels: A8-mergeoncegreen, B0-silent

#893 TS Test precompiles for democracy
  Cargo.lock
  precompiles/pallet-democracy/Cargo.toml
  precompiles/pallet-democracy/src/tests.rs
  tests/contracts/compiled/Democracy.json
  tests/contracts/sources.ts
  tests/package-lock.json
  tests/package.json
  tests/tests/test-precompile/test-precompile-assets-erc20.ts
  tests/tests/test-precompile/test-precompile-blake2.ts
  tests/tests/test-precompile/test-precompile-democracy.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
  tests/util/constants.ts
  tests/util/governance.ts
  tests/util/transactions.ts
Labels: A0-pleasereview, B0-silent, C1-low

#1085 Adapt to associate and replay attack prevention sig
  Cargo.lock
  precompiles/crowdloan-rewards/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-crowdloan.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#1035 Deferred staking rewards
  Cargo.lock
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
Labels: A0-pleasereview, A3-inprogress, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, I7-optimisation ⏱

#958 Nimbus 0.9 and Sign blocks in dev service
  Cargo.lock
  node/service/src/client.rs
  node/service/src/lib.rs
  pallets/author-mapping/src/benchmarks.rs
  pallets/author-mapping/src/lib.rs
  pallets/author-mapping/src/migrations.rs
  pallets/author-mapping/src/mock.rs
  pallets/author-mapping/src/tests.rs
  runtime/common/src/apis.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/runtime_apis.rs
  tests/tests/test-polkadot-api.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C9-critical, D5-nicetohaveaudit⚠️

#1081 Moonbeam Phase 2 - Remove Sudo pallet
  Cargo.lock
  node/service/src/chain_spec/moonbeam.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1086 AuthorMapping: fix self key rotation
  Cargo.lock
  pallets/author-mapping/Cargo.toml
  pallets/author-mapping/src/lib.rs
  pallets/author-mapping/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#1091 [Moonbeam] Delegation minimum Stake from 500 -> 50 GLMR
  runtime/moonbeam/src/lib.rs
Labels: B7-runtimenoteworthy

#1092 Test for voted and seconded events from democracy
  tests/tests/test-democracy.ts
  tests/tests/test-proxy/test-proxy-governance.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1088 Use fungigbles adapter to withdraw (burn) assets and not get trapped
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  precompiles/xcm_transactor/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1095 Bug bounty
  bug-bounty.md
Labels: B0-silent

#1094 Increase client version to v0.17.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#1093 Max weight defined in the runtime for transactors
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/tests.rs
  precompiles/xcm_transactor/src/mock.rs
  primitives/xcm/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#912 Add instructions to use the rpc port in launch
  tools/README.md
Labels: A8-mergeoncegreen, B0-silent, C1-low

#1101 fix moonbeam skylake binary name
  .github/workflows/publish-binary.yml
Labels: B0-silent

#1082 Moonbeam Phase 2 - Remove call filter
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy

#1098 Reduces deposit for moonbeam to 10 GLMR per key
  runtime/moonbeam/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#1099 Girazoki xtokens fee with extrinsic to 0.9.12 (#1007)
  Cargo.lock
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/tests.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/contracts/compiled/XtokensInstance.json
  tests/contracts/sources.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#1087 Add XCM to moonriver runtime
  Cargo.lock
  node/service/src/chain_spec/moonriver.rs
  runtime/moonbase/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/relay_chain.rs
  runtime/moonriver/tests/xcm_tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1096 [Staking] Increase max delegations per candidate
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/tests.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D1-runtime-migration

#1103 Enable Native ERC20 precompile in Moonriver
  Cargo.lock
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1070 Test maintenance mode
  tests/tests/test-assets-pallet.ts
  tests/tests/test-balance/test-balance-extrinsics.ts
  tests/tests/test-crowdloan.ts
  tests/tests/test-pallet-maintenance-mode.ts
  tests/tests/test-precompile/test-precompile-assets-erc20.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
  tests/tests/test-staking.ts
  tests/tests/test-xcm-transactor.ts
  tests/util/constants.ts
  tests/util/governance.ts
Labels: A0-pleasereview, B0-silent, C1-low

#1102 Upgrades runtime to version 1100
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#1109 Fix integration tests on master
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent

#1112 Adds missing bond to total counted staking
  pallets/parachain-staking/migrations.md
  pallets/parachain-staking/src/migrations.rs
  runtime/common/src/migrations.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D1-runtime-migration

#1113 Prevents people to kick other authorMapping associations
  pallets/author-mapping/src/lib.rs
  pallets/author-mapping/src/tests.rs
  tests/tests/test-author-mapping.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1033 Improve performance of EVM tracing Step event
  Cargo.lock
  client/evm-tracing/src/listeners/call_list.rs
  client/evm-tracing/src/listeners/raw.rs
  primitives/ext/src/lib.rs
  primitives/rpc/evm-tracing-events/Cargo.toml
  primitives/rpc/evm-tracing-events/src/lib.rs
  primitives/rpc/evm-tracing-events/src/runtime.rs
  runtime/evm_tracer/src/lib.rs
Labels: B7-runtimenoteworthy, I7-optimisation ⏱

#1077 Configurable is_sufficient and tests to test sufficients
  pallets/asset-manager/src/benchmarks.rs
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/mock.rs
  pallets/asset-manager/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_tests.rs
  tests/para-tests-no-ci/test-xcm-para.ts
  tests/tests/test-asset-manager.ts
  tests/tests/test-assets-sufficients.ts
  tests/tests/test-mock-dmp.ts
  tests/tests/test-mock-hrmp.ts
  tests/tests/test-precompile/test-precompile-assets-erc20.ts
  tests/tests/test-precompile/test-precompile-xcm-transactor.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#1115 fix proposal (authorizeUpgrade) computation
  tools/github/generate-runtimes-body.ts
Labels: B0-silent

#1111 Make try-runtime compile and execute pre and post upgrade hooks
  pallets/author-mapping/src/migrations.rs
  pallets/parachain-staking/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: A0-pleasereview, B0-silent

#855 Adds PERF.md
  PERF.md
Labels: A8-mergeoncegreen, B0-silent

#1123 Add Identity to NonTransfer proxy for all runtimes
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy

#1134 More xcmp and dmp tests for maintenance mode
  tests/tests/test-pallet-maintenance-mode.ts
Labels: B0-silent
