Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-10, with the labels that each got.

#861 Xtokens precompiles
  Cargo.lock
  precompiles/utils/src/data.rs
  precompiles/xtokens/Cargo.toml
  precompiles/xtokens/src/encoding.rs
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/mock.rs
  precompiles/xtokens/src/tests.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
Labels: B7-runtimenoteworthy, C1-low

#796 pallet-migrations: try-runtime support, and manage author mapping blake2 migration
  Cargo.lock
  pallets/author-mapping/src/lib.rs
  pallets/author-mapping/src/migrations.rs
  pallets/migrations/Cargo.toml
  pallets/migrations/src/lib.rs
  pallets/migrations/src/mock.rs
  pallets/migrations/src/tests.rs
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, I4-tests 🎯

#873 Crowdloan with change reward address origin
  Cargo.lock
  precompiles/crowdloan-rewards/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-crowdloan.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#837 [ci] compute authorizeUpgrade hash by hand for moonbase
  tests/tests/test-authorize-upgrade-hash.ts
  tools/github/generate-runtimes-body.ts
Labels: B0-silent

#874 Erc20 metadata for native tokens (DEV) (fixed strings)
  precompiles/balances-erc20/ERC20.sol
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/mock.rs
  precompiles/balances-erc20/src/tests.rs
  runtime/moonbase/src/precompiles.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#878 Change token name + fix doc
  precompiles/balances-erc20/ERC20.sol
  precompiles/balances-erc20/src/mock.rs
  precompiles/balances-erc20/src/tests.rs
  runtime/moonbase/src/precompiles.rs
Labels: A8-mergeoncegreen, B0-silent

#882 Revert "Migrate from pallet version to storage version (#788)"
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D1-runtime-migration

#936 Updates runtime version to 900
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy
