Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-08, with the labels that each got.

#657 add tech comitee to dev spec
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/test_spec.rs
Labels: B0-silent

#654 Bot waiting for a confirmation block when sending funds
  tools/bots/mission-control-bot/actions.ts
Labels: B0-silent

#660 Remove moonshadow runtime
  .github/workflows/publish-runtime.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  moonbeam-types-bundle/index.ts
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/mod.rs
  node/service/src/chain_spec/moonshadow.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  node/src/tests.rs
  runtime/moonshadow/Cargo.toml
  runtime/moonshadow/build.rs
  runtime/moonshadow/src/lib.rs
  runtime/moonshadow/src/precompiles.rs
  runtime/moonshadow/tests/common/mod.rs
  runtime/moonshadow/tests/integration_test.rs
  runtime/moonshadow/tests/runtime_tests.rs
  scripts/bump-node-version.sh
  scripts/embed-specs.sh
  scripts/generate-runtimes.sh
  specs/moonshadow/parachain-embedded-specs.json
  tests/util/para-node.ts
  tools/README.md
  tools/github/generate-runtimes-body.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, B7-runtimenoteworthy

#656 Updates load testing loop to match new moonbase setup
  tools/load-testing/load-gas-loop.ts
Labels: A8-mergeoncegreen, B0-silent

#664 Update Frontier
  Cargo.lock
  client/rpc-core/txpool/Cargo.toml
  client/rpc/debug/Cargo.toml
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  node/service/Cargo.toml
  node/service/src/rpc.rs
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/parachain-staking/Cargo.toml
  precompiles/utils/Cargo.toml
  primitives/account/Cargo.toml
  runtime/common/src/apis.rs
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/runtime_apis.rs
  tests/tests/test-block-1.ts
  tests/tests/test-block-genesis.ts
  tests/tests/test-subscription.ts
Labels: A9-buythat(wo)manabeer, B5-clientnoteworthy, B7-runtimenoteworthy

#662 Remove staking delay exits migration
  pallets/parachain-staking/migrations.md
  pallets/parachain-staking/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#661 Add details to parachain-staking pallet README
  pallets/parachain-staking/README.md
Labels: A2-insubstantial, B0-silent

#668 Update rust toolchain: `nightly-2021-02-24` -> `nightly-2021-08-01`
  rust-toolchain
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#652 Restore sudo moonbase
  Cargo.lock
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/test_spec.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-crowdloan.ts
  tests/tests/test-parachain-bond.ts
  tests/tests/test-sudo.ts
  tests/tests/test-treasury-proposal.ts
Labels: A6-revertrevert, A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#669 Upgrade runtime to 300 and client to 0.10.0
  Cargo.lock
  README.md
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, B7-runtimenoteworthy

#667 Enable binary search in gas estimation
  client/rpc/debug/Cargo.toml
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  node/service/Cargo.toml
  tests/tests/test-gas-estimation.ts
  tests/tests/test-gas-estimation2.ts
Labels: B5-clientnoteworthy

#672 feat(precompile-utils): impl EvmData for all primitive uint
  precompiles/utils/src/data.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/tests.rs
Labels: A6-seemsok, B0-silent, C1-low

#675 Proper solidity comments for StakingInterface.sol
  precompiles/parachain-staking/StakingInterface.sol
Labels: A0-pleasereview, B0-silent

#674 fix incorrect reported txid in txpool rpc
  Cargo.lock
  client/rpc/txpool/Cargo.toml
  client/rpc/txpool/src/lib.rs
  tests/tests/test-txpool-future.ts
  tests/tests/test-txpool-pending.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#677 Improve parachain staking precompile error message
  Cargo.lock
  precompiles/parachain-staking/Cargo.toml
  precompiles/parachain-staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#663 create proc_macro calculate_fn_selector_for
  Cargo.lock
  Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/crowdloan-rewards/src/tests.rs
  precompiles/utils/Cargo.toml
  precompiles/utils/macro/Cargo.toml
  precompiles/utils/macro/src/lib.rs
  precompiles/utils/macro/tests/tests.rs
  precompiles/utils/src/data.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent

#682 Remove unused deps
  Cargo.lock
  node/cli-opt/Cargo.toml
  pallets/parachain-staking/Cargo.toml
  precompiles/utils/Cargo.toml
  primitives/account/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#687 fix(precompile-utils): uints must be serialized in big endian repr
  precompiles/utils/src/data.rs
  precompiles/utils/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent

#686 Revert dependency mistake which prevents runtime compilation
  pallets/parachain-staking/Cargo.toml
Labels: A0-pleasereview, A6-revertrevert, B0-silent

#684 Local chains export id dependent state
  node/cli/src/cli.rs
  node/cli/src/command.rs
  scripts/generate-parachain-specs.sh
Labels: B5-clientnoteworthy

#688 Plumb `try-runtime`
  Cargo.lock
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
Labels: A3-inprogress, B0-silent

#685 Use precompile-utils in parachain staking precompiles
  Cargo.lock
  precompiles/parachain-staking/Cargo.toml
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
  precompiles/utils/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B0-silent, C1-low

#694 Normalize currency units like moonriver conventions
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#696 Add weight hint getters to staking precompile
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B0-silent

#665 Finish removing staking delay exits migration
  pallets/parachain-staking/src/lib.rs
Labels: A2-insubstantial, B0-silent

#690 Launch multi parachain
  tools/launch.ts
Labels: A8-mergeoncegreen, B0-silent

#599 Increase minimum collator candidate stake 100 -> 1_000
  runtime/moonbase/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#692 Reduce overhead of EVM tracing outside of block replaying
  Cargo.lock
  Cargo.toml
  runtime/evm_tracer/src/call_list.rs
  runtime/evm_tracer/src/raw.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, dependencies, I7-optimisation ⏱

#698 Gorka crowdloan cb weights
  Cargo.lock
  precompiles/crowdloan-rewards/src/mock.rs
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#699 Switch from `free_balance` to `reducible_balance`
  Cargo.lock
  client/rpc-core/txpool/Cargo.toml
  client/rpc/debug/Cargo.toml
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  node/service/Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  precompiles/utils/Cargo.toml
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
  tests/tests/test-balance-reducible.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#703 Add integration tets for identity association and reward address update
  tests/tests/test-crowdloan.ts
Labels: A6-seemsok, B0-silent, C1-low, I4-tests 🎯

#702 [Moonriver] Remove BaseFilter
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/runtime_apis.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#701 Remove phantomdata field from pallet_migrations::GenesisConfig
  pallets/migrations/src/lib.rs
  pallets/migrations/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
  specs/alphanet/parachain-specs-template.json
Labels: A0-pleasereview, B0-silent

#683 Runtime `EvmTracer` as message proxy
  Cargo.lock
  client/rpc/debug/src/lib.rs
  client/rpc/trace/src/lib.rs
  primitives/ext/src/lib.rs
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/debug/src/lib.rs
  primitives/rpc/debug/src/proxy/mod.rs
  primitives/rpc/debug/src/proxy/types/evm_gasometer_types.rs
  primitives/rpc/debug/src/proxy/types/evm_runtime_types.rs
  primitives/rpc/debug/src/proxy/types/evm_types.rs
  primitives/rpc/debug/src/proxy/types/mod.rs
  primitives/rpc/debug/src/proxy/v1/mod.rs
  primitives/rpc/debug/src/proxy/v2/call_list.rs
  primitives/rpc/debug/src/proxy/v2/mod.rs
  primitives/rpc/debug/src/proxy/v2/raw.rs
  runtime/common/src/apis.rs
  runtime/evm_tracer/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/runtime_apis.rs
  tests/tests/test-trace-concurrency.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, B7-runtimenoteworthy, D6-newhostfunctions

#704 Always author in first slot of new round
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#706 Check for `trace_type` early on
  client/rpc/debug/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent

#708 Fix off-by-one in active_on_initialize benchmark
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/weights.rs
Labels: A8-mergeoncegreen, B0-silent

#693 Maintenance Mode Pallet
  Cargo.lock
  Cargo.toml
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  pallets/maintenance-mode/Cargo.toml
  pallets/maintenance-mode/src/lib.rs
  pallets/maintenance-mode/src/mock.rs
  pallets/maintenance-mode/src/tests.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  specs/alphanet/parachain-specs-template.json
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#709 Point to latest crowdloan changes
  Cargo.lock
  moonbeam-types-bundle/index.ts
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy

#714 Increase max collators per nominator 25 -> 100
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#713 Point to latest commit in crowdloan rewards
  Cargo.lock
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#715 Release client v0.11.0
  README.md
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#716 Fix cargo lock
  Cargo.lock
Labels: A8-mergeoncegreen, B0-silent

#719 Fix `trace_transaction_before_version_3`
  client/rpc/debug/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#723 Release client 0.11.2
  Cargo.lock
  README.md
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#718 Launch to support docker
  tools/launch.ts
Labels: B0-silent

#722 Make --force-authoring skip slot prediction
  Cargo.lock
  node/service/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C1-low

#655 Refactor types with spread operator
  moonbeam-types-bundle/check.ts
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
  tests/package-lock.json
  tests/package.json
  tests/tests/test-crowdloan.ts
  tests/tests/test-stake.ts
  tools/generate-rpc-types.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low

#733 Remove unused constant `VestingPeriod` from runtimes
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#749 add try-runtime for moonriver
  Cargo.lock
  node/cli/src/command.rs
  pallets/author-mapping/Cargo.toml
  pallets/ethereum-chain-id/Cargo.toml
  pallets/maintenance-mode/Cargo.toml
  pallets/parachain-staking/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B0-silent

#751 Fix max nominators per collator upgrade bug
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: A3-inprogress, B7-runtimenoteworthy, C7-high

#757 Patch patch for staking migration consistency fix
  pallets/parachain-staking/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D1-runtime-migration

#738 add proxy proxy event test
  tests/package.json
  tests/tests/test-proxy-governance.ts
Labels: A0-pleasereview, B0-silent, C1-low

#760 Add selectors to StakingPrecompile.sol function comments
  precompiles/parachain-staking/StakingInterface.sol
Labels: A0-pleasereview, B0-silent

#763 Fix empty traces
  Cargo.lock
  client/rpc/debug/src/lib.rs
  primitives/ext/Cargo.toml
  primitives/ext/src/lib.rs
  primitives/rpc/debug/src/proxy/v2/call_list.rs
Labels: A0-pleasereview, B5-clientnoteworthy

#765 Remove the most recent staking migration
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B0-silent
