Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-07, with the labels that each got.

#568 replace blockweight formula by const
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonshadow/src/lib.rs
Labels: B0-silent

#580 Adapt to new crowdloan initialization
  Cargo.lock
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonshadow/src/lib.rs
  runtime/moonshadow/tests/integration_test.rs
  tests/tests/test-crowdloan.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#515 Environmental-aware externalities for tracing in execution wasm
  Cargo.lock
  client/rpc/debug/src/lib.rs
  client/rpc/trace/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  primitives/ext/Cargo.toml
  primitives/ext/src/lib.rs
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/debug/src/lib.rs
  primitives/rpc/debug/src/proxy.rs
  primitives/rpc/debug/src/single.rs
  runtime/common/src/apis.rs
  runtime/evm_tracer/Cargo.toml
  runtime/evm_tracer/src/call_list.rs
  runtime/evm_tracer/src/raw.rs
  tests/contracts/compiled/OverflowingTrace.json
  tests/contracts/sources.ts
  tests/tests/test-trace.ts
  tests/util/dev-node.ts
  tests/util/setup-dev-tests.ts
Labels: B7-runtimenoteworthy, D6-newhostfunctions

#587 Update dependencies to v0.9.8 series
  Cargo.lock
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/txpool/Cargo.toml
  client/rpc/debug/Cargo.toml
  client/rpc/debug/src/lib.rs
  client/rpc/trace/Cargo.toml
  client/rpc/trace/src/lib.rs
  client/rpc/txpool/Cargo.toml
  core-primitives/Cargo.toml
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  pallets/author-mapping/Cargo.toml
  pallets/ethereum-chain-id/Cargo.toml
  pallets/parachain-staking/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  primitives/account/Cargo.toml
  primitives/ext/Cargo.toml
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/debug/src/lib.rs
  primitives/rpc/txpool/Cargo.toml
  runtime/common/src/apis.rs
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/runtime_apis.rs
  runtime/moonshadow/Cargo.toml
  runtime/moonshadow/src/lib.rs
  runtime/moonshadow/tests/runtime_tests.rs
  tests/package-lock.json
  tests/package.json
Labels: A0-pleasereview, A1-needsburnin, B2-breaksapi, B5-clientnoteworthy, B7-runtimenoteworthy, C9-critical, dependencies

#592 Clean parachain-staking tests
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: B0-silent

#596 Adds check in the build CI for build version
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: B0-silent

#603 Adds alphanet 9.2 to the launch.ts config
  tools/launch.ts
Labels: B0-silent

#606 runtime: reduce fast tracking to 3 hours
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy

#609 Hopefully improving CI SCCache for git version
  .github/workflows/build.yml
Labels: B0-silent

#613 Set Polkadot native runtime features as default
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec/moonbase.rs
Labels: A0-pleasereview, B5-clientnoteworthy

#614 Runtime Api versioning
  Cargo.lock
  client/rpc/debug/src/lib.rs
  client/rpc/trace/src/lib.rs
  primitives/rpc/debug/src/lib.rs
Labels: A0-pleasereview, A1-needsburnin, B7-runtimenoteworthy

#604 Enforce changelog labels for all PR
  .github/workflows/enforce-pr-labels.yml
  CONTRIBUTIONS.md
Labels: B0-silent

#618 Fix `ApiRef` re-use for `can_author` in cumulus
  Cargo.lock
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#611 Introduce parachain tests
  .github/workflows/build.yml
  tests/package-lock.json
  tests/package.json
  tests/para-tests/moonriver/test-balance-genesis.ts
  tests/util/constants.ts
  tests/util/para-node.ts
  tests/util/setup-para-tests.ts
  tools/package-lock.json
  tools/package.json
Labels: B0-silent

#621 Updates to node v0.9.5
  Cargo.lock
  README.md
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#622 Bump runtime version to 157
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#623 Better submitExtrinsic util for tests
  tests/tests/test-treasury-proposal.ts
  tests/util/constants.ts
  tests/util/substrate-rpc.ts
Labels: A8-mergeoncegreen, B0-silent

#620 Release note filter labels
  .github/workflows/publish-binary.yml
  tools/github/generate-release-body.ts
  tools/github/generate-runtimes-body.ts
  tools/github/github-utils.ts
Labels: B0-silent

#628 Pin substrate#74101dc + cumulus#ed6ba5d
  Cargo.lock
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#630 Bump client v0.9.6 & runtime 158
  Cargo.lock
  README.md
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
  tools/launch.ts
Labels: A0-pleasereview, B5-clientnoteworthy, B7-runtimenoteworthy

#631 Make the runtime release script use purestake repo
  tools/github/generate-runtimes-body.ts
Labels: B0-silent

#633 Reduce transaction byte fees to 10 micro per byte
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#635 Precompile units (standalone)
  precompiles/utils/Cargo.toml
  precompiles/utils/src/lib.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent

#607 Crowdloan rewards precompiles
  Cargo.lock
  Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/crowdloan-rewards/CrowdloanInterface.sol
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/crowdloan-rewards/src/tests.rs
  precompiles/utils/Cargo.toml
  precompiles/utils/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonshadow/Cargo.toml
  runtime/moonshadow/src/precompiles.rs
  runtime/moonshadow/tests/integration_test.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B7-runtimenoteworthy

#637 Precompiles : Gasometer util
  precompiles/utils/src/lib.rs
Labels: A0-pleasereview, B0-silent

#636 Client fix for tracing nodes >= v0.9.8
  client/rpc/debug/src/lib.rs
  client/rpc/trace/src/lib.rs
  primitives/rpc/debug/src/proxy.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#610 Delay nominator revocations and exits
  Cargo.lock
  moonbeam-types-bundle/index.ts
  pallets/parachain-staking/Cargo.toml
  pallets/parachain-staking/README.md
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonshadow/src/lib.rs
  runtime/moonshadow/tests/integration_test.rs
  tests/tests/test-stake.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D1-runtime-migration

#634 Expose parachain-staking constants in polkadot-js apps
  pallets/parachain-staking/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#639 Make `--rpc-http-threads` usable
  Cargo.lock
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#641 Fix tracing response handling for `DebugRuntimeApi` v1
  client/rpc/debug/src/lib.rs
  client/rpc/trace/src/lib.rs
  primitives/rpc/debug/src/lib.rs
  primitives/rpc/debug/src/proxy.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#617 Add a link to apopiak/substrate-migrations repo
  tools/github/print-version-bump-info.ts
Labels: B0-silent

#643 update moonbeam-types-bundle dependencies
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
Labels: A8-mergeoncegreen, B0-silent, C1-low

#648 Kill the PR checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low, D10-breaksdocs

#642 precompiles utils + crowdloan precompile refactor
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/crowdloan-rewards/src/tests.rs
  precompiles/utils/src/data.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent

#647 Rename SED to WEI
  Cargo.lock
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#649 Add tests for crowdloan initialization through democracy and dust burn
  Cargo.lock
  tests/tests/test-crowdloan.ts
Labels: A0-pleasereview, B0-silent

#605 Test proxing governance
  tests/tests/test-proxy-governance.ts
  tests/util/constants.ts
Labels: A8-mergeoncegreen, B0-silent

#650 Remove sudo from Moonriver (and Alphanet temporarily)
  Cargo.lock
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/chain_spec/test_spec.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-crowdloan.ts
  tests/tests/test-parachain-bond.ts
  tests/tests/test-sudo.ts
  tests/tests/test-treasury-proposal.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#651 Updates runtimes to version 0200
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#653 Skipping introduced test with sudo
  tests/tests/test-crowdloan.ts
Labels: B0-silent
