Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-11, with the labels that each got.

#944 Use dedicated nimbus repo
  Cargo.lock
  node/cli/Cargo.toml
  node/perf-test/Cargo.toml
  node/service/Cargo.toml
  pallets/author-mapping/Cargo.toml
  pallets/parachain-staking/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B0-silent, C1-low

#943 Update rust toolchain to `nightly-2021-09-10`
  rust-toolchain
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#949 Deny warnings on CI
  .github/workflows/build.yml
  node/perf-test/src/command.rs
  node/perf-test/src/lib.rs
  node/perf-test/src/sysinfo.rs
  node/perf-test/src/tests/block_creation.rs
  node/perf-test/src/tests/fibonacci.rs
  node/perf-test/src/tests/mod.rs
  node/perf-test/src/tests/storage.rs
  node/service/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/runtime_apis.rs
Labels: B0-silent

#950 CI: not retrigger CI when PR description is edited + autocancel previous build
  .github/workflows/build.yml
  .github/workflows/cancel.yml
Labels: B0-silent

#935 Add Blake2 precompile to runtimes
  Cargo.lock
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  tests/contracts/compiled/Blake2Check.json
  tests/contracts/sources.ts
  tests/tests/test-precompile-blake2.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#956 ci: don't cancel past builds on master
  .github/workflows/cancel.yml
Labels: B0-silent

#954 CI: skip some jobs on forks
  .github/workflows/build.yml
Labels: B0-silent

#948 List all migrations in new chain spec
  pallets/migrations/src/lib.rs
  pallets/migrations/src/mock.rs
  pallets/migrations/src/tests.rs
Labels: B0-silent

#915 Don't depend directly on Sputnik EVM
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/rpc.rs
  precompiles/assets-erc20/Cargo.toml
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  precompiles/balances-erc20/Cargo.toml
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/tests.rs
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/pallet-democracy/Cargo.toml
  precompiles/pallet-democracy/src/lib.rs
  precompiles/pallet-democracy/src/mock.rs
  precompiles/pallet-democracy/src/tests.rs
  precompiles/parachain-staking/Cargo.toml
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/relay-encoder/Cargo.toml
  precompiles/relay-encoder/src/lib.rs
  precompiles/relay-encoder/src/mock.rs
  precompiles/utils/Cargo.toml
  precompiles/utils/src/data/xcm.rs
  precompiles/utils/src/lib.rs
  precompiles/xtokens/Cargo.toml
  precompiles/xtokens/src/encoding.rs
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/mock.rs
  precompiles/xtokens/src/tests.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low

#955 Refund on 0 ED chains Frontier hotfix
  Cargo.lock
Labels: B7-runtimenoteworthy

#961 comment migration collectives
  runtime/common/src/migrations.rs
Labels: B0-silent

#963 Fix approval assets bug plus ts tests
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/contracts/compiled/ERC20Instance.json
  tests/contracts/sources.ts
  tests/tests/test-precompile-assets-erc20.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#965 Client v0.14.1
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#966 perf-test filtering and add txpool test
  node/perf-test/src/command.rs
  node/perf-test/src/lib.rs
  node/perf-test/src/tests/block_creation.rs
  node/perf-test/src/tests/fibonacci.rs
  node/perf-test/src/tests/mod.rs
  node/perf-test/src/tests/storage.rs
Labels: B5-clientnoteworthy

#967 Make release create optimized binaries
  .github/workflows/publish-binary.yml
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#968 Removes icelake from release CI
  .github/workflows/publish-binary.yml
Labels: A8-mergeoncegreen, B0-silent

#972 Includes substrate hotfix & Updates client v0.14.2
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#945 Perf Test Resiliency
  node/perf-test/src/command.rs
  node/perf-test/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#971 [Staking] Emit event to show origin of nominator rewards during payout
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B0-silent

#973 Adds support for optimized binary in docker image
  .github/workflows/publish-docker.yml
  docker/moonbeam-release.Dockerfile
Labels: A8-mergeoncegreen, B0-silent

#960 print-version-bump-info: deduplicate PRs
  tools/github/print-version-bump-info.ts
Labels: B0-silent

#970 [Staking] Kill unnecessary storage bloat
  Cargo.lock
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/tests.rs
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
Labels: A0-pleasereview, B0-silent, D1-runtime-migration

#975 Fix test for new AccountId20 type branch
  tests/package-lock.json
  tests/package.json
  tests/tests/test-balance-transfer-txwrapper-substrate.ts
  tests/tests/test-democracy.ts
  tests/tests/test-parachain-bond.ts
  tests/tests/test-precompile-staking.ts
  tests/tests/test-staking.ts
Labels: A0-pleasereview, B0-silent, C1-low

#974 Girazoki runtime 901 moonbase alpha approval fix
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/contracts/compiled/ERC20Instance.json
  tests/contracts/sources.ts
  tests/tests/test-precompile-assets-erc20.ts
Labels: B7-runtimenoteworthy

#938 Automatic xcm version negotiation
  node/service/src/chain_spec/moonbase.rs
  node/src/tests.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/util/constants.ts
Labels: A0-pleasereview, A8-mergeoncegreen, B7-runtimenoteworthy

#964 Add tests for ED 0 transfer and refund
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B0-silent

#977 Joshy moonbeam account : remove toLowercase
  tests/package-lock.json
  tests/tests/test-asset-manager.ts
  tests/tests/test-author-mapping.ts
  tests/tests/test-block-1.ts
  tests/tests/test-event.ts
  tests/tests/test-filter-api-polling.ts
  tests/tests/test-precompile-erc20.ts
  tests/tests/test-receipt.ts
  tests/tests/test-staking.ts
  tests/tests/test-subscription.ts
  tests/tests/test-txpool-future.ts
  tests/tests/test-txpool-pending.ts
  tests/util/constants.ts
  tests/util/tracer/blockscout_tracer.min.json
  tools/test-scripts/test-alpha.ts
  tools/test-scripts/test-staking.ts
Labels: A0-pleasereview, B0-silent, C1-low

#978 Re-enable moonbeam tests with new gas price
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/tests/common/mod.rs
Labels: A0-pleasereview, B0-silent

#981 More info on type migration
  moonbeam-types-bundle/README.md
Labels: A8-mergeoncegreen, B0-silent

#984 Even better readme for types
  moonbeam-types-bundle/README.md
Labels: A8-mergeoncegreen, B0-silent

#986 Pin nimbus branch to 94e54bd
  Cargo.lock
  node/service/src/client.rs
  runtime/common/src/apis.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#983 Girazoki allowance in assets precompile should work now
  precompiles/assets-erc20/ERC20.sol
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  runtime/moonbase/tests/integration_test.rs
  tests/contracts/compiled/ERC20Instance.json
  tests/contracts/sources.ts
  tests/tests/test-precompile-assets-erc20.ts
Labels: B7-runtimenoteworthy

#980 Girazoki versioned xcm transactor too
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/tests.rs
  precompiles/xcm_transactor/src/lib.rs
  precompiles/xcm_transactor/src/tests.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/tests/test-precompile/test-precompile-xcm-transactor.ts
Labels: B7-runtimenoteworthy

#940 Support all runtimes in perf-tests
  Cargo.lock
  node/cli/src/command.rs
  node/perf-test/src/command.rs
  node/perf-test/src/lib.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy

#992 derive num_enum traits in macro
  Cargo.lock
  precompiles/assets-erc20/src/lib.rs
  precompiles/balances-erc20/src/lib.rs
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/pallet-democracy/src/lib.rs
  precompiles/parachain-staking/src/lib.rs
  precompiles/relay-encoder/src/lib.rs
  precompiles/utils/macro/Cargo.toml
  precompiles/utils/macro/src/lib.rs
  precompiles/utils/src/tests.rs
  precompiles/xcm_transactor/src/lib.rs
  precompiles/xtokens/src/lib.rs
Labels: A0-pleasereview, B0-silent

#995 update substrate: increase MAX_RUNTIMES
  Cargo.lock
Labels: B5-clientnoteworthy

#990 fix return types in asset erc20 and refactor asseterc20precompileset
  node/src/tests.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  runtime/moonbase/tests/integration_test.rs
  tests/contracts/compiled/ERC20Instance.json
  tests/contracts/sources.ts
  tests/tests/test-precompile-assets-erc20.ts
Labels: B7-runtimenoteworthy, C7-high

#997 Add custom ProxyType for old types
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
Labels: A0-pleasereview, B0-silent, C1-low

#999 Assets erc20 call delegate call hotfix runtime 902
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/contracts/compiled/ERC20Instance.json
  tests/contracts/sources.ts
  tests/tests/test-precompile-assets-erc20.ts
Labels: B7-runtimenoteworthy

#1001 Girazoki point to latest polkadot commit with xcm no inline changes
  Cargo.lock
  node/src/tests.rs
  tests/util/constants.ts
Labels: A8-mergeoncegreen, B0-silent

#1004 Client version v0.15.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#991 benchmark pallet asset manager
  .cargo/config.toml
  Cargo.lock
  node/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  pallets/asset-manager/Cargo.toml
  pallets/asset-manager/src/benchmarks.rs
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/mock.rs
  pallets/asset-manager/src/weights.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
Labels: B7-runtimenoteworthy

#1000 Normalize Cargo.toml
  Cargo.toml
  bin/utils/moonkey/Cargo.toml
  client/evm-tracing/Cargo.toml
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/trace/Cargo.toml
  client/rpc-core/txpool/Cargo.toml
  client/rpc-core/types/Cargo.toml
  client/rpc/debug/Cargo.toml
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  core-primitives/Cargo.toml
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/perf-test/Cargo.toml
  node/service/Cargo.toml
  pallets/asset-manager/Cargo.toml
  pallets/author-mapping/Cargo.toml
  pallets/ethereum-chain-id/Cargo.toml
  pallets/maintenance-mode/Cargo.toml
  pallets/migrations/Cargo.toml
  pallets/parachain-staking/Cargo.toml
  pallets/proxy-genesis-companion/Cargo.toml
  pallets/xcm-transactor/Cargo.toml
  precompiles/assets-erc20/Cargo.toml
  precompiles/balances-erc20/Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/pallet-democracy/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  precompiles/relay-encoder/Cargo.toml
  precompiles/utils/Cargo.toml
  precompiles/utils/macro/Cargo.toml
  precompiles/xcm_transactor/Cargo.toml
  precompiles/xtokens/Cargo.toml
  primitives/account/Cargo.toml
  primitives/ext/Cargo.toml
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/evm-tracing-events/Cargo.toml
  primitives/rpc/txpool/Cargo.toml
  primitives/xcm/Cargo.toml
  runtime/common/Cargo.toml
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
  runtime/relay-encoder/Cargo.toml
  scripts/toml-sort.sh
  toml-sort.toml
Labels: A0-pleasereview, B0-silent

#1003 CI: check Cargo.toml files format with toml_sort
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent

#1009 Fix `try-runtime`
  node/cli/src/command.rs
  pallets/parachain-staking/src/migrations.rs
  runtime/common/src/apis.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent

#1010 Add test to ensure gas estimate is sufficient
  Cargo.lock
  tests/tests/test-gas/test-gas-contract-creation.ts
  tests/tests/test-gas/test-gas-estimation.ts
Labels: B5-clientnoteworthy, C7-high

#810 [Staking] Make exits manual, patch lack of delay for {increasing, decreasing} bonds
  Cargo.lock
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/chain_spec/test_spec.rs
  pallets/parachain-staking/Cargo.toml
  pallets/parachain-staking/README.md
  pallets/parachain-staking/migrations.md
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/set.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/runtime_apis.rs
  scripts/run_benchmarks.sh
  tests/contracts/compiled/JoinCandidatesWrapper.json
  tests/contracts/compiled/StakingDelegationAttaker.json
  tests/contracts/compiled/StakingNominationAttaker.json
  tests/contracts/sources.ts
  tests/tests/test-precompile/test-precompile-revert-attack.ts
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/tests/test-staking.ts
  tests/util/constants.ts
  tools/test-scripts/test-staking.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D1-runtime-migration

#1014 Make staking compile for try-runtime tests
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent

#1017 Girazoki fix xcm end to end tests
  tests/para-tests-no-ci/test-xcm-para.ts
Labels: B0-silent, C1-low

#926 Dedicated `AccountId20` type
  Cargo.lock
  moonbeam-types-bundle/package-lock.json
  node/cli-opt/src/account_key.rs
  node/service/src/chain_spec/mod.rs
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  primitives/account/Cargo.toml
  primitives/account/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  tests/package-lock.json
  tests/package.json
  tests/tests/test-asset-manager.ts
  tests/tests/test-author-mapping.ts
  tests/tests/test-balance/test-balance-transfer-txwrapper-substrate.ts
  tests/tests/test-block/test-block-1.ts
  tests/tests/test-democracy.ts
  tests/tests/test-event.ts
  tests/tests/test-filter/test-filter-api-polling.ts
  tests/tests/test-parachain-bond.ts
  tests/tests/test-precompile/test-precompile-erc20.ts
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/tests/test-receipt/test-receipt.ts
  tests/tests/test-staking.ts
  tests/tests/test-subscription/test-subscription.ts
  tests/tests/test-txpool/test-txpool-future.ts
  tests/tests/test-txpool/test-txpool-pending.ts
  tests/util/constants.ts
  tests/util/tracer/blockscout_tracer.min.json
  tools/package.json
  tools/test-scripts/test-alpha.ts
  tools/test-scripts/test-staking.ts
  tools/yarn.lock
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#1021 Updates runtime version to 1000
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1020 Replace yarn with npm in tools repo
  tools/README.md
  tools/bots/mission-control-bot/yarn.lock
  tools/github/print-version-bump-info.ts
  tools/package-lock.json
  tools/yarn.lock
Labels: A0-pleasereview, B0-silent, C1-low

#994 create script create-substrate-fork.sh
  scripts/create-substrate-fork.sh
Labels: B0-silent

#988 Minor modifications to Types README
  moonbeam-types-bundle/README.md
Labels: A8-mergeoncegreen, B0-silent

#1026 fix ci job check-cargo-toml-format
  .github/workflows/build.yml
  primitives/account/Cargo.toml
  runtime/common/Cargo.toml
  scripts/check-cargo-toml-files-format.sh
Labels: A8-mergeoncegreen, B0-silent

#1005 Remove multiweighttrader as it is not necessary anymore
  primitives/xcm/src/lib.rs
  runtime/moonbase/src/lib.rs
Labels: B0-silent, C1-low

#1028 Unnecessary Private Key Usage When Computing Account ID
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec/mod.rs
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
Labels: A0-pleasereview, B0-silent

#446 Add pallet Proxy tests
  tests/package-lock.json
  tests/package.json
  tests/tests/test-proxy.ts
  tests/util/constants.ts
Labels: A0-pleasereview, B0-silent, C1-low

#1032 Fixed indices for ProxyType
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A8-mergeoncegreen, B0-silent

#1027 add nimbus to version bump info
  tools/github/print-version-bump-info.ts
Labels: B0-silent

#1029 Check block fees
  tests/package-lock.json
  tests/tests/test-asset-manager.ts
  tests/tests/test-balance/test-balance-transfer-txwrapper-substrate.ts
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-contract/test-contract-creation.ts
  tests/tests/test-contract/test-contract-error.ts
  tests/tests/test-contract/test-contract-incr-loop.ts
  tests/tests/test-crowdloan.ts
  tests/tests/test-existential-deposit.ts
  tests/tests/test-pallet-evm-transfer.ts
  tests/tests/test-precompile-assets-erc20.ts
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/tests/test-precompile/test-precompile-xcm-transactor.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
  tests/tests/test-sudo.ts
  tests/util/block.ts
  tests/util/constants.ts
Labels: A0-pleasereview, B0-silent, C1-low

#1038 add Xtokens.sol interface
  precompiles/xtokens/Xtokens.sol
Labels: B0-silent, C1-low, I5-documentation 📄

#1039 Girazoki wrong param name
  precompiles/xtokens/Xtokens.sol
Labels: B0-silent, C1-low, I5-documentation 📄
