Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-02, with the labels that each got.

#213 Wire author inherent to pallet ethereum
  pallets/author-inherent/src/lib.rs
  runtime/src/lib.rs
  runtime/src/parachain.rs
  runtime/src/standalone.rs
  tests/tests/test-block.ts
  tests/tests/test-subscription.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#204 Combine standalone and parachain node
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  README.md
  docker/moonbase-standalone.Dockerfile
  node/Cargo.toml
  node/build.rs
  node/parachain/src/main.rs
  node/rpc/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/dev_service.rs
  node/src/inherents.rs
  node/src/main.rs
  node/src/rpc.rs
  node/src/service.rs
  node/standalone/Cargo.lock
  node/standalone/Cargo.toml
  node/standalone/build.rs
  node/standalone/src/chain_spec.rs
  node/standalone/src/cli.rs
  node/standalone/src/command.rs
  node/standalone/src/mock_timestamp.rs
  node/standalone/src/service.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/parachain.rs
  runtime/src/standalone.rs
  tests/README.md
  tests/tests/constants/constants.ts
  tests/tests/test-polkadot-api.ts
  tests/tests/util/testWithMoonbeam.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C3-medium

#218 Remove event from Author Inherent
  pallets/author-inherent/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#221 update readme with author and stake
  README.md
Labels: A0-pleasereview, A2-insubstantial, B0-silent

#224 Added tests for extrinsic events
  tests/tests/test-balance.ts
  tests/tests/test-polkadot-api.ts
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low

#225 Support instant seal
  Cargo.lock
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/dev_service.rs
  tests/tests/util/testWithMoonbeam.ts
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium

#189 staking multiple nominations
  moonbeam-types-bundle/index.ts
  node/src/chain_spec.rs
  pallets/stake/src/lib.rs
  pallets/stake/src/mock.rs
  pallets/stake/src/tests.rs
  runtime/src/lib.rs
  tests/tests/test-stake.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#222 set frontier_log to last log that decodes and break
  node/src/dev_service.rs
  node/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low

#187 Update pallet-etheruem-chain-id to FRAME V2
  pallets/ethereum-chain-id/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#220 created script to use moonbeam-launch
  .gitignore
  tests/package-lock.json
  tools/README.md
  tools/config_moonbeam.json
  tools/moonbeam-launch.ts
  tools/package.json
  tools/tsconfig.json
Labels: A0-pleasereview, B0-silent, C1-low

#230 declare stake constants for polkadot-js
  pallets/stake/src/lib.rs
  pallets/stake/src/mock.rs
  runtime/src/lib.rs
Labels: A2-insubstantial, A8-mergeoncegreen

#229 Filter Authors at each block height
  Cargo.lock
  pallets/author-filter/Cargo.toml
  pallets/author-filter/src/lib.rs
  pallets/author-inherent/src/lib.rs
  pallets/stake/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#232 staking inflation
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec.rs
  pallets/stake/Cargo.toml
  pallets/stake/src/inflation.rs
  pallets/stake/src/lib.rs
  pallets/stake/src/mock.rs
  pallets/stake/src/tests.rs
  runtime/src/lib.rs
  tests/tests/test-stake.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#241 Remove relay block from author filter
  pallets/author-filter/src/lib.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#239 Improve clippy CI performance
  .github/workflows/release.yml
Labels: A0-pleasereview

#242 update cargo.lock
  Cargo.lock
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#240 patch stake nominations bug
  Cargo.lock
  pallets/stake/Cargo.toml
  pallets/stake/src/lib.rs
  pallets/stake/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#254 bump substrate by two commits
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C7-high

#260 Cleaner enabling of development service
  Cargo.lock
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package-lock.json
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/dev_service.rs
  node/src/main.rs
  node/src/service.rs
Labels: A0-pleasereview, A1-needsburnin, B5-clientnoteworthy, C3-medium
