Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-03, with the labels that each got.

#281 Update support URL
  node/src/command.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#282 Prune unused dependencies from the former standalone node.
  Cargo.lock
  runtime/Cargo.toml
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#283 Add utility pallet to runtime
  Cargo.lock
  README.md
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#284 Update copyright years
  client/rpc-core/txpool/src/lib.rs
  client/rpc-core/txpool/src/types/content.rs
  client/rpc-core/txpool/src/types/inspect.rs
  client/rpc-core/txpool/src/types/mod.rs
  client/rpc/txpool/src/lib.rs
  node/build.rs
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/inherents.rs
  node/src/main.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/author-filter/src/lib.rs
  pallets/author-inherent/src/lib.rs
  pallets/ethereum-chain-id/src/lib.rs
  pallets/parachain-info/src/lib.rs
  pallets/stake/src/inflation.rs
  pallets/stake/src/lib.rs
  pallets/stake/src/mock.rs
  pallets/stake/src/set.rs
  pallets/stake/src/tests.rs
  pallets/token-dealer/src/lib.rs
  primitives/rpc/txpool/src/lib.rs
  runtime/account/src/lib.rs
  runtime/build.rs
  runtime/precompiles/src/lib.rs
  runtime/src/lib.rs
  tools/generate-rpc-types.ts
Labels: A0-pleasereview, B0-silent, C1-low

#265 Publish rustdocs to github pages
  .github/workflows/docs.yml
Labels: A0-pleasereview, B0-silent, C1-low

#290 Clean interfaces and docs
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#259 v0.7 dependency updates
  Cargo.lock
  client/rpc-core/txpool/Cargo.toml
  client/rpc/txpool/Cargo.toml
  docker/polkadot-relay.Dockerfile
  moonbeam-types-bundle/package-lock.json
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/command.rs
  node/src/inherents.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/author-filter/Cargo.toml
  pallets/author-filter/src/lib.rs
  pallets/author-inherent/Cargo.toml
  pallets/author-inherent/src/lib.rs
  pallets/ethereum-chain-id/Cargo.toml
  pallets/ethereum-chain-id/src/lib.rs
  pallets/parachain-info/Cargo.toml
  pallets/parachain-info/src/lib.rs
  pallets/parachain-staking/Cargo.toml
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/token-dealer/Cargo.toml
  primitives/rpc/txpool/Cargo.toml
  runtime/Cargo.toml
  runtime/account/Cargo.toml
  runtime/precompiles/Cargo.toml
  runtime/src/lib.rs
  rust-toolchain
  scripts/build-alphanet-relay-image.sh
  scripts/generate-relay-specs.sh
  scripts/run-alphanet-parachain.sh
  scripts/run-rococo-local.sh
  specs/alphanet/parachain-specs-template.json
  specs/stagenet/parachain-specs-template.json
  tests/package-lock.json
  tests/package.json
  tests/tests/test-block.ts
  tests/tests/test-filter-api.ts
  tests/tests/test-subscription.ts
  tests/tests/test-web3api.ts
Labels: A8-mergeoncegreen, A9-FUCKYEAH!, A9-buythat(wo)manabeer, B5-clientnoteworthy, C9-critical, D7-breakseverything

#289 Overhaul README
  README.md
Labels: A0-pleasereview, B0-silent, C1-low

#294 stake: revoke nomination => leave nominators if no nominations left
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  runtime/src/lib.rs
  tools/staking-test-spec.json
  tools/test-staking.ts
Labels: A2-insubstantial, A6-seemsok

#297 increase max collators per nominator from 8 to 25
  runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#305 use cumulus::parachain-info instead of local clone
  Cargo.lock
  pallets/parachain-info/Cargo.toml
  pallets/parachain-info/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#302 Add missing precompiles
  Cargo.lock
  runtime/precompiles/Cargo.toml
  runtime/precompiles/src/lib.rs
  runtime/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low

#306 stake: fix collator fee to 20%
  moonbeam-types-bundle/index.ts
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#300 update tools readme with polkadot-launch instructions
  tools/README.md
  tools/yarn.lock
Labels: A8-mergeoncegreen, B0-silent, C1-low

#308 Re-unify new_partial
  node/src/command.rs
  node/src/service.rs
Labels: A8-mergeoncegreen, B0-silent, C3-medium

#310 Add integration tests for bn128 and sha3fips precompiles
  tests/tests/test-precompiles.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low

#313 Pin Ethers JS to 5.0.32
  tests/package.json
Labels: A8-mergeoncegreen, B0-silent, C1-low

#312 Crystalin fixes ci wrong exit
  scripts/generate-parachain-specs.sh
  scripts/generate-relay-specs.sh
  specs/alphanet/parachain-specs-template.json
  specs/stagenet/parachain-specs-template.json
Labels: A8-mergeoncegreen, B0-silent, C1-low

#309 Update Substrate to 401c24e
  Cargo.lock
  node/src/service.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#196 `debug_traceTransaction` RPC method support
  Cargo.lock
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/debug/src/lib.rs
  client/rpc-core/txpool/src/types/content.rs
  client/rpc/debug/Cargo.toml
  client/rpc/debug/src/lib.rs
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/rpc.rs
  node/src/service.rs
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/debug/src/lib.rs
  runtime/Cargo.toml
  runtime/extensions/evm/Cargo.toml
  runtime/extensions/evm/src/executor/mod.rs
  runtime/extensions/evm/src/executor/util.rs
  runtime/extensions/evm/src/executor/wrapper.rs
  runtime/extensions/evm/src/lib.rs
  runtime/extensions/evm/src/runner/mod.rs
  runtime/extensions/evm/src/runner/stack.rs
  runtime/src/lib.rs
  tests/replay/.gitignore
  tests/replay/package.json
  tests/replay/replay.ts
  tests/replay/tsconfig.json
  tests/tests/constants/Callee.json
  tests/tests/constants/Caller.json
  tests/tests/constants/Incrementer.json
  tests/tests/constants/blockscout_tracer.min.json
  tests/tests/test-block.ts
  tests/tests/test-trace.ts
  tests/tests/util/testWithMoonbeam.ts
Labels: A6-mustntgrumble, A9-buythat(wo)manabeer, B5-clientnoteworthy, B7-runtimenoteworthy, C1-low
