Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-09, with the labels that each got.

#734 Test staking precompile
  tests/package.json
  tests/tests/test-precompile-staking.ts
  tests/tests/test-staking.ts
  tests/util/transactions.ts
Labels: A0-pleasereview, B0-silent, C1-low

#732 fix: evm txs must deal with fees the same way that substrate txs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  tests/tests/test-balance-extrinsics.ts
  tests/tests/test-deal-fees.ts
  tests/util/constants.ts
Labels: B7-runtimenoteworthy

#728 Small tools/launch modifs
  tools/README.md
  tools/launch.ts
  tools/package-lock.json
  tools/yarn.lock
Labels: A8-mergeoncegreen, B0-silent, C1-low

#770 Filter out invalid Ethereum transaction from blocks
  Cargo.lock
  client/rpc-core/txpool/Cargo.toml
  client/rpc/debug/Cargo.toml
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  node/service/Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  precompiles/utils/Cargo.toml
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
  tests/tests/test-trace.ts
  tests/tests/test-tx-early-exits.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#771 Filters out invalid transaction trace entries
  primitives/rpc/debug/src/proxy/formats/trace_filter.rs
  primitives/rpc/debug/src/proxy/v1/mod.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#773 Runtime 600
  Cargo.lock
  README.md
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, B7-runtimenoteworthy

#772 Test apply extrinsic for invalid transaction cost
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/runtime_apis.rs
Labels: A0-pleasereview, B0-silent

#774 Handle unknown opcodes gracefully
  primitives/rpc/debug/src/proxy/v2/mod.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#775 Add record-proof for benchmark
  scripts/run_benchmarks.sh
Labels: B0-silent

#743 [Staking] Execute balance transfer at most once per nominator
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#777 remove unused import
  runtime/moonbase/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent

#781 Fixes build requirement for parachain tests
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent

#782 Removes parachain template
  .github/workflows/build.yml
  scripts/README.md
  scripts/generate-parachain-specs.sh
  specs/alphanet/parachain-specs-template.json
  tools/launch.ts
Labels: A8-mergeoncegreen, B0-silent

#779 update deps and republish
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
Labels: A8-mergeoncegreen, B0-silent, C1-low

#769 Use createBlockWithExtrinsic where necessary
  tests/package.json
  tests/tests/test-author-mapping.ts
  tests/tests/test-parachain-bond.ts
  tests/tests/test-sudo.ts
Labels: B0-silent

#727 Selective runtime at compilation
  .cargo/config.toml
  .gitignore
  node/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/fake_spec.rs
  node/service/src/chain_spec/mod.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
  tools/README.md
Labels: B0-silent, B5-clientnoteworthy

#780 Trigger CI by PR instead of push
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent

#784 Pin frontier `a9464d7`
  Cargo.lock
Labels: A0-pleasereview, B5-clientnoteworthy, B7-runtimenoteworthy

#787 Prune dead comment
  Cargo.toml
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#788 Migrate from pallet version to storage version
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low, D1-runtime-migration

#785 Adapt CI for conditional tracing
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent

#778 Add `evm-tracing` feature
  node/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/rpc.rs
  node/service/src/rpc/tracing.rs
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/debug/src/proxy/types/evm_gasometer_types.rs
  primitives/rpc/debug/src/proxy/types/evm_runtime_types.rs
  primitives/rpc/debug/src/proxy/types/evm_types.rs
  runtime/common/src/apis.rs
  runtime/evm_tracer/Cargo.toml
  runtime/evm_tracer/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
  tests/package.json
  tests/tracing-tests/test-trace-concurrency.ts
  tests/tracing-tests/test-trace-filter-reorg.ts
  tests/tracing-tests/test-trace-filter.ts
  tests/tracing-tests/test-trace-gas.ts
  tests/tracing-tests/test-trace.ts
  tests/util/constants.ts
  tests/util/dev-node.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, B7-runtimenoteworthy, A10-evmtracing

#695 Add identity pallet
  Cargo.lock
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#792 Update ci to check for un-updated package-lock files
  .github/workflows/build.yml
  moonbeam-types-bundle/package-lock.json
Labels: A8-mergeoncegreen, B0-silent, C1-low, ci

#744 Run collator election during slot prediction
  Cargo.lock
  runtime/common/src/apis.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#766 add test for wrong contract address call
  tests/util/transactions.ts
  tools/test-scripts/create-erc20-contract.ts
  tools/test-scripts/test-alpha.ts
  tools/test-scripts/test-staking.ts
  tools/test-scripts/test-wrong-contract-address.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low

#794 rework tracing ci: always run all "classic" ci jobs
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent

#799 Upgrade client to v0.12.0
  Cargo.lock
  README.md
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C1-low

#798 Update ethers.js
  tests/package-lock.json
  tests/package.json
Labels: A0-pleasereview, B0-silent, C1-low

#802 Updates substrate version
  Cargo.lock
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#808 Point frontier at 6da65d9405cb8eac8e2b8c9397182b8fca128f88
  Cargo.lock
Labels: A0-pleasereview, B5-clientnoteworthy

#809 Client release v0.12.2
  Cargo.lock
  README.md
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#807 Allow staking proxies to modify author mapping
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#800 Test to show nominator_bond_less decreases the nomination amount for nominator state
  pallets/parachain-staking/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, I4-tests 🎯

#795 [CI] Use compressed WASM in publish-runtime-draft
  .github/workflows/publish-runtime.yml
  tools/github/generate-runtimes-body.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#812 Fix wrong commit hash in PRs CI
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent

#789 Fix one runtime compilation + remove useless deps + impl dev spec for all runtimes
  Cargo.lock
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/mod.rs
  node/service/src/chain_spec/test_spec.rs
  node/service/src/client.rs
  node/service/src/lib.rs
Labels: B0-silent

#815 Simplify precompile trait bounds
  precompiles/parachain-staking/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/src/precompiles.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#581 Re-Prioritize pool transactions by effective gas price
  Cargo.lock
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#813 [ci] Publish blake2 hash and parachain.authorizeUpgrade in release notes
  tools/github/generate-runtimes-body.ts
Labels: B0-silent

#816 Add threshold and change cumulus block provider to cr
  Cargo.lock
  moonbeam-types-bundle/index.ts
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/crowdloan-rewards/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-crowdloan.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#625 ERC20 Precompile for pallet_balances
  Cargo.lock
  precompiles/balances-erc20/Cargo.toml
  precompiles/balances-erc20/ERC20.sol
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/mock.rs
  precompiles/balances-erc20/src/tests.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  tests/tests/test-precompile-erc20.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#680 Xcm with pallet assets and xtokens
  Cargo.lock
  core-primitives/src/lib.rs
  pallets/asset-manager/Cargo.toml
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/mock.rs
  pallets/asset-manager/src/tests.rs
  primitives/xcm/Cargo.toml
  primitives/xcm/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/package.json
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#820 Forces transaction receipt only on canonical (bump frontier)
  Cargo.lock
  client/rpc/debug/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#821 Upgrade client to version 0.12.3
  Cargo.lock
  README.md
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#825 Upgrade runtime to 700
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#822 Add indices to moonbeam runtime enum
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
Labels: A0-pleasereview, B0-silent

#679 Secure hasher in AuthorMapping
  Cargo.lock
  pallets/author-mapping/Cargo.toml
  pallets/author-mapping/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low, D1-runtime-migration

#832 Fixes the collator reward wrong percentage
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#828 Patch staking client author prediction bug
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C7-high

#594 TS Test Democracy
  .github/workflows/build.yml
  moonbeam-types-bundle/package.json
  tests/package.json
  tests/tests/test-democracy.ts
  tests/tests/test-governance.ts
  tests/util/constants.ts
  tests/util/governance.ts
Labels: A0-pleasereview, B0-silent, C1-low

#819 Set --execution wasm as default
  node/cli/src/command.rs
Labels: B5-clientnoteworthy

#818 TS Test type XCM
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
  tests/package-lock.json
  tests/package.json
  tests/para-tests-no-ci/test-xcm-para.ts
  tests/para-tests/moonriver/test-balance-genesis.ts
  tests/tests/test-asset-manager.ts
  tests/tests/test-precompile-staking.ts
  tests/tests/test-staking.ts
  tests/tests/test-sudo.ts
  tests/util/para-node.ts
  tests/util/providers.ts
  tests/util/setup-para-tests.ts
  tests/util/substrate-rpc.ts
  tools/launch.ts
  tools/package.json
  tools/yarn.lock
Labels: A0-pleasereview, B0-silent, C3-medium

#790 Test nominate bond more and less
  tests/package.json
  tests/tests/test-staking.ts
  tests/util/constants.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low

#527 pallet-migrations Initial Implementation
  Cargo.lock
  Cargo.toml
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  pallets/migrations/Cargo.toml
  pallets/migrations/src/lib.rs
  pallets/migrations/src/mock.rs
  pallets/migrations/src/tests.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: A1-needsburnin, A8-mergeoncegreen, B7-runtimenoteworthy

#676 Add transfer test using txwrapper
  tests/package-lock.json
  tests/package.json
  tests/tests/test-balance-transfer-txwrapper-substrate.ts
  tests/util/setup-dev-tests.ts
  tests/util/transactions.ts
Labels: A0-pleasereview, B0-silent, C1-low

#839 Add democracy precompile address to used list
  runtime/moonbase/src/precompiles.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#838 Add readme and method to export json
  moonbeam-types-bundle/.gitignore
  moonbeam-types-bundle/README.md
  moonbeam-types-bundle/generateJSON.ts
  moonbeam-types-bundle/index.ts
Labels: A0-pleasereview, B0-silent, C1-low

#840 Make precompile utils slightly more useful
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/utils/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#791 Unified client for regular and tracing nodes
  .github/workflows/build.yml
  .vscode/tasks.json
  Cargo.lock
  Cargo.toml
  client/evm-tracing/Cargo.toml
  client/evm-tracing/src/formatters/blockscout.rs
  client/evm-tracing/src/formatters/mod.rs
  client/evm-tracing/src/formatters/raw.rs
  client/evm-tracing/src/formatters/trace_filter.rs
  client/evm-tracing/src/lib.rs
  client/evm-tracing/src/listeners/call_list.rs
  client/evm-tracing/src/listeners/mod.rs
  client/evm-tracing/src/listeners/raw.rs
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/debug/src/lib.rs
  client/rpc-core/trace/src/lib.rs
  client/rpc/debug/Cargo.toml
  client/rpc/debug/src/lib.rs
  client/rpc/trace/Cargo.toml
  client/rpc/trace/src/lib.rs
  node/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/rpc.rs
  primitives/ext/Cargo.toml
  primitives/ext/src/lib.rs
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/debug/src/api/block.rs
  primitives/rpc/debug/src/api/mod.rs
  primitives/rpc/debug/src/api/single.rs
  primitives/rpc/debug/src/lib.rs
  primitives/rpc/debug/src/proxy/v1/mod.rs
  primitives/rpc/evm-tracing-events/Cargo.toml
  primitives/rpc/evm-tracing-events/src/evm.rs
  primitives/rpc/evm-tracing-events/src/gasometer.rs
  primitives/rpc/evm-tracing-events/src/lib.rs
  primitives/rpc/evm-tracing-events/src/runtime.rs
  runtime/common/src/apis.rs
  runtime/evm_tracer/Cargo.toml
  runtime/evm_tracer/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/tests/evm_tracing.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/tests/evm_tracing.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/tests/evm_tracing.rs
  runtime/moonriver/tests/runtime_apis.rs
  tests/util/dev-node.ts
Labels: A6-seemsok, B5-clientnoteworthy, B3-apinoteworthy, B7-runtimenoteworthy, A10-evmtracing

#845 Add `on_nonzero_unbalanced()` impl to all runtimes
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C7-high, D0-patchthis

#843 Create proc macro keccak256
  precompiles/balances-erc20/src/lib.rs
  precompiles/utils/macro/src/lib.rs
  precompiles/utils/macro/tests/tests.rs
  precompiles/utils/src/lib.rs
Labels: B0-silent

#849 moonbase need westend
  node/cli/Cargo.toml
Labels: B0-silent

#852 Trace known Ethereum transactions only
  client/rpc/trace/src/lib.rs
  primitives/rpc/debug/src/lib.rs
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/tests/evm_tracing.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/tests/evm_tracing.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/tests/evm_tracing.rs
Labels: A0-pleasereview, B5-clientnoteworthy, B7-runtimenoteworthy, A10-evmtracing

#846 Correct gas used for simple transfers in raw tracing
  client/evm-tracing/src/listeners/raw.rs
  tests/tracing-tests/test-trace.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, A10-evmtracing

#850 Improve tracing ci
  .cargo/config.toml
  .github/workflows/build.yml
  node/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, A10-evmtracing

#857 Fix deploy docs CI
  .github/workflows/docs.yml
Labels: B0-silent

#841 Forces to use commit branch/tag associated with release
  .github/workflows/publish-runtime.yml
Labels: A8-mergeoncegreen, B0-silent

#859 Pallet ParachainSystem must have index 1
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-polkadot-api.ts
  tests/tests/test-treasury-proposal.ts
Labels: B7-runtimenoteworthy

#862 Revert "Erc20 metadata for native tokens (DEV)"
  precompiles/balances-erc20/ERC20.sol
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/mock.rs
  precompiles/balances-erc20/src/tests.rs
  runtime/moonbase/src/precompiles.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#826 Update substrate dependencies to `polkadot-v0.9.10` series
  Cargo.lock
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/txpool/Cargo.toml
  client/rpc/debug/Cargo.toml
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  core-primitives/Cargo.toml
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli-opt/src/account_key.rs
  node/cli/Cargo.toml
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/rpc.rs
  pallets/asset-manager/Cargo.toml
  pallets/author-mapping/Cargo.toml
  pallets/ethereum-chain-id/Cargo.toml
  pallets/maintenance-mode/Cargo.toml
  pallets/migrations/Cargo.toml
  pallets/parachain-staking/Cargo.toml
  precompiles/balances-erc20/Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/pallet-democracy/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  precompiles/utils/Cargo.toml
  primitives/account/Cargo.toml
  primitives/account/src/lib.rs
  primitives/ext/Cargo.toml
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/evm-tracing-events/src/evm.rs
  primitives/rpc/evm-tracing-events/src/gasometer.rs
  primitives/rpc/evm-tracing-events/src/runtime.rs
  primitives/rpc/txpool/Cargo.toml
  primitives/xcm/Cargo.toml
  primitives/xcm/src/lib.rs
  runtime/common/Cargo.toml
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  tests/tests/test-block-gas.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C3-medium

#847 Etherscan support
  Cargo.lock
  client/evm-tracing/Cargo.toml
  client/evm-tracing/src/formatters/blockscout.rs
  client/evm-tracing/src/formatters/call_tracer.rs
  client/evm-tracing/src/formatters/mod.rs
  client/evm-tracing/src/formatters/raw.rs
  client/evm-tracing/src/formatters/trace_filter.rs
  client/evm-tracing/src/lib.rs
  client/evm-tracing/src/listeners/call_list.rs
  client/evm-tracing/src/listeners/raw.rs
  client/evm-tracing/src/types/block.rs
  client/evm-tracing/src/types/mod.rs
  client/evm-tracing/src/types/serialization.rs
  client/evm-tracing/src/types/single.rs
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/debug/src/lib.rs
  client/rpc-core/trace/Cargo.toml
  client/rpc-core/trace/src/lib.rs
  client/rpc-core/types/Cargo.toml
  client/rpc-core/types/src/lib.rs
  client/rpc/debug/Cargo.toml
  client/rpc/debug/src/lib.rs
  client/rpc/trace/Cargo.toml
  client/rpc/trace/src/lib.rs
  primitives/rpc/debug/src/api/block.rs
  primitives/rpc/debug/src/api/mod.rs
  primitives/rpc/debug/src/api/single.rs
  primitives/rpc/debug/src/lib.rs
  primitives/rpc/evm-tracing-events/Cargo.toml
  primitives/rpc/evm-tracing-events/src/lib.rs
  tests/package.json
  tests/tracing-tests/test-trace.ts
Labels: A0-pleasereview, B5-clientnoteworthy, A10-evmtracing

#864 Add test to make sure evm is only callable through sudo
  tests/package.json
  tests/tests/test-pallet-evm-transfer.ts
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low

#867 fix sp-std client evm tracing dependency
  Cargo.lock
  client/evm-tracing/Cargo.toml
Labels: B0-silent

#870 Revert "Pallet ParachainSystem must have index 1 (#859)"
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-polkadot-api.ts
  tests/tests/test-treasury-proposal.ts
Labels: B0-silent

#866 Bump to newer Rust nightly
  rust-toolchain
Labels: A0-pleasereview, A2-insubstantial, B0-silent, C1-low

#868 Fix precompile-utils arrays + bytes/string support
  precompiles/utils/src/data.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/tests.rs
Labels: A0-pleasereview, B0-silent

#865 Create client v0.13.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy
