Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-04, with the labels that each got.

#329 Allow purging relay and para separately
  Cargo.lock
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
Labels: A0-pleasereview, B5-clientnoteworthy, C1-low

#342 fix readme links
  README.md
Labels: A2-insubstantial

#335 move staking test spec to node/chainspec
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/command.rs
  node/src/main.rs
  node/src/test_spec.rs
  tools/config_moonbeam_staking.json
  tools/staking-test-spec.json
Labels: A0-pleasereview, B0-silent

#344 Restrict `pallet_evm::Call` access to root
  runtime/src/lib.rs
Labels: A0-pleasereview, B2-breaksapi, B7-runtimenoteworthy, C1-low

#363 improve parachain-staking test externalities
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B0-silent

#349 Make purge-chain work with dev service
  node/src/command.rs
Labels: A0-pleasereview, B0-silent, C3-medium

#339 rust runtime integration tests
  Cargo.lock
  runtime/Cargo.toml
  runtime/tests/integration_test.rs
Labels: A0-pleasereview, B0-silent

#382 Patch stake inflation bug
  moonbeam-types-bundle/index.ts
  node/src/chain_spec.rs
  pallets/parachain-staking/src/inflation.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  runtime/src/lib.rs
  runtime/tests/integration_test.rs
  specs/alphanet/parachain-specs-template.json
  specs/stagenet/parachain-specs-template.json
  tests/tests/test-stake.ts
Labels: A0-pleasereview, C7-high
