Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-06, with the labels that each got.

#455 Use cumulus's `RunCmd` (make --collator same as --validator)
  node/cli/src/cli.rs
  node/cli/src/command.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C3-medium

#489 Staking Early Optimizations and Sudo Dispatchable Tests
  Cargo.lock
  pallets/parachain-staking/Cargo.toml
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, C1-low

#495 Detect git problems in lockfile CI
  .github/workflows/release.yml
Labels: A8-mergeoncegreen, B0-silent, C1-low, ci

#501 Minor cleanups to servie
  node/cli/src/command.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low

#500 Add "key" subcommand
  node/cli/src/cli.rs
  node/cli/src/command.rs
Labels: B3-apinoteworthy, C3-medium

#508 Add benchmarking to CI
  .github/workflows/release.yml
  Cargo.lock
  node/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
Labels: A0-pleasereview, B0-silent

#498 Refactor identical code between runtimes in separate crate
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/common/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/Cargo.toml
  runtime/moonshadow/src/lib.rs
Labels: A8-mergeoncegreen

#510 Add `[Parachain]` log prefix
  node/service/src/lib.rs
Labels: B0-silent, C1-low

#517 Update nimbus comment to reflect current code
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, A8-mergeoncegreen, B0-silent, C1-low

#505 Patch nomination DOS vector
  Cargo.lock
  moonbeam-types-bundle/index.ts
  pallets/parachain-staking/Cargo.toml
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonshadow/src/lib.rs
  runtime/moonshadow/tests/integration_test.rs
  tests/tests/test-stake.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#525 [Staking] Benchmark Dispatchables (2)
  Cargo.lock
  pallets/parachain-staking/Cargo.toml
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonshadow/src/lib.rs
  runtime/moonshadow/tests/common/mod.rs
  runtime/moonshadow/tests/integration_test.rs
  runtime/precompiles/src/staking.rs
  scripts/run_benchmarks.sh
  tests/tests/test-stake.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#549 More robust fork test
  tests/tests/test-fork-chain.ts
Labels: B0-silent

#550 Fix wrong fmt
  node/cli/src/command.rs
Labels: B0-silent
