Repository moonbeam-foundation/moonbeam, pull requests merged in 2021-05, with the labels that each got.

#403 fix types and publish
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package.json
Labels: A8-mergeoncegreen, B0-silent, C1-low

#408 update types to fix apps
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package.json
  moonbeam-types-bundle/tsconfig.json
Labels: A8-mergeoncegreen, B0-silent, C1-low

#414 Block Signing
  Cargo.lock
Labels: A3-inprogress, B5-clientnoteworthy, C9-critical, D3-breaksconsensus, D4-breaksauthoring, D7-breakseverything, D9-needsaudit👮

#436 Remove NetApi TODO
  node/service/src/rpc.rs
  tests/tests/test-web3api.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low

#439 Bump Nimbus
  Cargo.lock
  pallets/author-mapping/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low

#442 Unit tests for Author Mapping
  Cargo.lock
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/chain_spec/moonshadow.rs
  pallets/author-mapping/Cargo.toml
  pallets/author-mapping/src/lib.rs
  pallets/author-mapping/src/mock.rs
  pallets/author-mapping/src/tests.rs
  pallets/parachain-staking/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonshadow/src/lib.rs
  runtime/moonshadow/tests/integration_test.rs
  specs/alphanet/parachain-specs-template.json
  tests/tests/test-stake.ts
  tests/util/constants.ts
Labels: A8-mergeoncegreen, B2-breaksapi, C1-low

#454 Add author filter call to all runtimes
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonshadow/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, C1-low
