Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-08, with the labels that each got.

#1715 Bump runtime to 1800
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial

#1716 Bump client version to v0.26.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial

#1717 update client release process
  tools/github/print-client-release-issue.ts
Labels: B0-silent, D2-notlive

#1701 Move note author to staking on finalize
  Cargo.lock
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/runtime_apis.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1709 Hrmp typescript tests utility functions
  tests/tests/test-xcm/test-mock-hrmp-asset-transfer.ts
  tests/tests/test-xcm/test-mock-hrmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
  tests/tests/test-xcm/test-mock-hrmp-transact.ts
  tests/util/xcm.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1727 Add randomness to all runtimes
  Cargo.lock
  runtime/common/src/apis.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1656 Bound length of Vec and Bytes when parsing precompile input
  precompiles/assets-erc20/src/lib.rs
  precompiles/batch/src/lib.rs
  precompiles/call-permit/src/lib.rs
  precompiles/pallet-democracy/src/lib.rs
  precompiles/relay-encoder/src/lib.rs
  precompiles/utils/src/data/mod.rs
  precompiles/utils/src/data/xcm.rs
  precompiles/utils/src/lib.rs
  precompiles/xcm-transactor/src/lib.rs
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1729 Change name of descend origin barrier
  primitives/xcm/src/barriers.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbeam/tests/xcm_mock/relay_chain.rs
  runtime/moonriver/tests/xcm_mock/relay_chain.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1708 Add precompile length fee test
  tests/tests/test-fees/test-length-fees.ts
Labels: B0-silent, D3-trivial

#1735 Fix staking benchmarking
  pallets/parachain-staking/src/benchmarks.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1736 fix tracing tests
  Cargo.lock
  precompiles/batch/Cargo.toml
  precompiles/call-permit/Cargo.toml
  precompiles/utils/Cargo.toml
  precompiles/xcm-transactor/Cargo.toml
  primitives/rpc/evm-tracing-events/Cargo.toml
  runtime/evm_tracer/Cargo.toml
Labels: B0-silent, A10-evmtracing, D2-notlive

#1737 add democracy enactment offset
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  tests/tests/test-democracy/test-democracy-genesis.ts
Labels: B7-runtimenoteworthy, D3-trivial

#1733 [MOON-1846] add call permit solidity test
  precompiles/call-permit/src/lib.rs
  precompiles/call-permit/src/tests.rs
  tests/contracts/compiled/CallPermitDemo.json
  tests/contracts/solidity/CallPermitDemo.sol
  tests/package-lock.json
  tests/package.json
  tests/tests/test-precompile/test-precompile-call-permit-demo.ts
  tests/util/constants.ts
Labels: B7-runtimenoteworthy, D3-trivial

#1713 Remove staking locks migration code
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  tests/tests/test-staking/test-staking-locks.ts
Labels: B3-apinoteworthy, B7-runtimenoteworthy, D2-breaksapi, D3-trivial

#1576 Tune extrinsic base fee
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-author/test-author-mapping.ts
  tests/tests/test-eth-tx/test-eth-tx-size.ts
  tests/tests/test-fees/test-length-fees.ts
  tests/tests/test-staking/test-staking-locks.ts
  tests/util/constants.ts
Labels: B7-runtimenoteworthy, D2-breaksapi, D3-breaksconsensus, D5-nicetohaveaudit⚠️, D10-breaksdocs

#1647 unify solidity interfaces
  precompiles/assets-erc20/ERC20.sol
  precompiles/assets-erc20/LocalAsset.sol
  precompiles/assets-erc20/Permit.sol
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  precompiles/author-mapping/AuthorMappingInterface.sol
  precompiles/author-mapping/src/lib.rs
  precompiles/author-mapping/src/tests.rs
  precompiles/balances-erc20/ERC20.sol
  precompiles/balances-erc20/Permit.sol
  precompiles/balances-erc20/src/tests.rs
  precompiles/batch/Batch.sol
  precompiles/batch/src/tests.rs
  precompiles/call-permit/CallPermit.sol
  precompiles/call-permit/src/tests.rs
  precompiles/crowdloan-rewards/CrowdloanInterface.sol
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/crowdloan-rewards/src/tests.rs
  precompiles/pallet-democracy/DemocracyInterface.sol
  precompiles/pallet-democracy/PoliticalPartyDao.sol
  precompiles/pallet-democracy/src/lib.rs
  precompiles/pallet-democracy/src/tests.rs
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  precompiles/randomness/Randomness.sol
  precompiles/randomness/src/tests.rs
  precompiles/relay-encoder/RelayEncoder.sol
  precompiles/relay-encoder/src/lib.rs
  precompiles/relay-encoder/src/tests.rs
  precompiles/utils/src/solidity.rs
  precompiles/utils/tests/solidity_test.sol
  precompiles/xcm-transactor/XcmTransactor.sol
  precompiles/xcm-transactor/src/lib.rs
  precompiles/xcm-transactor/src/tests.rs
  precompiles/xtokens/Xtokens.sol
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/tests.rs
Labels: B7-runtimenoteworthy, D1-audited👍

#1742 Use "original" type for BlockWeights
  runtime/moonbase/src/lib.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1740 use local metadata to generate typescript API
  .github/workflows/upgrade-typescript-api.yml
  typescript-api/scripts/runtime-upgrade.sh
Labels: B0-silent, D2-notlive

#1741 Pin frontier `9ba9c18`
  Cargo.lock
Labels: A0-pleasereview, B0-silent, D3-trivial

#1743 Add required deposit to randomness precompile
  precompiles/randomness/Randomness.sol
  precompiles/randomness/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1749 Update randomness lottery demo to use requiredDeposit
  tests/contracts/compiled/Randomness.json
  tests/contracts/compiled/RandomnessLotteryDemo.json
  tests/contracts/solidity/RandomnessLotteryDemo.sol
Labels: A0-pleasereview, B0-silent, D3-trivial

#584 Standard for the git branches in Moonbeam and Dependencies
  CONTRIBUTIONS.md
  docs/git-branches-conventions.md
Labels: A0-pleasereview, A3-inprogress, A9-buythat(wo)manabeer, B0-silent, C1-low, D2-notlive

#1734 Improve precompiles revert messages + fix few issues
  Cargo.lock
  precompiles/assets-erc20/src/eip2612.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  precompiles/author-mapping/src/lib.rs
  precompiles/author-mapping/src/tests.rs
  precompiles/balances-erc20/src/eip2612.rs
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/tests.rs
  precompiles/batch/src/lib.rs
  precompiles/batch/src/tests.rs
  precompiles/call-permit/src/lib.rs
  precompiles/call-permit/src/tests.rs
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/crowdloan-rewards/src/tests.rs
  precompiles/pallet-democracy/src/lib.rs
  precompiles/pallet-democracy/src/tests.rs
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  precompiles/randomness/src/lib.rs
  precompiles/randomness/src/solidity_types.rs
  precompiles/relay-encoder/src/lib.rs
  precompiles/relay-encoder/src/tests.rs
  precompiles/utils/Cargo.toml
  precompiles/utils/src/data/mod.rs
  precompiles/utils/src/data/xcm.rs
  precompiles/utils/src/handle.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/modifier.rs
  precompiles/utils/src/precompile_set.rs
  precompiles/utils/src/revert.rs
  precompiles/utils/src/testing.rs
  precompiles/utils/src/tests.rs
  precompiles/xcm-transactor/src/lib.rs
  precompiles/xcm-transactor/src/tests.rs
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/tests.rs
  tests/tests/test-contract/test-contract-delegate-call.ts
  tests/tests/test-randomness/test-randomness-babe-request.ts
  tests/tests/test-randomness/test-randomness-vrf-lottery.ts
  tests/tests/test-randomness/test-randomness-vrf-request.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1748 regenerate compiled contracts
  precompiles/randomness/src/lib.rs
  precompiles/relay-encoder/RelayEncoder.sol
  precompiles/utils/src/solidity.rs
  precompiles/utils/tests/solidity_test.sol
  tests/contracts/compiled/AuthorMapping.json
  tests/contracts/compiled/Batch.json
  tests/contracts/compiled/CallPermit.json
  tests/contracts/compiled/CallPermitDemo.json
  tests/contracts/compiled/CrowdloanRewards.json
  tests/contracts/compiled/Democracy.json
  tests/contracts/compiled/ERC20Instance.json
  tests/contracts/compiled/IERC20.json
  tests/contracts/compiled/LocalAsset.json
  tests/contracts/compiled/ParachainStaking.json
  tests/contracts/compiled/Permit.json
  tests/contracts/compiled/PoliticalPartyDao.json
  tests/contracts/compiled/RandomnessLotteryDemo.json
  tests/contracts/compiled/RelayEncoder.json
  tests/contracts/compiled/RelayEncoderInstance.json
  tests/contracts/compiled/SolidityTest.json
  tests/contracts/compiled/StakingAttacker.json
  tests/contracts/compiled/WrappedNativeCurrency.json
  tests/contracts/compiled/XcmTransactor.json
  tests/contracts/compiled/XcmTransactorInstance.json
  tests/contracts/compiled/Xtokens.json
  tests/contracts/compiled/XtokensInstance.json
  tests/contracts/solidity/RelayEncoderInstance.sol
  tests/contracts/solidity/XCMTransactorInstance.sol
  tests/contracts/solidity/XTokensInstance.sol
  tests/tests/test-precompile/test-precompile-author-mapping.ts
  tests/tests/test-precompile/test-precompile-democracy.ts
  tests/tests/test-precompile/test-precompile-relay-encoder.ts
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/tests/test-precompile/test-precompile-xcm-transactor.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
Labels: B0-silent, D2-notlive

#1724 EthereumXcm transact through proxy
  Cargo.lock
  pallets/ethereum-xcm/Cargo.toml
  pallets/ethereum-xcm/src/lib.rs
  pallets/ethereum-xcm/src/mock.rs
  pallets/ethereum-xcm/src/tests/v1/eip1559.rs
  pallets/ethereum-xcm/src/tests/v1/eip2930.rs
  pallets/ethereum-xcm/src/tests/v1/legacy.rs
  pallets/ethereum-xcm/src/tests/v2.rs
  primitives/xcm/src/ethereum_xcm.rs
  runtime/common/src/impl_moonbeam_xcm_call.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1732 Girazoki xcm utils ml to account
  Cargo.lock
  precompiles/xcm-utils/Cargo.toml
  precompiles/xcm-utils/XcmUtils.sol
  precompiles/xcm-utils/src/lib.rs
  precompiles/xcm-utils/src/mock.rs
  precompiles/xcm-utils/src/tests.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  tests/contracts/compiled/XcmUtils.json
  tests/tests/test-precompile/test-precompile-xcm-utils.ts
  tests/util/constants.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1731 throw proper error if relay url missing
  tests/util/setup-smoke-tests.ts
Labels: B0-silent, D2-notlive

#1705 [MOON-863] add proxy precompile
  Cargo.lock
  Cargo.toml
  precompiles/proxy/Cargo.toml
  precompiles/proxy/Proxy.sol
  precompiles/proxy/src/lib.rs
  precompiles/proxy/src/mock.rs
  precompiles/proxy/src/tests.rs
  precompiles/utils/src/testing.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  tests/contracts/compiled/CallForwarder.json
  tests/contracts/compiled/Proxy.json
  tests/contracts/compiled/ProxyCall.json
  tests/contracts/compiled/ProxyLeaderDemo.json
  tests/contracts/solidity/CallForwarder.sol
  tests/contracts/solidity/ProxyLeaderDemo.sol
  tests/tests/test-contract/test-contract-creation.ts
  tests/tests/test-contract/test-contract-delegate-call.ts
  tests/tests/test-eth-fee/test-eth-fee-history.ts
  tests/tests/test-ethers/test-ethers.ts
  tests/tests/test-evm/test-pallet-evm-transfer.ts
  tests/tests/test-gas/test-gas-contract-creation.ts
  tests/tests/test-gas/test-gas-estimation.ts
  tests/tests/test-precompile/test-precompile-batch.ts
  tests/tests/test-precompile/test-precompile-erc20-overflow.ts
  tests/tests/test-precompile/test-precompile-proxy.ts
  tests/tests/test-proxy/test-proxy-leader-demo.ts
  tests/tracing-tests/test-trace.ts
  tests/util/accounts.ts
  tests/util/constants.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1746 Decode Solidity bytes in precompile AuthorMapping::setKey
  precompiles/author-mapping/src/lib.rs
  precompiles/author-mapping/src/tests.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-precompile/test-precompile-author-mapping-keys.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1758 use read_args in author mapping precompile (fix master)
  precompiles/author-mapping/src/lib.rs
  tests/tests/test-precompile/test-precompile-author-mapping-keys.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1759 fix ts build errors
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
Labels: B0-silent, D2-notlive

#1719 Fix staking collator snapshot to use total counted instead of total exposure
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  tests/smoke-tests/test-staking-rewards.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1764 check reward amount only after RT1800
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#1723 New collective to accept and reject treasury spending proposal
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/chain_spec/test_spec.rs
  node/service/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  rust-toolchain
  tests/tests/test-treasury/test-treasury-proposal.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1706 Add CallPermit precompile to Moonriver and Moonbeam
  Cargo.lock
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium, D1-audited👍

#1760 [MOON-1763] deprecate delegator leave in favor of batch schedule revoke
  pallets/parachain-staking/src/lib.rs
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  tests/contracts/compiled/ParachainStaking.json
Labels: B7-runtimenoteworthy, D3-trivial

#1767 fix tracing tests
  tests/tracing-tests/test-trace-filter.ts
  tests/tracing-tests/test-trace.ts
Labels: B0-silent, A10-evmtracing, D2-notlive

#1750 Benchmark VRF verification
  Cargo.lock
  pallets/author-mapping/Cargo.toml
  pallets/author-mapping/src/lib.rs
  pallets/randomness/Cargo.toml
  pallets/randomness/src/benchmarks.rs
  pallets/randomness/src/lib.rs
  pallets/randomness/src/vrf.rs
  pallets/randomness/src/weights.rs
  primitives/session-keys/Cargo.toml
  primitives/session-keys/src/lib.rs
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1725 Girazoki refactor xcm transactor
  Cargo.lock
  pallets/xcm-transactor/Cargo.toml
  pallets/xcm-transactor/src/benchmarks.rs
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/tests.rs
  precompiles/xcm-transactor/Cargo.toml
  precompiles/xcm-transactor/src/functions.rs
  precompiles/xcm-transactor/src/lib.rs
  precompiles/xcm-transactor/src/mock.rs
  precompiles/xcm-transactor/src/tests.rs
  precompiles/xcm-transactor/src/v1/XcmTransactorV1.sol
  precompiles/xcm-transactor/src/v1/mod.rs
  precompiles/xcm-transactor/src/v2/XcmTransactorV2.sol
  precompiles/xcm-transactor/src/v2/mod.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_tests.rs
  tests/contracts/compiled/XcmTransactor.json
  tests/contracts/compiled/XcmTransactorV1.json
  tests/contracts/compiled/XcmTransactorV1Instance.json
  tests/contracts/compiled/XcmTransactorV2.json
  tests/contracts/compiled/XcmTransactorV2Instance.json
  tests/contracts/solidity/XCMTransactorInstance.sol
  tests/tests/test-maintenance/test-maintenance-filter.ts
  tests/tests/test-precompile/test-precompile-xcm-transactor.ts
  tests/util/constants.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D2-breaksapi, D9-needsaudit👮

#1770 Add OnFinality bootnode to Moonbeam
  specs/moonbeam/parachain-embedded-specs.json
Labels: B5-clientnoteworthy, D3-trivial

#1728 fix: orbiters was rewarded only on rounds with rotation
  pallets/moonbeam-orbiters/src/lib.rs
  pallets/moonbeam-orbiters/src/tests.rs
  tests/smoke-tests/test-orbiter-consistency.ts
  tests/util/common.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1769 Remove extra round whitelist
  runtime/common/src/apis.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1768 Benchmark randomness inherent
  pallets/randomness/src/benchmarks.rs
  pallets/randomness/src/lib.rs
  pallets/randomness/src/weights.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1776 Include client v0.26.0 in launch.ts config
  tools/launch.ts
Labels: B0-silent, D2-notlive

#1777 patch jsonrpsee: allow unknown fields in json requests
  Cargo.lock
  Cargo.toml
Labels: B5-clientnoteworthy, D3-trivial

#1755 add latest round in staking rewards smoke test log
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#1781 CI: step generate-release-body need GH authentication
  .github/workflows/publish-binary.yml
Labels: B0-silent, D2-notlive

#1780 [MOON-1885] fix staking rewards smoke test to account for Perbill arithmetic
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#1745 Set `LegacyTransaction` in `moonbeam-types-bundle`
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
Labels: A0-pleasereview, B0-silent, D3-trivial

#1786 bump RT and CLI versions
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial

#1721 Adds more consistency tests
  pallets/randomness/src/tests.rs
  tests/package-lock.json
  tests/package.json
  tests/smoke-tests/test-author-mapping-consistency.ts
  tests/smoke-tests/test-block-weight-per-class.ts
  tests/smoke-tests/test-ethereum-contract-code.ts
  tests/smoke-tests/test-ethereum-current-consistency.ts
  tests/smoke-tests/test-foreign-asset-consistency.ts
  tests/smoke-tests/test-local-asset-consistency.ts
  tests/smoke-tests/test-proxy-consistency.ts
  tests/smoke-tests/test-randomness-consistency.ts
  tests/smoke-tests/test-relay-xcm-fees.ts
  tests/smoke-tests/test-staking-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1788 Enable randomness for moonriver and moonbeam
  Cargo.lock
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1787 Fixes smoke test for runtime without randomness
  tests/smoke-tests/test-ethereum-current-consistency.ts
  tests/smoke-tests/test-randomness-consistency.ts
  tests/smoke-tests/test-staking-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1744 Add `BaseFeeElasticity` storage value update to migration code
  runtime/common/src/migrations.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D1-runtime-migration, D5-nicetohaveaudit⚠️

#1690 Add test for estimate gas invalid opcode response
  tests/tests/test-gas/test-gas-estimation.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1793 Adds more time for large smoke tests
  tests/smoke-tests/test-author-mapping-consistency.ts
  tests/smoke-tests/test-ethereum-contract-code.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1772 Girazoki test dispatch precompile bounds
  tests/tests/test-precompile/test-precompile-dispatch.ts
  tests/util/constants.ts
Labels: A0-pleasereview, B0-silent, I4-tests 🎯, D3-trivial

#1791 Base XCM weight increase
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-xcm/test-mock-dmp-error-and-appendix.ts
  tests/tests/test-xcm/test-mock-dmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-asset-transfer.ts
  tests/tests/test-xcm/test-mock-hrmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1789 Fix chi squared test
  tests/smoke-tests/test-randomness-consistency.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1784 Randomness pallet docs
  pallets/randomness/src/lib.rs
  pallets/randomness/src/mock.rs
  pallets/randomness/src/tests.rs
  pallets/randomness/src/types.rs
  pallets/randomness/src/vrf.rs
Labels: A0-pleasereview, B0-silent, D3-trivial
