Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-07, with the labels that each got.

#1642 Improve precompile-utils
  precompiles/assets-erc20/src/eip2612.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  precompiles/author-mapping/src/lib.rs
  precompiles/author-mapping/src/tests.rs
  precompiles/balances-erc20/src/eip2612.rs
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/tests.rs
  precompiles/batch/src/lib.rs
  precompiles/batch/src/tests.rs
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/crowdloan-rewards/src/tests.rs
  precompiles/pallet-democracy/src/lib.rs
  precompiles/pallet-democracy/src/tests.rs
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  precompiles/relay-encoder/src/lib.rs
  precompiles/relay-encoder/src/tests.rs
  precompiles/utils/src/costs.rs
  precompiles/utils/src/data/mod.rs
  precompiles/utils/src/data/xcm.rs
  precompiles/utils/src/handle.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/logs.rs
  precompiles/utils/src/modifier.rs
  precompiles/utils/src/substrate.rs
  precompiles/utils/src/testing.rs
  precompiles/utils/src/tests.rs
  precompiles/xcm-transactor/src/lib.rs
  precompiles/xcm-transactor/src/tests.rs
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/tests.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1648 Update call-permit following precompile-utils changes
  precompiles/call-permit/src/lib.rs
  precompiles/call-permit/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial

#1652 Fix typo and update launch version
  tools/launch.ts
  tools/package-lock.json
  tools/package.json
Labels: A0-pleasereview, B0-silent, D3-trivial

#1650 fix tracing tests
  tests/package.json
  tests/tracing-tests/test-trace-filter.ts
  tests/tracing-tests/test-trace.ts
Labels: B0-silent, A10-evmtracing, D2-notlive

#1658 Pin frontier `81c4b28`
  Cargo.lock
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1644 fix solidity test file and add randomness precompile tests
  precompiles/randomness/src/tests.rs
  precompiles/utils/solidity_test.sol
  precompiles/utils/src/solidity.rs
  precompiles/utils/tests/solidity_test.sol
  runtime/moonbase/src/lib.rs
  tests/contracts/compiled/Randomness.json
  tests/para-tests/moonbase/test-runtime-upgrade.ts
  tests/tests/test-precompile/test-precompile-randomness-vrf.ts
  tests/tests/test-xcm/test-mock-hrmp.ts
  tests/util/constants.ts
Labels: B0-silent, D3-trivial

#1657 Improve batch precompile docs
  precompiles/batch/Batch.sol
Labels: A0-pleasereview, B0-silent, D2-notlive

#1664 Add weight trader tests
  primitives/xcm/src/fee_handlers.rs
  tests/tests/test-xcm/test-mock-hrmp.ts
Labels: B0-silent, D9-needsaudit👮

#1665 Adds support for solidity test in subfolders
  tests/contracts/compiled/Batch.json
  tests/contracts/compiled/ParachainStaking.json
  tests/contracts/compiled/SolidityTest.json
  tests/contracts/compiled/StakingAttacker.json
  tests/tests/test-xcm/test-mock-hrmp.ts
  tests/tools/pre-build-contracts.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1666 Increase srtool version to 1.62.0 (rootless docker image)
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D2-notlive

#1670 [MOON-1510] add check-features build action
  .github/workflows/check-features.yml
Labels: B0-silent, ci, D2-notlive

#1669 Redesign Randomness Precompile Interface
  precompiles/randomness/Randomness.sol
  precompiles/randomness/RandomnessConsumer.sol
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1660 Consistent WEIGHT_FEE
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  tests/tests/test-fees/test-length-fees.ts
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, D3-trivial

#1534 refactor tests for parachain staking
  pallets/parachain-staking/src/tests.rs
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/tests/test-staking/test-candidate-join.ts
  tests/tests/test-staking/test-candidate-leave.ts
  tests/tests/test-staking/test-delegation-scheduled-requests.ts
  tests/tests/test-staking/test-delegator-bond-more.ts
  tests/tests/test-staking/test-delegator-join.ts
  tests/tests/test-staking/test-delegator-leave.ts
  tests/tests/test-staking/test-genesis.ts
  tests/tests/test-staking/test-parachain-bond.ts
  tests/tests/test-staking/test-rewards.ts
  tests/tests/test-staking/test-staking-consts.ts
  tests/tests/test-staking/test-staking-locks.ts
  tests/tests/test-staking/test-staking.ts
  tests/util/block.ts
  tests/util/expect.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1673 Fix geth error mismatches
  Cargo.lock
  tests/tests/test-block/test-block-gas.ts
  tests/tests/test-eth-pool/test-eth-pool-error.ts
  tests/util/transactions.ts
Labels: A0-pleasereview, B5-clientnoteworthy, D3-trivial

#1671 Girazoki remove xcm migrations
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1679 [Companion] Updates cumulus to cherry-picked beed leak fix
  Cargo.lock
Labels: A0-pleasereview, B5-clientnoteworthy, D3-trivial

#1680 Filter anonymous proxy
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, B7-runtimenoteworthy, D3-trivial

#1676 Girazoki test limits outbound xcmp queue
  tests/tests/test-xcm/test-mock-hrmp.ts
  tests/util/xcm.ts
Labels: B0-silent, D3-trivial

#1678 Temp receipt root fix
  Cargo.lock
  tests/package-lock.json
  tests/package.json
  tests/tests/test-receipt/test-receipt-root.ts
Labels: A0-pleasereview, B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮

#1682 Reduces gas limit in ethereum transaction for test
  tests/tests/test-eth-tx/test-eth-tx-types.ts
  tests/tests/test-subscription/test-subscription.ts
  tests/tests/test-txpool/test-txpool-pending.ts
  tests/util/transactions.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1685 Support 1700 new api-augment
  tests/smoke-tests/test-relay-xcm-fees.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1687 bump client version to v0.25.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial

#1688 fix author inherent benchmark
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B0-silent, D3-trivial

#1681 Refactor and add new xcm tests
  tests/tests/test-assets/test-asset-manager.ts
  tests/tests/test-xcm/test-mock-dmp-asset-transfer.ts
  tests/tests/test-xcm/test-mock-dmp-error-and-appendix.ts
  tests/tests/test-xcm/test-mock-dmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-asset-transfer.ts
  tests/tests/test-xcm/test-mock-hrmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-transact.ts
  tests/tests/test-xcm/test-mock-hrmp.ts
  tests/util/assets.ts
  tests/util/xcm.ts
Labels: B0-silent, I4-tests 🎯, D3-trivial

#1692 fix tracing tests: 1000 loop require higher gas limit
  tests/tracing-tests/test-trace-gas.ts
Labels: B0-silent, A10-evmtracing, D2-notlive

#1702 [MOON-1745] re-add status Leaving as deprecated
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  tests/tests/test-staking/test-delegator-join.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1704 Note about diener in README.md
  README.md
Labels: B0-silent, D3-trivial

#1695 Read both delegator and collator migration storage
  tests/smoke-tests/test-balances-consistency.ts
Labels: B0-silent, D3-trivial

#1655 Test substrate events after evm revert/success
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1700 [MOON-1806] remove deprecated parachain-staking items
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/tests.rs
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  runtime/common/src/migrations.rs
  tests/package-lock.json
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/util/transactions.ts
Labels: B7-runtimenoteworthy, D2-breaksapi, D5-nicetohaveaudit⚠️

#1581 [MOON-1718] add benchmark PoV analysis script
  tools/pov/README.md
  tools/pov/index.ts
Labels: A0-pleasereview, B0-silent, D2-notlive

#1712 Add identity judgement reserves
  tests/smoke-tests/test-balances-consistency.ts
Labels: B0-silent, D2-notlive

#1710 Precompiles `revert` function abi-encoded output
  precompiles/batch/src/tests.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/testing.rs
  precompiles/utils/src/tests.rs
  tests/tests/test-contract/test-contract-delegate-call.ts
  tests/tests/test-precompile/test-precompile-erc20.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️
