Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-11, with the labels that each got.

#1921 fix ed25519 again by passing reference to the signature
  Cargo.lock
Labels: A0-pleasereview, B5-clientnoteworthy, D3-trivial

#1907 [Moon-1953] Refactor staking tests, reset events between blocks
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
Labels: B0-silent, D2-notlive

#1925 Adds support for typescript-api generated types in tests
  .github/workflows/build.yml
  tests/package.json
Labels: B0-silent, D2-notlive

#1902 Change the way to obtain units per second
  precompiles/xcm-utils/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1930 Prevent AtStake smoke check on RT1901
  tests/smoke-tests/test-polkadot-decoding.ts
Labels: B0-silent, D2-notlive

#1929 staking smoke test - skip autoCompound if pending revoke
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#1872 Democracy Precompile events
  precompiles/pallet-democracy/DemocracyInterface.sol
  precompiles/pallet-democracy/src/lib.rs
  precompiles/pallet-democracy/src/tests.rs
  precompiles/utils/src/data/mod.rs
Labels: A3-inprogress, B7-runtimenoteworthy, D3-trivial

#1919 New Precompile tests
  tests/contracts/compiled/ERC20Instance.json
  tests/contracts/solidity/ERC20Instance.sol
  tests/package.json
  tests/tests/test-precompile/test-precompile-assets-erc20-low-level.ts
  tests/tests/test-precompile/test-precompile-assets-erc20.ts
Labels: B0-silent, D2-notlive

#1922 Fix trace block for ethereum xcm
  client/evm-tracing/src/formatters/call_tracer.rs
  runtime/common/src/impl_moonbeam_xcm_call_tracing.rs
  tests/tracing-tests/test-trace-ethereum-xcm.ts
Labels: A0-pleasereview, B5-clientnoteworthy, A10-evmtracing, D3-trivial

#1904 Fix democracy precompile log msg
  precompiles/pallet-democracy/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1893 Improve staking round change benchmarks
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
Labels: A0-pleasereview, B0-silent, D5-nicetohaveaudit⚠️

#1936 Update @polkadot/api
  tests/package-lock.json
  tests/package.json
Labels: A0-pleasereview, B0-silent, D3-trivial

#1935 [MOON-2006] change log level for failing to auto-compound to debug
  pallets/parachain-staking/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial

#1896 use AtStake to dispatch rewards instead of AwardedPts
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1937 [MOON-1941] use AllPalletsWithSystem for hook order
  pallets/maintenance-mode/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1934 [MOON-1943] add PayoutCollatorReward trait to override payout behavior for orbiters
  pallets/moonbeam-orbiters/src/lib.rs
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/traits.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1932 Adding AtStake Consistency Smoke Tests
  tests/package.json
  tests/smoke-tests/test-staking-rewards.ts
  tests/util/constants.ts
Labels: B0-silent, D2-notlive

#1940 Adhoc tracing test for live networks
  tests/smoke-tests/test-historic-compatibility.ts
  tests/util/tracing-txns.ts
Labels: B0-silent, D2-notlive

#1946 Roll out base_extrinsic_weight to all runtimes
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-fees/test-length-fees.ts
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, I5-documentation 📄

#1947 Filtered out test networks for smoke test
  tests/smoke-tests/test-historic-compatibility.ts
  tests/util/tracing-txns.ts
Labels: B0-silent, D2-notlive

#1948 Fix the build
  runtime/common/src/apis.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, D3-trivial

#1951 remove old staking benchmark tests
  pallets/parachain-staking/src/benchmarks.rs
Labels: B0-silent, D2-notlive, D3-trivial

#1895 Remove "reward for delegator" staking warn logs
  pallets/parachain-staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1961 New smoke test to detect emulated Ethereum txn failures
  .vscode/settings.json
  tests/smoke-tests/test-ethereum-failures.ts
Labels: B0-silent

#1963 Fix CI for external pr
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive

#1964 Fixing master build
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-block-weights.ts
  tests/tests/test-crowdloan/test-crowdloan.ts
  tests/tests/test-democracy/test-democracy-preimage.ts
  tests/tests/test-democracy/test-democracy-proposal.ts
  tests/tests/test-eth-fee/test-eth-txn-weights.ts
  tests/tests/test-precompile/test-precompile-democracy.ts
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
  tests/util/upgrade.ts
Labels: B0-silent, D2-notlive

#1962 Preimage lazy migration
  Cargo.lock
  pallets/migrations/Cargo.toml
  pallets/migrations/src/benchmarks.rs
  pallets/migrations/src/democracy_preimages.rs
  pallets/migrations/src/lib.rs
  pallets/migrations/src/mock.rs
  pallets/migrations/src/tests.rs
  pallets/migrations/src/weights.rs
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1955 New smoke tests for detecting XCM and ETH failures
  tests/smoke-tests/test-block-weights.ts
  tests/smoke-tests/test-ethereum-failures.ts
  tests/smoke-tests/test-xcm-failures.ts
  tests/tracing-tests/test-trace.ts
  tests/util/block.ts
Labels: B0-silent, D2-notlive

#1966 0.9.31 ts fixes
  tests/tests/test-assets/test-asset-manager.ts
  tests/tests/test-assets/test-assets-pallet.ts
  tests/tests/test-democracy/test-democracy-proposal.ts
  tests/tests/test-proxy/test-proxy-identity.ts
Labels: B0-silent, D2-notlive

#1959 update sha3 and libsecp256k1 dependencies
  Cargo.lock
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  node/cli-opt/Cargo.toml
  node/service/Cargo.toml
  precompiles/assets-erc20/Cargo.toml
  precompiles/balances-erc20/Cargo.toml
  precompiles/batch/Cargo.toml
  precompiles/call-permit/Cargo.toml
  precompiles/collective/Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  precompiles/proxy/Cargo.toml
  precompiles/relay-encoder/Cargo.toml
  precompiles/utils/Cargo.toml
  precompiles/utils/macro/Cargo.toml
  precompiles/utils/macro/src/generate_function_selector.rs
  precompiles/utils/macro/src/lib.rs
  precompiles/utils/macro/src/precompile/parse.rs
  precompiles/utils/macro/tests/tests.rs
  precompiles/xcm-transactor/Cargo.toml
  precompiles/xcm-utils/Cargo.toml
  precompiles/xtokens/Cargo.toml
  primitives/account/Cargo.toml
  primitives/xcm/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B5-clientnoteworthy, D3-trivial

#1967 fix(ci): job prepare-polkadot must never be skipped
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive

#1970 fix workflow check features
  .github/workflows/check-features.yml
Labels: B0-silent, D2-notlive

#1968 Added preimage bal check for staging
  tests/smoke-tests/test-balances-consistency.ts
Labels: B0-silent, D2-notlive

#1977 Included XCM originated calls for eth smoke tests
  tests/smoke-tests/test-ethereum-failures.ts
Labels: B0-silent, D2-notlive

#1978 upgrade srtool
  .github/workflows/publish-runtime.yml
Labels: B7-runtimenoteworthy, D3-trivial

#1979 Remove test for too expensive, as it is quite a common error
  tests/smoke-tests/test-xcm-failures.ts
Labels: A0-pleasereview, B0-silent, I4-tests 🎯, D3-trivial

#1974 Cherry-pick Frontier 892 and 898
  Cargo.lock
  tests/tests/test-eth-fee/test-eth-fee-history.ts
Labels: B5-clientnoteworthy, D3-trivial
