Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-06, with the labels that each got.

#1563 Fix local assets precompile interface selectors
  precompiles/assets-erc20/LocalAsset.sol
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1531 Girazoki remove moonbase runtime benchmarks flag
  .cargo/config.toml
  node/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B0-silent, C1-low, D3-trivial

#1567 enable xcm migrations for moonbeam
  runtime/moonbeam/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial

#1569 bring nimbus change kick off authorship validation
  Cargo.lock
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1516 Girazoki benchmark kick off authorship validaton
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B7-runtimenoteworthy, D3-trivial

#1577 Make `cargo test` from runtimes compile
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B0-silent, D3-trivial

#1584 Update runtime version to 1700
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial

#1586 [MOON-1745] re-add status Leaving as deprecated
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1591 fix indirect read of bond.amount value
  pallets/parachain-staking/src/delegation_requests.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, Z1-mentor

#1595 Add nesting limit to Batch precompile
  precompiles/batch/src/lib.rs
  precompiles/batch/src/mock.rs
  precompiles/batch/src/tests.rs
  precompiles/utils/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/src/precompiles.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮, D10-breaksdocs

#1593 Orbiters: add storage entry RegisteredOrbiter & events OrbiterRegistered & OrbiterUnRegistered
  pallets/moonbeam-orbiters/src/lib.rs
  pallets/moonbeam-orbiters/src/tests.rs
  pallets/moonbeam-orbiters/src/weights.rs
Labels: B7-runtimenoteworthy, D3-trivial

#1596 Update `exit-future` 0.2.0
  Cargo.lock
  node/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, D3-trivial

#1585 Configurable runtimes in ts tests for length fee changes
  tests/tests/test-assets/test-assets-sufficients.ts
  tests/tests/test-eth-tx/test-eth-tx-types.ts
  tests/tests/test-fees/test-length-fees.ts
  tests/util/dev-node.ts
  tests/util/setup-dev-tests.ts
Labels: B0-silent, I4-tests 🎯, D3-trivial

#1602 Fix dead link due to crate renaming
  pallets/parachain-staking/README.md
Labels: A8-mergeoncegreen, B0-silent, D10-breaksdocs, D2-notlive

#1574 add smoke tests for evaluating rewards
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#1599 update editorconfig-checker version
  .github/workflows/build.yml
Labels: B0-silent, ci, D2-notlive

#1607 Fixes smoke types
  tests/smoke-tests/test-staking-rewards.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1609 Improve smoke tests
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-staking-rewards.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1606 Fix tracing tests
  tests/package.json
  tests/tracing-tests/test-trace-filter.ts
  tests/tracing-tests/test-trace-gas.ts
  tests/tracing-tests/test-trace.ts
  tests/util/accounts.ts
Labels: B0-silent, A10-evmtracing, D2-notlive

#1612 Remove grandpa revert
  Cargo.lock
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
Labels: B5-clientnoteworthy, D3-trivial

#1598 Adds decoding smoke test
  tests/smoke-tests/test-polkadot-decoding.ts
Labels: B0-silent, D2-notlive

#1614 Upgrade test dependencies
  tests/package-lock.json
  tests/package.json
  tests/para-tests/moonbase/test-runtime-upgrade.ts
  tests/tests/test-balance/test-balance-transfer-txwrapper-substrate.ts
  tests/util/setup-para-tests.ts
Labels: B0-silent, D2-notlive

#1601 PrecompileSet util with opt-out checks
  precompiles/assets-erc20/src/lib.rs
  precompiles/batch/src/lib.rs
  precompiles/batch/src/mock.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/precompile_set.rs
  precompiles/utils/src/testing.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/src/precompiles.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1597 [MOON-1737] adds IdentityJudgement Proxy type support
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-proxy/test-proxy-identity.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1618 Restores support for 1500 runtime smoke tests
  tests/smoke-tests/test-orbiter-reserve-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1565 Girazoki add account20 hash struct
  Cargo.lock
  primitives/xcm/Cargo.toml
  primitives/xcm/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/tests/test-xcm/test-mock-hrmp.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1546 record raw tracing memory usage with limit
  client/evm-tracing/src/formatters/raw.rs
  client/evm-tracing/src/listeners/raw.rs
  client/rpc/debug/src/lib.rs
  node/cli-opt/src/lib.rs
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/rpc/tracing.rs
  tests/contracts/compiled/TracingHeavy.json
  tests/contracts/sources.ts
  tests/tracing-tests/test-trace.ts
Labels: A0-pleasereview, B5-clientnoteworthy, B3-apinoteworthy, D5-nicetohaveaudit⚠️, A10-evmtracing

#1627 Adds get-binary tools script
  tools/README.md
  tools/get-binary.ts
  tools/package.json
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1625 Staking Locks: JIT migration
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
  tests/para-tests/moonriver/test-balance-genesis.ts
  tests/smoke-tests/test-balances-consistency.ts
  tests/tests/test-author/test-author-mapping.ts
  tests/tests/test-balance/test-balance-existential.ts
  tests/tests/test-balance/test-balance-genesis.ts
  tests/tests/test-balance/test-balance-reducible.ts
  tests/tests/test-balance/test-balance-transfer-txwrapper-substrate.ts
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-crowdloan/test-crowdloan.ts
  tests/tests/test-precompile/test-precompile-erc20.ts
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/tests/test-staking/test-staking-consts.ts
  tests/tests/test-staking/test-staking-locks.ts
  tests/tests/test-staking/test-staking.ts
  tests/tests/test-sudo/test-sudo.ts
  tests/util/accounts.ts
  tests/util/block.ts
Labels: A0-pleasereview, A3-inprogress, B3-apinoteworthy, B7-runtimenoteworthy, D1-runtime-migration, D2-breaksapi, D9-needsaudit👮, D10-breaksdocs

#1635 Fixes dependency
  Cargo.lock
  client/rpc-core/txpool/Cargo.toml
  client/rpc/debug/Cargo.toml
  client/rpc/finality/Cargo.toml
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  core-primitives/Cargo.toml
  node/perf-test/Cargo.toml
  node/service/Cargo.toml
  precompiles/assets-erc20/Cargo.toml
  precompiles/author-mapping/Cargo.toml
  precompiles/balances-erc20/Cargo.toml
  precompiles/batch/Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/pallet-democracy/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  precompiles/relay-encoder/Cargo.toml
  precompiles/utils/Cargo.toml
  precompiles/xcm_transactor/Cargo.toml
  precompiles/xtokens/Cargo.toml
  runtime/common/Cargo.toml
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1634 [MOON-1378] endow test accounts
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/chain_spec/test_spec.rs
Labels: B7-runtimenoteworthy, D3-trivial

#1613 Adds rpc types to moonbeam-types-bundle
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package.json
  tests/package-lock.json
  tests/package.json
  tools/package-lock.json
  tools/package.json
  typescript-api/package-lock.json
  typescript-api/package.json
  typescript-api/scripts/generate-local-types.sh
  typescript-api/src/moonbase/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbase/interfaces/augment-types.ts
  typescript-api/src/moonbase/interfaces/definitions.ts
  typescript-api/src/moonbase/interfaces/empty/definitions.ts
  typescript-api/src/moonbase/interfaces/moon/definitions.ts
  typescript-api/src/moonbase/interfaces/moon/index.ts
  typescript-api/src/moonbase/interfaces/moon/types.ts
  typescript-api/src/moonbase/interfaces/types.ts
  typescript-api/src/moonbeam/interfaces/augment-api-consts.ts
  typescript-api/src/moonbeam/interfaces/augment-api-errors.ts
  typescript-api/src/moonbeam/interfaces/augment-api-events.ts
  typescript-api/src/moonbeam/interfaces/augment-api-query.ts
  typescript-api/src/moonbeam/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbeam/interfaces/augment-api-tx.ts
  typescript-api/src/moonbeam/interfaces/augment-types.ts
  typescript-api/src/moonbeam/interfaces/lookup.ts
  typescript-api/src/moonbeam/interfaces/registry.ts
  typescript-api/src/moonbeam/interfaces/types-lookup.ts
  typescript-api/src/moonriver/interfaces/augment-api-consts.ts
  typescript-api/src/moonriver/interfaces/augment-api-errors.ts
  typescript-api/src/moonriver/interfaces/augment-api-events.ts
  typescript-api/src/moonriver/interfaces/augment-api-query.ts
  typescript-api/src/moonriver/interfaces/augment-api-rpc.ts
  typescript-api/src/moonriver/interfaces/augment-api-tx.ts
  typescript-api/src/moonriver/interfaces/augment-types.ts
  typescript-api/src/moonriver/interfaces/lookup.ts
  typescript-api/src/moonriver/interfaces/registry.ts
  typescript-api/src/moonriver/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1617 Call Permit Precompile
  Cargo.lock
  Cargo.toml
  precompiles/balances-erc20/src/lib.rs
  precompiles/call-permit/CallPermit.sol
  precompiles/call-permit/Cargo.toml
  precompiles/call-permit/README.md
  precompiles/call-permit/src/lib.rs
  precompiles/call-permit/src/mock.rs
  precompiles/call-permit/src/tests.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1433 [WIP] Adds fork tests
  docker/moonbeam-fork-tests.Dockerfile
  scripts/run-fork-chain.sh
  scripts/run-fork-test.sh
  tests/README.md
  tests/fork-tests/test-pov-migration.ts
  tests/package.json
  tests/smoke-tests/test-relay-xcm-fees.ts
  tests/spawn-fork-node.ts
  tests/state-modifier.ts
  tests/util/constants.ts
  tests/util/governance.ts
  tests/util/para-node.ts
  tests/util/setup-para-tests.ts
  tools/extract-migration-logs.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1646 Prevent rust code formatting check to fail on spaces after tabs
  .ecrc
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive
