Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-02, with the labels that each got.

#1234 Fixes launch script support for runtime upgrade
  tools/launch.ts
Labels: A8-mergeoncegreen, B0-silent

#1241 Include SplitCandidateState migration in pallet-migrations
  runtime/common/src/migrations.rs
Labels: A0-pleasereview, B0-silent

#1245 Update frontier `b4729e6`
  Cargo.lock
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#1244 Patch evm `ExitError` variant
  Cargo.lock
  Cargo.toml
Labels: A8-mergeoncegreen, B0-silent

#1243 fix(tracing): support new blockscout js hash
  Cargo.lock
  README.md
  client/rpc/debug/Cargo.toml
  client/rpc/debug/src/lib.rs
  tests/tracing-tests/test-trace.ts
  tests/util/tracer/blockscout_tracer_v2.min.json
Labels: A8-mergeoncegreen, B5-clientnoteworthy, A10-evmtracing

#1246 ci: prettier: ignore non-relevant files
  .github/workflows/build.yml
  .prettierignore
Labels: A8-mergeoncegreen, B0-silent

#1189 Add ts tests for transaction by index rpc method
  tests/tests/test-tx-index-bound-check.ts
Labels: A0-pleasereview, B0-silent

#1252 Upgrade frontier
  Cargo.lock
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#1253 Client v0.19.1
  README.md
  tools/launch.ts
Labels: B0-silent

#1254 Client v0.19.1
  Cargo.lock
  README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#1263 Fix parent block eth hash calculation between runtime version
  Cargo.lock
Labels: A0-pleasereview, B7-runtimenoteworthy, A10-evmtracing

#1267 Fixes package-lock dependencies
  tests/package-lock.json
  tests/package.json
Labels: A8-mergeoncegreen, B0-silent

#1266 Runtime 1201
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent

#1270 Use storage overrides in debug and tracing modules
  client/rpc/debug/src/lib.rs
  client/rpc/trace/src/lib.rs
  node/service/src/rpc/tracing.rs
  tests/package-lock.json
  tests/package.json
Labels: A0-pleasereview, B5-clientnoteworthy, A10-evmtracing

#1265 Update frontier `32b7cf4`
  Cargo.lock
Labels: A0-pleasereview, B5-clientnoteworthy

#1274 Girazoki support both pre and post 0.9.16 anchoring logics for native token 0.9.16
  precompiles/xtokens/src/tests.rs
  primitives/xcm/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-mock-hrmp.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, B7-runtimenoteworthy

#1282 Bump frontier to include schema cache removal
  Cargo.lock
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#1283 Create client v0.20.1
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#1297 fix(ci): runtime release issue: add --client option
  .github/workflows/runtime-release-issue.yml
  tools/github/print-runtime-release-issue.ts
Labels: A8-mergeoncegreen, B0-silent

#1291 [Staking] Patch delegations total mismatch
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/tests.rs
  runtime/common/src/migrations.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1298 Add `BaseFeePerGas` storage value update to migration code
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: A0-pleasereview, B7-runtimenoteworthy, D1-runtime-migration

#1277 Add field names to pallet Event variants
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/tests.rs
  pallets/author-mapping/src/lib.rs
  pallets/author-mapping/src/tests.rs
  pallets/migrations/src/lib.rs
  pallets/migrations/src/tests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/tests.rs
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/tests.rs
  precompiles/author-mapping/src/tests.rs
  precompiles/parachain-staking/src/tests.rs
  precompiles/xcm_transactor/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy

#1292 Uncomment event and pin to new xtokens commit
  Cargo.lock
  precompiles/xtokens/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low

#1247 Adds parachain test for runtime upgrade/migrations
  .github/workflows/build.yml
  .gitignore
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
  tests/package-lock.json
  tests/package.json
  tests/para-tests-no-ci/test-xcm-para.ts
  tests/para-tests/moonbase/1200/skip-bug-ethereum-parent-hash.ts
  tests/para-tests/moonbase/1200/test-migration-split-staking.ts
  tests/para-tests/moonbase/1201/skip-ethereum-parent-hash.ts
  tests/para-tests/moonbase/1300/test-migration-fix-total-staking.ts
  tests/para-tests/moonbase/test-runtime-upgrade.ts
  tests/para-tests/moonriver/test-balance-genesis.ts
  tests/tests/test-assets-sufficients.ts
  tests/tests/test-author-mapping.ts
  tests/tests/test-balance/test-balance-extrinsics.ts
  tests/tests/test-balance/test-balance-genesis.ts
  tests/tests/test-balance/test-balance-transfer-txwrapper-substrate.ts
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-crowdloan.ts
  tests/tests/test-democracy.ts
  tests/tests/test-existential-deposit.ts
  tests/tests/test-mock-hrmp.ts
  tests/tests/test-polkadot-api.ts
  tests/tests/test-precompile/test-precompile-democracy.ts
  tests/tests/test-proxy/test-proxy-governance.ts
  tests/tests/test-staking.ts
  tests/tests/test-sudo.ts
  tests/tests/test-treasury-proposal.ts
  tests/util/block.ts
  tests/util/constants.ts
  tests/util/para-node.ts
  tests/util/setup-para-tests.ts
  tests/util/substrate-rpc.ts
  tests/util/transactions.ts
Labels: A8-mergeoncegreen, B0-silent

#1303 Pin frontier `eth_call` return code instead address
  Cargo.lock
  tests/tests/test-contract/test-contract-creation.ts
Labels: A0-pleasereview, B5-clientnoteworthy

#1309 Removing 1300 para test to investigate
  tests/para-tests/moonbase/1300/skip-migration-fix-total-staking.ts
Labels: A8-mergeoncegreen, B0-silent

#1276 Fix client debug unwrap issue
  client/rpc/debug/src/lib.rs
Labels: B5-clientnoteworthy

#1311 Adds rococo-9140 to launch script
  tools/launch.ts
Labels: A8-mergeoncegreen, B0-silent

#1312 CI: build opt internal binary: remove znver3
  .github/workflows/prepare-binary.yml
Labels: B0-silent

#1308 Add GLMR ERC20 precompile on Moonbeam
  Cargo.lock
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1236 Girazoki enable native asset cross chain transfer in moonriver
  Cargo.lock
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1307 [Staking] Remove request when delegation is kicked from bottom
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1118 Girazoki supported fee payment assets storage
  pallets/asset-manager/src/benchmarks.rs
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/migrations.rs
  pallets/asset-manager/src/tests.rs
  pallets/asset-manager/src/weights.rs
  primitives/xcm/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/tests/xcm_tests.rs
  tests/tests/test-asset-manager.ts
  tests/tests/test-mock-dmp.ts
  tests/tests/test-mock-hrmp.ts
  tests/tests/test-pallet-maintenance-mode.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1316 Fixes parachain tests with 0.9.16 relay
  tests/para-tests/moonbase/test-runtime-upgrade.ts
  tests/util/para-node.ts
Labels: A8-mergeoncegreen, B0-silent

#1223 Removal extrinsics for asset manager and xcm transactor
  Cargo.lock
  pallets/asset-manager/src/benchmarks.rs
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/tests.rs
  pallets/asset-manager/src/weights.rs
  pallets/xcm-transactor/Cargo.toml
  pallets/xcm-transactor/src/benchmarks.rs
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/tests.rs
  pallets/xcm-transactor/src/weights.rs
  precompiles/xcm_transactor/src/mock.rs
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1310 ci: introduce same clippy lints as substrate
  .cargo/config.toml
  .github/workflows/build.yml
  client/evm-tracing/src/formatters/call_tracer.rs
  client/rpc/debug/src/lib.rs
  client/rpc/txpool/src/lib.rs
  pallets/asset-manager/src/mock.rs
  pallets/parachain-staking/src/lib.rs
  precompiles/utils/src/data.rs
  primitives/account/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: B0-silent

#1239 Unskip EVM regression test
  tests/tests/test-evm-memory-allocation.ts
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent, D3-trivial

#1150 Add audit label enforcement to CI
  .github/workflows/enforce-pr-labels.yml
Labels: B0-silent, D3-trivial

#1222 Saturate all staking math ops
  pallets/migrations/src/lib.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
Labels: A2-insubstantial, A8-mergeoncegreen, B0-silent

#1322 v0.21.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: B0-silent, D3-trivial

#1324 Fix issues from migrating to clap v3
  Cargo.lock
  node/cli/src/cli.rs
Labels: A0-pleasereview, B5-clientnoteworthy, D3-trivial

#1299 Fix wrong "to" value in tracing for DelegateCall
  client/evm-tracing/src/listeners/call_list.rs
  tests/contracts/compiled/TestCallList.json
  tests/contracts/sources.ts
  tests/tracing-tests/test-trace.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, A10-evmtracing, D3-trivial

#1325 [Staking] More saturating ops
  pallets/parachain-staking/src/lib.rs
Labels: A0-pleasereview, B0-silent, D3-trivial
