Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-10, with the labels that each got.

#1841 Enable feature "forbid evm reentrancy"
  Cargo.lock
  node/service/Cargo.toml
  pallets/ethereum-xcm/Cargo.toml
  pallets/randomness/Cargo.toml
  precompiles/assets-erc20/Cargo.toml
  precompiles/author-mapping/Cargo.toml
  precompiles/balances-erc20/Cargo.toml
  precompiles/batch/Cargo.toml
  precompiles/call-permit/Cargo.toml
  precompiles/collective/Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/pallet-democracy/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  precompiles/proxy/Cargo.toml
  precompiles/randomness/Cargo.toml
  precompiles/relay-encoder/Cargo.toml
  precompiles/utils/Cargo.toml
  precompiles/xcm-transactor/Cargo.toml
  precompiles/xcm-utils/Cargo.toml
  precompiles/xtokens/Cargo.toml
  runtime/common/Cargo.toml
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1818 Adds zombienet tests
  .github/workflows/build.yml
  .vscode/launch.json
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
  scripts/run-fork-test.sh
  tests/.gitignore
  tests/README.md
  tests/package-lock.json
  tests/package.json
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-precompile/test-precompile-assets-erc20.ts
  tests/tests/test-proxy/test-proxy-identity.ts
  tests/tests/test-receipt/test-receipt-root.ts
  tests/util/block.ts
  tests/util/providers.ts
  tests/util/setup-dev-tests.ts
  tests/util/setup-para-tests.ts
  tests/util/setup-zombie-tests.ts
  tests/util/transactions.ts
  tests/zombie-tests/test-first-block.ts
  tests/zombienet/default-config.json
  tests/zombienet/moonbase.env
  typescript-api/package-lock.json
  typescript-api/package.json
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1843 Fix blockWeights access in smoke test
  tests/smoke-tests/test-relay-xcm-fees.ts
  tests/util/common.ts
Labels: B0-silent, I4-tests 🎯, D3-trivial

#1842 Removes forced branch on fork tests
  scripts/run-fork-test.sh
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1844 update lock with latest xtokens change
  Cargo.lock
Labels: B7-runtimenoteworthy, D3-trivial

#1504 ci: create a manual workflow to publish typescript API
  .github/workflows/publish-typescript-api.yml
Labels: B0-silent, ci, D2-notlive

#1846 Updates polkadot api for moonbeam type bundle
  moonbeam-types-bundle/package.json
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1847 Add non-sc proxy account smoke test
  tests/smoke-tests/test-proxy-consistency.ts
Labels: B0-silent, D2-notlive

#1840 impl missing Democracy precompile functions
  precompiles/pallet-democracy/DemocracyInterface.sol
  precompiles/pallet-democracy/src/lib.rs
  precompiles/pallet-democracy/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1852 fix try-runtime: Migrations should impl TryState
  pallets/maintenance-mode/src/types.rs
  runtime/common/src/apis.rs
Labels: B0-silent, D2-notlive

#1849 Test showing event is thrown per fragment, not per message
  tests/tests/test-xcm/test-mock-hrmp-queue.ts
Labels: B0-silent, I4-tests 🎯, D3-trivial

#1837 Girazoki benchmark orbiters on initialize
  pallets/moonbeam-orbiters/src/benchmarks.rs
  pallets/moonbeam-orbiters/src/lib.rs
  pallets/moonbeam-orbiters/src/weights.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1853 Add `MaximumMultiplier` as upper bound for dynamic fee multiplier
  Cargo.lock
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1826 Supports for highestSlotSeen in state modifier
  scripts/run-fork-chain.sh
  scripts/run-fork-test.sh
  tests/fork-tests/test-pov-migration.ts
  tests/package-lock.json
  tests/package.json
  tests/para-tests/moonbase/1200/skip-bug-ethereum-parent-hash.ts
  tests/para-tests/moonbase/1200/skip-test-migration-split-staking.ts
  tests/para-tests/moonbase/1201/skip-ethereum-parent-hash.ts
  tests/para-tests/moonbase/1300/skip-migration-fix-total-staking.ts
  tests/para-tests/moonbase/test-runtime-upgrade.ts
  tests/state-modifier.ts
  tests/util/binaries.ts
  tests/util/para-node.ts
  tests/util/providers.ts
  tests/util/setup-para-tests.ts
  tests/util/setup-zombie-tests.ts
  tests/util/upgrade.ts
  tests/zombie-tests/test-first-block.ts
  tests/zombienet/default-config.json
  tests/zombienet/fork-config.json
  tools/package-lock.json
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1854 Cherry-pick Frontier #857, #871, and #875
  Cargo.lock
Labels: A0-pleasereview, B0-silent, D3-trivial

#1822 Girazoki benchmark generic instructions xcm
  Cargo.lock
  pallets/asset-manager/src/lib.rs
  pallets/moonbeam-xcm-benchmarks/Cargo.toml
  pallets/moonbeam-xcm-benchmarks/src/generic/benchmarking.rs
  pallets/moonbeam-xcm-benchmarks/src/generic/mock.rs
  pallets/moonbeam-xcm-benchmarks/src/generic/mod.rs
  pallets/moonbeam-xcm-benchmarks/src/lib.rs
  pallets/moonbeam-xcm-benchmarks/src/mock.rs
  pallets/moonbeam-xcm-benchmarks/src/weights/mod.rs
  pallets/moonbeam-xcm-benchmarks/src/weights/moonbeam_xcm_benchmarks_fungible.rs
  pallets/moonbeam-xcm-benchmarks/src/weights/moonbeam_xcm_benchmarks_generic.rs
  primitives/xcm/src/fee_handlers.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/Cargo.toml
  tests/tests/test-precompile/test-precompile-xcm-utils.ts
  tests/tests/test-xcm/test-mock-dmp-asset-transfer.ts
  tests/tests/test-xcm/test-mock-dmp-error-and-appendix.ts
  tests/tests/test-xcm/test-mock-dmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-asset-transfer.ts
  tests/tests/test-xcm/test-mock-hrmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
  tests/util/xcm.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1828 [MOON-1902] autocompound staking rewards
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  pallets/parachain-staking/Cargo.toml
  pallets/parachain-staking/src/auto_compound.rs
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonriver/tests/common/mod.rs
  scripts/benchmarking.sh
  tests/tests/test-staking/test-delegate-with-auto-compound.ts
  tests/tests/test-staking/test-rewards-auto-compound.ts
  tests/tests/test-staking/test-set-auto-compound.ts
  tests/util/common.ts
  tools/pov/README.md
  tools/pov/index.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1850 Use `ChainId` in `EthereumXcm`
  pallets/ethereum-xcm/src/lib.rs
  primitives/xcm/src/ethereum_xcm.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1851 Added smoke test for block finalization
  tests/package-lock.json
  tests/package.json
  tests/smoke-tests/test-block-finalized.ts
  tests/smoke-tests/test-proxy-consistency.ts
  tests/util/block.ts
  tests/util/setup-smoke-tests.ts
Labels: B0-silent, D2-notlive

#1868 Fixes smoke test using previous types
  tests/smoke-tests/test-staking-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1869 Increase smoke test time
  tests/smoke-tests/test-block-finalized.ts
Labels: A8-mergeoncegreen, B0-silent

#1862 Frontier db v2 migration
  Cargo.lock
  client/rpc/debug/src/lib.rs
  client/rpc/finality/src/lib.rs
  node/service/src/lib.rs
  tests/util/upgrade.ts
Labels: A0-pleasereview, B5-clientnoteworthy, D3-trivial

#1865 Allows the fork test script to exit properly
  scripts/run-fork-test.sh
Labels: A3-inprogress, B0-silent, D2-notlive

#1871 Improves fork test for moon bot
  scripts/run-fork-test.sh
  tests/fork-tests/test-pov-migration.ts
Labels: B0-silent, D2-notlive

#1838 Gov2 (moonbase only)
  Cargo.lock
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/governance/councils.rs
  runtime/moonbase/src/governance/democracy.rs
  runtime/moonbase/src/governance/mod.rs
  runtime/moonbase/src/governance/origins.rs
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbase/src/governance/tracks.rs
  runtime/moonbase/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮

#1845 auto upgrade polkadot/api
  .github/workflows/publish-typescript-api.yml
  .github/workflows/upgrade-typescript-api.yml
Labels: B0-silent, D2-notlive

#1877 Patch pallet identity: check registrar is providing judgement for correct ID
  Cargo.lock
  tests/tests/test-proxy/test-proxy-identity.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1876 Allow is_static to be passed to precompiles
  Cargo.lock
  tests/contracts/compiled/StaticSubcall.json
  tests/contracts/solidity/StaticSubcall.sol
  tests/tests/test-randomness/test-randomness-vrf-lottery.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1878 add migration for AtStake stale entries + autocompound, fix for removing candidates without blocks from rewarded rounds
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/tests.rs
  runtime/common/src/migrations.rs
  tests/state-modifier.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1881 Run MigrateAtStakeAutoCompound only for unpaid rounds
  pallets/parachain-staking/src/migrations.rs
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1882 update weights, remove all entries from AtStake on round change
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/weights.rs
  tests/tests/test-staking/test-rewards-auto-compound.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1884 Align `GasWeightMapping` with Substrate `do_pre_dispatch` logic
  Cargo.lock
  pallets/ethereum-xcm/src/lib.rs
  pallets/ethereum-xcm/src/mock.rs
  precompiles/assets-erc20/src/mock.rs
  precompiles/author-mapping/src/mock.rs
  precompiles/balances-erc20/src/mock.rs
  precompiles/batch/src/mock.rs
  precompiles/call-permit/src/mock.rs
  precompiles/collective/src/mock.rs
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/pallet-democracy/src/mock.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/proxy/src/mock.rs
  precompiles/randomness/src/mock.rs
  precompiles/relay-encoder/src/mock.rs
  precompiles/xcm-transactor/src/mock.rs
  precompiles/xcm-utils/src/mock.rs
  precompiles/xtokens/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  tests/tests/test-eth-fee/test-eth-txn-weights.ts
  tests/tests/test-eth-tx/test-eth-tx-size.ts
  tests/util/block.ts
  tests/util/constants.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1888 Fix proxy precompile error message for smart contracts
  precompiles/proxy/src/lib.rs
  precompiles/proxy/src/tests.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1889 Add smoke test for block hash mapping db
  tests/smoke-tests/test-ethereum-db-mapping.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1891 launch conf for v0.27.0
  tools/launch.ts
Labels: B0-silent, D2-notlive

#1894 Properly destroy EtherJS Provider in smoke tests
  tests/util/setup-smoke-tests.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1875 add over percent tests for auto-compound, return error in precompiles
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  tests/tests/test-staking/test-delegate-with-auto-compound.ts
  tests/tests/test-staking/test-set-auto-compound.ts
Labels: B0-silent, D2-notlive, D3-trivial

#1890 add smoke test for staking snapshots
  tests/smoke-tests/test-staking-round-cleanup.ts
Labels: B0-silent, D2-notlive

#1873 Updated smoke tests to be compatible with forks
  scripts/run-fork-test.sh
  tests/fork-tests/test-pov-migration.ts
  tests/package-lock.json
  tests/package.json
  tests/smoke-tests/test-block-finalized.ts
  tests/smoke-tests/test-block-weight-per-class.ts
  tests/smoke-tests/test-ethereum-current-consistency.ts
  tests/smoke-tests/test-polkadot-decoding.ts
  tests/smoke-tests/test-relay-xcm-fees.ts
Labels: B0-silent, D2-notlive

#1898 upgrade @polkadot/typegen at typescript-api upgrade
  .github/workflows/upgrade-typescript-api.yml
Labels: B0-silent, D2-notlive

#1900 Missing 'view' modifiers in XC20 precompile
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  precompiles/author-mapping/src/tests.rs
  precompiles/balances-erc20/src/tests.rs
  precompiles/batch/src/tests.rs
  precompiles/call-permit/src/tests.rs
  precompiles/collective/src/tests.rs
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/crowdloan-rewards/src/tests.rs
  precompiles/pallet-democracy/src/tests.rs
  precompiles/parachain-staking/src/tests.rs
  precompiles/proxy/src/tests.rs
  precompiles/relay-encoder/src/tests.rs
  precompiles/utils/src/testing.rs
  precompiles/xcm-transactor/src/tests.rs
  precompiles/xcm-utils/Cargo.toml
  precompiles/xcm-utils/src/tests.rs
  precompiles/xtokens/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1899 Reuse ws connections between smoke tests
  tests/package-lock.json
  tests/package.json
  tests/smoke-tests/test-author-filter-consistency.ts
  tests/smoke-tests/test-author-mapping-consistency.ts
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-block-finalized.ts
  tests/smoke-tests/test-block-weight-per-class.ts
  tests/smoke-tests/test-ethereum-contract-code.ts
  tests/smoke-tests/test-ethereum-current-consistency.ts
  tests/smoke-tests/test-ethereum-db-mapping.ts
  tests/smoke-tests/test-foreign-asset-consistency.ts
  tests/smoke-tests/test-local-asset-consistency.ts
  tests/smoke-tests/test-orbiter-consistency.ts
  tests/smoke-tests/test-polkadot-decoding.ts
  tests/smoke-tests/test-proxy-consistency.ts
  tests/smoke-tests/test-randomness-consistency.ts
  tests/smoke-tests/test-relay-xcm-fees.ts
  tests/smoke-tests/test-staking-consistency.ts
  tests/smoke-tests/test-staking-rewards.ts
  tests/smoke-tests/test-staking-round-cleanup.ts
  tests/smoke-tests/test-treasury-consistency.ts
  tests/util/setup-smoke-tests.ts
  tests/util/smokeFixtures.ts
  tests/util/wsApis.ts
Labels: B0-silent, D2-notlive

#1883 New and fixed tests for gas refunding and block weight reporting
  tests/smoke-tests/test-block-weight-per-class.ts
  tests/smoke-tests/test-block-weights.ts
  tests/tests/test-eth-fee/test-eth-txn-weights.ts
Labels: B0-silent, D2-notlive

#1903 Lengthy smoke tests use dynamic timeout
  tests/smoke-tests/test-block-finalized.ts
  tests/smoke-tests/test-block-weights.ts
Labels: B0-silent, D2-notlive

#1906 Smoke test fixes
  tests/smoke-tests/test-author-mapping-consistency.ts
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-block-finalized.ts
  tests/smoke-tests/test-block-weights.ts
  tests/smoke-tests/test-ethereum-contract-code.ts
  tests/smoke-tests/test-foreign-asset-consistency.ts
  tests/smoke-tests/test-local-asset-consistency.ts
Labels: B0-silent, D2-notlive

#1905 fix tracing tests
  tests/tracing-tests/test-trace-filter.ts
  tests/tracing-tests/test-trace-gas.ts
Labels: B0-silent, A10-evmtracing, D2-notlive

#1897 verify autoCompound in smoke-test
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#1909 fix ed25519 verification
  Cargo.lock
Labels: B5-clientnoteworthy, D5-nicetohaveaudit⚠️

#1914 Temporarily suppressed failing tests
  tests/smoke-tests/test-block-weights.ts
Labels: B0-silent, D2-notlive

#1913 only check auto-compound if delegator is to be rewarded
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#1912 Add codec type when creating it
  tests/tests/test-assets/test-assets-pallet.ts
  tests/tests/test-assets/test-assets-sufficients.ts
  tests/tests/test-maintenance/test-maintenance-filter.ts
  tests/tests/test-precompile/test-precompile-assets-erc20.ts
  tests/tests/test-precompile/test-precompile-xcm-transactor.ts
Labels: B0-silent, D3-trivial

#1915 calculate maxRoundChecks from first block of round
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive
