Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-04, with the labels that each got.

#1375 Create a new cli option for statuses cache size & adapt default size to the new unit (bytes instead of blocks)
  node/cli-opt/src/lib.rs
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/lib.rs
Labels: B0-silent, D3-trivial

#1380 Update parachain-staking/migrations.md
  pallets/parachain-staking/migrations.md
Labels: B0-silent, D2-notlive

#1360 Girazoki add transfer multcurriencies to precompiles
  precompiles/xtokens/Xtokens.sol
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/tests.rs
  tests/contracts/compiled/XtokensInstance.json
  tests/contracts/sources.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
Labels: B7-runtimenoteworthy, C3-medium, D5-nicetohaveaudit⚠️

#1383 Upgrade bundle dependencies
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1384 Fixes package-lock.json for moonbeam type bundle
  moonbeam-types-bundle/package-lock.json
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1279 Girazoki local assets
  pallets/asset-manager/src/benchmarks.rs
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/migrations.rs
  pallets/asset-manager/src/mock.rs
  pallets/asset-manager/src/tests.rs
  pallets/asset-manager/src/weights.rs
  precompiles/assets-erc20/ERC20_local.sol
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/mock.rs
  precompiles/assets-erc20/src/tests.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/src/asset_config.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_tests.rs
  tests/contracts/compiled/LocalAssetExtendedErc20Instance.json
  tests/contracts/sources.ts
  tests/tests/test-asset-manager.ts
  tests/tests/test-assets-sufficients.ts
  tests/tests/test-mock-dmp.ts
  tests/tests/test-mock-hrmp.ts
  tests/tests/test-pallet-maintenance-mode.ts
  tests/tests/test-precompile/test-precompile-assets-erc20.ts
  tests/tests/test-precompile/test-precompile-local-assets-erc20.ts
  tests/tests/test-precompile/test-precompile-xcm-transactor.ts
Labels: B7-runtimenoteworthy, C3-medium, D9-needsaudit👮

#1386 Comment migrations from runtime 1300
  runtime/common/src/migrations.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1392 fix: client build use production profile
  .github/workflows/publish-binary.yml
Labels: B0-silent, D2-notlive

#1389 Add local assets to Moonbeam, without them being transferrable through xcm
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/asset_config.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1358 Add BlockWeight, staking Round, and treasury to whitelist
  runtime/common/src/apis.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1356 Improve traceBlock raw-tracing support error message
  client/rpc/debug/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, A10-evmtracing, D3-trivial

#1393 Upgrades runtime to 1400
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  tests/package-lock.json
  tests/package.json
  tests/para-tests/moonbase/1200/skip-test-migration-split-staking.ts
  tests/tests/test-pallet-maintenance-mode.ts
  tests/tests/test-sudo.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, C1-low, D3-trivial

#1395 Update srtool actions ci dependency
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D2-notlive

#1394 Make try-runtime compile with latest changes
  pallets/asset-manager/src/migrations.rs
Labels: B0-silent, D3-trivial

#1396 Add link to rustdocs in README.md
  README.md
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, D3-trivial

#1398 Fix docker issue with release folder name
  docker/moonbeam-release.Dockerfile
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1399 Remove some unused crates from perf-test
  Cargo.lock
  node/perf-test/Cargo.toml
Labels: B0-silent, D3-trivial

#1385 evm `0.35.0` release
  Cargo.lock
  Cargo.toml
Labels: B0-silent, D3-trivial

#1387 impl EvmData for tuples
  Cargo.lock
  precompiles/relay-encoder/src/lib.rs
  precompiles/utils/Cargo.toml
  precompiles/utils/src/data.rs
  precompiles/utils/src/data/xcm.rs
  precompiles/utils/src/tests.rs
  precompiles/xtokens/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1363 Test `max_fee_per_gas` and `max_priority_fee_per_gas` fixes
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-receipt/test-receipt.ts
Labels: B0-silent, D3-trivial

#1365 Test asset destruction in pallet-assets
  tests/tests/test-assets-pallet.ts
Labels: B0-silent, I4-tests 🎯, D3-trivial

#1404 Revert back wrong hasher introduced for AssetTypeUnitsPerSecond
  pallets/asset-manager/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1405 runtime-1401
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#1397 launch: add rococo 9180
  tools/launch.ts
Labels: B0-silent, D2-notlive

#1400 [MOON-1460] add migration for author-slot-filter EligibleRatioToEligiblityCount
  Cargo.lock
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B7-runtimenoteworthy, D3-trivial

#1411 Fix relay config for para tests
  tests/para-tests/moonbase/test-runtime-upgrade.ts
  tests/util/para-node.ts
  tests/util/setup-para-tests.ts
  tools/launch.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1406 Girazoki pending delegation request precompile
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  tests/tests/test-precompile/test-precompile-staking.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1412 Update frontier `79ed3f2`
  Cargo.lock
  runtime/common/src/apis.rs
  tests/tests/test-gas/test-gas-estimation.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1417 Cherry-pick: Update frontier `79ed3f2` (#1412)
  Cargo.lock
  runtime/common/src/apis.rs
  tests/tests/test-gas/test-gas-estimation.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial

#1414 Add candidate request is pending to staking precompile
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial

#1401 Girazoki xcm cleanup
  Cargo.lock
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  precompiles/xcm_transactor/Cargo.toml
  precompiles/xcm_transactor/src/mock.rs
  primitives/xcm/Cargo.toml
  primitives/xcm/src/lib.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/statemint_like.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/statemint_like.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/statemine_like.rs
  runtime/moonriver/tests/xcm_tests.rs
  tests/tests/test-mock-hrmp.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
Labels: B7-runtimenoteworthy, I6-refactor 🧹, D3-trivial

#1419 [Tests] Fixes github wrong commit in typescript test
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-notlive

#1418 NF: Change cyrillic `С`.
  pallets/parachain-staking/src/lib.rs
Labels: B0-silent, D3-trivial

#1423 Fix version-bump script (add dashes)
  .github/workflows/version-bump.yml
Labels: B0-silent, D3-trivial

#1427 Better error for print-version-bump-info script
  tools/github/print-version-bump-info.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1432 Expose round number in staking precompile
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1429 EIP2612 (Permit) for ERC20 precompiles
  Cargo.lock
  Cargo.toml
  precompiles/assets-erc20/Cargo.toml
  precompiles/assets-erc20/ERC20.sol
  precompiles/assets-erc20/ERC20_local.sol
  precompiles/assets-erc20/LocalAsset.sol
  precompiles/assets-erc20/Permit.sol
  precompiles/assets-erc20/src/eip2612.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/mock.rs
  precompiles/assets-erc20/src/tests.rs
  precompiles/balances-erc20/Cargo.toml
  precompiles/balances-erc20/Permit.sol
  precompiles/balances-erc20/src/eip2612.rs
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/mock.rs
  precompiles/balances-erc20/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1437 CI: generate runtime release issue: fix documentation
  .github/workflows/runtime-release-issue.yml
Labels: B0-silent, D2-notlive

#1439 fix author-slot-filter migration in nimbus
  Cargo.lock
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D1-runtime-migration, D3-trivial

#1408 [MOON-1453] calculate outgoing rewards based on pending revoke and decrease changes
  pallets/author-mapping/src/migrations.rs
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  runtime/common/src/migrations.rs
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/tests/test-staking.ts
  tests/util/tracer/blockscout_tracer_v2.min.json
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1442 Added publish section to typescript-api readme file
  typescript-api/README.md
Labels: B0-silent, D3-trivial

#1441 Support on-chain-release-build
  .github/workflows/publish-runtime.yml
  .github/workflows/release.yml
Labels: B7-runtimenoteworthy, D3-trivial

#1443 Bump runtime version to 1500
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial

#1445 fix: rust 1.57 not support semi-pub types with derive Encode/Decode
  pallets/moonbeam-orbiters/src/types.rs
Labels: B0-silent, D3-trivial
