Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-01, with the labels that each got.

#1135 Happy new year 2022, cleanup trace debug module
  client/rpc/debug/src/lib.rs
Labels: A0-pleasereview, B0-silent

#1126 `eth_feeHistory` support
  Cargo.lock
  node/cli-opt/src/lib.rs
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/perf-test/src/command.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/lib.rs
  node/service/src/rpc.rs
  runtime/common/src/apis.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  tests/tests/test-fee-history.ts
Labels: A0-pleasereview, B5-clientnoteworthy, B7-runtimenoteworthy

#1137 fix impl Debug for AccountId20
  primitives/account/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent

#1136 [CI] Create client release issue should not add `v` to the tag
  tools/github/print-client-release-issue.ts
  tools/github/print-runtime-release-issue.ts
Labels: A8-mergeoncegreen, B0-silent

#1129 Girazoki author mapping precompile
  Cargo.lock
  precompiles/author-mapping/AuthorMappingInterface.sol
  precompiles/author-mapping/Cargo.toml
  precompiles/author-mapping/src/lib.rs
  precompiles/author-mapping/src/mock.rs
  precompiles/author-mapping/src/tests.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  tests/contracts/compiled/AuthorMapping.json
  tests/contracts/sources.ts
  tests/tests/test-precompile/test-precompile-author-mapping.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#1106 Add deposit/withdraw wETH functions to balances ERC20 precompile
  precompiles/balances-erc20/ERC20.sol
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/mock.rs
  precompiles/balances-erc20/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#1144 Fix typed transaction hashing
  runtime/common/src/apis.rs
  runtime/moonbase/tests/evm_tracing.rs
  runtime/moonbeam/tests/evm_tracing.rs
  runtime/moonriver/tests/evm_tracing.rs
  tests/tracing-tests/test-trace-filter.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#1140 CI: rework job typescript-tracing-tests & remove job tracing-build
  .cargo/config.toml
  .github/workflows/build.yml
  Cargo.lock
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/debug/src/lib.rs
  client/rpc-core/trace/Cargo.toml
  client/rpc-core/trace/src/lib.rs
  client/rpc-core/types/Cargo.toml
  client/rpc-core/types/src/lib.rs
  client/rpc/debug/Cargo.toml
  client/rpc/debug/src/lib.rs
  client/rpc/trace/Cargo.toml
  client/rpc/trace/src/lib.rs
  node/Cargo.toml
  node/service/Cargo.toml
  scripts/build-last-tracing-runtime.sh
  scripts/run-tracing-tests.sh
  tests/tracing-tests/test-trace-filter.ts
  tests/tracing-tests/test-trace-gas.ts
  tests/tracing-tests/test-trace.ts
  tests/util/constants.ts
  tests/util/dev-node.ts
  tests/util/tracer/blockscout_tracer.min.json
Labels: A0-pleasereview, B0-silent, A10-evmtracing

#1149 fix tracing tests: revert changes in expected values introduced by #1140
  tests/tracing-tests/test-trace-filter.ts
  tests/tracing-tests/test-trace-gas.ts
Labels: A0-pleasereview, B0-silent, A10-evmtracing

#1152 Upgrade mocha to v9
  tests/package-lock.json
  tests/package.json
Labels: B0-silent

#1151 Adapt moonbeam dev chainspec to supply and fill tech committee
  node/service/src/chain_spec/moonbeam.rs
Labels: B5-clientnoteworthy, C1-low

#1132 Test assets + evm reference handling with ED 0
  Cargo.lock
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_tests.rs
  tests/tests/test-contract/test-contract-loop-cost.ts
  tests/tests/test-treasury-proposal.ts
Labels: A0-pleasereview, B0-silent

#1148 Add democracy precompile to Moonriver
  Cargo.lock
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1154 Adapt tracing tests to EVM london configuration
  tests/tracing-tests/test-trace-gas.ts
Labels: B0-silent, A10-evmtracing

#1153 Disable Identity, ParachainStaking and Treasury in MaintenanceMode
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy

#1158 Fixes Launch script ports
  tools/launch.ts
Labels: B0-silent

#1157 Adds step for migration cleanup in release ticket
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent

#1142 payable/view checks in precompiles
  precompiles/assets-erc20/src/lib.rs
  precompiles/author-mapping/src/lib.rs
  precompiles/balances-erc20/src/lib.rs
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/pallet-democracy/src/lib.rs
  precompiles/parachain-staking/src/lib.rs
  precompiles/relay-encoder/src/lib.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/tests.rs
  precompiles/xcm_transactor/src/lib.rs
  precompiles/xtokens/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#1145 WETH withdraw/deposit should only exist for the native currency
  precompiles/balances-erc20/ERC20.sol
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/mock.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonriver/src/precompiles.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#1160 Add author mapping precompile to Moonbeam and Moonriver
  Cargo.lock
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#1164 Fix npm install error related to git
  tests/package-lock.json
  tests/package.json
Labels: A0-pleasereview, B0-silent

#1171 Include the dmp and xcmp queues in cumulus-parachain system
  runtime/moonriver/src/lib.rs
  tests/tests/test-subscription/test-subscription.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#1174 Add tech and council to moonriver-local to be able to test locally
  node/service/src/chain_spec/moonriver.rs
Labels: B0-silent

#1161 Point nimbus to 29c58f1 (fix modulo-bias issue)
  Cargo.lock
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1176 Update Frontier
  Cargo.lock
  client/evm-tracing/Cargo.toml
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/trace/Cargo.toml
  client/rpc-core/txpool/Cargo.toml
  client/rpc-core/types/Cargo.toml
  client/rpc/debug/Cargo.toml
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  node/perf-test/Cargo.toml
  node/perf-test/src/command.rs
  node/service/src/rpc.rs
  precompiles/xcm_transactor/Cargo.toml
  primitives/ext/Cargo.toml
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/evm-tracing-events/Cargo.toml
  primitives/rpc/txpool/Cargo.toml
  runtime/common/src/apis.rs
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/tests/runtime_apis.rs
  tests/tests/test-subscription/test-subscription.ts
Labels: A0-pleasereview, B5-clientnoteworthy, B7-runtimenoteworthy, A10-evmtracing

#1114 Girazoki xcm max ump weight and transact info migration
  Cargo.lock
  pallets/migrations/Cargo.toml
  pallets/migrations/src/lib.rs
  pallets/migrations/src/mock.rs
  pallets/xcm-transactor/Cargo.toml
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/migrations.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/tests.rs
  precompiles/xcm_transactor/XcmTransactor.sol
  precompiles/xcm_transactor/src/lib.rs
  precompiles/xcm_transactor/src/mock.rs
  precompiles/xcm_transactor/src/tests.rs
  primitives/xcm/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_tests.rs
  tests/contracts/compiled/XcmTransactorInstance.json
  tests/contracts/sources.ts
  tests/tests/test-precompile/test-precompile-xcm-transactor.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1181 Handle potential overflow when calculating fee to be substracted
  primitives/xcm/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1180 Comment ParachainStakingIncreaseMaxDelegationsPerCandidate migration
  runtime/common/src/migrations.rs
Labels: A0-pleasereview, B0-silent

#1178 Disable `BaseFee` based `FeeCalculator` in moonbase.
  node/service/src/chain_spec/moonbase.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  tests/tests/test-fee-history.ts
Labels: A0-pleasereview, B7-runtimenoteworthy

#1188 Client v0.18.1
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: A0-pleasereview, B5-clientnoteworthy

#1162 [Staking] Patch candidate bond more to update CandidatePool + migration to fix incorrect state
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C9-critical, D9-needsaudit👮

#1166 Test that each runtime have the expected set of precompiles
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B0-silent

#1184 Finality RPC: add RPC methods isBlockFinalized & isTxFinalize
  Cargo.lock
  Cargo.toml
  client/rpc/finality/Cargo.toml
  client/rpc/finality/src/lib.rs
  node/service/Cargo.toml
  node/service/src/rpc.rs
Labels: B5-clientnoteworthy

#1183 XCM to moonbeam
  Cargo.lock
  node/service/src/chain_spec/moonbeam.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/relay_chain.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1198 Patch ethereum `0.11.1`
  Cargo.lock
  Cargo.toml
  tests/tests/test-ext-eth-data.ts
  tests/tests/test-nonce.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, C9-critical

#1200 Client v0.19.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: B0-silent

#1202 Reduces parallelization of test from 7 to 4 concurrent
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent

#1121 Adds support for optimized binary testing
  .github/workflows/prepare-binary.yml
  docker/moonbeam.Dockerfile
Labels: A0-pleasereview, B0-silent

#1201 ERC20 precompiles approve should support up to U256::MAX
  Cargo.lock
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  precompiles/balances-erc20/Cargo.toml
  precompiles/balances-erc20/src/lib.rs
  precompiles/balances-erc20/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#1159 Girazoki avoid statemine prefix breaking change
  Cargo.lock
  moonbeam-types-bundle/package-lock.json
  pallets/asset-manager/Cargo.toml
  pallets/asset-manager/src/benchmarks.rs
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/migrations.rs
  pallets/asset-manager/src/mock.rs
  pallets/asset-manager/src/tests.rs
  pallets/asset-manager/src/weights.rs
  primitives/xcm/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/statemint_like.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/statemint_like.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/statemine_like.rs
  runtime/moonriver/tests/xcm_tests.rs
  tests/package-lock.json
  tests/para-tests-no-ci/test-xcm-para.ts
  tests/tests/test-asset-manager.ts
  tests/tests/test-assets-sufficients.ts
  tests/tests/test-mock-dmp.ts
  tests/tests/test-mock-hrmp.ts
  tests/tests/test-pallet-maintenance-mode.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮

#1204 Patch ethereum `0.11.1` (2)
  Cargo.lock
Labels: A0-pleasereview, B5-clientnoteworthy

#1203 ci(prepare-binary): typo
  .github/workflows/prepare-binary.yml
Labels: B0-silent

#1199 Use saturating_add to prevent possible overflow in migrations
  pallets/migrations/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D9-needsaudit👮

#1206 Updating bootnodes
  specs/moonriver/parachain-embedded-specs.json
Labels: A8-mergeoncegreen, B5-clientnoteworthy

#1052 Added precompiled addresses to the interface
  precompiles/author-mapping/AuthorMappingInterface.sol
  precompiles/balances-erc20/ERC20.sol
  precompiles/crowdloan-rewards/CrowdloanInterface.sol
  precompiles/pallet-democracy/DemocracyInterface.sol
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/relay-encoder/RelayEncoder.sol
  precompiles/xcm_transactor/XcmTransactor.sol
  precompiles/xtokens/Xtokens.sol
Labels: A0-pleasereview, B0-silent

#1210 Adds --parachain-runtime parameter to launch script
  tools/README.md
  tools/launch.ts
Labels: A8-mergeoncegreen, B0-silent

#1213 Fix staking precompile selector comments
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B0-silent

#1216 Runtime 1103
  Cargo.lock
  node/perf-test/src/command.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  node/service/src/rpc.rs
  runtime/common/src/apis.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
Labels: B7-runtimenoteworthy

#1207 [Staking] Remove delegation request in execute_leave_candidates + hotfix extrinsic to remove leftover delegation requests
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1205 Fix incorrect check to see if previous migration already passed
  pallets/asset-manager/src/migrations.rs
  pallets/asset-manager/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy

#1215 Early return in trader when amount to be charged is 0
  primitives/xcm/src/lib.rs
Labels: A0-pleasereview, B0-silent

#1217 Use new runtime API introduced in runtime 1103 (convert_transaction)
  Cargo.lock
  node/perf-test/src/command.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  node/service/src/rpc.rs
  runtime/common/src/apis.rs
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮

#1117 [Staking] Split candidate state for PoV optimization
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  tests/tests/test-staking.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮

#1225 Fix for optional `type` field in transaction request
  Cargo.lock
Labels: A0-pleasereview, B5-clientnoteworthy

#1228 Increase amount charged for xcm in local unit
  Cargo.lock
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  tests/tests/test-mock-hrmp.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1226 Runtime 1200
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1229 `DebugRuntimeApi` version 2
  client/rpc/debug/src/lib.rs
  primitives/rpc/debug/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, A10-evmtracing

#1231 `DebugRuntimeApi` version 4
  client/rpc/debug/src/lib.rs
  primitives/rpc/debug/src/lib.rs
Labels: A8-mergeoncegreen, B5-clientnoteworthy, A10-evmtracing

#1230 Upgrade srtool
  .github/workflows/publish-runtime.yml
Labels: B0-silent

#1233 Add `DefaultBaseFeePerGas` to runtimes
  Cargo.lock
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy

#1242 Fixes inflation formula in comments
  pallets/parachain-staking/src/inflation.rs
Labels: A8-mergeoncegreen, B0-silent
