Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-09, with the labels that each got.

#1796 Updated wrong param labels
  precompiles/xcm-transactor/src/v2/XcmTransactorV2.sol
Labels: B0-silent, D3-trivial

#1794 More properly benchmark xcm transactor
  pallets/asset-manager/Cargo.toml
  pallets/asset-manager/src/lib.rs
  pallets/xcm-transactor/src/benchmarks.rs
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/weights.rs
  precompiles/xcm-transactor/src/tests.rs
  primitives/xcm/Cargo.toml
  primitives/xcm/src/asset_id_conversions.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/src/xcm_config.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1795 Add `XcmFragment` typescript test utilities
  tests/tests/test-xcm/test-mock-dmp-error-and-appendix.ts
  tests/tests/test-xcm/test-mock-dmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-asset-transfer.ts
  tests/tests/test-xcm/test-mock-hrmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
  tests/tests/test-xcm/test-mock-hrmp-transact.ts
  tests/util/xcm.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1790 `EthereumXcm` global nonce
  Cargo.lock
  pallets/ethereum-xcm/src/lib.rs
  pallets/ethereum-xcm/src/tests/v1/eip1559.rs
  pallets/ethereum-xcm/src/tests/v1/eip2930.rs
  pallets/ethereum-xcm/src/tests/v1/legacy.rs
  pallets/ethereum-xcm/src/tests/v2.rs
  primitives/xcm/src/ethereum_xcm.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1798 Staking: move `Default` config associated types to GenesisConfig
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1797 Randomness: make fulfillfment overhead cost depend on num_words
  pallets/randomness/src/benchmarks.rs
  pallets/randomness/src/weights.rs
  precompiles/randomness/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1803 Adds code check, gas increase for batch precompile
  precompiles/batch/src/lib.rs
  precompiles/batch/src/tests.rs
  tests/tests/test-precompile/test-precompile-batch.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮

#1800 Ethereum xcm suspend switch
  pallets/ethereum-xcm/src/lib.rs
  pallets/ethereum-xcm/src/mock.rs
  pallets/ethereum-xcm/src/tests/v2.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1806 Precompile fixes
  precompiles/proxy/src/lib.rs
  precompiles/proxy/src/tests.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-contract/test-contract-delegate-call.ts
  tests/tests/test-precompile/test-precompile-dispatch.ts
  tests/tests/test-proxy/test-proxy-leader-demo.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1807 Fix Ethereum post-dispatch weight
  Cargo.lock
  tests/tests/test-eth-fee/test-eth-txn-weights.ts
Labels: B0-silent, D9-needsaudit👮

#1805 `EthereumXcm` limit input size
  pallets/ethereum-xcm/src/tests/v1/eip1559.rs
  pallets/ethereum-xcm/src/tests/v1/eip2930.rs
  pallets/ethereum-xcm/src/tests/v1/legacy.rs
  pallets/ethereum-xcm/src/tests/v2.rs
  primitives/xcm/src/ethereum_xcm.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D1-audited👍

#1802 Girazoki more ethereum xcm tests
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
  tests/tests/test-xcm/test-mock-hrmp-transact.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1763 Build moonbeam-specific srtool image
  .github/workflows/publish-runtime.yml
  docker/moonbeam-srtool.Dockerfile
  scripts/build-runtime-srtool.sh
Labels: B0-silent, D2-notlive

#1774 fix GH workflow "upgrade typescript api"
  .github/workflows/upgrade-typescript-api.yml
Labels: B0-silent, D2-notlive

#1815 Fix smoke test regarding relay weight 1.5
  tests/smoke-tests/test-relay-xcm-fees.ts
Labels: A0-pleasereview, B0-silent, I4-tests 🎯, D3-trivial

#1808 Improve frontier weight test
  tests/tests/test-eth-fee/test-eth-txn-weights.ts
  tests/util/constants.ts
Labels: B0-silent, D3-trivial

#1816 Pallet randomness tradeoff analysis README
  pallets/randomness/README.md
Labels: A0-pleasereview, B0-silent, D3-trivial

#1821 fix bug in calculation of totalBondReward
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#1817 pallet-parachain-staking: Inflation conversion can panic the RT for for large round numbers
  pallets/parachain-staking/src/inflation.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1824 Support release body for multiple repos
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime.yml
  tools/github/generate-release-body.ts
  tools/github/generate-runtimes-body.ts
  tools/github/github-utils.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1830 Pin frontier `afc693a`
  Cargo.lock
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-contract/test-contract-creation.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial

#1799 use u32 as BlockNumber in mocks
  pallets/asset-manager/src/mock.rs
  pallets/author-mapping/src/mock.rs
  pallets/ethereum-xcm/src/mock.rs
  pallets/maintenance-mode/src/mock.rs
  pallets/migrations/src/mock.rs
  pallets/moonbeam-orbiters/src/mock.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/proxy-genesis-companion/src/mock.rs
  pallets/randomness/src/mock.rs
  pallets/randomness/src/tests.rs
  pallets/xcm-transactor/src/mock.rs
  precompiles/assets-erc20/src/mock.rs
  precompiles/author-mapping/src/mock.rs
  precompiles/balances-erc20/src/mock.rs
  precompiles/batch/src/mock.rs
  precompiles/call-permit/src/mock.rs
  precompiles/collective/src/mock.rs
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/pallet-democracy/src/mock.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
  precompiles/proxy/src/mock.rs
  precompiles/proxy/src/tests.rs
  precompiles/randomness/src/mock.rs
  precompiles/relay-encoder/src/mock.rs
  precompiles/xcm-transactor/src/mock.rs
  precompiles/xcm-utils/src/mock.rs
  precompiles/xtokens/src/mock.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbase/tests/xcm_mock/statemint_like.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/relay_chain.rs
  runtime/moonbeam/tests/xcm_mock/statemint_like.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/relay_chain.rs
  runtime/moonriver/tests/xcm_mock/statemine_like.rs
Labels: B0-silent, D3-trivial

#1823 Allow prepare-polkadot CI to run even on non-official moonbeam
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1801 `EthereumXcm` tracing support
  primitives/xcm/src/ethereum_xcm.rs
  runtime/common/src/apis.rs
  runtime/common/src/impl_moonbeam_xcm_call_tracing.rs
  runtime/common/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  tests/tracing-tests/test-trace-ethereum-xcm.ts
Labels: A0-pleasereview, B0-silent, A10-evmtracing, D3-trivial

#1778 remove doc details for filter
  precompiles/proxy/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D5-nicetohaveaudit⚠️, D2-notlive

#1833 More getters for Collective precompile
  precompiles/collective/Collective.sol
  precompiles/collective/src/lib.rs
  precompiles/collective/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial
