Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-12, with the labels that each got.

#1980 Fixes smoke tests for weight v2
  scripts/run-fork-test.sh
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-block-weights.ts
  tests/smoke-tests/test-ethereum-current-consistency.ts
  tests/smoke-tests/test-historic-compatibility.ts
  tests/smoke-tests/test-relay-xcm-fees.ts
  tests/smoke-tests/test-staking-rewards.ts
  tests/smoke-tests/test-staking-round-cleanup.ts
  tests/tests/test-eth-fee/test-eth-txn-weights.ts
  tests/tests/test-xcm/test-mock-dmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
  tests/util/block.ts
  tests/util/upgrade.ts
Labels: B0-silent, D2-notlive

#1983 Additionnal fixes for smoke tests with Weight v2
  tests/package.json
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-block-weights.ts
  tests/smoke-tests/test-historic-compatibility.ts
  tests/util/block.ts
Labels: B0-silent, D2-notlive

#1985 Fix precompile macro cargo doc
  precompiles/utils/macro/docs/precompile_macro.md
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-notlive

#1984 Updates some Purestake bootnodes for Moonriver and Moonbeam
  specs/moonbeam/parachain-embedded-specs.json
  specs/moonriver/parachain-embedded-specs.json
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial

#1987 Add XCM smoke tests for Foreign chains
  tests/package-lock.json
  tests/package.json
  tests/smoke-tests/test-foreign-xcm-failures.ts
  tests/smoke-tests/test-xcm-failures.ts
  tests/util/block.ts
  tests/util/foreign-chains.ts
  tests/util/wsApis.ts
Labels: B0-silent, D2-notlive

#1990 Adapt smoke test to at stake
  tests/smoke-tests/test-staking-rewards.ts
Labels: A0-pleasereview, B0-silent, I4-tests 🎯, D3-trivial

#1982 impl ed25519 backward compatibility
  Cargo.lock
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D3-trivial

#1989 Fix `eth-fee-history` ts tests
  tests/tests/test-eth-fee/test-eth-fee-history.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1991 fix rust docs generation
  .github/workflows/docs.yml
Labels: B0-silent, D2-notlive

#1855 Defer first deferred staking payout
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-staking/test-rewards-auto-compound.ts
  tests/tests/test-staking/test-rewards.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1994 add launch config for client v0.28.0
  tools/launch.ts
Labels: B0-silent, D2-notlive

#1992 add some points in runtime release check list
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent, D2-notlive

#1993 Take into account orbiter event
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, I4-tests 🎯, D3-trivial

#1953 Unify precompiles mock accounts
  Cargo.lock
  precompiles/assets-erc20/src/mock.rs
  precompiles/assets-erc20/src/tests.rs
  precompiles/author-mapping/src/mock.rs
  precompiles/author-mapping/src/tests.rs
  precompiles/balances-erc20/src/mock.rs
  precompiles/balances-erc20/src/tests.rs
  precompiles/batch/src/mock.rs
  precompiles/batch/src/tests.rs
  precompiles/call-permit/src/mock.rs
  precompiles/call-permit/src/tests.rs
  precompiles/collective/src/mock.rs
  precompiles/collective/src/tests.rs
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/crowdloan-rewards/src/tests.rs
  precompiles/pallet-democracy/src/mock.rs
  precompiles/pallet-democracy/src/tests.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
  precompiles/proxy/src/mock.rs
  precompiles/proxy/src/tests.rs
  precompiles/relay-encoder/src/mock.rs
  precompiles/relay-encoder/src/tests.rs
  precompiles/utils/Cargo.toml
  precompiles/utils/src/lib.rs
  precompiles/utils/src/testing.rs
  precompiles/utils/src/testing/account.rs
  precompiles/utils/src/testing/execution.rs
  precompiles/utils/src/testing/handle.rs
  precompiles/utils/src/testing/mod.rs
  precompiles/utils/src/testing/modifier.rs
  precompiles/utils/src/testing/solidity.rs
  precompiles/xcm-transactor/src/mock.rs
  precompiles/xcm-transactor/src/tests.rs
  precompiles/xcm-utils/src/mock.rs
  precompiles/xcm-utils/src/tests.rs
  precompiles/xtokens/src/mock.rs
  precompiles/xtokens/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D3-trivial

#1969 Derive `TypeInfo` for `EthereumSigner`
  primitives/account/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low, D3-trivial

#1986 Remove `pallet-base-fee`
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  precompiles/randomness/src/lib.rs
  runtime/common/src/apis.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1998 Downgrade ed25519
  Cargo.lock
Labels: B5-clientnoteworthy, D3-trivial

#2004 CENTS in Kusama are now 1e12/3000
  tests/smoke-tests/test-relay-xcm-fees.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1831 Add Ethereum block tag para-test
  tests/para-tests/moonbase/test-eth-rpc-block-tags.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#2003 [MOON-1989] Randomness precompile unit tests
  Cargo.lock
  pallets/randomness/src/lib.rs
  precompiles/randomness/Cargo.toml
  precompiles/randomness/src/lib.rs
  precompiles/randomness/src/mock.rs
  precompiles/randomness/src/tests.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1163 doc: update RELEASE.md
  RELEASE.md
Labels: B0-silent, D2-notlive

#2002 [MOON-2032] remove Default* config constants from parachain-staking unit tests
  pallets/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/mock.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1654 Append non-supported parachain-id flag to be able to run multi-parach…
  tools/launch.ts
Labels: B0-silent, D3-trivial

#2000 Girazoki add ed25519 version breaking check
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: B0-silent, I4-tests 🎯, D3-trivial

#1960 improves staking docs for scheduled requests
  pallets/parachain-staking/src/lib.rs
Labels: B0-silent, D2-notlive

#2008 Bump RT to 2100 and Client to v0.29.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  tests/util/binaries.ts
  tests/util/upgrade.ts
  tools/launch.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, B7-runtimenoteworthy, D3-trivial

#2011 smoke test staking rewards - revert check
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#1952 fix staking benchmarks tests
  pallets/author-mapping/src/benchmarks.rs
  pallets/parachain-staking/src/benchmarks.rs
Labels: B0-silent, D2-notlive

#1870 Derive AccountId20 from keccak digest directly
  primitives/account/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1956 [MOON-1812] attempt using pallet_randomness for auth_slot_filter
  pallets/randomness/src/lib.rs
  runtime/moonbase/src/lib.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#2015 Add GH action to check reentrancy feature
  .github/workflows/build.yml
  scripts/check-forbid-evm-reentrancy.sh
Labels: B0-silent, D3-trivial

#2012 Add owner admin frezer issuer accessors to assets precompile
  precompiles/assets-erc20/ERC20.sol
  precompiles/assets-erc20/Permit.sol
  precompiles/assets-erc20/Roles.sol
  precompiles/assets-erc20/src/eip2612.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
  tests/contracts/compiled/Roles.json
  tests/tests/test-precompile/test-precompile-local-assets-erc20.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#2019 staking smoke test - fix computing outstanding revokes
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#2020 staking smoke test - fix checking outstanding revokes
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#2013 Use chainType for running in Dev mode
  node/service/src/lib.rs
Labels: B0-silent, D2-notlive

#2014 Improve client release issue
  tools/github/print-client-release-issue.ts
Labels: B0-silent, D2-notlive
