Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-03, with the labels that each got.

#1326 [Staking] If no collators selected, fallback to last selected candidates
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1331 Updated package.json and readme for typescript-api
  typescript-api/README.md
  typescript-api/package.json
Labels: B0-silent

#1332 Fix staking benchmark assertion(s)
  pallets/parachain-staking/src/benchmarks.rs
Labels: B0-silent, D3-trivial

#1333 [Staking] Fix benchmarks (and update weights) for pay_one_collator_reward and round_transition_on_initialize
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/weights.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1329 use 'moonbeam' prefix when emitting prometheus metrics
  Cargo.lock
  node/cli/Cargo.toml
  node/perf-test/src/command.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D3-trivial

#1339 Add benchmarking whitelist used in Substrate
  Cargo.lock
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: A0-pleasereview, B0-silent, D3-trivial

#1341 Pin frontier `e37f7d9` (fix fee history unwrap)
  Cargo.lock
  precompiles/assets-erc20/src/mock.rs
  precompiles/author-mapping/src/mock.rs
  precompiles/balances-erc20/src/mock.rs
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/pallet-democracy/src/mock.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/relay-encoder/src/mock.rs
  precompiles/xcm_transactor/src/mock.rs
  precompiles/xtokens/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: A0-pleasereview, B5-clientnoteworthy, D3-trivial

#1340 Reduce benchmark load
  benchmarking/frame-weight-template.hbs
  scripts/benchmarking.sh
  scripts/run_benchmarks.sh
Labels: B0-silent, D3-trivial

#1345 Move staking types into separate file
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
Labels: A0-pleasereview, B0-silent, D3-trivial

#1330 Create a production cargo profile like polkadot
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  Cargo.toml
Labels: B0-silent, D3-trivial

#1348 Use release binary instead of debug binary in benchamark script
  scripts/benchmarking.sh
Labels: B0-silent, D3-trivial

#1317 Separate xcm config file
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, C3-medium, D3-trivial

#1351 Added CommonJS module support for Typescript API type definition package
  typescript-api/README.md
  typescript-api/package-lock.json
  typescript-api/package.json
  typescript-api/scripts/postbuild.js
  typescript-api/src/index.cjs
Labels: B0-silent, D3-trivial

#1354 CI: fix job enforce-auditability-label
  .github/workflows/enforce-pr-labels.yml
Labels: B0-silent, D2-notlive

#1352 enable democracy runtime for moonbeam
  Cargo.lock
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1336 Girazoki more freedom when transacting through sovereign
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/tests.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/tests/xcm_tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1350 Benchmark refresh
  benchmarking/frame-weight-template.hbs
  pallets/asset-manager/src/weights.rs
  pallets/author-mapping/src/weights.rs
  pallets/parachain-staking/src/weights.rs
  pallets/xcm-transactor/src/weights.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-author-mapping.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#1337 Benchmark pallet author slot filter
  Cargo.lock
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1334 Use ConstX types when possible
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1355 Add support for optimized binaries in Docker image
  .github/workflows/publish-docker.yml
  docker/moonbeam-release.Dockerfile
Labels: B0-silent, D3-trivial

#1359 {suspend, resume} xcm execution when {enter, exit}ing maintenance-mode
  pallets/maintenance-mode/src/lib.rs
  pallets/maintenance-mode/src/mock.rs
  pallets/maintenance-mode/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1366 [Staking] Expose selected_candidates: Vec<AccountId> in precompile
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1362 Fix `evm-tracing-events` integrations
  primitives/rpc/evm-tracing-events/src/gasometer.rs
  primitives/rpc/evm-tracing-events/src/lib.rs
  primitives/rpc/evm-tracing-events/src/runtime.rs
Labels: A0-pleasereview, B5-clientnoteworthy, A10-evmtracing, D3-trivial

#1370 Fix `evm-tracing-events` compile
  primitives/rpc/evm-tracing-events/Cargo.toml
Labels: A0-pleasereview, B5-clientnoteworthy, A10-evmtracing, D3-trivial

#1371 eth blocks cache: add prometheus metrics & replace blocks size by bytes size
  Cargo.lock
  node/perf-test/src/command.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/rpc.rs
Labels: B0-silent, D3-trivial
