Repository moonbeam-foundation/moonbeam, pull requests merged in 2022-05, with the labels that each got.

#1447 Bump runtime to 1600
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial

#1448 Improve runtime release ticket
  tools/github/print-runtime-release-issue.ts
Labels: A0-pleasereview, B0-silent, D2-notlive

#1451 EIP2612: fix timestamp units
  precompiles/assets-erc20/src/eip2612.rs
  precompiles/assets-erc20/src/tests.rs
  precompiles/balances-erc20/src/eip2612.rs
  precompiles/balances-erc20/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1431 Adds test for XCM weight fee with relay
  tests/smoke-tests/test-author-filter-consistency.ts
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-relay-xcm-fees.ts
  tests/smoke-tests/test-treasury-consistency.ts
  tests/util/setup-smoke-tests.ts
Labels: B0-silent, I4-tests 🎯, D3-trivial

#1458 Fix for Typescript types and new version
  .github/workflows/build.yml
  typescript-api/package-lock.json
  typescript-api/package.json
  typescript-api/src/moonbase/interfaces/augment-api-consts.ts
  typescript-api/src/moonbase/interfaces/augment-api-errors.ts
  typescript-api/src/moonbase/interfaces/augment-api-events.ts
  typescript-api/src/moonbase/interfaces/augment-api-query.ts
  typescript-api/src/moonbase/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbase/interfaces/augment-api-tx.ts
  typescript-api/src/moonbase/interfaces/augment-types.ts
  typescript-api/src/moonbase/interfaces/lookup.ts
  typescript-api/src/moonbase/interfaces/registry.ts
  typescript-api/src/moonbase/interfaces/types-lookup.ts
  typescript-api/src/moonbeam/interfaces/augment-api-consts.ts
  typescript-api/src/moonbeam/interfaces/augment-api-errors.ts
  typescript-api/src/moonbeam/interfaces/augment-api-events.ts
  typescript-api/src/moonbeam/interfaces/augment-api-query.ts
  typescript-api/src/moonbeam/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbeam/interfaces/augment-api-tx.ts
  typescript-api/src/moonbeam/interfaces/augment-types.ts
  typescript-api/src/moonbeam/interfaces/lookup.ts
  typescript-api/src/moonbeam/interfaces/registry.ts
  typescript-api/src/moonbeam/interfaces/types-lookup.ts
  typescript-api/src/moonriver/interfaces/augment-api-consts.ts
  typescript-api/src/moonriver/interfaces/augment-api-errors.ts
  typescript-api/src/moonriver/interfaces/augment-api-events.ts
  typescript-api/src/moonriver/interfaces/augment-api-query.ts
  typescript-api/src/moonriver/interfaces/augment-api-rpc.ts
  typescript-api/src/moonriver/interfaces/augment-api-tx.ts
  typescript-api/src/moonriver/interfaces/augment-types.ts
  typescript-api/src/moonriver/interfaces/lookup.ts
  typescript-api/src/moonriver/interfaces/registry.ts
  typescript-api/src/moonriver/interfaces/types-lookup.ts
Labels: B0-silent, D3-trivial

#1455 Adds smoke test for Staking
  tests/smoke-tests/test-author-filter-consistency.ts
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-staking-consistency.ts
  tests/util/setup-smoke-tests.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1461 CI: Trigger build on perm-* branches
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1460 Update frontier `2025d5b`
  Cargo.lock
Labels: B5-clientnoteworthy, D3-trivial

#1459 auto force authoring when runtime change
  Cargo.lock
Labels: B5-clientnoteworthy, D3-trivial

#1469 Fixes XCM smoke test for multi transact info
  tests/smoke-tests/test-relay-xcm-fees.ts
Labels: B0-silent, D2-notlive

#1466 client v0.23.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  scripts/README.md
  tools/launch.ts
Labels: B0-silent, D3-trivial

#1472 Enable local tokens (GLMR and local assets) transactors in moonbeam
  Cargo.lock
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1478 Improves xcm fee smoke test computation
  tests/smoke-tests/test-relay-xcm-fees.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1473 add additional staking typescript tests
  pallets/parachain-staking/src/lib.rs
  tests/tests/test-staking.ts
Labels: B0-silent, D2-notlive

#1479 Fixing para-test CI
  .github/workflows/build.yml
  docker/polkadot-para-tests.Dockerfile
  scripts/build-alphanet-relay-image.sh
  tests/util/para-node.ts
  tests/util/providers.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1280 fix(tools): get PR associated with a commit by reading commit message
  tools/github/github-utils.ts
Labels: B0-silent, D3-trivial

#1481 Fix maintenance mode executive hooks name
  pallets/maintenance-mode/src/lib.rs
  pallets/maintenance-mode/src/mock.rs
  pallets/maintenance-mode/src/types.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#1484 fix reverse iteration in CI script
  tools/github/github-utils.ts
Labels: B0-silent, ci, D2-notlive

#1495 Updating sccache version
  .github/workflows/build.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#1493 Add migrations.md to author-mapping
  pallets/author-mapping/migrations.md
Labels: B0-silent, D2-notlive

#1492 Update parachain-staking migrations.md
  pallets/parachain-staking/migrations.md
Labels: B0-silent, D2-notlive

#1488 More standard EIP712 name for XC20 assets
  precompiles/assets-erc20/Cargo.toml
  precompiles/assets-erc20/src/eip2612.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1480 Add vrf key to session keys type
  Cargo.lock
  primitives/session-keys/Cargo.toml
  primitives/session-keys/src/lib.rs
  primitives/session-keys/src/vrf.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D2-breaksapi, D5-nicetohaveaudit⚠️

#1221 Always use test address from consts in tests
  tests/tests/test-assets-pallet.ts
  tests/tests/test-balance/test-balance-extrinsics.ts
  tests/tests/test-balance/test-balance-reducible.ts
  tests/tests/test-balance/test-balance-transfer-txwrapper-substrate.ts
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-contract/test-contract-creation.ts
  tests/tests/test-deal-fees.ts
  tests/tests/test-ethpool/test-ethpool-nonce-future.ts
  tests/tests/test-existential-deposit.ts
  tests/tests/test-ext-eth-data.ts
  tests/tests/test-nonce.ts
  tests/tests/test-pallet-evm-transfer.ts
  tests/tests/test-pallet-maintenance-mode.ts
  tests/tests/test-polkadot-api.ts
  tests/tests/test-resubmit-txn.ts
  tests/tests/test-subscription/test-subscription-logs.ts
  tests/tests/test-subscription/test-subscription.ts
Labels: A8-mergeoncegreen, B0-silent, C1-low, D2-notlive

#1502 Adds support for localAssetDeposits in smoke tests
  tests/package-lock.json
  tests/package.json
  tests/smoke-tests/test-balances-consistency.ts
Labels: B0-silent, D2-notlive

#1500 Girazoki author mapping and asset sufficients avoid hardcoding values in ts tests
  tests/tests/test-assets-sufficients.ts
  tests/tests/test-author-mapping.ts
Labels: B0-silent, I4-tests 🎯, D3-trivial

#1494 automate typescript API upgrade
  .github/workflows/upgrade-typescript-api.yml
  tools/github/print-runtime-release-issue.ts
  typescript-api/README.md
  typescript-api/scripts/runtime-upgrade.sh
Labels: B0-silent, ci, D2-notlive

#1506 More conservative smoke test
  tests/smoke-tests/test-relay-xcm-fees.ts
Labels: B0-silent, D2-notlive

#1507 Adds smoke test for candidate pool
  tests/package-lock.json
  tests/package.json
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-staking-consistency.ts
Labels: B0-silent, D2-notlive

#1508 Adds --wasm-execution=interpreted-i-know-what-i-do to tests
  .github/workflows/build.yml
  tests/util/dev-node.ts
  tests/util/para-node.ts
Labels: B0-silent, D2-notlive

#1237 fix typos on code comments
  pallets/asset-manager/src/lib.rs
  pallets/maintenance-mode/src/lib.rs
  pallets/xcm-transactor/src/lib.rs
  precompiles/utils/macro/src/lib.rs
  precompiles/utils/src/data.rs
  precompiles/utils/src/data/xcm.rs
  precompiles/utils/src/lib.rs
  primitives/rpc/debug/src/lib.rs
  primitives/rpc/evm-tracing-events/src/lib.rs
  primitives/xcm/src/lib.rs
Labels: B0-silent, D2-notlive

#1512 [MOON-1674] skip minting rewards if amount is 0
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: B7-runtimenoteworthy, D2-breaksapi, D5-nicetohaveaudit⚠️

#910 Documentation asset manager and xcm
  pallets/asset-manager/src/lib.rs
  primitives/xcm/src/lib.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/tests/xcm_tests.rs
Labels: B0-silent, C1-low, D3-trivial

#1517 adapt benchmark command to new version
  scripts/benchmarking.sh
Labels: B0-silent, D3-trivial

#1510 Clean up dummy container in test before using them
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive

#1519 CI: improve runtime release issue
  .github/workflows/runtime-release-issue.yml
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent, ci, D2-notlive

#1518 fix list benchmarks command
  scripts/benchmarking.sh
Labels: B0-silent, D3-trivial

#1521 Switch to exhaustive selector match in staking precompiles
  precompiles/parachain-staking/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial

#1513 build runtimes without feature on-chain-release-build
  .github/workflows/publish-runtime.yml
Labels: B7-runtimenoteworthy, D2-notlive

#1523 create local asset id just encoding once
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/asset_config.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1511 Use rounded up computation when calculating fee
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#1527 fix(orbiters): panic if we trying to add an orbiter just after removing another
  pallets/moonbeam-orbiters/src/tests.rs
  pallets/moonbeam-orbiters/src/types.rs
Labels: B7-runtimenoteworthy, D3-trivial

#1525 Make author_mapping::set_keys take 1 input like pallet_session::set_keys
  pallets/author-mapping/src/benchmarks.rs
  pallets/author-mapping/src/lib.rs
  pallets/author-mapping/src/migrations.rs
  pallets/author-mapping/src/tests.rs
  pallets/author-mapping/src/weights.rs
  precompiles/author-mapping/AuthorMappingInterface.sol
  precompiles/author-mapping/src/lib.rs
  precompiles/author-mapping/src/tests.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-author-mapping.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D1-runtime-migration, D5-nicetohaveaudit⚠️

#1489 v0.9.20 dependency update
  Cargo.lock
  client/evm-tracing/Cargo.toml
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/txpool/Cargo.toml
  client/rpc/debug/Cargo.toml
  client/rpc/finality/Cargo.toml
  client/rpc/manual-xcm/Cargo.toml
  client/rpc/trace/Cargo.toml
  client/rpc/txpool/Cargo.toml
  core-primitives/Cargo.toml
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/perf-test/Cargo.toml
  node/perf-test/src/command.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/rpc.rs
  pallets/asset-manager/Cargo.toml
  pallets/author-mapping/Cargo.toml
  pallets/ethereum-chain-id/Cargo.toml
  pallets/maintenance-mode/Cargo.toml
  pallets/migrations/Cargo.toml
  pallets/moonbeam-orbiters/Cargo.toml
  pallets/parachain-staking/Cargo.toml
  pallets/proxy-genesis-companion/Cargo.toml
  pallets/xcm-transactor/Cargo.toml
  precompiles/assets-erc20/Cargo.toml
  precompiles/author-mapping/Cargo.toml
  precompiles/balances-erc20/Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/pallet-democracy/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  precompiles/relay-encoder/Cargo.toml
  precompiles/utils/Cargo.toml
  precompiles/xcm_transactor/Cargo.toml
  precompiles/xtokens/Cargo.toml
  primitives/account/Cargo.toml
  primitives/ext/Cargo.toml
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/evm-tracing-events/Cargo.toml
  primitives/rpc/txpool/Cargo.toml
  primitives/session-keys/Cargo.toml
  primitives/xcm/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/common/src/impl_self_contained_call.rs
  runtime/evm_tracer/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/runtime_apis.rs
  runtime/relay-encoder/Cargo.toml
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, dependencies

#1529 force compiled wasm for tracing tests
  .github/workflows/build.yml
  tests/package-lock.json
  tests/tracing-tests/test-trace-concurrency.ts
  tests/tracing-tests/test-trace-filter-reorg.ts
  tests/tracing-tests/test-trace-filter.ts
  tests/tracing-tests/test-trace-gas.ts
  tests/tracing-tests/test-trace.ts
  tests/util/dev-node.ts
Labels: A0-pleasereview, B0-silent, A10-evmtracing, D2-notlive

#1496 Introduce exponential length fee for substrate-based fees
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-author-mapping.ts
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️

#1528 Author priority fees fix
  Cargo.lock
  runtime/common/src/impl_on_charge_evm_transaction.rs
  runtime/common/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮

#1530 fix(orbiters):use orbiters for author mapping to enable author forward
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial

#1515 do not issue rewards for leaving delegators - Method B
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  tests/tests/test-staking.ts
Labels: B7-runtimenoteworthy, D2-breaksapi, D9-needsaudit👮

#1532 Cleanup 1500 migrations
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, C3-medium, D3-trivial

#1538 Adds support for vec<u8> for keys
  pallets/author-mapping/src/lib.rs
  precompiles/author-mapping/src/lib.rs
  tests/tests/test-author-mapping-keys.ts
  tests/tests/test-precompile/test-precompile-author-mapping-keys.ts
  tests/util/block.ts
  tests/util/transactions.ts
Labels: B0-silent, D3-trivial

#1535 Fix author mapping set_keys to take input Vec<u8>
  .prettierignore
  pallets/author-mapping/src/benchmarks.rs
  pallets/author-mapping/src/lib.rs
  pallets/author-mapping/src/migrations.rs
  pallets/author-mapping/src/tests.rs
  pallets/author-mapping/src/weights.rs
  precompiles/assets-erc20/Cargo.toml
  precompiles/author-mapping/AuthorMappingInterface.sol
  precompiles/author-mapping/Cargo.toml
  precompiles/author-mapping/src/lib.rs
  precompiles/author-mapping/src/tests.rs
  precompiles/balances-erc20/Cargo.toml
  precompiles/crowdloan-rewards/Cargo.toml
  precompiles/pallet-democracy/Cargo.toml
  precompiles/parachain-staking/Cargo.toml
  precompiles/relay-encoder/Cargo.toml
  precompiles/xcm_transactor/Cargo.toml
  precompiles/xtokens/Cargo.toml
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-author-mapping-keys.ts
  tests/tests/test-author-mapping.ts
  tests/tests/test-precompile/test-precompile-author-mapping-keys.ts
  tests/util/block.ts
  tests/util/transactions.ts
  typescript-api/src/moonbase/interfaces/augment-api-events.ts
  typescript-api/src/moonbase/interfaces/lookup.ts
  typescript-api/src/moonbase/interfaces/types-lookup.ts
  typescript-api/src/moonbeam/interfaces/augment-api-events.ts
  typescript-api/src/moonbeam/interfaces/lookup.ts
  typescript-api/src/moonbeam/interfaces/types-lookup.ts
  typescript-api/src/moonriver/interfaces/augment-api-events.ts
  typescript-api/src/moonriver/interfaces/lookup.ts
  typescript-api/src/moonriver/interfaces/types-lookup.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D2-breaksapi, D3-trivial

#1542 Fix author mapping setKeys precompile to take 1 input like extrinsic
  precompiles/author-mapping/AuthorMappingInterface.sol
  precompiles/author-mapping/src/lib.rs
  precompiles/author-mapping/src/tests.rs
  tests/tests/test-precompile/test-precompile-author-mapping-keys.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D2-breaksapi, D3-trivial

#1539 Fix Github Action Typescript Api
  .github/workflows/upgrade-typescript-api.yml
Labels: B0-silent, ci, D2-notlive

#1545 [MOON-1714] disallow bond_more when revoke is pending
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  tests/tests/test-staking.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D2-breaksapi, D5-nicetohaveaudit⚠️

#1553 Corrects ERC20.sol annotation
  precompiles/balances-erc20/ERC20.sol
Labels: A8-mergeoncegreen, B0-silent

#1547 Reduced minimum staking delegation in Moonbase
  runtime/moonbase/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D2-breaksapi, D3-trivial

#1551 Import Runtime 1504 changes
  runtime/moonbase/src/precompiles.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/src/precompiles.rs
  tests/tests/test-contract/test-contract-delegate-call.ts
  tests/tests/test-precompile/test-precompile-assets-erc20.ts
  tests/tests/test-precompile/test-precompile-local-assets-erc20.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮

#1555 [MOON-1714] update benchmarking weight for bond more
  pallets/parachain-staking/src/weights.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#1558 Move spec_version to 1601
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial
