Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-10, with the labels that each got.

#2496 Update docs site links in README.md
  README.md
Labels: B0-silent, D2-notlive

#2471 fix typos and errors in examples in Draft MBIP-5
  MBIPS/MBIP-5.md
Labels: B0-silent, D3-trivial, not-breaking

#2500 enable MBIP-5 on Moonriver
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2510 add test for delegating to multiple tracks
  test/suites/dev/test-conviction-voting/test-conviction-delegation-batch.ts
Labels: B0-silent, D2-notlive

#2514 CLI flag to disable Prometheus metrics moonbeam prefix
  node/cli-opt/src/lib.rs
  node/cli/src/cli.rs
  node/service/src/lib.rs
Labels: A0-pleasereview, B5-clientnoteworthy, D3-trivial, not-breaking

#2482 Update solidity to v0.8.21 when running tests
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/test-contract/test-contract-loop-cost.ts
  test/suites/dev/test-eth-fee/test-eth-fee-history.ts
  test/suites/dev/test-fees/test-fee-multiplier-max.ts
  test/suites/dev/test-gas/test-gas-contract-creation.ts
  test/suites/dev/test-gas/test-gas-estimation-contracts.ts
  test/suites/dev/test-gas/test-gas-estimation-multiply.ts
  test/suites/dev/test-receipt/test-receipt-revert.ts
  test/suites/dev/test-storage-growth/test-block-storage-growth.ts
  test/suites/dev/test-storage-growth/test-evm-create-storage-growth.ts
  test/suites/dev/test-txpool/test-txpool-limits2.ts
Labels: B0-silent, D2-notlive

#2515 Avoid CI to push to S3 for external PRs
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive, not-breaking

#2259 [Manual] Marking offline collators not producing blocks during X rounds
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/traits.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, D10-breaksdocs, breaking

#2516 small smoke test fixes
  test/helpers/foreign-chains.ts
  test/suites/smoke/test-polkadot-decoding.ts
Labels: B0-silent, D2-notlive

#2513 Add XCM Transactor precompile V3 to Moonriver and Moonbeam
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  test/helpers/constants.ts
  test/suites/dev/test-precompile/test-precompile-xcm-transactor10.ts
  test/suites/dev/test-precompile/test-precompile-xcm-transactor11.ts
  test/suites/dev/test-precompile/test-precompile-xcm-transactor12.ts
  test/suites/dev/test-precompile/test-precompile-xcm-transactor9.ts
  test/suites/dev/test-precompile/test-precompile-xcm-utils.ts
  test/suites/dev/test-precompile/test-precompile-xtokens.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2517 Fix the build error in typescript-tracing-tests
  Cargo.lock
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
  runtime/relay-encoder/Cargo.toml
  test/moonwall.config.json
  test/suites/tracing-tests/test-trace-erc20-xcm.ts
  test/suites/tracing-tests/test-trace-ethereum-xcm-1.ts
  test/suites/tracing-tests/test-trace-ethereum-xcm-2.ts
  test/suites/tracing-tests/test-trace-filter.ts
  test/suites/tracing-tests/test-trace-gas.ts
Labels: B5-clientnoteworthy, A10-evmtracing, D3-trivial, not-breaking

#2494 MoonScope Integration
  .github/workflows/build.yml
  test/.gitignore
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/test-treasury/test-treasury-proposal10.ts
Labels: B0-silent, D2-notlive

#2497 do not install protoc on bare-metal runners
  .github/workflows/docs.yml
Labels: B0-silent, ci, D2-notlive

#2520 Fix tracing tests and update workflow to run more tests
  .github/workflows/build.yml
  test/suites/tracing-tests/test-trace-gas.ts
Labels: B0-silent, ci, D2-notlive

#2421 test: [MOON-2252] add lock test for voting and staking
  test/suites/dev/test-locks/test-locks-multiple-locks.ts
Labels: B0-silent, C1-low, D2-notlive

#2487 update staking weights
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/src/tests.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
Labels: B7-runtimenoteworthy, D1-audited👍, not-breaking

#2525 Update API Augment to 2500
  .github/workflows/publish-typescript-api.yml
  .github/workflows/upgrade-typescript-api.yml
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
  typescript-api/package-lock.json
  typescript-api/package.json
  typescript-api/scripts/runtime-upgrade.sh
  typescript-api/src/moonbase/interfaces/augment-api-consts.ts
  typescript-api/src/moonbase/interfaces/augment-api-errors.ts
  typescript-api/src/moonbase/interfaces/augment-api-events.ts
  typescript-api/src/moonbase/interfaces/augment-api-query.ts
  typescript-api/src/moonbase/interfaces/augment-api-runtime.ts
  typescript-api/src/moonbase/interfaces/augment-api-tx.ts
  typescript-api/src/moonbase/interfaces/augment-types.ts
  typescript-api/src/moonbase/interfaces/lookup.ts
  typescript-api/src/moonbase/interfaces/registry.ts
  typescript-api/src/moonbase/interfaces/types-lookup.ts
  typescript-api/src/moonbeam/interfaces/augment-api-consts.ts
  typescript-api/src/moonbeam/interfaces/augment-api-errors.ts
  typescript-api/src/moonbeam/interfaces/augment-api-events.ts
  typescript-api/src/moonbeam/interfaces/augment-api-query.ts
  typescript-api/src/moonbeam/interfaces/augment-api-runtime.ts
  typescript-api/src/moonbeam/interfaces/augment-api-tx.ts
  typescript-api/src/moonbeam/interfaces/augment-types.ts
  typescript-api/src/moonbeam/interfaces/lookup.ts
  typescript-api/src/moonbeam/interfaces/registry.ts
  typescript-api/src/moonbeam/interfaces/types-lookup.ts
  typescript-api/src/moonriver/interfaces/augment-api-consts.ts
  typescript-api/src/moonriver/interfaces/augment-api-errors.ts
  typescript-api/src/moonriver/interfaces/augment-api-events.ts
  typescript-api/src/moonriver/interfaces/augment-api-query.ts
  typescript-api/src/moonriver/interfaces/augment-api-runtime.ts
  typescript-api/src/moonriver/interfaces/augment-api-tx.ts
  typescript-api/src/moonriver/interfaces/augment-types.ts
  typescript-api/src/moonriver/interfaces/lookup.ts
  typescript-api/src/moonriver/interfaces/registry.ts
  typescript-api/src/moonriver/interfaces/types-lookup.ts
Labels: B0-silent, D2-notlive

#2523 Withdrawability check
  Cargo.lock
  runtime/common/src/impl_on_charge_evm_transaction.rs
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2524 fix incorrect eth parent hashes on moonbase
  node/service/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2528 Gracefully handle error condition in node service
  node/service/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#2529 Coverage CI report improvement
  .github/scripts/coverage-report.py
  .github/workflows/coverage.yml
Labels: B0-silent, D2-notlive

#2131 Decouple relay pallet indices from runtimes
  Cargo.lock
  Cargo.toml
  node/service/Cargo.toml
  node/service/src/chain_spec/moonbase.rs
  pallets/xcm-transactor/Cargo.toml
  pallets/xcm-transactor/src/encode.rs
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/relay_indices.rs
  pallets/xcm-transactor/src/tests.rs
  precompiles/relay-encoder/Cargo.toml
  precompiles/relay-encoder/src/lib.rs
  precompiles/relay-encoder/src/mock.rs
  precompiles/relay-encoder/src/test_relay_runtime.rs
  precompiles/xcm-transactor/src/mock.rs
  primitives/xcm/Cargo.toml
  primitives/xcm/src/transactor_traits.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_tests.rs
  runtime/relay-encoder/Cargo.toml
  runtime/relay-encoder/src/kusama.rs
  runtime/relay-encoder/src/polkadot.rs
  runtime/relay-encoder/src/westend.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D1-audited👍, breaking

#2526 Remove the minimum bond requirement for the orbitor pool collator
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  pallets/parachain-staking/src/weights.rs
  runtime/common/src/migrations.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  test/suites/dev/test-staking/test-candidate-force-join.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests10-bondless-collator.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests11-bondless-collator.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests12-bondless-collator.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests4-bondless-collator.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests5-bondless-collator.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests6-bondless-collator.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests7-bondless-collator.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests8-bondless-collator.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests9-bondless-collator.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2530 Use barrier from the polkadot-sdk for XCM asset transfer
  Cargo.lock
  archived_tests/archived_specs/test-xcm/test-xcm-erc20-transfer-two-ERC20.ts
  runtime/common/src/lib.rs
  runtime/common/src/xcm.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/statemint_like.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/statemint_like.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/statemine_like.rs
  test/suites/dev/test-xcm-v2/test-xcm-erc20-transfer-two-ERC20.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2531 GMP: Only query for wrapped asset if not our chain id
  precompiles/gmp/src/lib.rs
  test/suites/dev/test-precompile/test-precompile-wormhole.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2503 Change undecided timeout from 14 to 21 days
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbeam/src/governance/referenda.rs
  runtime/moonriver/src/governance/referenda.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2533 Fix Delegation through Proxy Pallet
  runtime/common/src/weights/pallet_proxy.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  scripts/benchmarking.sh
  test/contracts/src/ProxyForContractsDemo.sol
  test/suites/dev/test-proxy/test-proxy-for-contracts.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking
