Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-01, with the labels that each got.

#2018 allow isProxy to be called by smart contracts
  precompiles/proxy/src/lib.rs
  precompiles/proxy/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D5-nicetohaveaudit⚠️

#2025 Fix XCM Failures Smoke test
  tests/util/foreign-chains.ts
Labels: B0-silent, D2-notlive

#2016 add uniqueness note to randomness.sol salt parameter
  precompiles/randomness/Randomness.sol
Labels: B0-silent, D2-notlive

#1954 Account for early-exit weight in pay_one_collator_reward
  pallets/parachain-staking/src/lib.rs
Labels: B0-silent, D3-trivial

#2005 [MOON-1099] Staking precompile delegation amount getter
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/tests.rs
  tests/contracts/compiled/ParachainStaking.json
  tests/tests/test-precompile/test-precompile-staking.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial

#2030 Add new ts-tests for Moon isFinalized RPC methods
  tests/tests/test-moon/test-moon-rpc.ts
Labels: B0-silent, D2-notlive

#2029 introduce breaking and not-breaking label check
  .github/workflows/enforce-pr-labels.yml
Labels: B0-silent, D3-trivial

#2032 Improves PERF documentation
  PERF.md
Labels: B0-silent, D2-notlive

#1785 xcm utils precompile improvements: Send and Execute in Moonbase
  Cargo.lock
  precompiles/utils/src/data/mod.rs
  precompiles/utils/src/handle.rs
  precompiles/utils/src/testing/account.rs
  precompiles/xcm-utils/Cargo.toml
  precompiles/xcm-utils/XcmUtils.sol
  precompiles/xcm-utils/src/lib.rs
  precompiles/xcm-utils/src/mock.rs
  precompiles/xcm-utils/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  tests/contracts/compiled/XcmUtils.json
  tests/tests/test-precompile/test-precompile-xcm-utils.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2033 Staking precompile: getDelegatorTotalStaked and getCandidateTotalBacked getters
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D3-trivial, not-breaking

#2022 Add proxy method for proxy precompile (moonbase only)
  Cargo.lock
  pallets/ethereum-xcm/Cargo.toml
  pallets/ethereum-xcm/src/mock.rs
  pallets/proxy-genesis-companion/Cargo.toml
  pallets/proxy-genesis-companion/src/mock.rs
  precompiles/proxy/Cargo.toml
  precompiles/proxy/Proxy.sol
  precompiles/proxy/src/lib.rs
  precompiles/proxy/src/mock.rs
  precompiles/proxy/src/tests.rs
  precompiles/utils/macro/src/lib.rs
  precompiles/utils/macro/src/precompile_name_from_address.rs
  precompiles/utils/src/data/native.rs
  precompiles/utils/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  tests/contracts/compiled/Proxy.json
  tests/package.json
  tests/tests/test-precompile/test-precompile-proxy-author-mapping.ts
  tests/tests/test-precompile/test-precompile-proxy-governance.ts
  tests/tests/test-precompile/test-precompile-proxy-non-transfer.ts
  tests/tests/test-precompile/test-precompile-proxy.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2021 clean old migrations
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/tests.rs
  pallets/xcm-transactor/src/migrations.rs
  pallets/xcm-transactor/src/tests.rs
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2037 Staking precompile: candidateAutoCompoundingDelegationCount
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D3-trivial, not-breaking

#2040 Fixes balance smoke test
  tests/smoke-tests/test-balances-consistency.ts
Labels: B0-silent, D2-notlive

#2026 Patch EVM version for explicit call stack
  Cargo.lock
  Cargo.toml
Labels: A0-pleasereview, B7-runtimenoteworthy, C7-high, D1-audited👍, A10-evmtracing, not-breaking

#2043 Update eth contract code smoke test
  tests/smoke-tests/test-ethereum-contract-code.ts
Labels: B0-silent, D2-notlive

#2010 Girazoki hrmp general admin track manipulator
  Cargo.lock
  pallets/xcm-transactor/src/benchmarks.rs
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/tests.rs
  pallets/xcm-transactor/src/weights.rs
  precompiles/relay-encoder/Cargo.toml
  precompiles/relay-encoder/RelayEncoder.sol
  precompiles/relay-encoder/src/lib.rs
  precompiles/relay-encoder/src/test_relay_runtime.rs
  precompiles/xcm-transactor/Cargo.toml
  precompiles/xcm-transactor/src/functions.rs
  precompiles/xcm-transactor/src/mock.rs
  precompiles/xcm-transactor/src/v1/XcmTransactorV1.sol
  precompiles/xcm-transactor/src/v1/mod.rs
  precompiles/xcm-transactor/src/v2/XcmTransactorV2.sol
  precompiles/xcm-transactor/src/v2/mod.rs
  primitives/xcm/Cargo.toml
  primitives/xcm/src/filter_asset_max_fee.rs
  primitives/xcm/src/lib.rs
  primitives/xcm/src/transactor_traits.rs
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/relay_chain.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/src/governance/referenda.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/relay_chain.rs
  runtime/moonriver/tests/xcm_tests.rs
  runtime/relay-encoder/Cargo.toml
  runtime/relay-encoder/src/kusama.rs
  runtime/relay-encoder/src/polkadot.rs
  runtime/relay-encoder/src/westend.rs
  tests/contracts/solidity/RelayEncoderInstance.sol
  tests/tests/test-democracy/test-referenda-general-admin.ts
  tests/tests/test-xcm/test-xcm-transactor.ts
  tests/util/governance.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2044 Adds GeneralAdmin as Origin of multiple extrinsics (Moonbase/Moonriver)
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2039 Add smoke tests for relaychain call index checking
  tests/smoke-tests/test-relay-indices.ts
Labels: B0-silent, D2-notlive

#1765 Use `transaction-payment`'s congestion modifier for Ethereum base-fee
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  tests/tests/test-balance/test-balance-existential.ts
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-contract/test-contract-evm-limits.ts
  tests/tests/test-eth-fee/test-eth-fee-history.ts
  tests/tests/test-eth-fee/test-eth-txn-weights.ts
  tests/tests/test-eth-pool/test-eth-pool-error.ts
  tests/tests/test-eth-tx/test-eth-tx-size.ts
  tests/tests/test-eth-tx/test-eth-tx-types.ts
  tests/tests/test-ethers/test-ethers.ts
  tests/tests/test-evm/test-pallet-evm-transfer.ts
  tests/tests/test-fees/test-fee-multiplier.ts
  tests/tests/test-fees/test-fees-repartition.ts
  tests/tests/test-fees/test-length-fees.ts
  tests/tests/test-maintenance/test-maintenance-filter.ts
  tests/tests/test-moon/test-moon-rpc.ts
  tests/tests/test-precompile/test-precompile-erc20.ts
  tests/tests/test-precompile/test-precompile-local-assets-erc20.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
  tests/tests/test-receipt/test-receipt.ts
  tests/tests/test-staking/test-rewards-auto-compound.ts
  tests/tests/test-staking/test-staking-locks.ts
  tests/tests/test-subscription/test-subscription.ts
  tests/tests/test-sudo/test-sudo.ts
  tests/tests/test-txpool/test-txpool-future.ts
  tests/tests/test-txpool/test-txpool-pending.ts
  tests/util/block.ts
  tests/util/constants.ts
  tests/util/contracts.ts
  tests/util/expect.ts
  tests/util/setup-dev-tests.ts
  tests/util/transactions.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2028 add gov2 tech committee
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/chain_spec/test_spec.rs
  node/service/src/lib.rs
  runtime/moonbase/src/governance/councils.rs
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonriver/src/governance/councils.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2047 Fix para para-tests (bump gas price)
  tests/para-tests/moonbase/test-migration-txpool.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#1885 Gov2 Precompiles
  Cargo.lock
  Cargo.toml
  precompiles/conviction-voting/Cargo.toml
  precompiles/conviction-voting/ConvictionVoting.sol
  precompiles/conviction-voting/src/lib.rs
  precompiles/conviction-voting/src/mock.rs
  precompiles/conviction-voting/src/tests.rs
  precompiles/preimage/Cargo.toml
  precompiles/preimage/Preimage.sol
  precompiles/preimage/src/lib.rs
  precompiles/preimage/src/mock.rs
  precompiles/preimage/src/tests.rs
  precompiles/referenda/Cargo.toml
  precompiles/referenda/Referenda.sol
  precompiles/referenda/src/lib.rs
  precompiles/referenda/src/mock.rs
  precompiles/referenda/src/tests.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/governance/origins.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/governance/origins.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2048 Update proxies for new pallets
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2049 Bump frontier version
  Cargo.lock
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2046 tests: update compiled pre-deployed contract files
  tests/contracts/compiled/ConvictionVoting.json
  tests/contracts/compiled/Democracy.json
  tests/contracts/compiled/ERC20Instance.json
  tests/contracts/compiled/ParachainStaking.json
  tests/contracts/compiled/Preimage.json
  tests/contracts/compiled/Proxy.json
  tests/contracts/compiled/ProxyLeaderDemo.json
  tests/contracts/compiled/Randomness.json
  tests/contracts/compiled/RandomnessLotteryDemo.json
  tests/contracts/compiled/Referenda.json
  tests/contracts/compiled/RelayEncoder.json
  tests/contracts/compiled/RelayEncoderInstance.json
  tests/contracts/compiled/Roles.json
  tests/contracts/compiled/StakingAttacker.json
  tests/contracts/compiled/StaticSubcall.json
  tests/contracts/compiled/XcmTransactorV1.json
  tests/contracts/compiled/XcmTransactorV2.json
  tests/contracts/compiled/XcmUtils.json
Labels: B0-silent, D2-notlive

#2050 smoke test - check staking rewards starting from the block after first
  tests/smoke-tests/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#2031 CI: copy tools scripts in workflows using it
  .github/workflows/client-release-issue.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/runtime-release-issue.yml
  tools/github/print-client-release-issue.ts
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent, D2-notlive

#2051 Improve gas checks in Randomness precompile
  precompiles/randomness/src/lib.rs
  precompiles/randomness/src/tests.rs
  precompiles/utils/src/testing/execution.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2053 Weights benchmarks for RT2100
  pallets/asset-manager/src/weights.rs
  pallets/author-mapping/src/weights.rs
  pallets/migrations/src/weights.rs
  pallets/moonbeam-orbiters/src/weights.rs
  pallets/moonbeam-xcm-benchmarks/src/weights/moonbeam_xcm_benchmarks_generic.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  pallets/randomness/src/weights.rs
  pallets/xcm-transactor/src/weights.rs
  precompiles/parachain-staking/src/tests.rs
  precompiles/randomness/src/lib.rs
  precompiles/xcm-transactor/src/tests.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  tests/tests/test-precompile/test-precompile-xcm-utils.ts
Labels: B0-silent, D3-trivial

#2055 Added correct expected values
  tests/smoke-tests/test-relay-indices.ts
Labels: B0-silent, D2-notlive

#2042 Start minimal relay node if `relay_chain_rpc_url` is set
  Cargo.lock
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D3-trivial, breaking

#2058 bump runtimes spec version to 2200
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#2027 Add Smoke test IDs
  tests/smoke-tests/test-author-filter-consistency.ts
  tests/smoke-tests/test-author-mapping-consistency.ts
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-block-finalized.ts
  tests/smoke-tests/test-block-weights.ts
  tests/smoke-tests/test-ethereum-contract-code.ts
  tests/smoke-tests/test-ethereum-current-consistency.ts
  tests/smoke-tests/test-ethereum-db-mapping.ts
  tests/smoke-tests/test-ethereum-failures.ts
  tests/smoke-tests/test-foreign-asset-consistency.ts
  tests/smoke-tests/test-foreign-xcm-failures.ts
  tests/smoke-tests/test-historic-compatibility.ts
  tests/smoke-tests/test-local-asset-consistency.ts
  tests/smoke-tests/test-orbiter-consistency.ts
  tests/smoke-tests/test-polkadot-decoding.ts
  tests/smoke-tests/test-proxy-consistency.ts
  tests/smoke-tests/test-randomness-consistency.ts
  tests/smoke-tests/test-relay-indices.ts
  tests/smoke-tests/test-relay-xcm-fees.ts
  tests/smoke-tests/test-staking-consistency.ts
  tests/smoke-tests/test-staking-rewards.ts
  tests/smoke-tests/test-staking-round-cleanup.ts
  tests/smoke-tests/test-treasury-consistency.ts
  tests/smoke-tests/test-xcm-failures.ts
  tests/util/dev-node.ts
  tests/util/foreign-chains.ts
  tests/util/setup-smoke-tests.ts
  tests/util/smokeFixtures.ts
Labels: B0-silent, D2-notlive

#2060 Utility.asDerivativeV2 test skipped for moonriver/beam
  tests/smoke-tests/test-relay-indices.ts
Labels: B0-silent, D2-notlive

#2061 fix: distribute_rewards not forward balance anymore but create instead
  pallets/moonbeam-orbiters/src/benchmarks.rs
Labels: B0-silent, D2-notlive

#2062 Increase timeout for mb smoke tctc
  tests/smoke-tests/test-balances-consistency.ts
Labels: B0-silent, D2-notlive

#1995 Add AMM contract sanity checks for forked state testing
  scripts/run-fork-chain.sh
  tests/fork-tests/staticData.ts
  tests/fork-tests/test-contract-amm.ts
  tests/fork-tests/test-contract-mm.ts
  tests/package-lock.json
  tests/package.json
  tests/smoke-tests/test-ethereum-current-consistency.ts
  tests/smoke-tests/test-historic-compatibility.ts
  tests/state-modifier.ts
  tests/util/constants.ts
  tests/util/dev-node.ts
  tests/util/governance.ts
  tests/util/para-node.ts
  tests/util/setup-dev-tests.ts
  tests/util/setup-para-tests.ts
Labels: B0-silent, D2-notlive

#2054 Add XCM scenarios to fee-multiplier tests
  tests/tests/test-fees/test-fee-multiplier.ts
  tests/util/constants.ts
Labels: B0-silent, D2-notlive

#2065 Rename Slow to Fast (documentation/code clarity)
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
Labels: A0-pleasereview, A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#2056 [MOON-2077] add awarded_pts to precompiles
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  tests/contracts/compiled/ParachainStaking.json
  tests/contracts/compiled/StakingAttacker.json
  tests/tests/test-precompile/test-precompile-staking.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2066 createTransaction txn type consistency
  tests/tests/test-balance/test-balance-existential.ts
  tests/tests/test-balance/test-balance-transfer.ts
  tests/tests/test-eth-pool/test-eth-pool-error.ts
  tests/tests/test-fees/test-fee-multiplier.ts
  tests/tests/test-precompile/test-precompile-xtokens.ts
  tests/tests/test-txpool/test-txpool-pending.ts
  tests/util/transactions.ts
Labels: B0-silent, D3-trivial, not-breaking

#1957 Prioritize Substrate txns by tip-per-effective-gas
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-staking/test-staking-locks.ts
  tests/tests/test-txpool/test-txpool-fairness.ts
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking
