Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-12, with the labels that each got.

#2584 [Moonriver] Add identity precompile
  Cargo.lock
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2585 [Moonbeam] Add identity precompile
  Cargo.lock
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2572 Disable proposal submission for the Democracy pallet by rejecting the tx
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/suites/dev/test-balance/test-balance-reducible.ts
  test/suites/dev/test-democracy/test-democracy-proposal-seconding.ts
  test/suites/dev/test-democracy/test-democracy-proposal.ts
  test/suites/dev/test-precompile/test-precompile-democracy2.ts
  test/suites/dev/test-precompile/test-precompile-democracy3.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2555 Migrate pallets old versions
  runtime/common/src/migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2553 Allow setting Unlimited for BuyExecution in XCM Transactor
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/tests.rs
  precompiles/xcm-transactor/src/functions.rs
  precompiles/xcm-transactor/src/v3/XcmTransactorV3.sol
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/tests/xcm_tests.rs
  test/suites/dev/test-democracy/test-referenda-general-admin.ts
  test/suites/dev/test-xcm-v3/test-xcm-transactor-2.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2512 Transferable Balance Test
  test/helpers/voting.ts
  test/suites/dev/test-balance/test-balance-transferable.ts
  test/suites/dev/test-locks/test-locks-multiple-locks.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting2.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting3.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting4.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting5.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting6.ts
Labels: B0-silent, D2-notlive, D3-trivial, not-breaking

#2591 skip steps with secrets from forks
  .github/workflows/build.yml
Labels: B0-silent, ci, D2-notlive

#2486 Fix features not being passed to cargo-build template
  .github/workflow-templates/cargo-build/action.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
Labels: B0-silent, D2-notlive

#2590 Remove old migrations
  runtime/common/src/migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#2597 Pre-release chores
  Cargo.lock
  client/evm-tracing/Cargo.toml
  client/evm-tracing/src/types/serialization.rs
  primitives/account/src/lib.rs
Labels: B0-silent, D2-notlive, not-breaking

#2586 Improving CI reliability cont.
  test/helpers/index.ts
  test/helpers/tracingFns.ts
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/para-rpc/test_moonbase.ts
  test/suites/para-rpc/test_moonbeam.ts
  test/suites/para/test_moonbase.ts
  test/suites/para/test_moonbeam.ts
  test/suites/rt-upgrade/test-upgrade-chain.ts
  test/suites/tracing-tests/test-trace-1.ts
  test/suites/tracing-tests/test-trace-2.ts
  test/suites/tracing-tests/test-trace-5.ts
  test/suites/tracing-tests/test-trace-7.ts
Labels: B0-silent, D2-notlive

#2593 Allow async backing in moonbase
  Cargo.lock
  Cargo.toml
  core-primitives/Cargo.toml
  core-primitives/src/lib.rs
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/client.rs
  node/service/src/lib.rs
  pallets/ethereum-xcm/src/lib.rs
  precompiles/assets-erc20/src/eip2612.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/balances-erc20/Cargo.toml
  precompiles/balances-erc20/src/eip2612.rs
  precompiles/balances-erc20/src/lib.rs
  precompiles/call-permit/Cargo.toml
  precompiles/call-permit/src/lib.rs
  precompiles/crowdloan-rewards/src/mock.rs
  precompiles/relay-encoder/src/mock.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/timestamp.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  test/suites/dev/test-pov/test-evm-over-pov2.ts
  test/suites/dev/test-pov/test-precompile-over-pov2.ts
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2599 Pre release chores
  .github/workflows/publish-binary.yml
  scripts/run-benches-for-runtime.sh
  scripts/run_benches_for_runtime.sh
  tools/README.md
  tools/github/print-client-release-issue.ts
  tools/launch.ts
Labels: B0-silent, ci, D2-notlive, not-breaking

#2603 Fix client build
  .github/workflows/publish-binary.yml
Labels: B0-silent, ci, D2-notlive
