Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-04, with the labels that each got.

#2174 Moonbeam: update collator candidate self-bond
  node/service/src/chain_spec/moonbeam.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, D10-breaksdocs, breaking

#2188 [MOON-2174] add smoke test to ensure managed assets are live
  tests/smoke-tests/test-foreign-asset-consistency.ts
Labels: B0-silent, D2-notlive

#2195 add `GeneralAdminOrRoot` to `SetMembersOrigin`
  Cargo.lock
  precompiles/collective/src/mock.rs
  runtime/moonbase/src/governance/councils.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/governance/councils.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2207 Switch to stable rust and make rust debug build usable
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  pallets/moonbeam-orbiters/src/lib.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/author-mapping/src/lib.rs
  precompiles/balances-erc20/src/lib.rs
  precompiles/conviction-voting/src/lib.rs
  precompiles/crowdloan-rewards/src/lib.rs
  precompiles/pallet-democracy/src/lib.rs
  precompiles/parachain-staking/src/lib.rs
  precompiles/preimage/src/lib.rs
  precompiles/proxy/src/lib.rs
  precompiles/randomness/src/lib.rs
  precompiles/referenda/src/lib.rs
  precompiles/relay-encoder/src/lib.rs
  precompiles/utils/macro/tests/compile-fail/precompile/discriminant/missing-param.stderr
  precompiles/utils/macro/tests/compile-fail/precompile/discriminant/too-many-arguments.stderr
  precompiles/utils/macro/tests/compile-fail/precompile/evm-data/no-output.stderr
  precompiles/utils/macro/tests/compile-fail/precompile/evm-data/output-dont-impl-evmdata.stderr
  precompiles/utils/macro/tests/compile-fail/precompile/evm-data/output-wrong-error-result.stderr
  precompiles/utils/macro/tests/compile-fail/precompile/handle/missing.stderr
  precompiles/utils/macro/tests/compile-fail/precompile/handle/set-missing.stderr
  precompiles/utils/macro/tests/compile-fail/precompile/pre-check/no-parameter.stderr
  precompiles/utils/macro/tests/compile-fail/precompile/pre-check/too-many-parameters.stderr
  precompiles/utils/macro/tests/expand/precompile.expanded.rs
  precompiles/utils/macro/tests/expand/precompileset.expanded.rs
  precompiles/utils/macro/tests/expand/returns_tuple.expanded.rs
  precompiles/utils/macro/tests/tests.rs
  precompiles/utils/src/lib.rs
  precompiles/xcm-transactor/src/lib.rs
  precompiles/xcm-utils/src/lib.rs
  precompiles/xtokens/src/lib.rs
  rust-toolchain
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2190 Update Moonriver bootnodes
  specs/moonriver/parachain-embedded-specs.json
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial, not-breaking

#2204 Add PrecompileRegistry precompile to all runtimes
  Cargo.lock
  precompiles/precompile-registry/PrecompileRegistry.sol
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low, D5-nicetohaveaudit⚠️, not-breaking

#2206 Add xcm-transactor V2 precompile to moonriver/moonbeam
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2201 [MOON-2307] Precompile method conviction_voting::removeVoteForTrack
  precompiles/conviction-voting/ConvictionVoting.sol
  precompiles/conviction-voting/src/lib.rs
  precompiles/conviction-voting/src/tests.rs
  tests/contracts/compiled/ConvictionVoting.json
  tests/tests/test-precompile/test-precompile-conviction-voting.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2163 Allows Ethereum Tracing with Collator
  node/cli/src/cli.rs
Labels: A0-pleasereview, B5-clientnoteworthy, D3-trivial, not-breaking

#2196 add missing collective storage prefix checks
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B0-silent, D3-trivial, not-breaking

#2220 [MOON-2311] expose VotingFor and ClassLocksFor data in precompile
  precompiles/conviction-voting/ConvictionVoting.sol
  precompiles/conviction-voting/src/lib.rs
  precompiles/conviction-voting/src/tests.rs
  precompiles/utils/src/data/native.rs
  tests/contracts/compiled/ConvictionVoting.json
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2221 Pin frontier `df4e329`
  Cargo.lock
  tests/tests/test-gas/test-gas-estimation.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, not-breaking

#2222 fix old erc20-xcm implementation: recreate XcmExecutorWrapper
  pallets/erc20-xcm-bridge/src/lib.rs
  pallets/erc20-xcm-bridge/src/xcm_holding_ext.rs
  runtime/moonbase/src/xcm_config.rs
Labels: B0-silent, D3-trivial

#2227 Fix runtime-benchmarks
  pallets/parachain-staking/src/benchmarks.rs
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#2225 add typescript test for erc20 xcm reception + refactor xcm utils (ts)
  tests/package-lock.json
  tests/package.json
  tests/tests/test-fees/test-fee-multiplier.ts
  tests/tests/test-xcm/test-mock-dmp-error-and-appendix.ts
  tests/tests/test-xcm/test-mock-dmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-asset-transfer.ts
  tests/tests/test-xcm/test-mock-hrmp-queue.ts
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
  tests/tests/test-xcm/test-mock-hrmp-transact.ts
  tests/tests/test-xcm/test-xcm-erc20-transfer.ts
  tests/tracing-tests/test-trace-ethereum-xcm.ts
  tests/util/xcm.ts
Labels: B0-silent, D2-notlive

#2228 MOdify proof size for XCM
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/src/xcm_config.rs
  tests/tests/test-xcm/test-xcm-ver-conversion.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2232 remove typo in publish runtime workflow
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D2-notlive

#2223 Update Moonbeam bootnodes
  specs/moonbeam/parachain-embedded-specs.json
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial, not-breaking

#2233 bump spec version
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#2208 Enable proof recording in dev mode
  Cargo.lock
  node/service/src/lib.rs
  tests/tests/test-xcm/test-xcm-erc20-transfer.ts
Labels: B0-silent, D2-notlive

#2238 Restore fix for set-heap-page overflow
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#2226 Import extract_genesis_wasm function instead of duplicating it
  node/cli/src/command.rs
Labels: B0-silent, D3-trivial, not-breaking

#2241 use cargo resolver v2
  Cargo.toml
Labels: B0-silent, D2-notlive

#2242 Moving CI to bare-metal
  .github/workflows/build.yml
  node/src/main.rs
  node/src/tests.rs
  test/suites/rt-upgrade/test-upgrade-chain.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#2251 Cleanup CI
  .github/workflows/build.yml
  .github/workflows/check-features.yml
  precompiles/gmp/src/types.rs
Labels: B0-silent, D2-notlive

#2252 Fix `xcm-transactor` migration values
  pallets/xcm-transactor/src/migrations.rs
Labels: A0-pleasereview, B0-silent, D5-nicetohaveaudit⚠️, breaking

#2247 Avoid binary search over potentially unsorted data
  precompiles/referenda/Cargo.toml
  precompiles/referenda/src/lib.rs
  precompiles/referenda/src/tests.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2244 GMP: Rely only on amount transferred
  precompiles/gmp/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2245 Update solidity interface with correct precompile address
  precompiles/gmp/Gmp.sol
Labels: B0-silent, D3-trivial, not-breaking

#2250 Cleanup migrations
  pallets/asset-manager/src/migrations.rs
  pallets/asset-manager/src/tests.rs
  pallets/author-mapping/src/migrations.rs
  pallets/author-mapping/src/tests.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/xcm-transactor/src/migrations.rs
  pallets/xcm-transactor/src/tests.rs
  runtime/common/src/migrations.rs
Labels: B0-silent, D3-trivial

#2234 Add replacement para test for moonbase
  .github/workflows/build.yml
  scripts/build-runtime-srtool.sh
  test/.gitignore
  test/configs/zombieAlphanet.json
  test/configs/zombieAlphanetCI.json
  test/configs/zombieMoonbeam.json
  test/configs/zombieMoonbeamCI.json
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/scripts/modify-plain-specs.ts
  test/suites/chopsticks/sample/test-basic-actions.ts
  test/suites/dev/sample/test_basic.ts
  test/suites/para/test_moonbase.ts
  test/suites/para/test_moonbeam.ts
  test/suites/smoke/test-author-filter-consistency.ts
  test/suites/smoke/test-author-mapping-consistency.ts
  test/suites/smoke/test-balances-consistency.ts
  test/tsconfig.json
  tests/README.md
Labels: B0-silent, D2-notlive

#2187 Add pallet-multisig to Moonbase runtime
  Cargo.lock
  Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2231 Fix collators not producing blocks when selected candidates is zero
  pallets/parachain-staking/src/lib.rs
  runtime/common/src/apis.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/runtime_apis.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2243 Add TS tests for erc20-xcm
  tests/tests/test-xcm/test-xcm-erc20-fees-and-trap.ts
  tests/tests/test-xcm/test-xcm-erc20-transfer-two-ERC20.ts
  tests/tests/test-xcm/test-xcm-erc20-transfer.ts
  tests/util/transactions.ts
Labels: B0-silent, D2-notlive

#2150 add ui and expand tests for name macro
  precompiles/utils/macro/src/generate_function_selector.rs
  precompiles/utils/macro/src/precompile/expand.rs
  precompiles/utils/macro/src/precompile_name_from_address.rs
  precompiles/utils/macro/tests/compile-fail/precompile_name/not_tuple.rs
  precompiles/utils/macro/tests/compile-fail/precompile_name/not_tuple.stderr
  precompiles/utils/macro/tests/expand/precompile.expanded.rs
  precompiles/utils/macro/tests/expand/precompile_name.expanded.rs
  precompiles/utils/macro/tests/expand/precompile_name.rs
  precompiles/utils/macro/tests/expand/precompileset.expanded.rs
  precompiles/utils/macro/tests/expand/returns_tuple.expanded.rs
Labels: A0-pleasereview, B0-silent, C1-low, D3-trivial, not-breaking

#2258 enable features try-runtime, runtime-benchmarks for clippy
  .github/workflows/build.yml
  pallets/migrations/src/lib.rs
  pallets/moonbeam-orbiters/src/benchmarks.rs
  pallets/moonbeam-xcm-benchmarks/src/generic/benchmarking.rs
  pallets/parachain-staking/src/benchmarks.rs
  pallets/randomness/src/benchmarks.rs
  pallets/xcm-transactor/src/benchmarks.rs
Labels: B0-silent, ci, D2-notlive

#2257 Refactored RateLimiter for CI
  tests/smoke-tests/test-author-filter-consistency.ts
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-block-finalized.ts
  tests/smoke-tests/test-block-weights.ts
  tests/smoke-tests/test-dynamic-fees.ts
  tests/smoke-tests/test-ethereum-failures.ts
  tests/smoke-tests/test-foreign-xcm-failures.ts
  tests/smoke-tests/test-historic-compatibility.ts
  tests/smoke-tests/test-staking-rewards.ts
  tests/smoke-tests/test-xcm-failures.ts
  tests/util/block.ts
  tests/util/common.ts
Labels: B0-silent, D2-notlive

#2266 Increase the minimum period for pallet timestamp
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2270 Missing XCM benchmark overrides
  pallets/moonbeam-xcm-benchmarks/src/generic/benchmarking.rs
Labels: B0-silent, D3-trivial, not-breaking

#2275 Increase XCM benchmark overrides to max weight
  pallets/moonbeam-xcm-benchmarks/src/generic/benchmarking.rs
Labels: B0-silent, D3-trivial, not-breaking
