Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-11, with the labels that each got.

#2547 Update weights from new benchmarks
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/moonbeam_xcm_benchmarks_weights_generic.rs
  runtime/common/src/weights/pallet_asset_manager.rs
  runtime/common/src/weights/pallet_assets.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_collective.rs
  runtime/common/src/weights/pallet_conviction_voting.rs
  runtime/common/src/weights/pallet_crowdloan_rewards.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_evm.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_moonbeam_orbiters.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_randomness.rs
  runtime/common/src/weights/pallet_referenda.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_sudo.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_whitelist.rs
  runtime/common/src/weights/pallet_xcm.rs
  runtime/common/src/weights/pallet_xcm_transactor.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
  scripts/run-benches-for-runtime.sh
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2549 build release runtime with production profile
  scripts/build-runtime-srtool.sh
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2542 Adds docker image build for Polkadot Relay nodes
  docker/polkadot-relay.Dockerfile
Labels: B0-silent, D2-notlive

#2550 Update commit hash reference for frontier
  Cargo.lock
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/tests/xcm_tests.rs
Labels: B0-silent, D3-trivial, not-breaking

#2546 precompiles(xcm-transactor): fix rust tests compilation
  precompiles/xcm-transactor/Cargo.toml
Labels: B0-silent, D2-notlive

#2552 Set minimum bond to 500 MOVR for Moonriver
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2534 Switch `dev-test` to octocore execution
  .github/workflow-templates/dev-tests/action.yml
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/test-txpool/test-txpool-limits4.ts
Labels: B0-silent, D2-notlive

#2559 Update Smoke Tests for RT2600
  test/package.json
  test/pnpm-lock.yaml
  test/suites/smoke/test-relay-indices.ts
  test/suites/smoke/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#2560 Make min bound orbiter migration infaillible
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  runtime/common/src/migrations.rs
Labels: B0-silent, D3-trivial

#2564 Fix TracingTest & Docker CI
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive

#2567 Update cargo.lock
  Cargo.lock
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2473 Provides a Release Candidate Image for Releases
  .github/workflows/publish-binary.yml
  docker/moonbeam-production.Dockerfile
  tools/github/print-client-release-issue.ts
Labels: B0-silent, D2-notlive, not-breaking

#2563 Fixes Licenses CI & Package Update
  scripts/verify-licenses.sh
  test/package.json
  test/pnpm-lock.yaml
Labels: B0-silent, D2-notlive

#2578 Improve CI Reliability
  .github/workflow-templates/dev-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/upgrade-typescript-api.yml
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
Labels: B0-silent, D2-notlive

#2576 Fake VRF for ethereum pending blocks
  .github/workflows/build.yml
  Cargo.lock
  runtime/common/src/apis.rs
  test/configs/zombieAlphanetRpc.json
  test/configs/zombieMoonbeamRpc.json
  test/moonwall.config.json
  test/suites/para-rpc/test_moonbase.ts
  test/suites/para-rpc/test_moonbeam.ts
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2569 Bump versions RT2700/v0.35.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D3-trivial, breaking

#2575 Disable coverage gathering during cargo build
  .github/workflows/coverage.yml
Labels: B0-silent, ci, D2-notlive, not-breaking

#2574 Add checklist step for client downgrade
  tools/github/print-client-release-issue.ts
Labels: B0-silent, ci, D2-notlive

#2582 Batch precompile valid caller tests
  test/helpers/eth-transactions.ts
  test/suites/dev/test-precompile/test-precompile-batch.ts
  test/suites/dev/test-precompile/test-precompile-call-permit-demo.ts
Labels: A0-pleasereview, B0-silent, D2-notlive, not-breaking
