Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-05, with the labels that each got.

#2271 Add typescript tests for multisigs
  tests/tests/test-multisigs/test-multisigs.ts
Labels: B0-silent, D2-notlive, not-breaking

#2269 CI: Enable debug-assertions and overflow-checks in rust tests
  .github/workflows/build.yml
  Cargo.toml
  primitives/xcm/src/fee_handlers.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2265 Remove MinCollatorStk from parachain-staking pallet
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, D10-breaksdocs, breaking

#2274 fail step when subshell fails
  .github/workflows/build.yml
Labels: B0-silent, ci, D2-notlive

#2279 Upgrade polkadot pin to depend on a polkadot version that doesn't require nightly rust anymore
  .github/workflows/build.yml
  Cargo.lock
  test/package.json
  test/pnpm-lock.yaml
  test/suites/rt-upgrade/test-upgrade-chain.ts
Labels: B0-silent, D2-notlive

#2277 Refactor Balance Consistency Test
  tests/smoke-tests/test-balances-consistency.ts
Labels: B0-silent, D2-notlive

#2278 [MOON-2370] fix conviction-voting precompile return types
  precompiles/conviction-voting/ConvictionVoting.sol
  tests/contracts/compiled/precompiles/conviction-voting/ConvictionVoting.json
  tests/tests/test-precompile/test-precompile-conviction-voting.ts
Labels: B0-silent, D2-notlive

#2280 simplify xcm junction decoding
  precompiles/utils/src/solidity/codec/xcm.rs
Labels: A0-pleasereview, B0-silent, D5-nicetohaveaudit⚠️, not-breaking

#2267 update nimbus
  Cargo.lock
Labels: B5-clientnoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2289 Not skip docker login on master
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive

#2273 Adds code coverage to CI
  .github/workflows/coverage.yml
Labels: A0-pleasereview, B0-silent, D2-notlive, not-breaking

#2264 Add multisigs to Moonriver and Moonbeam
  Cargo.lock
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2296 Post Release checklist: Publish docker runtime image
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent, D2-notlive

#2298 Adds exemple to version-bump.yml workflow
  .github/workflows/version-bump.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#2306 Fix hrmp-manage in XCM Transactor
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/tests.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2291 Handle substrate tips
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2254 Add minimal tests to show that new runtime API endpoints exist
  tests/tests/test-fees/test-fee-multiplier.ts
  tests/util/block.ts
Labels: B0-silent, D3-trivial, not-breaking

#2307 Add Unlimited weight to Xtokens precompile
  precompiles/xtokens/Xtokens.sol
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/tests.rs
  tests/contracts/compiled/XtokensInstance.json
  tests/contracts/compiled/precompiles/xtokens/Xtokens.json
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2292 Add GMP precompile killswitch
  precompiles/gmp/src/lib.rs
  precompiles/gmp/src/mock.rs
  precompiles/gmp/src/tests.rs
  tests/tests/test-precompile/test-precompile-wormhole.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D1-audited👍, breaking

#2281 Moonriver RefCanceller track support ceiling
  runtime/moonriver/src/governance/tracks.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2309 Update randomness and author mapping weight benchmarks
  pallets/author-mapping/src/benchmarks.rs
  pallets/randomness/src/benchmarks.rs
Labels: A0-pleasereview, B0-silent, D3-trivial, not-breaking

#2213 Add tests for Collective precompile decode limit.
  precompiles/collective/Cargo.toml
  precompiles/collective/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low, D3-trivial, not-breaking

#2308 Refactor the MBIPs
  MBIPS/MBIP-1.md
  MBIPS/MBIP-2.md
  MBIPS/MBIP-3.md
  MBIPS/MBIP-4.md
  MBIPS/MBIP-5.md
Labels: B0-silent, D2-notlive, not-breaking

#2194 Restore default Port for Test + Test for PoV
  .vscode/settings.json
  PERF.md
  tests/contracts/compiled/CallForwarder.json
  tests/contracts/compiled/GmpPrecompile.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemo.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemoV1.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemoV2.json
  tests/contracts/compiled/ReferendaChecker.json
  tests/contracts/compiled/StateOverrideTest.json
  tests/contracts/compiled/precompiles/gmp/Gmp.json
  tests/contracts/solidity/CallForwarder.sol
  tests/tests/test-pov/test-evm-over-pov.ts
  tests/util/block.ts
  tests/util/constants.ts
  tests/util/setup-dev-tests.ts
Labels: B0-silent, D2-notlive, not-breaking

#2301 Updates docker files base image
  docker/moonbeam.Dockerfile
  docker/polkadot-relay.Dockerfile
Labels: B0-silent, D2-notlive, not-breaking

#2288 GMP: Use VersionedMultiLocation version in encoded struct
  precompiles/gmp/src/lib.rs
  precompiles/gmp/src/types.rs
  tests/tests/test-precompile/test-precompile-wormhole.ts
Labels: A0-pleasereview, B0-silent, D3-trivial, not-breaking

#2312 Update evm to 0.39
  Cargo.lock
  Cargo.toml
  precompiles/assets-erc20/src/lib.rs
  precompiles/precompile-registry/src/lib.rs
  precompiles/proxy/src/lib.rs
  precompiles/proxy/src/mock.rs
  precompiles/utils/macro/src/precompile/expand.rs
  precompiles/utils/macro/src/precompile/parse.rs
  precompiles/utils/macro/tests/expand/precompileset.expanded.rs
  precompiles/utils/macro/tests/tests.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/precompile_set.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, A10-evmtracing, breaking

#2315 XCM: Derive remote accounts according to polkadot standards
  Cargo.lock
  primitives/account/src/lib.rs
  primitives/xcm/src/lib.rs
  primitives/xcm/src/location_conversion.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  tests/tests/test-fees/test-fee-multiplier.ts
  tests/tests/test-precompile/test-precompile-xcm-utils.ts
  tests/tests/test-xcm/test-mock-hrmp-transact-ethereum.ts
  tests/tests/test-xcm/test-mock-hrmp-transact.ts
  tests/tracing-tests/test-trace-ethereum-xcm.ts
  tests/util/xcm.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2321 Fix precompiled proxy call transfer with tx value
  precompiles/proxy/Cargo.toml
  precompiles/proxy/src/lib.rs
  tests/tests/test-precompile/test-precompile-proxy.ts
Labels: B0-silent, D9-needsaudit👮, not-breaking
