Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-09, with the labels that each got.

#2470 Wrap FrontierBlockImport into ParachainBlockImport
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2475 Fix try-runtime pre/post hook (#2553)
  Cargo.lock
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2480 Fix Tracing Test CI
  archived_tests/README.md
  archived_tests/tsconfig.json
Labels: B0-silent, A10-evmtracing, D2-notlive

#2469 Check dev-service flag from CLI
  node/cli/src/command.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2484 Potential staking optimization: avoid decoding Vecs (#2414)
  pallets/parachain-staking/src/auto_compound.rs
  pallets/parachain-staking/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2483 Enable importing new blocks as best in dev mode
  .github/workflows/coverage.yml
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2478 Bump versions (v0.34.0/RT2600)
  .github/workflows/build.yml
  Cargo.lock
  MBIPS/MBIP-2.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#2492 Add tests for GeneralKey data field size
  test/helpers/xcm.ts
  test/suites/dev/test-xcm-v3/test-xcm-erc20-data-field-size.ts
Labels: B0-silent, D2-notlive, not-breaking

#2472 Moves doc CI action to bare-metal
  .github/workflows/docs.yml
Labels: B0-silent, D2-notlive, not-breaking

#2493 Fix typos
  MBIPS/MBIP-2.md
  MBIPS/MBIP-3.md
  MBIPS/MBIP-4.md
  MBIPS/MBIP-5.md
  MBIPS/MBIP-6.md
  PERF.md
  docs/git-branches-conventions.md
  docs/workspace-dependencies.md
  pallets/ethereum-xcm/Cargo.toml
Labels: B0-silent, D2-notlive

#2437 Testing uploading test report to S3
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive, not-breaking

#2379 Remove Pallet ethereum-chain-id in favor of frontier evm-chain-id
  Cargo.lock
  Cargo.toml
  README.md
  pallets/ethereum-chain-id/Cargo.toml
  pallets/ethereum-chain-id/src/lib.rs
  runtime/common/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
Labels: B7-runtimenoteworthy, D1-audited👍, breaking

#2462 Update release draft script for breaking PRs
  tools/github/generate-release-body.ts
  tools/github/generate-runtimes-body.ts
Labels: B0-silent, D2-notlive

#2498 Migrate Tracing tests to Moonwall
  .github/workflows/build.yml
  scripts/run-tracing-tests.sh
  test/helpers/tracer/blockscout_tracer.min.json
  test/helpers/tracer/blockscout_tracer_v2.min.json
  test/moonwall.config.json
  test/suites/tracing-tests/test-trace-1.ts
  test/suites/tracing-tests/test-trace-2.ts
  test/suites/tracing-tests/test-trace-3.ts
  test/suites/tracing-tests/test-trace-4.ts
  test/suites/tracing-tests/test-trace-5.ts
  test/suites/tracing-tests/test-trace-6.ts
  test/suites/tracing-tests/test-trace-7.ts
  test/suites/tracing-tests/test-trace-concurrency.ts
  test/suites/tracing-tests/test-trace-erc20-xcm.ts
  test/suites/tracing-tests/test-trace-ethereum-xcm-1.ts
  test/suites/tracing-tests/test-trace-ethereum-xcm-2.ts
  test/suites/tracing-tests/test-trace-filter-reorg.ts
  test/suites/tracing-tests/test-trace-filter.ts
  test/suites/tracing-tests/test-trace-gas.ts
Labels: B0-silent, A10-evmtracing, D2-notlive, not-breaking
