Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-06, with the labels that each got.

#2276 add a smoke test to verify fix for the invalid parent hash in moonbase
  tests/smoke-tests/test-eth-parent-hash-bad-block-fix.ts
Labels: B0-silent, D3-trivial

#2318 Enable Xcm->Evm and Erc20Xcm on Moonriver & Moonbeam
  Cargo.lock
  pallets/erc20-xcm-bridge/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/relay_chain.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/relay_chain.rs
  runtime/moonriver/tests/xcm_tests.rs
  tests/util/setup-dev-tests.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2317 staking new benchmarks
  pallets/parachain-staking/src/auto_compound.rs
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/weights.rs
  precompiles/parachain-staking/src/tests.rs
  tests/tests/test-staking/test-rewards-auto-compound.ts
  tests/tests/test-staking/test-staking-consts.ts
  tests/tests/test-staking/test-staking-locks.ts
  tests/tests/test-staking/test-weights.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2326 Set correct XCM config RelayNetwork for Moonbase
  runtime/moonbase/src/xcm_config.rs
Labels: B0-silent, D3-trivial, not-breaking

#2328 Fix weight v2 gas staking precompile typescript tests
  tests/tests/test-precompile/test-precompile-staking.ts
  tests/tests/test-precompile/test-precompile-xcm-utils.ts
Labels: B0-silent, D2-notlive, not-breaking

#2327 Add GMP precompile to Moonriver and Moonbeam runtimes
  Cargo.lock
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2335 Fix xcm barrier
  primitives/xcm/src/barriers.rs
  primitives/xcm/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/relay_chain.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/relay_chain.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2331 Fix tracing ts tests
  tests/tracing-tests/test-trace-filter.ts
Labels: B0-silent, A10-evmtracing, D2-notlive, not-breaking

#2332 ignore test for stagenet
  tests/smoke-tests/test-eth-parent-hash-bad-block-fix.ts
Labels: B0-silent, D2-notlive

#2337 Updates delegate weight
  pallets/parachain-staking/src/weights.rs
  tests/tests/test-staking/test-staking-locks.ts
Labels: B0-silent, D3-trivial, not-breaking

#2343 scope of already recorded codes and storages must be per transaction
  Cargo.lock
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2348 remove unused extrinsic
  pallets/parachain-staking/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2339 Updates srtool to 1.69.0 in the CI
  .github/workflows/build.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker-runtime.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/runtime-release-issue.yml
  AUTOMATION.md
  rust-toolchain
  scripts/build-runtime-srtool.sh
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent, D3-trivial, not-breaking

#2346 [MOON-2455] use checked-sub in refund weight
  precompiles/utils/src/substrate.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2352 Client version v0.32.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2345 Update ETH code smoke test
  .github/workflows/build.yml
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/sample/test_basic.ts
  test/suites/para/test_moonbase.ts
  test/suites/para/test_moonbeam.ts
  test/suites/rt-upgrade/test-upgrade-chain.ts
  test/suites/smoke/test-author-mapping-consistency.ts
  test/suites/smoke/test-block-finalized.ts
  test/suites/smoke/test-dynamic-fees.ts
  test/suites/smoke/test-ethereum-contract-code.ts
  test/suites/smoke/test-ethereum-db-mapping.ts
  test/suites/smoke/test-historic-compatibility.ts
  test/suites/smoke/test-relay-indices.ts
  tests/smoke-tests/test-ethereum-contract-code.ts
  tests/util/upgrade.ts
Labels: B0-silent, D2-notlive

#2356 Bump client to 0.33.0 & runtime to 2500
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D3-trivial, not-breaking

#2347 Add TS tests for PoV in XCM to EVM
  tests/tests/test-pov/test-xcm-to-evm-pov.ts
Labels: B0-silent, D2-notlive

#2360 pin frontier `688ad3b`
  Cargo.lock
Labels: A0-pleasereview, B0-silent, D3-trivial, not-breaking

#2358 fixes support for ethereum contract code length prefix
  test/pnpm-lock.yaml
  test/suites/smoke/test-ethereum-contract-code.ts
  tests/smoke-tests/test-ethereum-contract-code.ts
Labels: B0-silent, D2-notlive, not-breaking

#2368 Prune duplicate `hex` dependency
  primitives/account/Cargo.toml
Labels: B0-silent, D3-trivial

#2369 Make `account` crate clippy compliant
  primitives/account/src/lib.rs
Labels: B0-silent, D3-trivial

#2367 Remove `IntoAddressMapping`
  runtime/common/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: B0-silent, D3-trivial

#2370 fix rust tests
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: B0-silent, D2-notlive

#2333 deprecate delegate in sol
  precompiles/parachain-staking/StakingInterface.sol
  tests/contracts/compiled/precompiles/parachain-staking/ParachainStaking.json
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2359 merge ws-port and rpc-port
  tests/util/dev-node.ts
  tests/util/para-node.ts
  tests/util/setup-dev-tests.ts
  tests/util/setup-para-tests.ts
  tests/util/transactions.ts
  tools/block-tracker.ts
  tools/get-binary.ts
  tools/get-block.ts
  tools/init-web3.ts
  tools/launch.ts
  tools/load-testing/load-gas-loop.ts
Labels: B0-silent, ci, D2-notlive
