Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-02, with the labels that each got.

#1939 Regression tests for `ExtrinsicSuccess` missing `extrinsic_base_weight`
  tests/tests/test-eth-fee/test-eth-txn-weights.ts
Labels: A8-mergeoncegreen, B0-silent, B7-runtimenoteworthy, D3-trivial, not-breaking

#2070 Clean up min multiplier
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  tests/tests/test-fees/test-fee-multiplier.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2073 Record some weight in min_gas_price
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, not-breaking

#2034 Improve precompile set explicit list of security checks
  Cargo.lock
  Cargo.toml
  precompiles/batch/src/lib.rs
  precompiles/batch/src/mock.rs
  precompiles/call-permit/src/mock.rs
  precompiles/proxy/src/lib.rs
  precompiles/proxy/src/mock.rs
  precompiles/proxy/src/tests.rs
  precompiles/randomness/src/mock.rs
  precompiles/referenda/src/mock.rs
  precompiles/utils/Cargo.toml
  precompiles/utils/macro/src/precompile/expand.rs
  precompiles/utils/macro/src/precompile_name_from_address.rs
  precompiles/utils/macro/tests/precompile/expand/precompile.expanded.rs
  precompiles/utils/macro/tests/precompile/expand/precompileset.expanded.rs
  precompiles/utils/macro/tests/precompile/pass/fn-modifiers.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/precompile_set.rs
  precompiles/utils/tests-external/Cargo.toml
  precompiles/utils/tests-external/lib.rs
  precompiles/xcm-transactor/src/mock.rs
  precompiles/xcm-utils/src/lib.rs
  precompiles/xcm-utils/src/mock.rs
  precompiles/xcm-utils/src/tests.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/summarize-precompile-checks/Cargo.toml
  runtime/summarize-precompile-checks/src/main.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2077 Rename `submitAt.hash` and `submitAfter.hash` to `proposal`
  precompiles/referenda/Referenda.sol
Labels: A0-pleasereview, B0-silent, D3-trivial

#2081 Added WS waits/delays
  tests/util/setup-smoke-tests.ts
  tests/util/wsApis.ts
Labels: B0-silent, D2-notlive

#2082 Update macro expansion test
  precompiles/utils/macro/tests/precompile/expand/returns_tuple.expanded.rs
Labels: A0-pleasereview, B0-silent, D2-notlive, not-breaking

#2086 Record log cost first in `collective` precompile
  precompiles/collective/src/lib.rs
Labels: A0-pleasereview, B0-silent, D3-trivial, not-breaking

#2087 [MOON-2137] add randomness pallet as author filter source to moonriver
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2089 [MOON-2171] Return preimage hash from note preimage
  precompiles/preimage/Preimage.sol
  precompiles/preimage/src/lib.rs
  precompiles/preimage/src/mock.rs
  precompiles/preimage/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, not-breaking

#2096 Timbo bal test update
  tests/smoke-tests/test-balances-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#2088 Adds ParachainSystem pallet to non-transfer proxy
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, not-breaking

#2079 Return referendumIndex from submit
  precompiles/referenda/Referenda.sol
  precompiles/referenda/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, breaking

#2071 Add OpenGov precompile logs
  precompiles/conviction-voting/ConvictionVoting.sol
  precompiles/conviction-voting/src/lib.rs
  precompiles/conviction-voting/src/mock.rs
  precompiles/conviction-voting/src/tests.rs
  precompiles/preimage/Preimage.sol
  precompiles/preimage/src/lib.rs
  precompiles/preimage/src/mock.rs
  precompiles/preimage/src/tests.rs
  precompiles/referenda/Referenda.sol
  precompiles/referenda/src/lib.rs
  precompiles/referenda/src/mock.rs
  precompiles/referenda/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, not-breaking

#2099 Fix try runtime
  Cargo.lock
  node/cli/Cargo.toml
  node/cli/src/command.rs
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/governance/origins.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B0-silent, D2-notlive

#2091 Refund submission deposit
  precompiles/referenda/Referenda.sol
  precompiles/referenda/src/lib.rs
  tests/contracts/compiled/Referenda.json
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, breaking

#2098 allow "ANY proxy" to call to any EVM address
  runtime/moonbase/src/lib.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2104 Increase global smoke timeouts
  tests/.mocharc.json
  tests/smoke-tests/test-ethereum-failures.ts
Labels: B0-silent, D2-notlive

#2083 Improve Collective precompile call decoding
  precompiles/collective/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D1-audited👍, not-breaking

#2078 Dynamic Fee @ Moonriver
  node/service/src/chain_spec/moonriver.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/runtime_apis.rs
  tests/tests/test-fees/test-length-fees.ts
Labels: A0-pleasereview, B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2103 Add test to ensure moonbeam binary exists
  node/src/tests.rs
Labels: B0-silent, D2-notlive, not-breaking

#2084 Fix trackId=>Origin conversion, support submit for root track
  Cargo.lock
  precompiles/referenda/src/lib.rs
  precompiles/referenda/src/mock.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/governance/origins.rs
  runtime/moonbase/src/governance/tracks.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/governance/origins.rs
  runtime/moonriver/src/governance/tracks.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, not-breaking

#2105 Introduce Proxy Precompile to Moonriver/Moonbeam
  Cargo.lock
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2106 Adds open tech committee to moonbeam bundle definitions
  moonbeam-types-bundle/index.ts
  moonbeam-types-bundle/package-lock.json
  moonbeam-types-bundle/package.json
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#2069 Added smoke tests for dynamic fee monitoring
  tests/smoke-tests/test-dynamic-fees.ts
  tests/util/constants.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#2090 Erc20 XCM bridge
  Cargo.lock
  Cargo.toml
  pallets/erc20-xcm-bridge/Cargo.toml
  pallets/erc20-xcm-bridge/src/erc20_matcher.rs
  pallets/erc20-xcm-bridge/src/erc20_trap.rs
  pallets/erc20-xcm-bridge/src/errors.rs
  pallets/erc20-xcm-bridge/src/lib.rs
  pallets/erc20-xcm-bridge/src/xcm_exec_filter.rs
  pallets/erc20-xcm-bridge/src/xcm_holding_ext.rs
  pallets/moonbeam-xcm-benchmarks/Cargo.toml
  pallets/moonbeam-xcm-benchmarks/src/weights/mod.rs
  pallets/moonbeam-xcm-benchmarks/src/weights/moonbeam_xcm_benchmarks_fungible.rs
  precompiles/utils/Cargo.toml
  precompiles/utils/src/handle.rs
  precompiles/utils/src/lib.rs
  precompiles/utils/src/substrate.rs
  primitives/xcm/src/asset_id_conversions.rs
  runtime/common/Cargo.toml
  runtime/common/src/impl_xcm_evm_runner.rs
  runtime/common/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/src/xcm_config.rs
  tests/contracts/compiled/ERC20WithInitialSupply.json
  tests/contracts/solidity/ERC20WithInitialSupply.sol
  tests/package.json
  tests/tests/test-xcm/test-xcm-erc20-transfer.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2107 Changes referenda precompile to take proposal hash on submit (+Demo)
  precompiles/conviction-voting/ConvictionVoting.sol
  precompiles/preimage/Preimage.sol
  precompiles/referenda/Referenda.sol
  precompiles/referenda/src/lib.rs
  precompiles/referenda/src/tests.rs
  tests/README.md
  tests/contracts/compiled/ConvictionVoting.json
  tests/contracts/compiled/Preimage.json
  tests/contracts/compiled/Referenda.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemo.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemoV1.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemoV2.json
  tests/contracts/compiled/ReferendaChecker.json
  tests/contracts/compiled/StakingAttacker.json
  tests/contracts/compiled/SubstrateTools.json
  tests/contracts/solidity/ReferendaAutoUpgradeDemo.sol
  tests/contracts/solidity/ReferendaChecker.sol
  tests/contracts/solidity/SubstrateTools.sol
  tests/tests/test-precompile/test-precompile-referenda-demo.ts
  tests/tests/test-precompile/test-precompile-referenda.ts
  tests/util/block.ts
  tests/util/constants.ts
  tests/util/expect.ts
  tests/util/transactions.ts
Labels: A0-pleasereview, B0-silent, D3-trivial

#2112 fix tracing runtime build
  pallets/asset-manager/Cargo.toml
  pallets/ethereum-xcm/Cargo.toml
  pallets/moonbeam-xcm-benchmarks/Cargo.toml
  pallets/xcm-transactor/Cargo.toml
  precompiles/xcm-transactor/Cargo.toml
  precompiles/xtokens/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B0-silent, A10-evmtracing, D2-notlive

#2109 bump client version to v0.30.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D2-notlive

#2115 Add docker image for each Runtime release
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D2-notlive

#2113 Improve referenda precompile logs
  precompiles/referenda/Referenda.sol
  precompiles/referenda/src/lib.rs
  precompiles/referenda/src/mock.rs
  precompiles/referenda/src/tests.rs
  tests/contracts/compiled/Referenda.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemo.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemoV1.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemoV2.json
  tests/contracts/compiled/ReferendaChecker.json
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2092 referendumStatus, referendumInfo
  precompiles/referenda/Referenda.sol
  precompiles/referenda/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, breaking

#2117 Reduces conviction lock period to 1 day
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbase/src/governance/tracks.rs
  runtime/moonriver/src/governance/referenda.rs
  runtime/moonriver/src/governance/tracks.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2118 upgrade srtool to use rustc 1.66.1
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D2-notlive

#2119 fix {moonriver,moonbeam}-runtime build (std feature)
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B0-silent, D2-notlive

#2116 fix off by one in staking num collators logic
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2121 Reduce Submission Deposit and Timeout (Moonriver/Alphanet)
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonriver/src/governance/referenda.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, breaking

#2122 set env vars in run block
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D2-notlive

#2114 Introduce num_selected_candidates genesis config param
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonriver/tests/common/mod.rs
Labels: B0-silent, D3-trivial

#2126 move runtime job tag-docker in a separate workflow
  .github/workflows/publish-docker-runtime.yml
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D2-notlive

#2110 upgrade github actions that use deprecated node v12.x
  .github/workflows/build.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
Labels: B0-silent, D2-notlive

#2125 Bump runtime version to 2300
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, not-breaking

#2128 Fix github workflows that generate releases issues
  .github/workflows/client-release-issue.yml
  .github/workflows/publish-binary.yml
  .github/workflows/runtime-release-issue.yml
Labels: B0-silent, D2-notlive

#2130 update launch config for client v0.30
  tools/launch.ts
Labels: B0-silent, D2-notlive

#2127 Fixed TS build and added new CI
  tests/package-lock.json
  tests/package.json
  tests/util/block.ts
  tests/util/setup-zombie-tests.ts
Labels: B0-silent, D2-notlive

#2132 fix github workflow "Publish Docker runtime"
  .github/workflows/publish-docker-runtime.yml
Labels: B0-silent, D2-notlive

#2133 Workspace dependencies followup
  Cargo.lock
  Cargo.toml
  docs/workspace-dependencies.md
  precompiles/xtokens/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low, D3-trivial, not-breaking

#2134 [MOON-2215] add pallet referenda migration
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2137 fix try-runtime build after workspace deps PR
  node/cli/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low, D3-trivial, not-breaking

#2136 bump client version to v0.31.0
  Cargo.lock
  README.md
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D2-notlive

#2140 Update smoke balance test to account for optional deposit
  tests/smoke-tests/test-balances-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking
