Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-03, with the labels that each got.

#2141 Fix publish docker runtime workflow
  .github/workflows/publish-docker-runtime.yml
Labels: B0-silent, D2-notlive

#2142 Filter out XCM exts from smoke test
  tests/smoke-tests/test-dynamic-fees.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#2135 [MOON-2124] add randomness pallet as author filter source to moonbeam
  Cargo.lock
  Cargo.toml
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2144 Fix Balance Consistency Smoketest
  tests/smoke-tests/test-balances-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#2143 AuthorMapping precompile getters
  precompiles/assets-erc20/src/mock.rs
  precompiles/author-mapping/AuthorMappingInterface.sol
  precompiles/author-mapping/Cargo.toml
  precompiles/author-mapping/src/lib.rs
  precompiles/author-mapping/src/mock.rs
  precompiles/author-mapping/src/tests.rs
  precompiles/batch/src/mock.rs
  precompiles/call-permit/src/mock.rs
  precompiles/utils/src/testing/account.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, not-breaking

#2148 Allow calling proxy.proxy from smart contracts in moonbase
  precompiles/proxy/Proxy.sol
  precompiles/proxy/src/lib.rs
  precompiles/proxy/src/mock.rs
  precompiles/proxy/src/tests.rs
  runtime/moonbase/src/precompiles.rs
  tests/contracts/compiled/AuthorMapping.json
  tests/contracts/compiled/Proxy.json
  tests/contracts/compiled/ProxyLeaderDemo.json
  tests/contracts/compiled/Referenda.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemo.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemoV1.json
  tests/contracts/compiled/ReferendaAutoUpgradeDemoV2.json
  tests/contracts/compiled/ReferendaChecker.json
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2154 Modified proxy precompile comment
  precompiles/proxy/Proxy.sol
Labels: B0-silent, D2-notlive

#2123 Optimize compute_top_candidates
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2156 Adds test for minting 2^128 in local assets
  tests/tests/test-precompile/test-precompile-local-assets-erc20.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#2139 Update collator candidate self-bond in Moonriver
  node/service/src/chain_spec/moonriver.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, D10-breaksdocs, breaking

#2149 Update extensions for ESM compatibility
  typescript-api/package-lock.json
  typescript-api/package.json
  typescript-api/src/moonbase/index.ts
  typescript-api/src/moonbeam/index.ts
  typescript-api/src/moonriver/index.ts
Labels: B0-silent, D2-notlive

#2147 Improve compilation error message in precompile macro
  precompiles/utils/macro/src/precompile/parse.rs
  precompiles/utils/macro/tests/compile-fail/precompile/test-gen/generic-arg.rs
  precompiles/utils/macro/tests/compile-fail/precompile/test-gen/generic-arg.stderr
Labels: A0-pleasereview, B0-silent, C1-low, D3-trivial, not-breaking

#2162 Cleanup obsolete scripts and packages
  scripts/run-fork-chain.sh
  scripts/run-fork-test.sh
  tests/README.md
  tools/package-lock.json
  tools/package.json
Labels: B0-silent, D2-notlive

#2159 Add HRMP Cancel variant to hrmp_manage
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/tests.rs
  precompiles/relay-encoder/src/test_relay_runtime.rs
  primitives/xcm/src/transactor_traits.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/relay-encoder/src/kusama.rs
  runtime/relay-encoder/src/polkadot.rs
  runtime/relay-encoder/src/westend.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2167 Fix the NPM GA
  .github/workflows/publish-typescript-api.yml
  tests/tests/test-randomness/test-randomness-babe-request.ts
Labels: B0-silent, D2-notlive

#2172 Add CheckNonZeroSender on SignedExtra
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2173 Added asserts for revert reasons
  tests/package-lock.json
  tests/package.json
  tests/tests/test-precompile/test-precompile-proxy-non-transfer.ts
  tests/tests/test-precompile/test-precompile-proxy.ts
  tests/tests/test-precompile/test-precompile-referenda-demo.ts
  tests/tests/test-precompile/test-precompile-referenda.ts
  tests/tests/test-precompile/test-precompile-xcm-utils.ts
  tests/tests/test-randomness/test-randomness-babe-request.ts
  tests/tests/test-randomness/test-randomness-vrf-lottery.ts
  tests/tests/test-randomness/test-randomness-vrf-request.ts
  tests/util/eth-transactions.ts
Labels: B0-silent, D2-notlive

#2177 Allow proxy precompile to perform subcalls and to be callable from batch on Moonriver/Moonbeam
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/src/precompiles.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2158 [MOON-2268] update frontier version
  Cargo.lock
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2179 Modify RelayEncoder precompile to accept HRMP Cancel variant
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  precompiles/relay-encoder/RelayEncoder.sol
  precompiles/relay-encoder/src/lib.rs
  precompiles/relay-encoder/src/test_relay_runtime.rs
  primitives/xcm/src/transactor_traits.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/relay-encoder/src/kusama.rs
  runtime/relay-encoder/src/polkadot.rs
  runtime/relay-encoder/src/westend.rs
  tests/contracts/compiled/RelayEncoder.json
  tests/contracts/compiled/RelayEncoderInstance.json
  tests/contracts/solidity/RelayEncoderInstance.sol
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2169 Add conviction voting Split, SplitAbstain vote options
  precompiles/conviction-voting/ConvictionVoting.sol
  precompiles/conviction-voting/src/lib.rs
  precompiles/conviction-voting/src/tests.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, breaking

#2176 Moonwall Integration
  test/.gitignore
  test/README.md
  test/configs/alphanet.yml
  test/configs/moonbeam.yml
  test/configs/moonriver.yml
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/chopsticks/sample/test-basic-actions.ts
  test/suites/dev/sample/test_basic.ts
  test/suites/smoke/test-author-filter-consistency.ts
  test/suites/smoke/test-author-mapping-consistency.ts
  test/suites/smoke/test-balances-consistency.ts
  test/tsconfig.json
  tests/README.md
  tests/util/block.ts
Labels: B0-silent, D2-notlive

#2186 Rename raw tracing `stepLogs` tag to `structLogs`
  client/evm-tracing/src/formatters/raw.rs
  client/evm-tracing/src/listeners/raw.rs
  client/evm-tracing/src/types/single.rs
  tests/tracing-tests/test-trace.ts
Labels: A0-pleasereview, B0-silent, A10-evmtracing, D3-trivial, breaking

#2181 Added upgrade checks for smoke tests
  tests/package-lock.json
  tests/package.json
  tests/smoke-tests/test-dynamic-fees.ts
  tests/smoke-tests/test-ethereum-failures.ts
  tests/smoke-tests/test-foreign-xcm-failures.ts
  tests/smoke-tests/test-relay-indices.ts
  tests/smoke-tests/test-xcm-failures.ts
  tests/tests/test-eth-fee/test-eth-fee-history.ts
  tests/util/block.ts
  tests/util/foreign-chains.ts
  tests/util/setup-smoke-tests.ts
Labels: B0-silent, D2-notlive

#2191 fix 0.9.38 build
  pallets/xcm-transactor/src/tests.rs
  precompiles/precompile-registry/src/mock.rs
  precompiles/relay-encoder/src/lib.rs
Labels: A0-pleasereview, B0-silent, D3-trivial, not-breaking

#2171 [MOON-2201] allow only EOA in real for proxy call, add demo
  precompiles/proxy/src/lib.rs
  precompiles/proxy/src/tests.rs
  precompiles/utils/src/precompile_set.rs
  precompiles/utils/src/substrate.rs
  precompiles/utils/tests-external/lib.rs
  tests/contracts/compiled/ProxyCallStakingDemo.json
  tests/contracts/compiled/SmartContractPrecompileCallTest.json
  tests/contracts/solidity/ProxyCallStakingDemo.sol
  tests/contracts/solidity/SmartContractPrecompileCallTest.sol
  tests/tests/test-precompile/test-precompile-proxy-leader-demo.ts
  tests/tests/test-precompile/test-precompile-proxy-staking-demo.ts
  tests/tests/test-precompile/test-precompile-smart-contract-call.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking
