Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-08, with the labels that each got.

#2418 Make PrecompileRegistry follow the header convention
  precompiles/gmp/Gmp.sol
  precompiles/precompile-registry/PrecompileRegistry.sol
  tests/contracts/compiled/GmpPrecompile.json
  tests/contracts/compiled/precompiles/gmp/Gmp.json
  tests/contracts/compiled/precompiles/precompile-registry/PrecompileRegistry.json
  tests/util/constants.ts
Labels: A0-pleasereview, B0-silent, C1-low, D3-trivial

#2384 migrate to moonkit
  Cargo.lock
  Cargo.toml
  pallets/author-mapping/Cargo.toml
  pallets/author-mapping/migrations.md
  pallets/author-mapping/src/benchmarks.rs
  pallets/author-mapping/src/lib.rs
  pallets/author-mapping/src/migrations.rs
  pallets/author-mapping/src/mock.rs
  pallets/author-mapping/src/tests.rs
  pallets/author-mapping/src/weights.rs
  pallets/maintenance-mode/Cargo.toml
  pallets/maintenance-mode/src/lib.rs
  pallets/maintenance-mode/src/mock.rs
  pallets/maintenance-mode/src/tests.rs
  pallets/maintenance-mode/src/types.rs
  pallets/migrations/Cargo.toml
  pallets/migrations/src/benchmarks.rs
  pallets/migrations/src/democracy_preimages.rs
  pallets/migrations/src/lib.rs
  pallets/migrations/src/mock.rs
  pallets/migrations/src/tests.rs
  pallets/migrations/src/weights.rs
  pallets/randomness/Cargo.toml
  pallets/randomness/README.md
  pallets/randomness/src/benchmarks.rs
  pallets/randomness/src/lib.rs
  pallets/randomness/src/tests.rs
  pallets/randomness/src/types.rs
  pallets/randomness/src/vrf.rs
  pallets/randomness/src/weights.rs
  precompiles/utils/Cargo.toml
  precompiles/utils/src/testing/account.rs
  primitives/session-keys/Cargo.toml
  primitives/session-keys/src/digest.rs
  primitives/session-keys/src/inherent.rs
  primitives/session-keys/src/lib.rs
  primitives/session-keys/src/vrf.rs
  primitives/xcm/src/lib.rs
  primitives/xcm/src/xcm_execution_traits.rs
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2401 Fix conviction MaxVotes
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbeam/src/governance/referenda.rs
  runtime/moonriver/src/governance/referenda.rs
  test/helpers/expect.ts
  test/suites/dev/test-conviction-voting/test-conviction-delegation.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2410 Port ERC20-XCM tests. Add excess gas tests
  test/contracts/src/ERC20ExcessGas.sol
  test/contracts/src/ERC20WithInitialSupply.sol
  test/helpers/eth-transactions.ts
  test/helpers/xcm.ts
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/test-xcm/test-xcm-erc20-excess-gas.ts
  test/suites/dev/test-xcm/test-xcm-erc20-fees-and-trap.ts
  test/suites/dev/test-xcm/test-xcm-erc20-transfer-two-ERC20.ts
  test/suites/dev/test-xcm/test-xcm-erc20-transfer.ts
  test/suites/dev/test-xcm/test-xcm-erc20-v3.ts
Labels: B0-silent, D2-notlive, not-breaking

#2426 Run toml-sort and update repo reference
  precompiles/utils/Cargo.toml
  runtime/common/Cargo.toml
  scripts/toml-sort.sh
Labels: A0-pleasereview, B0-silent, not-breaking

#2349 [MOON-2434] remove deprecated leave delegator functionality
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  precompiles/parachain-staking/StakingInterface.sol
  precompiles/parachain-staking/src/lib.rs
  precompiles/parachain-staking/src/tests.rs
  tests/tests/test-staking/test-delegation-scheduled-requests.ts
  tests/tests/test-staking/test-delegator-leave.ts
  tests/tests/test-staking/test-rewards-auto-compound.ts
  tests/tests/test-staking/test-rewards.ts
  tests/tests/test-staking/test-weights.ts
  tests/util/setup-dev-tests.ts
  tests/util/substrate-rpc.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2419 Write TS tests for Emitted OpenGov events
  test/helpers/precompile-contract-calls.ts
  test/helpers/voting.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting2.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting3.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting4.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting5.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting6.ts
  test/suites/dev/test-precompile/test-precompile-preimage.ts
  test/suites/dev/test-precompile/test-precompile-referenda.ts
Labels: A0-pleasereview, B0-silent, C1-low, D3-trivial

#2434 fix smoke test
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/smoke/test-foreign-asset-consistency.ts
  test/suites/smoke/test-relay-xcm-fees.ts
Labels: B0-silent, D2-notlive

#2436 Smoke fix for testnets
  test/helpers/block.ts
  test/helpers/storageQueries.ts
  test/suites/smoke/test-balances-consistency.ts
Labels: B0-silent, D2-notlive

#2438 Fixes slow import
  Cargo.lock
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2424 Grw/moon 2490 max assets weighable
  test/suites/dev/test-xcm/test-xcm-erc20-v3-filter.ts
Labels: B0-silent, D2-notlive, not-breaking

#2429 fix tracing bug: ERC20-XCM transactions were not traced
  runtime/common/src/impl_xcm_evm_runner.rs
  tests/package.json
  tests/tracing-tests/test-trace-erc20-xcm.ts
Labels: B0-silent, A10-evmtracing, D2-notlive

#2445 Update setup-buildx-action to better support env
  .github/workflows/prepare-binary.yml
Labels: B0-silent, D2-notlive

#2444 Support latest Moonbeam in balance Smoketest
  test/suites/smoke/test-balances-consistency.ts
Labels: B0-silent, D2-notlive

#2446 Fix secret name in prepare binary
  .github/workflows/prepare-binary.yml
Labels: B0-silent, D2-notlive, not-breaking

#2433 refactor evm recursion lock
  Cargo.lock
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2440 Fix eth call diff
  runtime/common/src/apis.rs
  tests/tests/test-gas/test-gas-foreign-asset.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2450 Reduce Smoke Noise
  test/helpers/foreign-chains.ts
  test/package.json
  test/pnpm-lock.yaml
  test/suites/smoke/test-author-mapping-consistency.ts
  test/suites/smoke/test-foreign-xcm-failures.ts
  test/suites/smoke/test-randomness-consistency.ts
Labels: B0-silent, D2-notlive

#2451 Mute Nodle monitoring
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#2302 Draft MBIPs
  MBIPS/MBIP-1.md
  MBIPS/MBIP-2.md
  MBIPS/MBIP-3.md
  MBIPS/MBIP-4.md
  MBIPS/MBIP-5.md
  MBIPS/MBIP-6.md
  MBIPS/template.md
Labels: B0-silent, D3-trivial, not-breaking

#2338 XCM Transactor precompile V3 [Moonbase only]
  pallets/xcm-transactor/src/benchmarks.rs
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  pallets/xcm-transactor/src/tests.rs
  precompiles/utils/src/solidity/codec/xcm.rs
  precompiles/xcm-transactor/Cargo.toml
  precompiles/xcm-transactor/src/functions.rs
  precompiles/xcm-transactor/src/lib.rs
  precompiles/xcm-transactor/src/mock.rs
  precompiles/xcm-transactor/src/tests.rs
  precompiles/xcm-transactor/src/v3/XcmTransactorV3.sol
  precompiles/xcm-transactor/src/v3/mod.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_tests.rs
  tests/archived_specs/test-maintenance/test-maintenance-filter.ts
  tests/contracts/compiled/precompiles/xcm-transactor/src/v3/XcmTransactorV3.json
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2455 Fix maintenance filter test
  test/suites/dev/test-maintenance/test-maintenance-filter.ts
Labels: B0-silent, D2-notlive, not-breaking

#2422 Optional ERC20-XCM gas limit override and tests
  pallets/erc20-xcm-bridge/src/lib.rs
  pallets/moonbeam-xcm-benchmarks/src/weights/moonbeam_xcm_benchmarks_fungible.rs
  test/suites/dev/test-xcm-v3/test-xcm-erc20-excess-gas.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2454 Fixes test using random address in calldata
  test/suites/dev/test-precompile/test-precompile-proxy.ts
Labels: B0-silent, D2-notlive, not-breaking

#2456 Fixes CI having trouble with pnpm
  .github/workflow-templates/dev-tests/action.yml
Labels: B0-silent, D2-notlive, not-breaking

#2428 Add simple fee mechanism to GMP precompile
  precompiles/gmp/src/lib.rs
  precompiles/gmp/src/types.rs
  test/suites/dev/test-precompile/test-precompile-wormhole.ts
  tests/archived_specs/test-precompile/test-precompile-wormhole.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2457 Adds check CI for the licenses
  .github/workflows/check-licenses.yml
  scripts/verify-licenses.sh
Labels: B0-silent, D2-notlive, not-breaking

#2406 [MOON-2459] identity precompile
  Cargo.lock
  Cargo.toml
  precompiles/identity/Cargo.toml
  precompiles/identity/Identity.sol
  precompiles/identity/src/lib.rs
  precompiles/identity/src/mock.rs
  precompiles/identity/src/tests.rs
  precompiles/utils/src/solidity/codec/bytes.rs
  precompiles/utils/src/solidity/codec/native.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  test/package-lock.json
  test/suites/dev/test-precompile/test-precompile-identity.ts
  test/suites/dev/test-precompile/test-precompile-identity10.ts
  test/suites/dev/test-precompile/test-precompile-identity11.ts
  test/suites/dev/test-precompile/test-precompile-identity12.ts
  test/suites/dev/test-precompile/test-precompile-identity13.ts
  test/suites/dev/test-precompile/test-precompile-identity14.ts
  test/suites/dev/test-precompile/test-precompile-identity2.ts
  test/suites/dev/test-precompile/test-precompile-identity3.ts
  test/suites/dev/test-precompile/test-precompile-identity4.ts
  test/suites/dev/test-precompile/test-precompile-identity5.ts
  test/suites/dev/test-precompile/test-precompile-identity6.ts
  test/suites/dev/test-precompile/test-precompile-identity7.ts
  test/suites/dev/test-precompile/test-precompile-identity8.ts
  test/suites/dev/test-precompile/test-precompile-identity9.ts
  tests/contracts/compiled/precompiles/identity/Identity.json
  tests/util/constants.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2423 add conviction voting batch tests
  test/helpers/accounts.ts
  test/helpers/block.ts
  test/helpers/common.ts
  test/helpers/weights.ts
  test/suites/dev/test-conviction-voting/test-conviction-batch-delegate-undelegate.ts
  test/suites/dev/test-conviction-voting/test-conviction-delegate-weight-fit.ts
  test/suites/dev/test-conviction-voting/test-conviction-undelegate-weight-fit.ts
  test/suites/dev/test-staking/test-weights.ts
  test/suites/dev/test-staking/test-weights2.ts
  test/suites/dev/test-staking/test-weights3.ts
  test/suites/dev/test-staking/test-weights4.ts
  test/suites/dev/test-staking/test-weights5.ts
Labels: B0-silent, D2-notlive

#2463 Fix tracing tests (MBIP-5 break gas costs)
  tests/tracing-tests/test-trace-filter.ts
Labels: B0-silent, A10-evmtracing, D2-notlive, not-breaking

#2465 evm proxy: allow identity precompile through NonTransfer proxy
  runtime/moonbase/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2466 Upgrade srtool to 1.70.0
  .github/workflows/publish-runtime.yml
Labels: B0-silent, D2-notlive, not-breaking
