Repository moonbeam-foundation/moonbeam, pull requests merged in 2023-07, with the labels that each got.

#2366 Forces binary production from Ubuntu:20.04
  .github/workflows/publish-binary.yml
  docker/moonbeam-production.Dockerfile
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#2374 remove erroneous expression brackets in if-condition
  .github/workflows/build.yml
Labels: B0-silent, D3-trivial

#2373 [MOON-2356] Disallow clippy todo in master and perm-* branches
  .github/workflows/build.yml
  node/service/src/chain_spec/fake_spec.rs
Labels: B0-silent, D2-notlive

#2382 pin prettier version
  .github/workflows/build.yml
Labels: B0-silent, ci, D2-notlive

#2362 [MOON-1629] test runtime-benchmarks feature in CI
  .github/workflows/build.yml
  Cargo.toml
  node/service/Cargo.toml
  pallets/moonbeam-xcm-benchmarks/src/generic/mock.rs
  pallets/moonbeam-xcm-benchmarks/src/mock.rs
  pallets/parachain-staking/src/benchmarks.rs
  pallets/randomness/Cargo.toml
  pallets/randomness/src/mock.rs
  precompiles/conviction-voting/Cargo.toml
  precompiles/conviction-voting/src/mock.rs
  precompiles/gmp/Cargo.toml
  precompiles/gmp/src/mock.rs
  precompiles/referenda/Cargo.toml
  precompiles/xcm-transactor/Cargo.toml
  precompiles/xcm-transactor/src/mock.rs
  precompiles/xcm-utils/Cargo.toml
  precompiles/xcm-utils/src/mock.rs
  precompiles/xtokens/Cargo.toml
  precompiles/xtokens/src/mock.rs
  primitives/account/Cargo.toml
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbase/tests/xcm_mock/statemint_like.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/relay_chain.rs
  runtime/moonbeam/tests/xcm_mock/statemint_like.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/relay_chain.rs
  runtime/moonriver/tests/xcm_mock/statemine_like.rs
Labels: A0-pleasereview, B0-silent, ci, D2-notlive

#2385 Add MultiSig deposits to smoketests
  test/suites/smoke/test-author-filter-consistency.ts
  test/suites/smoke/test-author-mapping-consistency.ts
  test/suites/smoke/test-balances-consistency.ts
  test/suites/smoke/test-block-finalized.ts
  test/suites/smoke/test-block-weights.ts
  test/suites/smoke/test-dynamic-fees.ts
  test/suites/smoke/test-ethereum-contract-code.ts
  test/suites/smoke/test-ethereum-current-consistency.ts
  test/suites/smoke/test-ethereum-db-mapping.ts
  test/suites/smoke/test-ethereum-failures.ts
  test/suites/smoke/test-foreign-asset-consistency.ts
  test/suites/smoke/test-foreign-xcm-failures.ts
  test/suites/smoke/test-historic-compatibility.ts
  test/suites/smoke/test-local-asset-consistency.ts
  test/suites/smoke/test-orbiter-consistency.ts
  test/suites/smoke/test-polkadot-decoding.ts
  test/suites/smoke/test-proxy-consistency.ts
  test/suites/smoke/test-randomness-consistency.ts
  test/suites/smoke/test-relay-indices.ts
  test/suites/smoke/test-relay-xcm-fees.ts
  test/suites/smoke/test-staking-consistency.ts
  test/suites/smoke/test-staking-rewards.ts
  test/suites/smoke/test-staking-round-cleanup.ts
  test/suites/smoke/test-treasury-consistency.ts
  test/suites/smoke/test-xcm-failures.ts
  tests/smoke-tests/test-author-filter-consistency.ts
  tests/smoke-tests/test-author-mapping-consistency.ts
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-eth-parent-hash-bad-block-fix.ts
  tests/smoke-tests/test-foreign-asset-consistency.ts
  tests/smoke-tests/test-local-asset-consistency.ts
  tests/smoke-tests/test-orbiter-consistency.ts
  tests/smoke-tests/test-polkadot-decoding.ts
  tests/smoke-tests/test-proxy-consistency.ts
  tests/smoke-tests/test-randomness-consistency.ts
  tests/smoke-tests/test-relay-xcm-fees.ts
  tests/smoke-tests/test-staking-consistency.ts
  tests/smoke-tests/test-treasury-consistency.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#2381 [MOON-2467] remove MinDelegatorStk in favor of MinDelegation pallet-staking const
  pallets/parachain-staking/src/auto_compound.rs
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  tests/para-tests/moonbase/1200/skip-test-migration-split-staking.ts
  tests/para-tests/moonbase/1300/skip-migration-fix-total-staking.ts
  tests/tests/test-staking/test-delegate-with-auto-compound.ts
  tests/tests/test-staking/test-delegator-join.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2378 [MOON-2433] enforce MaxCandidates limit for staking storage items
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/set.rs
  pallets/parachain-staking/src/tests.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2387 fix benchmark tests
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
Labels: B0-silent, D2-notlive

#2389 modularize coverage
  .github/workflows/coverage.yml
Labels: B0-silent, D2-notlive, not-breaking

#2376 Update RelayEncoder to be 9430 compatible
  precompiles/relay-encoder/RelayEncoder.sol
  precompiles/relay-encoder/src/lib.rs
  precompiles/relay-encoder/src/test_relay_runtime.rs
  precompiles/relay-encoder/src/tests.rs
  runtime/relay-encoder/src/kusama.rs
  runtime/relay-encoder/src/polkadot.rs
  runtime/relay-encoder/src/westend.rs
  test/contracts/src/RelayEncoderInstance.sol
  test/suites/smoke/test-relay-indices.ts
  tests/contracts/compiled/RelayEncoderInstance.json
  tests/contracts/compiled/precompiles/relay-encoder/RelayEncoder.json
  tests/contracts/solidity/RelayEncoderInstance.sol
  tests/package.json
  tests/smoke-tests/test-relay-indices.ts
  tests/tests/test-precompile/test-precompile-relay-encoder.ts
  tests/util/dev-node.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, breaking

#2397 Adds a readme message to warn about monbeam repo moving
  README.md
Labels: B0-silent, D2-notlive, not-breaking

#2399 Make smoke test more resilient and faster
  test/helpers/storageQueries.ts
  test/moonwall.config.json
  test/suites/smoke/test-balances-consistency.ts
  test/suites/smoke/test-ethereum-contract-code.ts
  test/suites/smoke/test-relay-indices.ts
  tests/smoke-tests/test-balances-consistency.ts
  tests/smoke-tests/test-ethereum-contract-code.ts
  tests/util/common.ts
  tests/util/storage.ts
  typescript-api/package-lock.json
Labels: B0-silent, D2-notlive, not-breaking

#2403 More reliable docker image check
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive, not-breaking

#2372 Adds documentation about `debug` rpc
  client/rpc/debug/README.md
Labels: B0-silent, D2-notlive, not-breaking

#2404 Fix prepare polkadot CI
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive, not-breaking

#2405 Update references from purestake to moonbeam-foundation
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-docker-runtime.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/upgrade-typescript-api.yml
  CONTRIBUTIONS.md
  README.md
  RELEASE.md
  client/rpc/debug/README.md
  docker/moonbeam-fork-tests.Dockerfile
  docker/polkadot-para-tests.Dockerfile
  docker/polkadot-relay.Dockerfile
  moonbeam-types-bundle/package.json
  pallets/author-mapping/migrations.md
  pallets/parachain-staking/README.md
  pallets/parachain-staking/migrations.md
  scripts/build-alphanet-relay-image.sh
  scripts/build-last-tracing-runtime.sh
  scripts/bump-node-version.sh
  scripts/create-substrate-fork.sh
  scripts/embed-specs.sh
  scripts/generate-relay-specs.sh
  scripts/get-alphanet-relay-image.sh
  scripts/run-rococo-local.sh
  scripts/toml-sort.sh
  tests/README.md
  tests/run-para-tests.sh
  tests/util/binaries.ts
  tools/get-binary.ts
  tools/github/print-runtime-release-issue.ts
  tools/github/print-version-bump-info.ts
  typescript-api/package.json
Labels: B0-silent, D2-notlive, not-breaking

#2408 Increase erc20 xcm gas cost
  pallets/erc20-xcm-bridge/src/erc20_matcher.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/src/xcm_config.rs
  tests/tests/test-precompile/test-precompile-wormhole.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2411 Update substrate dependencies so as to include code substitute bug fix (#2514)
  Cargo.lock
Labels: A0-pleasereview, B5-clientnoteworthy, C3-medium, D3-trivial, not-breaking

#2413 Moves readme badge from release to build action
  README.md
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#2398 run docker-moonbeam on push events
  .github/workflows/build.yml
Labels: B0-silent, ci, D2-notlive

#2412 Add prometheus metrics for moobeam tracing cache (#1561)
  Cargo.lock
  client/rpc/trace/Cargo.toml
  client/rpc/trace/src/lib.rs
  node/service/src/lib.rs
  node/service/src/rpc/tracing.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking
