Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-11, with the labels that each got.

#3030 Fix `S22C500` smoke test
  test/moonwall.config.json
  test/suites/smoke/test-staking-rewards.ts
Labels: B0-silent, D2-notlive, not-breaking

#3032 CI/fix: :package: publish TS-API with pnpm
  .github/workflows/publish-typescript-api.yml
  pnpm-lock.yaml
  typescript-api/package.json
Labels: B0-silent, D2-notlive

#3035 feat(lazy-loading): Support querying old blocks by number
  node/service/src/lazy_loading/backend.rs
  node/service/src/lazy_loading/helpers.rs
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#3041 Fixes wrong runtime import with native flags
  node/cli/src/command.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#3042 Adds more documentation for contract proxying tests
  test/contracts/src/ProxyForContractsDemo.sol
  test/suites/dev/moonbase/test-proxy/test-proxy-for-contracts.ts
Labels: B0-silent, D2-notlive, not-breaking

#3037 Allow dist folder of api-augment to be included in the npm package
  typescript-api/.npmignore
Labels: B0-silent, D2-notlive, not-breaking

#3044 fix(smoke): use valid moonriver transaction for runtime 1605
  test/helpers/moonriver-tracing-samples.json
Labels: B0-silent, I4-tests 🎯, D2-notlive, not-breaking

#3045 chore: :package: Update Package Versions - November
  pnpm-lock.yaml
  test/package.json
Labels: B0-silent, D2-notlive

#3043 fix: FeesTreasuryProportion is only applied to substrate based tx only
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/suites/dev/moonbase/test-parameters/test-parameters-randomness.ts
  test/suites/dev/moonbase/test-parameters/test-parameters-runtime-FeesTreasuryProportion.ts
  test/suites/dev/moonbase/test-parameters/test-parameters.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2995 add bootnode to moonbeam
  specs/moonbeam/parachain-embedded-specs.json
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D2-notlive, not-breaking

#3046 chore(ci): fetch correct runtime release commit
  .github/workflows/build.yml
  .github/workflows/coverage.yml
Labels: B0-silent, I4-tests 🎯, D2-notlive, not-breaking

#3039 Remove suicided contracts lazy migration
  pallets/moonbeam-lazy-migrations/src/benchmarks.rs
  pallets/moonbeam-lazy-migrations/src/lib.rs
  pallets/moonbeam-lazy-migrations/src/mock.rs
  pallets/moonbeam-lazy-migrations/src/tests.rs
  pallets/moonbeam-lazy-migrations/src/weights.rs
  runtime/common/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/suites/dev/moonbase/test-moonbeam-lazy-migrations/test-clear-suicided-contracts.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, not-breaking

#3050 chore: removes Onfinality offline bootnodes
  specs/alphanet/parachain-embedded-specs-v8.json
  specs/moonbeam/parachain-embedded-specs.json
  specs/moonriver/parachain-embedded-specs.json
Labels: B0-silent, D2-notlive, not-breaking

#3048 Lazy loading improvements
  node/service/src/lazy_loading/call_executor.rs
  node/service/src/lazy_loading/client.rs
  node/service/src/lazy_loading/mod.rs
  node/service/src/lazy_loading/wasm_override.rs
  node/service/src/lazy_loading/wasm_substitutes.rs
Labels: B0-silent, D2-notlive, not-breaking, lazy-loading

#3052 update polkadotjs for typescript-api
  pnpm-lock.yaml
  typescript-api/package.json
Labels: B0-silent, D2-notlive

#3053 Bump api-augment version for publish
  typescript-api/package.json
Labels: B0-silent, D2-notlive

#3051 Enable native foreign assets on moonriver and moonbeam
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/src/xcm_config.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#3006 use state_version 1 when running benchmarks
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, breaking

#3049 feat: don't override fork strategy in import_queue
  Cargo.lock
  Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/lazy_loading/mod.rs
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D9-needsaudit👮, D2-notlive, breaking

#3047 Test XCM transfer and pay fees with foreign asset
  test/helpers/assets.ts
  test/helpers/xcm.ts
  test/suites/dev/moonbase/test-assets/test-foreign-assets-balances.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-evm-fee-with-origin-token.ts
Labels: B0-silent, D2-notlive, not-breaking

#3054 Fix panic when fetching block header in backend.state_at
  node/service/src/lazy_loading/backend.rs
Labels: B5-clientnoteworthy, D2-notlive, not-breaking, lazy-loading

#3056 override default host-config when using the dev node
  node/service/src/lib.rs
Labels: B0-silent, B5-clientnoteworthy, D2-notlive, not-breaking

#3036 [frontier] Add support for PoV gas refunding
  Cargo.lock
  client/rpc/debug/Cargo.toml
  client/rpc/debug/src/lib.rs
  test/moonwall.config.json
  test/suites/dev/moonbase/test-gas/test-gas-estimation-contracts.ts
  test/suites/dev/moonbase/test-gas/test-gas-estimation-multiply.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-assets-erc20d.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-proxy.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery4.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery5.ts
  test/suites/dev/moonbase/test-storage-growth/test-precompile-storage-growth.ts
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#3059 chore: :package: Update moonwall
  .github/workflow-templates/dev-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
  pnpm-lock.yaml
  test/helpers/common.ts
  test/moonwall.config.json
  test/package.json
  test/suites/lazy-loading/test-runtime-upgrade.ts
  test/suites/tracing-tests/test-trace-filter.ts
Labels: B0-silent, D2-notlive

#3061 test(smoke): Mute channel offline report InvArch
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#3062 Fix CI licenses check
  .github/workflows/check-licenses.yml
Labels: B0-silent, ci, D3-trivial

#3058 Divides min gas price by 4
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  test/helpers/constants.ts
  test/suites/dev/common/test-block/test-block-1.ts
  test/suites/dev/common/test-block/test-block-gas.ts
  test/suites/dev/common/test-block/test-block-genesis.ts
  test/suites/dev/moonbase/test-balance/test-balance-existential.ts
  test/suites/dev/moonbase/test-balance/test-balance-transfer.ts
  test/suites/dev/moonbase/test-eth-pool/test-eth-pool-error.ts
  test/suites/dev/moonbase/test-eth-pool/test-eth-pool-resubmit-txn.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-genesis.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-max.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-min.ts
  test/suites/dev/moonbase/test-fees/test-length-fees2.ts
  test/suites/dev/moonbase/test-parameters/test-parameters-runtime-FeesTreasuryProportion.ts
  test/suites/dev/moonbase/test-subscription/test-subscription.ts
  test/suites/dev/moonbase/test-txpool/test-txpool-pending2.ts
  test/suites/smoke/test-dynamic-fees.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮, D10-breaksdocs, breaking

#2984 [CI] - workflow maintenance
  .github/CODEOWNERS
  .github/workflow-templates/dev-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/cancel.yml
  .github/workflows/check-benchmarks.yml
  .github/workflows/check-licenses.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/enforce-pr-labels.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker-runtime.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/subxt-diff.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
  docker/moonbase-parachain.Dockerfile
  docker/moonbeam-production.Dockerfile
  docker/moonbeam.Dockerfile
  docker/polkadot-relay.Dockerfile
  pallets/moonbeam-foreign-assets/build.rs
  scripts/build-runtime-srtool.sh
  test/.nvmrc
Labels: A8-mergeoncegreen, B0-silent, D9-needsaudit👮, ci, D2-notlive

#3063 Adds new lazy loading parameters and improves documentation
  Cargo.lock
  node/cli-opt/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/lazy_loading/backend.rs
  test/moonwall.config.json
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D2-notlive, not-breaking, lazy-loading

#3060 Fix result of debug_traceBlockByNumber
  client/evm-tracing/src/formatters/call_tracer.rs
  client/evm-tracing/src/types/block.rs
  client/rpc-core/debug/src/lib.rs
  client/rpc/debug/src/lib.rs
  test/suites/tracing-tests/test-trace-5.ts
  test/suites/tracing-tests/test-trace-ethereum-xcm-2.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D2-notlive, breaking

#3064 ci: :green_heart: Fix Docs Perms
  .github/workflows/docs.yml
Labels: A8-mergeoncegreen, B0-silent, D2-notlive
