Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-07, with the labels that each got.

#2853 fix: auto-compound fail when free balance is too low
  .github/workflows/build.yml
  pallets/parachain-staking/src/auto_compound.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  test/suites/dev/moonbase/test-staking/test-delegate-with-auto-compound7.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2860 update moonwall to v5.3.0
  test/package.json
  test/pnpm-lock.yaml
Labels: B0-silent, D2-notlive

#2862 Mute Composable Finance monitoring
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#2864 test(smoke): fix S22C500 smoke test for moonriver and moonsama
  test/suites/smoke/test-staking-rewards.ts
Labels: B0-silent, D3-trivial

#2858 Expose moon_getLatestSyncedBlock RPC endpoint
  client/rpc/finality/src/lib.rs
  moonbeam-types-bundle/index.ts
  test/suites/dev/moonbase/test-moon/test-moon-rpc.ts
  typescript-api/src/moonbase/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbase/interfaces/moon/definitions.ts
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#2857 Add XcmPayment runtime API
  Cargo.lock
  Cargo.toml
  node/service/Cargo.toml
  node/service/src/client.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api-transact-foreign.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api-transact-native.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2861 ci: :construction_worker: Test sharding
  .github/workflow-templates/dev-tests/action.yml
  .github/workflows/build.yml
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-xcm.ts
  test/suites/dev/moonbase/test-txpool/test-txpool-limits.ts
Labels: B0-silent, D2-notlive

#2859 feat(precompile): Add secp256r1 precompile
  Cargo.lock
  Cargo.toml
  benchmarking/frame-weight-template.hbs
  pallets/precompile-benchmarks/Cargo.toml
  pallets/precompile-benchmarks/src/benchmarks.rs
  pallets/precompile-benchmarks/src/lib.rs
  pallets/precompile-benchmarks/src/mock.rs
  pallets/precompile-benchmarks/src/weights.rs
  precompiles/p256verify/Cargo.toml
  precompiles/p256verify/src/lib.rs
  precompiles/relay-data-verifier/src/mock.rs
  runtime/common/src/weights/pallet_precompile_benchmarks.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  test/contracts/src/P256Verify.sol
  test/suites/dev/moonbase/test-precompile/test-precompile-p256verify.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2865 Allows dev-test to run for Moonriver and Moonbeam
  .github/workflows/build.yml
  test/helpers/constants.ts
  test/moonwall.config.json
  test/suites/dev/common/test-block/test-block-1.ts
  test/suites/dev/common/test-block/test-block-2.ts
  test/suites/dev/common/test-block/test-block-gas.ts
  test/suites/dev/common/test-block/test-block-genesis.ts
  test/suites/dev/common/test-block/test-block-mocked-relay.ts
  test/suites/dev/moonbase/test-fees/test-length-fees2.ts
Labels: B0-silent, D2-notlive

#2866 [Moonbeam] Increase block gas limit from 15 mlns to 30 mlns
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  test/helpers/constants.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2867 [Moonriver] Increase block gas limit from 30 mlns to 60 mlns
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  test/helpers/constants.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2844 Allow bridged assets from Asset Hub
  primitives/xcm/src/origin_conversion.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/src/xcm_config.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2872 Fix referenda reserved deposits
  runtime/moonbeam/src/migrations.rs
  runtime/moonriver/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2879 add pallet_moonbeam_foreign_assets to moonbase benchmarks list
  pallets/moonbeam-foreign-assets/src/benchmarks.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
Labels: B0-silent, D2-notlive

#2874 New substrate event `ExecutedFromXcm` to link xcm message hash with ethereum tx hash
  Cargo.lock
  pallets/ethereum-xcm/Cargo.toml
  pallets/ethereum-xcm/src/lib.rs
  pallets/ethereum-xcm/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2881 Update runtime spec version to 3200
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#2884 Remove deployment to Purestake docker-hub
  .github/workflows/build.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-docker-runtime.yml
  .github/workflows/publish-docker.yml
Labels: B0-silent, D2-notlive

#2875 Update the client docker image to moonbeamfoundation/moonbeam:v0.39.0
  README.md
Labels: B0-silent, D2-notlive

#2876 Update client version to 0.40.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D3-trivial

#2886 CI: Add uncompressed runtimes to the artifact during Build step
  .github/workflow-templates/cargo-build/action.yml
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive

#2885 Remove past migrations
  pallets/parachain-staking/src/migrations.rs
  runtime/moonbeam/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2890 Fix smoke tests S16C100 & S25C1200
  test/helpers/foreign-chains.ts
  test/suites/smoke/test-polkadot-decoding.ts
Labels: B0-silent, D2-notlive
