Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-12, with the labels that each got.

#3068 [Moonriver] [Moonbeam] Add missing `EvmForeignAssets` transactor
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/src/xcm_config.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#3067 SELFDESTRUCT must reset contract account
  Cargo.lock
  test/contracts/src/SelfDestruct.sol
  test/suites/dev/moonbase/test-contract/test-self-destruct.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#3020 Foreign Assets Migration
  Cargo.lock
  pallets/moonbeam-foreign-assets/src/evm.rs
  pallets/moonbeam-foreign-assets/src/lib.rs
  pallets/moonbeam-lazy-migrations/Cargo.toml
  pallets/moonbeam-lazy-migrations/src/benchmarks.rs
  pallets/moonbeam-lazy-migrations/src/foreign_asset.rs
  pallets/moonbeam-lazy-migrations/src/lib.rs
  pallets/moonbeam-lazy-migrations/src/mock.rs
  pallets/moonbeam-lazy-migrations/src/tests.rs
  pallets/moonbeam-lazy-migrations/src/weights.rs
  precompiles/assets-erc20/Cargo.toml
  precompiles/assets-erc20/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/weights/pallet_moonbeam_lazy_migrations.rs
  test/suites/dev/moonbase/test-moonbeam-lazy-migrations/test-foreign-assets-migration.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#3072 Remove old migrations
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3074 Adds a GHA check for breaking change description
  .github/workflows/enforce-pr-labels.yml
Labels: B0-silent, D3-trivial, not-breaking

#3073 Weights for pallet-moonbeam-lazy-migration
  runtime/moonbase/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/moonbeam/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/moonriver/src/weights/pallet_moonbeam_lazy_migrations.rs
Labels: B0-silent, D3-trivial, not-breaking

#3070 test(smoke, moonriver): no longer monitor InvArch, Litmus HMRP channels
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#3076 Specify subxt version in subxt-diff gh action
  .github/workflows/subxt-diff.yml
Labels: B0-silent, D3-trivial

#3084 Use ParachainBlockImport::new_with_delayed_best_block when experimental_block_import_strategy is disabled
  node/service/src/lib.rs
  test/configs/localZombie.json
  test/configs/zombieAlphanet.json
  test/configs/zombieAlphanetRpc.json
  test/configs/zombieMoonbeam.json
  test/configs/zombieMoonbeamRpc.json
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#3085 Updates Moonkit to fix experimental import
  Cargo.lock
  node/service/src/lazy_loading/mod.rs
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#3087 Update the client docker image to moonbeamfoundation/moonbeam:v0.42.1
  README.md
Labels: B0-silent, D3-trivial

#3081 runtime 3500 bump
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#3088 Backport changes from v0.42.1 tag
  Cargo.lock
  docker/moonbeam-production.Dockerfile
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D3-trivial

#3083 Update client version to 0.43.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D3-trivial

#3092 fix smoke test (S06C400)
  test/helpers/constants.ts
  test/suites/smoke/test-dynamic-fees.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3093 Smoke tests: fix dynamic fee checks
  test/helpers/constants.ts
  test/suites/smoke/test-dynamic-fees.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3098 test(smoke): use parachain connection when fetching the runtime name
  test/helpers/constants.ts
  test/suites/lazy-loading/test-runtime-upgrade.ts
  test/suites/smoke/test-dynamic-fees.ts
Labels: B0-silent, D2-notlive

#3091 refactor: :sparkles: Create TS monorepo structure
  .github/workflow-templates/dev-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/upgrade-typescript-api.yml
  .gitignore
  moonbeam-types-bundle/.gitignore
  moonbeam-types-bundle/package.json
  moonbeam-types-bundle/tsconfig.json
  package.json
  pnpm-lock.yaml
  test/package.json
  tools/package-lock.json
  tools/package.json
  typescript-api/.gitignore
  typescript-api/package.json
  typescript-api/scripts/scrapeMetadata.ts
  typescript-api/src/moonbase/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbase/interfaces/definitions.ts
  typescript-api/src/moonbase/interfaces/moon/definitions.ts
  typescript-api/src/moonbase/tsconfig.json
  typescript-api/src/moonbeam/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbeam/interfaces/definitions.ts
  typescript-api/src/moonbeam/interfaces/empty/index.ts
  typescript-api/src/moonbeam/interfaces/empty/types.ts
  typescript-api/src/moonbeam/interfaces/moon/definitions.ts
  typescript-api/src/moonbeam/tsconfig.json
  typescript-api/src/moonriver/interfaces/augment-api-rpc.ts
  typescript-api/src/moonriver/interfaces/definitions.ts
  typescript-api/src/moonriver/interfaces/empty/index.ts
  typescript-api/src/moonriver/interfaces/empty/types.ts
  typescript-api/src/moonriver/interfaces/moon/definitions.ts
  typescript-api/src/moonriver/tsconfig.json
  typescript-api/tsconfig.json
  typescript-api/tsup.config.ts
Labels: B0-silent, D2-notlive

#3089 test(smoke): Correctly check egress hmrp channels
  test/suites/smoke/test-xcm-failures.ts
Labels: B0-silent, D2-notlive

#3097 chore: 📦️ Update NPM Packages
  package.json
  pnpm-lock.yaml
  test/package.json
  typescript-api/scripts/scrapeMetadata.ts
Labels: B0-silent, D2-notlive

#3106 Fix foreign assets smoke tests
  test/helpers/foreign-chains.ts
  test/suites/smoke/test-foreign-asset-consistency.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3111 Fix prop hash in runtime releases
  tools/github/generate-runtimes-body.ts
Labels: B0-silent, D2-notlive

#3028 test: :game_die: randomize contract size smoke test
  test/helpers/storageQueries.ts
  test/suites/smoke/test-ethereum-contract-code.ts
  test/suites/smoke/test-polkadot-decoding.ts
Labels: B0-silent, D2-notlive

#3115 :hammer: Fix CI for fork repos
  .github/workflows/build.yml
Labels: B0-silent, D2-notlive

#3021 chore: Fix clippy warnings
  precompiles/assets-erc20/src/eip2612.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/balances-erc20/src/eip2612.rs
  precompiles/balances-erc20/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#3114 Remove state trie migration code
  pallets/moonbeam-lazy-migrations/src/lib.rs
  pallets/moonbeam-lazy-migrations/src/mock.rs
  pallets/moonbeam-lazy-migrations/src/tests.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking
