Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-01, with the labels that each got.

#2604 restore changleog generation during releease
  tools/github/generate-release-body.ts
  tools/github/generate-runtimes-body.ts
Labels: B0-silent, ci, D2-notlive

#2598 Amend README
  README.md
Labels: B0-silent, D2-notlive

#2606 Add referenda migration for moonbeam
  Cargo.lock
  runtime/common/src/migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2607 Filter out new treasury dispatchables
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2608 Update Pallet Preimage weights
  runtime/common/src/weights/pallet_preimage.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2609 Restore CheckInherents for relay validation
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#2611 Remove pallet-base-fee
  Cargo.lock
  Cargo.toml
  precompiles/randomness/Cargo.toml
  runtime/common/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbeam/Cargo.toml
  runtime/moonriver/Cargo.toml
Labels: B0-silent, D3-trivial, not-breaking

#2610 Fix effectiveGasPrice computation for eth_getTransactionReceipt
  Cargo.lock
  test/suites/dev/test-eth-rpc/test-eth-rpc-transaction-receipt.ts
Labels: B5-clientnoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2619 mutate HRMP channel check for Equilibrium
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#2618 Enable debug-assertions for non-production profiles
  Cargo.toml
Labels: B0-silent, D2-notlive

#2625 Package Update for `/test`
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/scripts/fast-execute-chopstick-proposal.ts
Labels: B0-silent, D2-notlive

#2577 [Pre async-backing] [Moonbase] Use relay-slot number as clocktime
  Cargo.lock
  pallets/parachain-staking/Cargo.toml
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  precompiles/parachain-staking/Cargo.toml
  precompiles/parachain-staking/src/mock.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  test/suites/dev/test-staking/test-delegation-scheduled-requests.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests7-bondless-collator.ts
  test/suites/dev/test-staking/test-delegation-scheduled-requests7.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2632 Enforce minimum [pnpm, node] versions when running typescript tests
  .github/workflow-templates/dev-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
  test/.npmrc
  test/package.json
Labels: B0-silent, D2-notlive

#2631 Fix typo in xcm-transactor docs
  pallets/xcm-transactor/src/lib.rs
Labels: B0-silent, D2-notlive

#2633 chore(ci): handle pr's from forked repositories
  .github/workflows/build.yml
  .github/workflows/coverage.yml
Labels: B0-silent, D2-notlive
