Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-06, with the labels that each got.

#2832 fix warnings
  Cargo.lock
  pallets/erc20-xcm-bridge/Cargo.toml
  pallets/erc20-xcm-bridge/src/errors.rs
  pallets/moonbeam-orbiters/src/benchmarks.rs
  pallets/parachain-staking/src/benchmarks.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/evm_tracing.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/evm_tracing.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/evm_tracing.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/runtime_apis.rs
Labels: B0-silent, D3-trivial

#2839 Update client version to 0.39.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D3-trivial

#2847 chore(CI): Increase coverage timeout to 90 minutes
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/upgrade-typescript-api.yml
Labels: B0-silent, D3-trivial

#2843 feat: add cancun evm opcodes to evm-tracing-events
  primitives/rpc/evm-tracing-events/src/runtime.rs
Labels: B0-silent, D3-trivial

#2845 add migration ComputeTheoreticalFirstSlot for moonbeam
  Cargo.lock
  pallets/erc20-xcm-bridge/Cargo.toml
  pallets/erc20-xcm-bridge/src/errors.rs
  pallets/moonbeam-orbiters/src/benchmarks.rs
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/evm_tracing.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/migrations.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/evm_tracing.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/runtime_apis.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/evm_tracing.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/runtime_apis.rs
  test/suites/dev/moonbase/test-txpool/test-txpool-limits.ts
Labels: A0-pleasereview, B7-runtimenoteworthy, D3-trivial, not-breaking

#2846 Update repo URL in command.rs
  node/cli/src/command.rs
Labels: B0-silent, D3-trivial

#2852 set the first_slot to zero and fallback to ideal duration for one round
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
Labels: B7-runtimenoteworthy, D1-runtime-migration, D5-nicetohaveaudit⚠️, not-breaking

#2827 Github workflows chores
  .github/workflow-templates/cargo-build/action.yml
  .github/workflows/build.yml
  .github/workflows/check-benchmarks.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/docs.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/subxt-diff.yml
  .github/workflows/upgrade-typescript-api.yml
  tools/github/print-client-release-issue.ts
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent, ci, D2-notlive

#2848 Add test suite for checking a remote EVM call can be payed in DOT
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-evm-with-dot.ts
Labels: B0-silent, D2-notlive
