Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-10, with the labels that each got.

#2972 Test: Fix polkadot-decoding smoke test
  test/suites/smoke/test-polkadot-decoding.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#2980 Add XCM `DryRun` and `LocationToAccount` runtime APIs to all runtimes
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-dry-run-api.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-location-to-account-api.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, not-breaking

#2985 update chopsticks and upgradeRestrictionSignal check
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/chopsticks/test-upgrade-chain.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#2946 fix unfairness on proof size check estimation
  Cargo.lock
  precompiles/batch/src/tests.rs
  test/suites/dev/moonbase/test-eth-tx/test-eth-tx-native-transfer.ts
  test/suites/dev/moonbase/test-pov/test-evm-over-pov.ts
  test/suites/dev/moonbase/test-pov/test-evm-over-pov2.ts
  test/suites/dev/moonbase/test-pov/test-precompile-over-pov.ts
  test/suites/dev/moonbase/test-pov/test-precompile-over-pov2.ts
  test/suites/dev/moonbase/test-pov/test-xcm-to-evm-pov.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery4.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery5.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2986 test: add case for eth_getLogs with more than 16 addresses filtered
  test/suites/smoke/test-old-regressions.ts
Labels: B0-silent, D2-notlive

#2993 Suspend XCM checks for Litms until November 30
  test/helpers/foreign-chains.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#2992 Add pallet-xcm precompile to Moonbeam and Moonriver (`transfer_assets_using_type_and_then` extrinsic support)
  Cargo.lock
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  test/contracts/src/XcmInterface.sol
  test/suites/dev/moonbase/test-precompile/test-precompile-pallet-xcm.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2969 Remove all dependencies to repository open-runtime-module-library
  Cargo.lock
  Cargo.toml
  pallets/parachain-staking/src/set.rs
  pallets/xcm-transactor/Cargo.toml
  pallets/xcm-transactor/src/encode.rs
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  precompiles/gmp/Cargo.toml
  precompiles/gmp/src/lib.rs
  precompiles/gmp/src/mock.rs
  precompiles/relay-encoder/Cargo.toml
  precompiles/relay-encoder/src/mock.rs
  precompiles/xcm-transactor/Cargo.toml
  precompiles/xcm-transactor/src/mock.rs
  precompiles/xcm-utils/Cargo.toml
  precompiles/xtokens/Cargo.toml
  precompiles/xtokens/src/lib.rs
  precompiles/xtokens/src/mock.rs
  precompiles/xtokens/src/tests.rs
  primitives/xcm/Cargo.toml
  primitives/xcm/src/get_by_key.rs
  primitives/xcm/src/lib.rs
  primitives/xcm/src/origin_conversion.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/statemint_like.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/statemint_like.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/governance/origins.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/statemine_like.rs
  runtime/moonriver/tests/xcm_tests.rs
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-wormhole.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-xtokens.ts
  test/suites/tracing-tests/test-trace-filter.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2999 Update weights for runtime 3300
  runtime/common/src/weights/cumulus_pallet_parachain_system.rs
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/pallet_asset_manager.rs
  runtime/common/src/weights/pallet_assets.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_conviction_voting.rs
  runtime/common/src/weights/pallet_crowdloan_rewards.rs
  runtime/common/src/weights/pallet_evm.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_message_queue.rs
  runtime/common/src/weights/pallet_moonbeam_foreign_assets.rs
  runtime/common/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/common/src/weights/pallet_moonbeam_orbiters.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_parameters.rs
  runtime/common/src/weights/pallet_precompile_benchmarks.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_randomness.rs
  runtime/common/src/weights/pallet_referenda.rs
  runtime/common/src/weights/pallet_relay_storage_roots.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_sudo.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_whitelist.rs
  runtime/common/src/weights/pallet_xcm.rs
  runtime/common/src/weights/pallet_xcm_transactor.rs
  runtime/common/src/weights/pallet_xcm_weight_trader.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-xcm.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3002 Cleanup old migrations
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3003 Update runtime spec version to 3400
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#3005 fix round initialization when in lazy loading
  node/service/src/lazy_loading/backend.rs
  node/service/src/lazy_loading/state_overrides.rs
Labels: B5-clientnoteworthy, D2-notlive, not-breaking, lazy-loading

#3000 Fix bad regressions smoke test
  test/suites/smoke/test-old-regressions.ts
Labels: B0-silent, D2-notlive

#3008 Update client version to 0.42.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#3007 Update the client docker image to moonbeamfoundation/moonbeam:v0.41.0
  README.md
Labels: B0-silent, D3-trivial

#3011 Pause XCM check on parachain 2019
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#3015 fix(metadata-hash): use original token symbol (DEV) in moonbase runtime
  node/service/src/chain_spec/moonbase.rs
  runtime/moonbase/build.rs
Labels: B0-silent, D3-trivial, not-breaking

#3016 Fix moonsama smoke tests
  test/suites/smoke/test-old-regressions.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3017 Fix moonriver smoke test
  test/suites/smoke/test-old-regressions.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#2964 refactor: :recycle: Update api-augment ci
  .github/workflows/publish-typescript-api.yml
  .github/workflows/upgrade-typescript-api.yml
  docker/moonbeam.Dockerfile
  typescript-api/src/moonbeam/interfaces/definitions.ts
  typescript-api/src/moonriver/interfaces/definitions.ts
  typescript-api/tsconfig.base.json
  typescript-api/tsconfig.json
Labels: B0-silent, D2-notlive

#3023 Fix encoding for debug_traceBlock
  client/evm-tracing/src/types/single.rs
Labels: B5-clientnoteworthy, A10-evmtracing, D2-notlive, not-breaking

#3025 Update the client docker image to moonbeamfoundation/moonbeam:v0.41.1
  README.md
Labels: B0-silent, D3-trivial
