Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-03, with the labels that each got.

#2685 Remove democracy pallet
  Cargo.lock
  Cargo.toml
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  pallets/moonbeam-lazy-migrations/Cargo.toml
  pallets/moonbeam-lazy-migrations/src/lib.rs
  pallets/moonbeam-lazy-migrations/src/mock.rs
  pallets/xcm-transactor/src/encode.rs
  precompiles/pallet-democracy/Cargo.toml
  precompiles/pallet-democracy/DemocracyInterface.sol
  precompiles/pallet-democracy/PoliticalPartyDao.sol
  precompiles/pallet-democracy/src/lib.rs
  precompiles/pallet-democracy/src/mock.rs
  precompiles/pallet-democracy/src/tests.rs
  runtime/common/Cargo.toml
  runtime/common/src/migrations.rs
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/governance/democracy.rs
  runtime/moonbase/src/governance/mod.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/governance/democracy.rs
  runtime/moonbeam/src/governance/mod.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/governance/democracy.rs
  runtime/moonriver/src/governance/mod.rs
  runtime/moonriver/src/governance/origins.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  test/helpers/democracy-unlock-test-data.ts
  test/helpers/index.ts
  test/helpers/precompiles.ts
  test/suites/dev/moonbase/test-balance/test-balance-reducible.ts
  test/suites/dev/moonbase/test-contract/test-contract-delegate-call.ts
  test/suites/dev/moonbase/test-moonbeam-lazy-migrations/test-unlock-democracy-funds.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-democracy.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-democracy2.ts
Labels: B7-runtimenoteworthy, D1-runtime-migration, D3-trivial, breaking

#2690 Go back to block based staking rounds and make inflation dynamic (slot based)
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/delegation_requests.rs
  pallets/parachain-staking/src/inflation.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/common/src/apis.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/migrations.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-staking/test-rewards-auto-compound-pov.ts
Labels: A3-inprogress, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2692 Increase target block fullness to 50%
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-max.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-xcm.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2699 Balances Consistency Fix
  test/suites/smoke/test-balances-consistency.ts
Labels: B0-silent, D2-notlive

#2696 Add comment about how values are selected in fee tests
  runtime/moonbase/tests/integration_test.rs
Labels: B0-silent, D2-notlive

#2686 Fix feature = "cargo-clippy" deprecation
  .cargo/config.toml
Labels: B0-silent, D2-notlive

#2687 Update ahash and curve25519-dalek to work on nightly compiler
  Cargo.lock
Labels: B0-silent, D3-trivial

#2701 Fix tracing for multiple xcm transactions in the same block
  runtime/common/src/impl_moonbeam_xcm_call_tracing.rs
  test/suites/tracing-tests/test-trace-ethereum-xcm-3.ts
  test/suites/tracing-tests/test-trace-filter-reorg.ts
  test/suites/tracing-tests/test-trace-filter.ts
  test/suites/tracing-tests/test-trace-gas.ts
Labels: B5-clientnoteworthy, A10-evmtracing, D3-trivial, not-breaking

#2702 RT2801 Smoke Test Compatibility
  test/helpers/constants.ts
  test/helpers/index.ts
  test/helpers/shortfalls.ts
  test/package.json
  test/pnpm-lock.yaml
  test/suites/smoke/test-balances-consistency.ts
  test/suites/smoke/test-dynamic-fees.ts
  test/suites/smoke/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#2705 Set async backing velocity to 1
  runtime/moonbase/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2708 Fix `eth_getBlockByHash` for HEADS
  Cargo.lock
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2710 Update TS Packages
  test/package.json
  test/pnpm-lock.yaml
Labels: B0-silent, D2-notlive

#2707 evm-tracing should replay on_idle
  runtime/common/src/apis.rs
  runtime/moonbase/tests/evm_tracing.rs
  runtime/moonbeam/tests/evm_tracing.rs
  runtime/moonriver/tests/evm_tracing.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2706 Github actions maintenance
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/check-licenses.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker-runtime.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
Labels: B0-silent, ci, D2-notlive

#2709 [XCM-Transactor] Make `fee_payer` field optional in `transact_through_sovereign`
  pallets/xcm-transactor/src/benchmarks.rs
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/tests.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/tests/xcm_tests.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2679 Fix benchmark tests
  .github/workflows/build.yml
  Cargo.toml
  pallets/ethereum-xcm/Cargo.toml
  pallets/moonbeam-lazy-migrations/Cargo.toml
  pallets/moonbeam-lazy-migrations/src/benchmarks.rs
  pallets/moonbeam-lazy-migrations/src/mock.rs
  pallets/moonbeam-lazy-migrations/src/tests.rs
  pallets/moonbeam-xcm-benchmarks/Cargo.toml
  pallets/xcm-transactor/Cargo.toml
  primitives/xcm/Cargo.toml
Labels: B0-silent, D2-notlive

#2727 Update benchmarks template and add extra read weight to pallet proxy
  benchmarking/frame-weight-template.hbs
  runtime/common/src/weights/pallet_proxy.rs
  scripts/benchmarking.sh
  scripts/run-benches-for-runtime.sh
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2726 add cli option --block-authoring-duration
  Cargo.lock
  Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking
