Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-08, with the labels that each got.

#2786 Update rocksDB weights
  runtime/common/src/weights/db/mod.rs
  runtime/common/src/weights/db/rocksdb.rs
  runtime/common/src/weights/mod.rs
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/src/governance/councils.rs
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/src/governance/councils.rs
  runtime/moonriver/src/governance/referenda.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-pov/test-xcm-to-evm-pov.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-batch.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-xcm-utils.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-1.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-12.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-3.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-6.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-6.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#2894 Fix typos
  precompiles/call-permit/README.md
  test/contracts/src/wormhole/Messages.sol
  tools/README.md
  tools/pov/README.md
  tools/test-scripts/test-staking.ts
Labels: B0-silent, D2-notlive

#2896 Upgrade typescript API for runtime-3100
  typescript-api/package-lock.json
  typescript-api/package.json
  typescript-api/src/moonbase/interfaces/augment-api-consts.ts
  typescript-api/src/moonbase/interfaces/augment-api-errors.ts
  typescript-api/src/moonbase/interfaces/augment-api-events.ts
  typescript-api/src/moonbase/interfaces/augment-api-query.ts
  typescript-api/src/moonbase/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbase/interfaces/augment-api-runtime.ts
  typescript-api/src/moonbase/interfaces/augment-api-tx.ts
  typescript-api/src/moonbase/interfaces/lookup.ts
  typescript-api/src/moonbase/interfaces/registry.ts
  typescript-api/src/moonbase/interfaces/types-lookup.ts
  typescript-api/src/moonbeam/interfaces/augment-api-consts.ts
  typescript-api/src/moonbeam/interfaces/augment-api-errors.ts
  typescript-api/src/moonbeam/interfaces/augment-api-events.ts
  typescript-api/src/moonbeam/interfaces/augment-api-query.ts
  typescript-api/src/moonbeam/interfaces/augment-api-runtime.ts
  typescript-api/src/moonbeam/interfaces/augment-api-tx.ts
  typescript-api/src/moonbeam/interfaces/lookup.ts
  typescript-api/src/moonbeam/interfaces/registry.ts
  typescript-api/src/moonbeam/interfaces/types-lookup.ts
  typescript-api/src/moonriver/interfaces/augment-api-consts.ts
  typescript-api/src/moonriver/interfaces/augment-api-errors.ts
  typescript-api/src/moonriver/interfaces/augment-api-events.ts
  typescript-api/src/moonriver/interfaces/augment-api-query.ts
  typescript-api/src/moonriver/interfaces/augment-api-runtime.ts
  typescript-api/src/moonriver/interfaces/augment-api-tx.ts
  typescript-api/src/moonriver/interfaces/lookup.ts
  typescript-api/src/moonriver/interfaces/registry.ts
  typescript-api/src/moonriver/interfaces/types-lookup.ts
Labels: B0-silent, D2-notlive

#2889 Fix ci node launch parameters
  .github/workflows/subxt-diff.yml
  .github/workflows/upgrade-typescript-api.yml
  typescript-api/scripts/runtime-upgrade.sh
Labels: B0-silent, ci, D2-notlive

#2901 test/smoke: Add randomization to polkadot-decoding smoke test
  test/suites/smoke/test-polkadot-decoding.ts
Labels: B0-silent, D2-notlive

#2905 Mute smoke test for composable parachain channel
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#2883 XCM instructions weights should comply with evm foreign assets
  Cargo.lock
  client/rpc/manual-xcm/src/lib.rs
  pallets/moonbeam-foreign-assets/src/evm.rs
  pallets/moonbeam-foreign-assets/src/lib.rs
  pallets/moonbeam-xcm-benchmarks/Cargo.toml
  pallets/moonbeam-xcm-benchmarks/src/weights/fungible.rs
  pallets/moonbeam-xcm-benchmarks/src/weights/mod.rs
  primitives/xcm/src/constants.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-xcm.ts
  test/suites/dev/moonbase/test-pov/test-xcm-to-evm-pov.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-3.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-5.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-6.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-1.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-1.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-12.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-2.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-3.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-4.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-5.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-6.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-7.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-8.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-fees-and-trap.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-v3-filter.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-v3.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-4.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-2.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-4.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-5.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-6.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-7.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-8.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-evm-with-dot.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api-transact-foreign.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api-transact-native.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-ver-conversion-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-ver-conversion-2.ts
  test/suites/tracing-tests/test-trace-ethereum-xcm-1.ts
  test/suites/tracing-tests/test-trace-ethereum-xcm-2.ts
  test/suites/tracing-tests/test-trace-ethereum-xcm-3.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2909 Add missing benchmarks
  Cargo.lock
  file_header.txt
  runtime/common/Cargo.toml
  runtime/common/src/weights/cumulus_pallet_parachain_system.rs
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_message_queue.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2910 test: Improve error msg & add reproduction instructions to randomized smoke test
  test/suites/smoke/test-polkadot-decoding.ts
Labels: B0-silent, D2-notlive

#2914 mute hrmp channel moonriver - Litmus
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#2918 Add `evm::tracing::Event::Log` event
  Cargo.lock
  primitives/rpc/evm-tracing-events/src/evm.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2915 Extract Storage Read costs for dev tests involved in #2786
  test/helpers/constants.ts
  test/suites/dev/moonbase/test-pov/test-xcm-to-evm-pov.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-batch.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-xcm-utils.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-1.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-12.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-3.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-6.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-6.ts
Labels: B0-silent, D2-notlive

#2913 Fix auto-pause xcm: incoming XCMP messages where dropped when auto-pause
  Cargo.lock
  Cargo.toml
  client/rpc/dev/Cargo.toml
  client/rpc/dev/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/rpc.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  test/suites/dev/moonbase/test-xcm-v4/test-auto-pause-xcm.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2921 Set the block size to 60mln gas for moonbeam
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  test/helpers/constants.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2923 Add pallet_parameters (moonbase only)
  Cargo.lock
  Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_parameters.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/runtime_params.rs
  test/suites/dev/moonbase/test-parameters/test-parameters.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking
