Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-04, with the labels that each got.

#2670 remove local-assets logic from assets-manager
  pallets/asset-manager/src/benchmarks.rs
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/mock.rs
  pallets/asset-manager/src/tests.rs
  pallets/asset-manager/src/weights.rs
  runtime/common/src/weights/pallet_asset_manager.rs
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/asset_config.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  test/suites/smoke/test-foreign-asset-consistency.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2732 Aggregate dependabot PR's
  .github/workflow-templates/dev-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/cancel.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/coverage.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/subxt-diff.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
Labels: B0-silent, ci, D2-notlive

#2672 CI: add manual action to check benchmarks
  .github/workflows/check-benchmarks.yml
Labels: B0-silent, ci, D2-notlive

#2711 Add migration to remove collective v1 storage
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, D1-runtime-migration, D3-trivial, not-breaking

#2731 Fix staking reward smoke test for old runtimes (<2801): always use max inflation
  test/suites/smoke/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#2737 Fix `ExpectedBlockTime` const
  runtime/moonbase/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2730 test: :recycle: Update smoke tests with latest RT changes
  .github/workflow-templates/cargo-build/action.yml
  .github/workflow-templates/dev-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/upgrade-typescript-api.yml
  .github/workflows/version-bump.yml
  test/helpers/foreign-chains.ts
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/moonbase/test-precompile/test-precompile-wormhole.ts
  test/suites/smoke/test-balances-consistency.ts
  test/suites/smoke/test-ethereum-contract-code.ts
  test/suites/smoke/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#2729 Enable Relay Data Verifier Precompile in Moonriver and Moonbeam
  Cargo.lock
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2741 Update owner of s3 upload action
  .github/workflows/build.yml
Labels: B0-silent, ci, D2-notlive

#2740 add codeowners
  .github/CODEOWNERS
Labels: B0-silent, D2-notlive, not-breaking

#2743 Improve release related content
  tools/github/generate-release-body.ts
  tools/github/generate-runtimes-body.ts
  tools/github/print-client-release-issue.ts
Labels: B0-silent, ci, D2-notlive

#2725 Add Storage Cleaner Precompile
  Cargo.lock
  Cargo.toml
  precompiles/utils/Cargo.toml
  precompiles/utils/macro/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  test/contracts/src/StorageCleaner.sol
  test/suites/dev/moonbase/test-precompile/test-precompile-clear-suicided-storage.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2738 Ignore user provided nonce for gas estimation
  Cargo.lock
Labels: B5-clientnoteworthy, D3-trivial, breaking

#2746 Fix benchmarks
  .github/workflows/check-benchmarks.yml
  Cargo.lock
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/moonbeam_xcm_benchmarks_weights_generic.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, dependencies, D3-trivial

#2736 Fast General Admin Track for opening HRMP channels
  pallets/xcm-transactor/src/lib.rs
  pallets/xcm-transactor/src/mock.rs
  precompiles/relay-encoder/src/mock.rs
  precompiles/xcm-transactor/src/mock.rs
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/governance/origins.rs
  runtime/moonbeam/src/governance/referenda.rs
  runtime/moonbeam/src/governance/tracks.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/governance/origins.rs
  runtime/moonriver/src/governance/referenda.rs
  runtime/moonriver/src/governance/tracks.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2749 Update Moonriver and Moonbeam bootnodes
  specs/moonbeam/parachain-embedded-specs.json
  specs/moonriver/parachain-embedded-specs.json
Labels: B5-clientnoteworthy, D3-trivial, breaking

#2735 Increase block gas limit
  runtime/moonbase/src/lib.rs
  test/helpers/constants.ts
  test/suites/dev/moonbase/test-block/test-block-1.ts
  test/suites/dev/moonbase/test-block/test-block-gas.ts
  test/suites/dev/moonbase/test-block/test-block-genesis.ts
  test/suites/dev/moonbase/test-eth-fee/test-eth-fee-history.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-max.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-xcm.ts
  test/suites/dev/moonbase/test-fees/test-length-fees2.ts
  test/suites/dev/moonbase/test-gas/test-gas-estimation-contracts.ts
  test/suites/dev/moonbase/test-pov/test-evm-over-pov.ts
  test/suites/dev/moonbase/test-pov/test-evm-over-pov2.ts
  test/suites/dev/moonbase/test-pov/test-precompile-over-pov.ts
  test/suites/dev/moonbase/test-pov/test-precompile-over-pov2.ts
  test/suites/dev/moonbase/test-pov/test-xcm-to-evm-pov.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-conviction-voting.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-proxy.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-referenda.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-relay-verifier.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-xtokens.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-request.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-request2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-request3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-result.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-result2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-result4.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-request.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-request2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-request3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-request5.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-request6.ts
  test/suites/dev/moonbase/test-storage-growth/test-block-storage-growth.ts
  test/suites/dev/moonbase/test-storage-growth/test-precompile-storage-growth.ts
  test/suites/dev/moonbase/test-txpool/test-txpool-limits.ts
  test/suites/dev/moonbase/test-txpool/test-txpool-limits2.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-10.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-10.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2744 Add benchmarks for runtime 2900
  Cargo.lock
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/pallet_asset_manager.rs
  runtime/common/src/weights/pallet_assets.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_conviction_voting.rs
  runtime/common/src/weights/pallet_crowdloan_rewards.rs
  runtime/common/src/weights/pallet_evm.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/common/src/weights/pallet_moonbeam_orbiters.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_precompile_benchmarks.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_randomness.rs
  runtime/common/src/weights/pallet_referenda.rs
  runtime/common/src/weights/pallet_relay_storage_roots.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_sudo.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_whitelist.rs
  runtime/common/src/weights/pallet_xcm_transactor.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-staking/test-rewards-auto-compound-pov.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2753 fix rust toolchain version for client prod build
  rust-toolchain
Labels: B0-silent, D2-notlive, D3-trivial

#2752 review scoreboard findings
  Cargo.lock
  Cargo.toml
  node/service/Cargo.toml
  test/package.json
  test/pnpm-lock.yaml
Labels: B0-silent, D3-trivial

#2761 Update client version to 0.38.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D3-trivial

#2760 Update runtime spec version to 3000
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#2755 Fix client binary build after artifact-upload changes
  .github/workflows/publish-binary.yml
  .github/workflows/subxt-diff.yml
Labels: B0-silent, ci, D3-trivial

#2763 Add pallet identity migration
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2762 test: :white_check_mark: Support new XCM events
  test/helpers/foreign-chains.ts
  test/suites/smoke/test-xcm-failures.ts
Labels: B0-silent, D2-notlive

#2768 Multiply Erc20TransferGasLimit constant by 4 for moonbase
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/contracts/src/ERC20ExcessGas.sol
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-excess-gas.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-fees-and-trap.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-v3-filter.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-v3.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-erc20-transfer.ts
  test/suites/tracing-tests/test-trace-erc20-xcm.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2778 enable async backing client side for all runtimes
  node/cli/src/command.rs
Labels: B5-clientnoteworthy, not-breaking

#2777 Runtime 2902 Smoke Fixes
  test/helpers/shortfalls.ts
  test/package.json
  test/pnpm-lock.yaml
  test/suites/smoke/test-balances-consistency.ts
  test/suites/smoke/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#2780 support eth_call for past blocks with old runtimes
  Cargo.lock
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2784 `MoonbeamFinalityApi` to fully async/await
  Cargo.lock
  client/rpc/finality/Cargo.toml
  client/rpc/finality/src/lib.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking
