Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-02, with the labels that each got.

#2638 Update Zombienet runtime upgrade CI
  .github/workflows/build.yml
  test/configs/zombieAlphanet.json
  test/configs/zombieAlphanetRpc.json
  test/configs/zombieMoonbeam.json
  test/configs/zombieMoonbeamRpc.json
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/scripts/modify-plain-specs.ts
  test/scripts/preapprove-rt-rawspec.ts
  test/suites/para-rpc/test_moonbeam.ts
  test/suites/para/test_moonbase.ts
  test/suites/para/test_moonbeam.ts
  test/suites/zombie/test_para.ts
Labels: B0-silent, D2-notlive

#2639 Add Subxt CI job
  .github/workflows/check-licenses.yml
  .github/workflows/subxt-diff.yml
  runtime-diffs/moonbase/runtime-2700.txt
  test/package.json
  test/pnpm-lock.yaml
  test/scripts/subxt-diff.ts
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent, D2-notlive

#2642 chore: fixes clippy redundant_closure_call error inside macros
  precompiles/utils/src/testing/account.rs
Labels: B0-silent, D2-notlive

#2644 Fix zombienet timeouts for async branch
  test/suites/zombie/test_para.ts
Labels: B0-silent, D2-notlive

#2647 Update rust to v1.74
  client/rpc/debug/src/lib.rs
  node/service/src/lib.rs
  precompiles/proxy/src/lib.rs
  precompiles/utils/macro/src/derive_codec.rs
  runtime/moonriver/src/lib.rs
  rust-toolchain
Labels: A8-mergeoncegreen, B5-clientnoteworthy, B7-runtimenoteworthy, D3-trivial, not-breaking

#2623 Enable async backing moonbase
  .github/workflows/build.yml
  .github/workflows/subxt-diff.yml
  Cargo.lock
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/lib.rs
  pallets/parachain-staking/src/inflation.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/tests.rs
  precompiles/parachain-staking/src/mock.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  test/configs/zombieAlphanet.json
  test/moonwall.config.json
  test/suites/dev/test-democracy/test-democracy-fastrack.ts
  test/suites/dev/test-democracy/test-democracy-genesis.ts
  test/suites/dev/test-precompile/test-precompile-conviction-voting5.ts
  test/suites/dev/test-staking/test-staking-consts.ts
  test/suites/dev/test-staking/test-staking-locks9.ts
  test/suites/zombie/test_para.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2640 Fix Subxt CI
  .github/workflows/subxt-diff.yml
  precompiles/xcm-utils/src/mock.rs
  test/package.json
  test/pnpm-lock.yaml
  test/scripts/subxt-diff.ts
Labels: B0-silent, D2-notlive

#2655 force add target wasm32 to fix runners corruption
  .github/workflow-templates/cargo-build/action.yml
Labels: A8-mergeoncegreen, B0-silent, D3-trivial

#2653 Fix typo in README.md
  README.md
Labels: B0-silent, D2-notlive

#2561 Add an extrinsic to clear storage entries for suicided contracts
  Cargo.lock
  Cargo.toml
  pallets/moonbeam-lazy-migrations/Cargo.toml
  pallets/moonbeam-lazy-migrations/src/benchmarks.rs
  pallets/moonbeam-lazy-migrations/src/lib.rs
  pallets/moonbeam-lazy-migrations/src/mock.rs
  pallets/moonbeam-lazy-migrations/src/tests.rs
  pallets/moonbeam-lazy-migrations/src/weights.rs
  runtime/common/Cargo.toml
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/contracts/src/Storage.sol
  test/suites/dev/moonbase/test-moonbeam-lazy-migrations/test-clear-suicided-contracts.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2657 Fix typo in `record_external_cost`
  precompiles/randomness/src/lib.rs
  precompiles/utils/src/substrate.rs
Labels: B0-silent, D2-notlive

#2658 cleanup migrations for 2800
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2649 Add a fast admin track to opengov for Hrmp manipulation
  runtime/moonbase/src/governance/origins.rs
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbase/src/governance/tracks.rs
  runtime/moonbase/src/xcm_config.rs
  test/suites/dev/moonbase/test-democracy/test-referenda-fast-general-admin.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2663 New openTech helper
  test/helpers/voting.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter2.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter3.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-mode.ts
Labels: B0-silent, D2-notlive

#2664 pallet lazy migration it's a utility, not xcm stuff
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B0-silent, D3-trivial

#2643 Remove Gov V1 collectives
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/chain_spec/test_spec.rs
  node/service/src/lib.rs
  precompiles/collective/src/mock.rs
  runtime/common/src/migrations.rs
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/src/governance/councils.rs
  runtime/moonbase/src/governance/democracy.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/asset_config.rs
  runtime/moonbeam/src/governance/councils.rs
  runtime/moonbeam/src/governance/democracy.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/src/governance/councils.rs
  runtime/moonriver/src/governance/democracy.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/tests/integration_test.rs
  test/helpers/voting.ts
  test/suites/dev/moonbase/test-crowdloan/test-crowdloan-democracy.ts
  test/suites/dev/moonbase/test-democracy/test-democracy-instant-fastrack.ts
  test/suites/dev/moonbase/test-democracy/test-democracy-proposal.ts
  test/suites/dev/moonbase/test-democracy/test-democracy-referendum.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter2.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter3.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-mode.ts
  test/suites/dev/moonbase/test-polkadot-js/test-polkadot-api.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-proxy-governance.ts
  test/suites/dev/moonbase/test-proxy/test-proxy-governance.ts
  test/suites/dev/moonbase/test-staking/test-staking-locks5.ts
  test/suites/dev/moonbase/test-treasury/test-treasury-proposal7.ts
  test/suites/dev/moonbase/test-treasury/test-treasury-proposal8.ts
Labels: B7-runtimenoteworthy, D1-runtime-migration, D5-nicetohaveaudit⚠️, breaking

#2665 Add more details about network configurations
  README.md
Labels: B0-silent, D2-notlive, not-breaking

#2651 Gov V1 removal: Add manual migration unlock_democracy_funds
  Cargo.lock
  pallets/moonbeam-lazy-migrations/Cargo.toml
  pallets/moonbeam-lazy-migrations/src/lib.rs
  pallets/moonbeam-lazy-migrations/src/mock.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, D1-runtime-migration, D5-nicetohaveaudit⚠️, not-breaking

#2667 CI: Fix `docker-moonbeam` build step
  .github/workflows/build.yml
Labels: B0-silent, ci, D2-notlive, not-breaking

#2666 Set minimum period to 3s on moonbase
  runtime/moonbase/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2650 Relay Chain Data Verifier Precompile
  Cargo.lock
  Cargo.toml
  pallets/precompile-benchmarks/Cargo.toml
  pallets/precompile-benchmarks/benchmark_proofs
  pallets/precompile-benchmarks/src/benchmarks.rs
  pallets/precompile-benchmarks/src/lib.rs
  pallets/precompile-benchmarks/src/weights.rs
  precompiles/relay-data-verifier/Cargo.toml
  precompiles/relay-data-verifier/RelayDataVerifier.sol
  precompiles/relay-data-verifier/proof
  precompiles/relay-data-verifier/src/lib.rs
  precompiles/relay-data-verifier/src/mock.rs
  precompiles/relay-data-verifier/src/tests.rs
  precompiles/relay-data-verifier/src/weights.rs
  precompiles/utils/src/solidity/codec/native.rs
  primitives/storage-proof/Cargo.toml
  primitives/storage-proof/proof
  primitives/storage-proof/src/lib.rs
  primitives/storage-proof/src/tests.rs
  runtime/common/Cargo.toml
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_precompile_benchmarks.rs
  runtime/common/src/weights/pallet_relay_storage_roots.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  test/helpers/constants.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-relay-verifier.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2671 Fix benchmarks for Suicided Contracts
  pallets/moonbeam-lazy-migrations/src/benchmarks.rs
Labels: B0-silent, D3-trivial, not-breaking

#2669 Add benchmarks for runtime 2800
  primitives/storage-proof/benchmark_proofs
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/pallet_assets.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_conviction_voting.rs
  runtime/common/src/weights/pallet_crowdloan_rewards.rs
  runtime/common/src/weights/pallet_democracy.rs
  runtime/common/src/weights/pallet_evm.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/common/src/weights/pallet_moonbeam_orbiters.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_precompile_benchmarks.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_randomness.rs
  runtime/common/src/weights/pallet_referenda.rs
  runtime/common/src/weights/pallet_relay_storage_roots.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_sudo.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_whitelist.rs
  runtime/common/src/weights/pallet_xcm.rs
  runtime/common/src/weights/pallet_xcm_transactor.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-xcm.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2674 Fix `vec` import in common migrations
  runtime/common/src/migrations.rs
Labels: B0-silent, D3-trivial, not-breaking

#2676 Update publish-runtime.yml
  .github/workflows/publish-runtime.yml
Labels: B0-silent, ci, D2-notlive, not-breaking

#2682 Bump runtime and client versions and fix CI
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/configs/alphanet.yml
  test/configs/moonbeam.yml
  test/configs/moonriver.yml
  test/moonwall.config.json
  test/scripts/modify-plain-specs.ts
  test/suites/zombie/test_para.ts
Labels: A8-mergeoncegreen, B0-silent, ci, D2-notlive

#2678 Chores: update README moonbeam docker version and add .idea in gitignore
  .gitignore
  README.md
Labels: B0-silent, D2-notlive, not-breaking

#2684 Rename is_orbiter method to reference collator pool
  pallets/moonbeam-orbiters/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial
