Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-05, with the labels that each got.

#2787 update frontier
  Cargo.lock
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2799 fix pallet-xcm benchmarks
  Cargo.lock
  runtime/common/src/apis.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial, not-breaking

#2776 Enable async backing on moonriver
  Cargo.lock
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/migrations.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2802 Update pallet weights
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/pallet_asset_manager.rs
  runtime/common/src/weights/pallet_assets.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_conviction_voting.rs
  runtime/common/src/weights/pallet_crowdloan_rewards.rs
  runtime/common/src/weights/pallet_evm.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/common/src/weights/pallet_moonbeam_orbiters.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_precompile_benchmarks.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_randomness.rs
  runtime/common/src/weights/pallet_referenda.rs
  runtime/common/src/weights/pallet_relay_storage_roots.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_sudo.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_whitelist.rs
  runtime/common/src/weights/pallet_xcm.rs
  runtime/common/src/weights/pallet_xcm_transactor.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-fees/test-length-fees.ts
  test/suites/dev/moonbase/test-staking/test-rewards-auto-compound-pov.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, D3-trivial, not-breaking

#2803 [Moonbase] Enable pallet-xcm precompile
  Cargo.lock
  Cargo.toml
  precompiles/assets-erc20/Cargo.toml
  precompiles/assets-erc20/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/asset_config.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/integration_test.rs
  test/contracts/src/XcmInterface.sol
  test/suites/dev/moonbase/test-precompile/test-precompile-pallet-xcm.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2800 Fixes 🔨 `trace_filter` RPC call by filtering out unknown ethereum transactions
  client/rpc/trace/src/lib.rs
  test/suites/tracing-tests/test-trace-filter.ts
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2796 Adds debug_traceCall RPC method
  Cargo.lock
  Cargo.toml
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/debug/src/lib.rs
  client/rpc/debug/Cargo.toml
  client/rpc/debug/src/lib.rs
  primitives/rpc/debug/Cargo.toml
  primitives/rpc/debug/src/lib.rs
  runtime/common/src/apis.rs
  runtime/moonbase/tests/evm_tracing.rs
  runtime/moonbeam/tests/evm_tracing.rs
  runtime/moonriver/tests/evm_tracing.rs
  test/suites/tracing-tests/test-trace-call.ts
Labels: A0-pleasereview, B5-clientnoteworthy, D5-nicetohaveaudit⚠️, A10-evmtracing, not-breaking

#2807 Remove moonbase migration
  runtime/moonbase/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2809 Update to newest Moonbeam brand guidelines
  CONTRIBUTIONS.md
  README.md
  media/Banner.jpg
  media/GLMR.png
  media/GLMR.svg
  media/MOVR.png
  media/MOVR.svg
  media/Moonbeam_Icon_White.svg
  media/Moonbeam_Logo_White.svg
  media/Moonriver_Icon_White.svg
  media/Moonriver_Logo_White.svg
  media/README.md
  media/moonbeam-cover.jpg
Labels: B0-silent, D2-notlive

#2804 [Moonriver] Fix async-backing implementation
  Cargo.lock
  node/cli/src/command.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/timestamp.rs
  runtime/moonbase/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2810 chore: :package: Update Moonwall versions
  test/package.json
  test/pnpm-lock.yaml
Labels: B0-silent, D2-notlive

#2805 [Moonbeam] Enable async-backing
  Cargo.lock
  node/cli/src/command.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/migrations.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  test/configs/zombieMoonbeam.json
  test/configs/zombieMoonbeamRpc.json
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D9-needsaudit👮, breaking

#2813 remove old runtime migrations
  runtime/common/src/migrations.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2814 set the default client authoring duration to 2s
  node/cli/src/cli.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2817 update rust version to 1.77.0
  rust-toolchain
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D2-notlive, D3-trivial, not-breaking

#2795 Cancun support
  Cargo.lock
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/tests/xcm_tests.rs
  test/contracts/src/ERC20ExcessGas.sol
  test/contracts/src/dancun/ProxySuicide.sol
  test/contracts/src/dancun/TransientStorage.sol
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/moonbase/test-contract/test-eip-6780.ts
  test/suites/dev/moonbase/test-contract/test-eip1153.ts
  test/suites/dev/moonbase/test-eth-tx/test-test-tx-nonce.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-max.ts
  test/suites/dev/moonbase/test-moonbeam-lazy-migrations/test-clear-suicided-contracts.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-clear-suicided-storage.ts
  test/suites/dev/moonbase/test-storage-growth/test-block-storage-growth.ts
  test/suites/dev/moonbase/test-storage-growth/test-evm-create-storage-growth.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, dependencies, breaking

#2816 set the target block fullness to 35%
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  test/helpers/constants.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-max.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-xcm.ts
  test/suites/dev/moonbase/test-fees/test-length-fees.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2818 [Moonriver] Set block gas limit to 30mln
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2820 Update weights
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/pallet_asset_manager.rs
  runtime/common/src/weights/pallet_assets.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_conviction_voting.rs
  runtime/common/src/weights/pallet_crowdloan_rewards.rs
  runtime/common/src/weights/pallet_evm.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/common/src/weights/pallet_moonbeam_orbiters.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_precompile_benchmarks.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_randomness.rs
  runtime/common/src/weights/pallet_referenda.rs
  runtime/common/src/weights/pallet_relay_storage_roots.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_sudo.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_whitelist.rs
  runtime/common/src/weights/pallet_xcm.rs
  runtime/common/src/weights/pallet_xcm_transactor.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-staking/test-rewards-auto-compound-pov.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2771 added Onfinality bootnodes
  specs/alphanet/parachain-embedded-specs-v8.json
  specs/moonbeam/parachain-embedded-specs.json
  specs/moonriver/parachain-embedded-specs.json
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2823 Fix staking smoke test round error
  test/suites/smoke/test-staking-rewards.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive, not-breaking

#2824 Refactor staking reward smoke test
  test/helpers/index.ts
  test/helpers/round.ts
  test/suites/smoke/test-dynamic-fees.ts
  test/suites/smoke/test-staking-rewards.ts
  test/suites/smoke/test-staking-round-cleanup.ts
Labels: B0-silent, D2-notlive, not-breaking

#2831 Fixes dynamic fees change smoke test
  test/helpers/constants.ts
  test/suites/smoke/test-dynamic-fees.ts
Labels: B0-silent, D2-notlive, not-breaking

#2830 Update runtime spec version to 3100
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#2829 Update the client docker image to moonbeamfoundation/moonbeam:v0.38.0
  README.md
Labels: B0-silent, D2-notlive
