Repository moonbeam-foundation/moonbeam, pull requests merged in 2024-09, with the labels that each got.

#2925 evm foreign asset: change_asset_location should not erase already existing location
  pallets/moonbeam-foreign-assets/src/lib.rs
  pallets/moonbeam-foreign-assets/src/tests.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#2927 refactor: move log_entries to Call
  client/evm-tracing/src/formatters/blockscout.rs
  client/evm-tracing/src/formatters/call_tracer.rs
  client/evm-tracing/src/listeners/call_list.rs
Labels: B5-clientnoteworthy, D3-trivial, not-breaking

#2930 fix smoke test auto-pause XCM
  test/suites/smoke/test-xcm-autopause.ts
Labels: B0-silent, D2-notlive

#2929 Divide ref time XCM fees by four
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-max.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-xcm-utils.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-5.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-fees-and-trap.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-4.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-ver-conversion-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-ver-conversion-2.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2931 feat: Enable storage weight reclaiming
  Cargo.lock
  Cargo.toml
  node/service/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-xcm.ts
Labels: B5-clientnoteworthy, D3-trivial, breaking

#2916 Add support for metadata hash extension
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/service/Cargo.toml
  runtime/moonbase/Cargo.toml
  runtime/moonbase/build.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/build.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/build.rs
  runtime/moonriver/src/lib.rs
  scripts/build-runtime-srtool.sh
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/common/test-transaction/test-transaction-with-metadata-hash.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-max.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#2934 Use single quote in BUILD_OPTS (ci)
  scripts/build-runtime-srtool.sh
Labels: B0-silent, ci, D3-trivial

#2935 Fix passing BUILD_OPTS for runtime build
  scripts/build-runtime-srtool.sh
Labels: ci, D2-notlive, D3-trivial

#2936 pass the build settings via the github workflow
  .github/workflows/publish-runtime.yml
  scripts/build-runtime-srtool.sh
Labels: B0-silent, ci, D2-notlive

#2897 add withLog parameter to debug_traceCall
  Cargo.lock
  client/evm-tracing/src/formatters/blockscout.rs
  client/evm-tracing/src/formatters/call_tracer.rs
  client/evm-tracing/src/listeners/call_list.rs
  client/evm-tracing/src/types/single.rs
  client/rpc-core/debug/src/lib.rs
  client/rpc/debug/src/lib.rs
  test/contracts/src/TraceFilter.sol
  test/suites/tracing-tests/test-trace-call.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, I8-enhancement 🎁, D3-trivial, not-breaking

#2922 Add RPC method moon_getEthSyncBlockRange
  Cargo.lock
  client/rpc/finality/src/lib.rs
  precompiles/proxy/src/tests.rs
  precompiles/xcm-utils/src/tests.rs
  test/helpers/assets.ts
  test/suites/dev/moonbase/test-moon/test-moon-rpc.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery5.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D2-notlive, breaking

#2919 Add lazy migration to set evm contract metadata
  Cargo.lock
  pallets/moonbeam-lazy-migrations/Cargo.toml
  pallets/moonbeam-lazy-migrations/src/lib.rs
  pallets/moonbeam-lazy-migrations/src/tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#2840 Lazy loading
  .github/workflow-templates/cargo-build/action.yml
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/cli-opt/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/test_spec.rs
  node/service/src/externalities.rs
  node/service/src/lazy_loading/backend.rs
  node/service/src/lazy_loading/call_executor.rs
  node/service/src/lazy_loading/client.rs
  node/service/src/lazy_loading/helpers.rs
  node/service/src/lazy_loading/mod.rs
  node/service/src/lazy_loading/state_overrides.rs
  node/service/src/lazy_loading/wasm_override.rs
  node/service/src/lazy_loading/wasm_substitutes.rs
  node/service/src/lib.rs
  test/configs/lazyLoadingStateOverrides.json
  test/moonwall.config.json
  test/scripts/prepare-lazy-loading-overrides.ts
  test/suites/lazy-loading/test-runtime-upgrade.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, dependencies, D2-notlive, not-breaking

#2944 Update the client docker image to moonbeamfoundation/moonbeam:v0.40.0
  README.md
Labels: B0-silent, D3-trivial

#2945 Update client version to 0.41.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D3-trivial

#2938 (fix): Send back xcDOT to AssetHub from Moonbeam
  Cargo.lock
  precompiles/xtokens/src/tests.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbase/tests/xcm_mock/statemint_like.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/relay_chain.rs
  runtime/moonbeam/tests/xcm_mock/statemint_like.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/relay_chain.rs
  runtime/moonriver/tests/xcm_mock/statemine_like.rs
  runtime/moonriver/tests/xcm_tests.rs
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2908 Allow to use evm foreign assets to pay XCM fees
  Cargo.lock
  Cargo.toml
  pallets/asset-manager/src/benchmarks.rs
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/tests.rs
  pallets/asset-manager/src/weights.rs
  pallets/moonbeam-foreign-assets/src/lib.rs
  pallets/xcm-weight-trader/Cargo.toml
  pallets/xcm-weight-trader/src/benchmarking.rs
  pallets/xcm-weight-trader/src/lib.rs
  pallets/xcm-weight-trader/src/mock.rs
  pallets/xcm-weight-trader/src/tests.rs
  pallets/xcm-weight-trader/src/weights.rs
  primitives/xcm/src/fee_handlers.rs
  primitives/xcm/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  runtime/common/src/migrations.rs
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_asset_manager.rs
  runtime/common/src/weights/pallet_xcm_weight_trader.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/mod.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/mod.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/mod.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_tests.rs
  test/helpers/assets.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter2.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter3.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#2948 add benchmarks for runtime-3200
  runtime/common/src/weights/cumulus_pallet_parachain_system.rs
  runtime/common/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/common/src/weights/pallet_asset_manager.rs
  runtime/common/src/weights/pallet_assets.rs
  runtime/common/src/weights/pallet_author_inherent.rs
  runtime/common/src/weights/pallet_author_mapping.rs
  runtime/common/src/weights/pallet_author_slot_filter.rs
  runtime/common/src/weights/pallet_balances.rs
  runtime/common/src/weights/pallet_conviction_voting.rs
  runtime/common/src/weights/pallet_crowdloan_rewards.rs
  runtime/common/src/weights/pallet_evm.rs
  runtime/common/src/weights/pallet_identity.rs
  runtime/common/src/weights/pallet_message_queue.rs
  runtime/common/src/weights/pallet_moonbeam_foreign_assets.rs
  runtime/common/src/weights/pallet_moonbeam_lazy_migrations.rs
  runtime/common/src/weights/pallet_moonbeam_orbiters.rs
  runtime/common/src/weights/pallet_multisig.rs
  runtime/common/src/weights/pallet_parachain_staking.rs
  runtime/common/src/weights/pallet_parameters.rs
  runtime/common/src/weights/pallet_precompile_benchmarks.rs
  runtime/common/src/weights/pallet_preimage.rs
  runtime/common/src/weights/pallet_proxy.rs
  runtime/common/src/weights/pallet_randomness.rs
  runtime/common/src/weights/pallet_referenda.rs
  runtime/common/src/weights/pallet_relay_storage_roots.rs
  runtime/common/src/weights/pallet_scheduler.rs
  runtime/common/src/weights/pallet_sudo.rs
  runtime/common/src/weights/pallet_timestamp.rs
  runtime/common/src/weights/pallet_treasury.rs
  runtime/common/src/weights/pallet_utility.rs
  runtime/common/src/weights/pallet_whitelist.rs
  runtime/common/src/weights/pallet_xcm.rs
  runtime/common/src/weights/pallet_xcm_transactor.rs
  runtime/common/src/weights/pallet_xcm_weight_trader.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-xcm.ts
Labels: B0-silent, D3-trivial, not-breaking

#2950 propagate OutOfGas to outer call if caused by proof size check or MBIP5
  Cargo.lock
  test/contracts/src/BloatedContract.sol
  test/contracts/src/SubCallOOG.sol
  test/suites/dev/moonbase/test-gas/test-gas-estimation-subcall-oog.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery4.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D5-nicetohaveaudit⚠️, dependencies, breaking

#2781 test: add regression tests for issues MOON-2822 MOON-2824 MOON-2702
  test/helpers/moonbase-tracing-samples.json
  test/helpers/moonbeam-tracing-samples.json
  test/helpers/moonriver-tracing-samples.json
  test/helpers/runtimes.ts
  test/scripts/get-sample-evm-txs.ts
  test/suites/smoke/test-old-regressions.ts
Labels: B0-silent, D3-trivial

#2951 Update runtime spec version to 3300
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#2949 Schedule recurrent build for benchmarks
  .github/workflows/check-benchmarks.yml
  .github/workflows/publish-runtime.yml
Labels: B0-silent, ci, D2-notlive

#2959 fix: support runtime api Core::initialize_block for old runtimes
  client/rpc/debug/src/lib.rs
  client/rpc/trace/src/lib.rs
Labels: A8-backport, B5-clientnoteworthy, D3-trivial, not-breaking

#2962 fix: increase VARIADIC_MULTIPLE_MAX_SIZE to 1024
  Cargo.lock
Labels: B5-clientnoteworthy, dependencies, D3-trivial, not-breaking

#2955 Update smoke tests for the EVM native assets
  test/helpers/assets.ts
  test/suites/smoke/test-foreign-asset-consistency.ts
Labels: B0-silent, D2-notlive

#2975 Fix inconsistencies in the CI pipeline
  .github/workflow-templates/dev-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/upgrade-typescript-api.yml
  test/configs/zombieAlphanetRpc.json
  test/moonwall.config.json
  test/package.json
  test/pnpm-lock.yaml
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery3.ts
Labels: B0-silent, D2-notlive

#2973 chore: fix some comments
  client/rpc/trace/src/lib.rs
  test/suites/dev/moonbase/test-orbiters/test-orbiters.ts
  test/suites/tracing-tests/test-trace-filter-reorg.ts
Labels: B0-silent, I5-documentation 📄, D2-notlive

#2971 Fix `key` iterator in lazy loading mode
  Cargo.lock
  Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/test_spec.rs
  node/service/src/externalities.rs
  node/service/src/lazy_loading/backend.rs
  node/service/src/lazy_loading/helpers.rs
  node/service/src/lazy_loading/lock.rs
  node/service/src/lazy_loading/mod.rs
Labels: B0-silent, D2-notlive

#2983 fix: propagate error instead of panicking in manual sealing
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#2981 Update the client docker image to moonbeamfoundation/moonbeam:v0.40.1
  README.md
Labels: B0-silent, D3-trivial

#2982 fix warning related to deprecated '--execution' argument
  node/cli/src/command.rs
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#2977 Update node baseline
  .github/workflows/subxt-diff.yml
Labels: A8-mergeoncegreen, B0-silent, ci, D2-notlive

#2978 Enable lazy-loading by default
  .github/workflow-templates/cargo-build/action.yml
  .github/workflows/build.yml
  node/Cargo.toml
  node/cli/src/command.rs
  node/service/src/lazy_loading/backend.rs
  node/service/src/lazy_loading/call_executor.rs
  node/service/src/lazy_loading/helpers.rs
  node/service/src/lazy_loading/mod.rs
  node/service/src/lazy_loading/wasm_override.rs
  test/moonwall.config.json
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D2-notlive, not-breaking

#2942 Tests: add inline snapshots for gas estimation & costs for Randomness
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery5.ts
Labels: A8-mergeoncegreen, B0-silent, D2-notlive
