Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-05, with the labels that each got.

#3258 fix: eth-xcm transactions are not included in the ethereum blocks if EVM revert
  Cargo.lock
  pallets/erc20-xcm-bridge/src/lib.rs
  pallets/ethereum-xcm/Cargo.toml
  pallets/ethereum-xcm/src/lib.rs
  pallets/ethereum-xcm/src/transactional_processor.rs
  pallets/moonbeam-foreign-assets/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/src/xcm_config.rs
  scripts/run-tracing-tests.sh
  test/suites/tracing-tests/test-trace-erc20-xcm.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#3279 Use pallet_ethereum to calculate proof_size_base_cost
  Cargo.lock
  runtime/common/Cargo.toml
  runtime/common/src/apis.rs
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery4.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery5.ts
  test/suites/dev/moonbase/test-storage-growth/test-precompile-storage-growth.ts
Labels: B5-clientnoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#3220 Allow Treasury to spend Foreign Assets
  Cargo.lock
  client/rpc/trace/src/lib.rs
  pallets/moonbeam-foreign-assets/Cargo.toml
  pallets/moonbeam-foreign-assets/src/evm.rs
  pallets/moonbeam-foreign-assets/src/lib.rs
  pallets/xcm-weight-trader/Cargo.toml
  pallets/xcm-weight-trader/src/lib.rs
  primitives/xcm/src/ethereum_xcm.rs
  runtime/common/src/benchmarking.rs
  runtime/common/src/impl_asset_conversion.rs
  runtime/common/src/impl_multiasset_paymaster.rs
  runtime/common/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  test/suites/dev/moonbase/test-treasury/test-treasury-other-assets.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#3293 Fix isolated runtime build
  Cargo.lock
  runtime/common/Cargo.toml
Labels: B0-silent, D2-notlive

#3294 runtime 3800 bump
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#3288 Update the client docker image to moonbeamfoundation/moonbeam:v0.45.0
  README.md
Labels: B0-silent, D3-trivial

#3289 Update client version to 0.46.0
  Cargo.lock
  node/Cargo.toml
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D3-trivial

#3284 remove redundant code from pallets/moonbeam-foreign-assets
  pallets/moonbeam-foreign-assets/src/lib.rs
  runtime/common/src/impl_asset_conversion.rs
  runtime/common/src/impl_multiasset_paymaster.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  test/suites/dev/moonbase/test-treasury/test-treasury-root-origin.ts
Labels: B0-silent, D3-trivial, not-breaking

#3295 Fix pallet identity issue smoke test
  test/suites/smoke/test-balances-consistency.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3297 Remove temporary smoke test
  test/suites/smoke/test-state-v1-migration.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3277 CI: add scout tool
  .github/workflows/scout.yml
Labels: B0-silent, ci, D2-notlive

#3299 Add XCM test for validating transactional outcomes
  test/suites/dev/common/test-xcm/test-transactional-outcomes.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3281 Remove Foreign Asset Migrator Precompile
  Cargo.lock
  Cargo.toml
  precompiles/foreign-asset-migrator/Cargo.toml
  precompiles/foreign-asset-migrator/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/tests/integration_test.rs
  test/suites/dev/moonbase/test-pov/test-precompile-over-pov2.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3300 Use MaintenanceMode pallet as FailedMigrationHandler
  Cargo.lock
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking
