Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-04, with the labels that each got.

#3246 Update rpc urls in moonwall.config.json
  test/moonwall.config.json
Labels: B0-silent, D2-notlive

#3237 Fix "Update Rust/TS bindings" workflow
  .github/workflows/build.yml
  .github/workflows/subxt-diff.yml
  .github/workflows/update-typescript-api.yml
  typescript-api/scripts/scrapeMetadata.ts
Labels: B0-silent, ci, D2-notlive

#3227 Update frontier to address pov underestimations
  Cargo.lock
  runtime/common/src/apis.rs
  test/helpers/block.ts
  test/suites/dev/moonbase/test-parameters/test-parameters-runtime-FeesTreasuryProportion.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-assets-erc20d.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery4.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery5.ts
  test/suites/dev/moonbase/test-storage-growth/test-precompile-storage-growth.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-12.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#3251 Update test-old-regressions.ts to use tracing endpoints
  test/suites/smoke/test-old-regressions.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3253 Fix incorrect CLI parameter description
  node/cli/src/cli.rs
Labels: B0-silent, D2-notlive

#3254 Fix test eth rpc pending transactions
  .github/workflow-templates/cargo-build/action.yml
  test/suites/dev/moonbase/test-eth-rpc/test-eth-rpc-pending-transactions.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3250 Add block range validation to eth_getLogs RPC
  Cargo.lock
  node/cli-opt/src/lib.rs
  node/cli/src/cli.rs
  node/service/src/lazy_loading/mod.rs
  node/service/src/lib.rs
  node/service/src/rpc.rs
  test/suites/tracing-tests/test-get-logs-limit.ts
Labels: B5-clientnoteworthy, dependencies, D2-notlive, breaking

#3264 readme/fix: polkadot/technology broken link
  README.md
Labels: B0-silent, D2-notlive

#3263 Temporarily clone bridge pallets and primitives
  Cargo.lock
  Cargo.toml
  pallets/xcm-bridge-router/Cargo.toml
  pallets/xcm-bridge-router/src/benchmarking.rs
  pallets/xcm-bridge-router/src/impls.rs
  pallets/xcm-bridge-router/src/lib.rs
  pallets/xcm-bridge-router/src/mock.rs
  pallets/xcm-bridge-router/src/tests.rs
  pallets/xcm-bridge-router/src/weights.rs
  pallets/xcm-bridge/Cargo.toml
  pallets/xcm-bridge/src/benchmarking.rs
  pallets/xcm-bridge/src/congestion.rs
  pallets/xcm-bridge/src/dispatcher.rs
  pallets/xcm-bridge/src/exporter.rs
  pallets/xcm-bridge/src/lib.rs
  pallets/xcm-bridge/src/migration.rs
  pallets/xcm-bridge/src/mock.rs
  pallets/xcm-bridge/src/tests.rs
  pallets/xcm-bridge/src/weights.rs
  primitives/bridge/xcm-bridge-router/Cargo.toml
  primitives/bridge/xcm-bridge-router/src/lib.rs
  primitives/bridge/xcm-bridge/Cargo.toml
  primitives/bridge/xcm-bridge/src/call_info.rs
  primitives/bridge/xcm-bridge/src/lib.rs
Labels: B0-silent, D2-notlive, not-breaking

#3260 docs: added a link to the build badge
  README.md
Labels: B0-silent, D2-notlive

#3266 backport fix to perm-client-v0.44.1
  .github/workflow-templates/cargo-build/action.yml
  .github/workflows/build.yml
  Cargo.lock
  node/cli-opt/src/lib.rs
  node/cli/src/cli.rs
  node/service/src/lazy_loading/mod.rs
  node/service/src/lib.rs
  node/service/src/rpc.rs
  test/suites/tracing-tests/test-get-logs-limit.ts
Labels: B5-clientnoteworthy, D2-notlive, breaking

#3261 feat(Moonbeam): Increase PoV limit to 10 MB
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#3270 Fix publish-binary.yml
  .github/workflow-templates/build-prod-binary/action.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker-runtime.yml
Labels: B0-silent, ci, D2-notlive

#3262 Improvements: make the EvmProxyCallFilter::Any consistent on all runtimes
  precompiles/proxy/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/src/precompiles.rs
  test/suites/dev/moonbase/test-gas/test-gas-estimation-subcall-oog.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-proxy.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-smart-contract-call4.ts
  test/suites/dev/moonbase/test-storage-growth/test-precompile-storage-growth.ts
Labels: B0-silent, D3-trivial, breaking

#3274 Remove left over migration code
  pallets/moonbeam-lazy-migrations/src/lib.rs
Labels: B0-silent, D2-notlive, not-breaking
