Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-02, with the labels that each got.

#3162 Fix typos
  RELEASE.md
  pallets/parachain-staking/migrations.md
  runtime-diffs/README.md
  tools/pov/README.md
  types-bundle/README.md
Labels: B0-silent, D2-notlive

#3172 Update ERC20_CREATE_GAS_LIMIT
  pallets/moonbeam-foreign-assets/src/evm.rs
Labels: B0-silent, D3-trivial, not-breaking

#3134 Test :test_tube:: add accessList gas cost tests
  test/contracts/src/AccessListHelper.sol
  test/suites/dev/moonbase/test-eth-tx/test-eth-tx-access-list.ts
Labels: B0-silent, D2-notlive

#3129 CI :chart_with_upwards_trend:: Add workflow for checking changes to weights in all runtimes
  .github/workflows/weight-diff-report.yml
Labels: B0-silent, ci, D2-notlive

#3182 Update the client docker image to moonbeamfoundation/moonbeam:v0.43.0
  README.md
Labels: B0-silent, D3-trivial

#3186 Fix local chain specs
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  test/scripts/modify-plain-specs.ts
Labels: A8-mergeoncegreen, B5-clientnoteworthy, D3-trivial, not-breaking

#3183 bump @moonbeam-network/api-augment version to 0.3500.0
  typescript-api/package.json
Labels: A8-mergeoncegreen, B0-silent, D2-notlive

#3178 fix subxt-diff
  .github/workflows/subxt-diff.yml
Labels: A8-mergeoncegreen, B0-silent, ci, D2-notlive

#3180 CI :truck:: Fix Weight Diff report
  .github/workflows/weight-diff-report.yml
Labels: A8-mergeoncegreen, B0-silent, ci, D2-notlive

#3189 chore(ci): fix zombienet tests
  test/scripts/modify-plain-specs.ts
Labels: B0-silent, ci, D2-notlive

#3190 Fix foreign assets migration
  pallets/moonbeam-foreign-assets/src/evm.rs
  pallets/moonbeam-foreign-assets/src/lib.rs
  pallets/moonbeam-lazy-migrations/src/benchmarks.rs
  pallets/moonbeam-lazy-migrations/src/foreign_asset.rs
  pallets/moonbeam-lazy-migrations/src/lib.rs
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-12.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3200 Update copyright year in file_header.txt
  file_header.txt
Labels: B0-silent, D2-notlive
