Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-06, with the labels that each got.

#3307 :sparkles: Update pallet benchmarks to use v2 syntax
  pallets/asset-manager/src/benchmarks.rs
  pallets/moonbeam-lazy-migrations/src/benchmarks.rs
  pallets/moonbeam-orbiters/src/benchmarks.rs
  pallets/moonbeam-xcm-benchmarks/src/generic/benchmarking.rs
  pallets/parachain-staking/src/benchmarks.rs
  pallets/precompile-benchmarks/src/benchmarks.rs
  pallets/xcm-transactor/src/benchmarks.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3309 Validate depth limit decoding in XCM transact instruction
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3310 CI: benchmarking improvement
  .github/workflows/check-benchmarks.yml
  Cargo.lock
  runtime/moonbase/src/governance/councils.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/weights/mod.rs
  runtime/moonbase/src/weights/pallet_collective_open_tech_committee_collective.rs
  runtime/moonbase/src/weights/pallet_collective_treasury_council_collective.rs
  runtime/moonbeam/src/governance/councils.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/weights/mod.rs
  runtime/moonbeam/src/weights/pallet_collective_open_tech_committee_collective.rs
  runtime/moonbeam/src/weights/pallet_collective_treasury_council_collective.rs
  runtime/moonriver/src/governance/councils.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/weights/mod.rs
  runtime/moonriver/src/weights/pallet_collective_open_tech_committee_collective.rs
  runtime/moonriver/src/weights/pallet_collective_treasury_council_collective.rs
Labels: B0-silent, ci, D2-notlive

#3308 state_traceBlock: replay the block with proof recording
  Cargo.lock
  test/suites/dev/common/test-block/test-block-trace.ts
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#3312 Re-enable lazy-loading tests
  .github/workflows/build.yml
  node/service/src/lazy_loading/backend.rs
  node/service/src/lazy_loading/mod.rs
Labels: B0-silent, I4-tests 🎯, ci, D2-notlive, lazy-loading

#3314 Add cli option -max-pov-percentage <percent>
  Cargo.lock
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/lib.rs
  test/moonwall.config.json
Labels: B5-clientnoteworthy, D2-notlive, breaking

#3327 GMP precompile: manually support XCM MultiLocation V1 for backward compatibility
  precompiles/gmp/src/types.rs
  test/suites/dev/moonbase/test-precompile/test-precompile-wormhole.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3333 test: call xcm-transactor v3 from smart-contract
  test/contracts/src/XcmTransactorCaller.sol
  test/suites/dev/moonbase/test-precompile/test-precompile-xcm-transactor12.ts
Labels: A8-mergeoncegreen, B0-silent, I4-tests 🎯, D2-notlive

#3324 Remove Foreign Assets migrations from Lazy Migrations pallet
  Cargo.lock
  pallets/moonbeam-lazy-migrations/Cargo.toml
  pallets/moonbeam-lazy-migrations/src/benchmarks.rs
  pallets/moonbeam-lazy-migrations/src/foreign_asset.rs
  pallets/moonbeam-lazy-migrations/src/lib.rs
  pallets/moonbeam-lazy-migrations/src/mock.rs
  pallets/moonbeam-lazy-migrations/src/tests.rs
  precompiles/assets-erc20/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/suites/dev/moonbase/test-moonbeam-lazy-migrations/test-foreign-assets-migration.ts
  test/suites/tracing-tests/test-multiple-traces-per-substrate-tx.ts
Labels: A8-mergeoncegreen, B7-runtimenoteworthy, D3-trivial, not-breaking
