Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-08, with the labels that each got.

#3375 Feat :rocket: Support frontier backend in lazy loading mode
  Cargo.lock
  Cargo.toml
  node/service/Cargo.toml
  node/service/src/lazy_loading/frontier_backend.rs
  node/service/src/lazy_loading/helpers.rs
  node/service/src/lazy_loading/mod.rs
  node/service/src/lazy_loading/rpc_client.rs
  node/service/src/lazy_loading/substrate_backend.rs
Labels: B5-clientnoteworthy, D2-notlive, not-breaking, lazy-loading

#3378 Fix moonlama smoke tests
  test/helpers/foreign-chains.ts
  test/suites/smoke/test-eth-parent-hash-bad-block-fix.ts
  test/suites/smoke/test-relay-xcm-fees.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3386 chore: update GitHub actions in CI workflows
  .github/workflows/build.yml
  .github/workflows/check-benchmarks.yml
  .github/workflows/check-licenses.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker-runtime.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-runtime.yml
  .github/workflows/publish-types-bundle.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/scout.yml
  .github/workflows/subxt-diff.yml
  .github/workflows/update-typescript-api.yml
  .github/workflows/version-bump.yml
  .github/workflows/weight-diff-report.yml
Labels: B0-silent, ci, D2-notlive

#3090 Deprecate generate-account-key in favour of generate-moonbeam-key
  Cargo.lock
  Cargo.toml
  bin/utils/moonkey/Cargo.toml
  bin/utils/moonkey/src/main.rs
  node/cli-opt/src/account_key.rs
  node/cli/Cargo.toml
  node/cli/src/cli.rs
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#3392 Foreign Assets Tests: update `dev/test-xcm-v4` to use new foreign assets
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-2.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-3.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-4.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-5.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-6.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-10.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-4.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-5.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-6.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-7.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-8.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-erc20-transfer-two-ERC20.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-erc20-transfer.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-evm-fee-with-origin-token.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-evm-with-dot.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api-transact-foreign.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api-transact-native.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-ver-conversion-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-ver-conversion-2.ts
Labels: B0-silent, D2-notlive

#3389 :scissors: Remove parachain staking deprecated code
  pallets/parachain-staking/src/benchmarks.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  pallets/parachain-staking/src/weights.rs
  runtime/moonbase/src/weights/pallet_parachain_staking.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/weights/pallet_parachain_staking.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/weights/pallet_parachain_staking.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-preimage/test-preimage.ts
  test/suites/dev/moonbase/test-referenda/test-referenda-submit.ts
  test/suites/dev/moonbase/test-staking/test-inflation-distribution-config.ts
  test/suites/dev/moonbase/test-staking/test-parachain-bond.ts
  test/suites/dev/moonbase/test-sudo/test-sudo.ts
  typescript-api/src/moonbase/interfaces/lookup.ts
  typescript-api/src/moonbeam/interfaces/lookup.ts
  typescript-api/src/moonriver/interfaces/lookup.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#3399 Remove old lazy migration from pallet staking
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/tests.rs
  typescript-api/src/moonbase/interfaces/lookup.ts
  typescript-api/src/moonbeam/interfaces/lookup.ts
  typescript-api/src/moonriver/interfaces/lookup.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3405 Fix broken link in README.md and increase the timeout on bridge tests
  README.md
  zombienet/integration-tests/bridges/tests/0001-moonbeam-moonriver-asset-transfer/run.sh
Labels: B0-silent, D2-notlive

#3406 Use new foreign assets for `pallet_xcm` benchmarking
  pallets/moonbeam-foreign-assets/src/benchmarks.rs
  pallets/moonbeam-foreign-assets/src/lib.rs
  runtime/common/src/apis.rs
  runtime/moonbeam/src/genesis_config_preset.rs
  runtime/moonriver/src/genesis_config_preset.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3402 Pallet XCM - transfer_assets pre-ahm patch
  Cargo.lock
  pallets/xcm-weight-trader/src/lib.rs
  runtime/moonbase/src/migrations.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/src/migrations.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/src/migrations.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_tests.rs
  test/helpers/assets.ts
  test/suites/dev/moonbase/test-assets/test-foreign-assets-change-xcm-location.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-pallet-xcm-2.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-pallet-xcm.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking
