Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-10, with the labels that each got.

#3476 smoke-tests: cleanup old hrmp channels
  pnpm-lock.yaml
  test/helpers/foreign-chains.ts
  test/package.json
Labels: B0-silent, D2-notlive

#3481 Update `polkadot-sdk`
  Cargo.lock
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#3485 Update the client docker image to moonbeamfoundation/moonbeam:v0.47.2
  README.md
Labels: B0-silent, D2-notlive, D3-trivial

#3366 Fix Typos in Documentation and Comments
  runtime/moonriver/tests/xcm_tests.rs
Labels: B0-silent, D2-notlive, suspicious-contribution

#3484 refactor: 📦️ Update Packages
  .gitignore
  biome.json
  package.json
  pnpm-lock.yaml
  test/.gitignore
  test/biome.json
  test/moonwall.config.json
  test/package.json
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter.ts
  types-bundle/package.json
  typescript-api/package.json
Labels: B0-silent, D2-notlive
