Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-01, with the labels that each got.

#3065 test(smoke): fix inflation distribution calculation
  test/suites/smoke/test-staking-rewards.ts
Labels: B0-silent, D2-notlive

#3107 Add more TS tests for pallet-xcm precompile
  runtime/moonbase/src/precompiles.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonriver/src/precompiles.rs
  test/helpers/assets.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-pallet-xcm-2.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-pallet-xcm.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3113 Make xcm config index friendly
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#3126 Test/Smoke 💨: mute Moonriver 2085 parachain for 2 months
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#3066 Lazy loading improvements
  node/service/src/lazy_loading/backend.rs
  node/service/src/lazy_loading/helpers.rs
  node/service/src/lazy_loading/manual_sealing.rs
  node/service/src/lazy_loading/mod.rs
  test/suites/lazy-loading/test-runtime-upgrade.ts
Labels: B0-silent, D2-notlive, not-breaking, lazy-loading

#3120 Send priority fees to collators
  runtime/common/src/deal_with_fees.rs
  runtime/common/src/impl_on_charge_evm_transaction.rs
  runtime/common/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/common/mod.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbase/tests/runtime_apis.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  test/helpers/block.ts
  test/helpers/fees.ts
  test/helpers/index.ts
  test/helpers/parameters.ts
  test/scripts/update-local-types.ts
  test/suites/dev/moonbase/test-balance/test-balance-transfer.ts
  test/suites/dev/moonbase/test-contract/test-contract-error.ts
  test/suites/dev/moonbase/test-eth-pool/test-eth-pool-error.ts
  test/suites/dev/moonbase/test-eth-pool/test-eth-pool-resubmit-txn.ts
  test/suites/dev/moonbase/test-fees/test-fees-repartition.ts
  test/suites/dev/moonbase/test-parameters/test-parameters-runtime-FeesTreasuryProportion.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-xtokens.ts
Labels: B7-runtimenoteworthy, D9-needsaudit👮, not-breaking

#3131 Remove any XCM v2 reference in codebase
  pallets/xcm-transactor/src/mock.rs
  runtime/moonbase/tests/xcm_tests.rs
  runtime/moonbeam/tests/xcm_tests.rs
  runtime/moonriver/tests/xcm_tests.rs
  test/helpers/xcm.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-dmp-error-and-appendix-1.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-dmp-error-and-appendix-2.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-dmp-error-and-appendix-3.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-dmp-error-and-appendix-4.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-dmp-error-and-appendix-5.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-dmp-error-and-appendix-6.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-2.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-3.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-4.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-5.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-6.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-asset-transfer-8.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-3.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-excess-gas.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-fees-and-trap.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-v3-filter.ts
  test/suites/dev/moonbase/test-xcm-v3/test-xcm-erc20-v3.ts
  test/suites/dev/moonbase/test-xcm-v4/test-auto-pause-xcm.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-dmp-error-and-appendix-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-dmp-error-and-appendix-2.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-dmp-error-and-appendix-3.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-dmp-error-and-appendix-4.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-dmp-error-and-appendix-5.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-dmp-error-and-appendix-6.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-2.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-3.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-4.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-5.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-asset-transfer-6.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-dry-run-api.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-erc20-transfer-two-ERC20.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-erc20-transfer.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-ver-conversion-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-ver-conversion-2.ts
  test/suites/tracing-tests/test-trace-erc20-xcm.ts
Labels: B0-silent, D2-notlive, not-breaking

#3133 Update spec version to 3401
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: A8-mergeoncegreen, B0-silent, D3-trivial, not-breaking

#3137 Smoke tests :test_tube:: remove Khala & Polkadex parachains
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive

#3130 Fix treasury spend origin
  runtime/moonbase/src/lib.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-treasury/test-treasury-council-origin.ts
  test/suites/dev/moonbase/test-treasury/test-treasury-pallet.ts
  test/suites/dev/moonbase/test-treasury/test-treasury-root-origin.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#3132 update spend origin
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, not-breaking

#3140 Update NonTransfer proxy filter
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/suites/dev/moonbase/test-proxy/test-proxy-identity.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#3141 Update NonTransfer proxy filter
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  test/suites/dev/moonbase/test-proxy/test-proxy-identity.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#3145 chore(ci): enable typegen_check
  .github/workflows/update-typescript-api.yml
  typescript-api/scripts/scrapeMetadata.ts
Labels: B0-silent, D2-notlive

#3147 Release process tweaks
  .github/workflows/subxt-diff.yml
  tools/github/print-client-release-issue.ts
  tools/github/print-runtime-release-issue.ts
Labels: B0-silent, D2-notlive

#3138 Add genesis config presets to runtime
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  client/evm-tracing/Cargo.toml
  client/rpc-core/debug/Cargo.toml
  client/rpc-core/trace/Cargo.toml
  client/rpc-core/txpool/Cargo.toml
  client/rpc-core/types/Cargo.toml
  node/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  node/service/src/chain_spec/moonbase.rs
  node/service/src/chain_spec/moonbeam.rs
  node/service/src/chain_spec/moonriver.rs
  node/service/src/chain_spec/test_spec.rs
  node/service/src/lazy_loading/backend.rs
  node/service/src/lib.rs
  pallets/xcm-transactor/src/lib.rs
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/genesis_config_preset.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/genesis_config_preset.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/genesis_config_preset.rs
  runtime/moonriver/src/lib.rs
  scripts/run-benches-for-runtime.sh
Labels: B5-clientnoteworthy, B7-runtimenoteworthy, D3-trivial, not-breaking

#3155 chore: 📦️ Update PolkadotJS Versions
  .github/workflows/publish-types-bundle.yml
  moonbeam-types-bundle/package.json
  package.json
  pnpm-lock.yaml
  test/package.json
  typescript-api/package.json
  typescript-api/src/moonbase/interfaces/augment-types.ts
  typescript-api/src/moonbeam/interfaces/augment-types.ts
  typescript-api/src/moonriver/interfaces/augment-types.ts
Labels: B0-silent, D2-notlive

#3150 CI Improvements
  .github/workflow-templates/build-prod-binary/action.yml
  .github/workflow-templates/cargo-build/action.yml
  .github/workflow-templates/publish-docker/action.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/prepare-binary.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-docker-runtime.yml
  .github/workflows/publish-docker.yml
  .github/workflows/subxt-diff.yml
  docker/moonbase-parachain.Dockerfile
  docker/moonbeam-production.Dockerfile
  docker/moonbeam-release.Dockerfile
  docker/moonbeam.Dockerfile
  docker/polkadot-relay.Dockerfile
Labels: B0-silent, ci, D2-notlive

#3117 fix: multiple typos of different importance
  .github/PULL_REQUEST_TEMPLATE.md
  client/evm-tracing/src/listeners/raw.rs
  client/rpc/debug/README.md
  client/rpc/debug/src/lib.rs
  client/rpc/dev/src/lib.rs
  client/rpc/trace/src/lib.rs
Labels: B0-silent, I5-documentation 📄, D2-notlive, suspicious-contribution

#3163 Remove feature `moonbase-runtime-benchmarks`
  .cargo/config.toml
  node/Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/command.rs
  node/service/Cargo.toml
  runtime/moonbase/Cargo.toml
Labels: B0-silent, D3-trivial

#3160 refactor: :package: Update moonbeam-types-bundle
  .github/workflows/publish-types-bundle.yml
  moonbeam-types-bundle/README.md
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/helpers/common.ts
  test/helpers/xcm.ts
  test/package.json
  test/scripts/fast-execute-chopstick-proposal.ts
  test/scripts/update-local-types.ts
  test/suites/dev/moonbase/test-assets/test-assets-transfer.ts
  test/suites/dev/moonbase/test-moon/test-moon-rpc.ts
  test/suites/dev/moonbase/test-moonbeam-lazy-migrations/test-foreign-assets-migration.ts
  test/suites/dev/moonbase/test-referenda/test-referenda-fast-general-admin.ts
  test/suites/dev/moonbase/test-referenda/test-referenda-general-admin.ts
  test/suites/dev/moonbase/test-staking/test-delegate-with-auto-compound2.ts
  test/suites/dev/moonbase/test-staking/test-delegate-with-auto-compound3.ts
  test/suites/dev/moonbase/test-staking/test-delegate-with-auto-compound4.ts
  test/suites/dev/moonbase/test-staking/test-delegate-with-auto-compound5.ts
  test/suites/dev/moonbase/test-staking/test-delegate-with-auto-compound6.ts
  test/suites/smoke/test-balances-consistency.ts
  test/suites/smoke/test-block-finalized.ts
  test/suites/smoke/test-block-weights.ts
  test/suites/smoke/test-relay-indices.ts
  test/suites/smoke/test-staking-round-cleanup.ts
  tools/test-scripts/test-alpha.ts
  tools/test-scripts/test-staking.ts
  types-bundle/.gitignore
  types-bundle/README.md
  types-bundle/package.json
  types-bundle/src/definitions.ts
  types-bundle/src/rpc.ts
  types-bundle/src/types.ts
  types-bundle/tsconfig.json
  typescript-api/package.json
  typescript-api/src/moonbase/interfaces/augment-api-query.ts
  typescript-api/src/moonbase/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbase/interfaces/moon/definitions.ts
  typescript-api/src/moonbase/tsconfig.json
  typescript-api/src/moonbeam/interfaces/augment-api-query.ts
  typescript-api/src/moonbeam/interfaces/augment-api-rpc.ts
  typescript-api/src/moonbeam/interfaces/moon/definitions.ts
  typescript-api/src/moonbeam/tsconfig.json
  typescript-api/src/moonriver/interfaces/augment-api-query.ts
  typescript-api/src/moonriver/interfaces/augment-api-rpc.ts
  typescript-api/src/moonriver/interfaces/moon/definitions.ts
  typescript-api/src/moonriver/tsconfig.json
Labels: B0-silent, D2-notlive

#3159 feat(gov): normalize FastGeneralAdmin track origin for creating new foreign assets
  runtime/moonbase/src/governance/referenda.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbeam/src/governance/referenda.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonriver/src/governance/referenda.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking
