Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-09, with the labels that each got.

#3413 Bump @moonbeam-network/api-augment version
  typescript-api/package.json
Labels: B0-silent, D2-notlive

#3420 chore: fix broken link
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D2-notlive

#3421 Fix moonbeam smoke test
  pnpm-lock.yaml
  test/helpers/foreign-chains.ts
  test/package.json
Labels: B0-silent, I4-tests 🎯, D3-trivial

#3411 Cherry-pick pre AssetHub migration changes
  Cargo.lock
  precompiles/gmp/src/mock.rs
  precompiles/xcm-utils/src/mock.rs
  precompiles/xtokens/src/mock.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbase/tests/xcm_mock/relay_chain.rs
  runtime/moonbase/tests/xcm_mock/statemint_like.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonbeam/tests/xcm_mock/relay_chain.rs
  runtime/moonbeam/tests/xcm_mock/statemint_like.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  runtime/moonriver/tests/xcm_mock/relay_chain.rs
  runtime/moonriver/tests/xcm_mock/statemine_like.rs
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#3422 Fix benchmarks
  runtime/common/src/apis.rs
Labels: B0-silent, D2-notlive

#3419 Remove `asset-manager` from all runtimes
  pallets/asset-manager/src/lib.rs
  primitives/xcm/src/asset_id_conversions.rs
  runtime/common/src/apis.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/src/weights/mod.rs
  runtime/moonbase/src/weights/pallet_asset_manager.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/asset_config.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/src/weights/mod.rs
  runtime/moonbeam/src/weights/pallet_asset_manager.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/src/weights/mod.rs
  runtime/moonriver/src/weights/pallet_asset_manager.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  test/suites/dev/moonbase/test-pov/test-precompile-over-pov2.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#3426 📏 Update Moonbeam weights - Runtime 3900
  runtime/moonbeam/src/weights/cumulus_pallet_parachain_system.rs
  runtime/moonbeam/src/weights/cumulus_pallet_weight_reclaim.rs
  runtime/moonbeam/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/moonbeam/src/weights/frame_system.rs
  runtime/moonbeam/src/weights/frame_system_extensions.rs
  runtime/moonbeam/src/weights/pallet_assets.rs
  runtime/moonbeam/src/weights/pallet_author_inherent.rs
  runtime/moonbeam/src/weights/pallet_author_mapping.rs
  runtime/moonbeam/src/weights/pallet_author_slot_filter.rs
  runtime/moonbeam/src/weights/pallet_balances.rs
  runtime/moonbeam/src/weights/pallet_bridge_grandpa.rs
  runtime/moonbeam/src/weights/pallet_bridge_messages.rs
  runtime/moonbeam/src/weights/pallet_bridge_parachains.rs
  runtime/moonbeam/src/weights/pallet_collective_open_tech_committee_collective.rs
  runtime/moonbeam/src/weights/pallet_collective_treasury_council_collective.rs
  runtime/moonbeam/src/weights/pallet_conviction_voting.rs
  runtime/moonbeam/src/weights/pallet_crowdloan_rewards.rs
  runtime/moonbeam/src/weights/pallet_evm.rs
  runtime/moonbeam/src/weights/pallet_identity.rs
  runtime/moonbeam/src/weights/pallet_message_queue.rs
  runtime/moonbeam/src/weights/pallet_migrations.rs
  runtime/moonbeam/src/weights/pallet_moonbeam_foreign_assets.rs
  runtime/moonbeam/src/weights/pallet_moonbeam_orbiters.rs
  runtime/moonbeam/src/weights/pallet_multisig.rs
  runtime/moonbeam/src/weights/pallet_parachain_staking.rs
  runtime/moonbeam/src/weights/pallet_parameters.rs
  runtime/moonbeam/src/weights/pallet_precompile_benchmarks.rs
  runtime/moonbeam/src/weights/pallet_preimage.rs
  runtime/moonbeam/src/weights/pallet_proxy.rs
  runtime/moonbeam/src/weights/pallet_randomness.rs
  runtime/moonbeam/src/weights/pallet_referenda.rs
  runtime/moonbeam/src/weights/pallet_relay_storage_roots.rs
  runtime/moonbeam/src/weights/pallet_scheduler.rs
  runtime/moonbeam/src/weights/pallet_timestamp.rs
  runtime/moonbeam/src/weights/pallet_transaction_payment.rs
  runtime/moonbeam/src/weights/pallet_treasury.rs
  runtime/moonbeam/src/weights/pallet_utility.rs
  runtime/moonbeam/src/weights/pallet_whitelist.rs
  runtime/moonbeam/src/weights/pallet_xcm.rs
  runtime/moonbeam/src/weights/pallet_xcm_transactor.rs
  runtime/moonbeam/src/weights/pallet_xcm_weight_trader.rs
  runtime/moonbeam/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking, weights-updates

#3425 📏 Update Moonriver weights - Runtime 3900
  runtime/moonriver/src/weights/cumulus_pallet_parachain_system.rs
  runtime/moonriver/src/weights/cumulus_pallet_weight_reclaim.rs
  runtime/moonriver/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/moonriver/src/weights/frame_system.rs
  runtime/moonriver/src/weights/frame_system_extensions.rs
  runtime/moonriver/src/weights/pallet_assets.rs
  runtime/moonriver/src/weights/pallet_author_inherent.rs
  runtime/moonriver/src/weights/pallet_author_mapping.rs
  runtime/moonriver/src/weights/pallet_author_slot_filter.rs
  runtime/moonriver/src/weights/pallet_balances.rs
  runtime/moonriver/src/weights/pallet_bridge_grandpa.rs
  runtime/moonriver/src/weights/pallet_bridge_messages.rs
  runtime/moonriver/src/weights/pallet_bridge_parachains.rs
  runtime/moonriver/src/weights/pallet_collective_open_tech_committee_collective.rs
  runtime/moonriver/src/weights/pallet_collective_treasury_council_collective.rs
  runtime/moonriver/src/weights/pallet_conviction_voting.rs
  runtime/moonriver/src/weights/pallet_crowdloan_rewards.rs
  runtime/moonriver/src/weights/pallet_evm.rs
  runtime/moonriver/src/weights/pallet_identity.rs
  runtime/moonriver/src/weights/pallet_message_queue.rs
  runtime/moonriver/src/weights/pallet_migrations.rs
  runtime/moonriver/src/weights/pallet_moonbeam_foreign_assets.rs
  runtime/moonriver/src/weights/pallet_moonbeam_orbiters.rs
  runtime/moonriver/src/weights/pallet_multisig.rs
  runtime/moonriver/src/weights/pallet_parachain_staking.rs
  runtime/moonriver/src/weights/pallet_parameters.rs
  runtime/moonriver/src/weights/pallet_precompile_benchmarks.rs
  runtime/moonriver/src/weights/pallet_preimage.rs
  runtime/moonriver/src/weights/pallet_proxy.rs
  runtime/moonriver/src/weights/pallet_randomness.rs
  runtime/moonriver/src/weights/pallet_referenda.rs
  runtime/moonriver/src/weights/pallet_relay_storage_roots.rs
  runtime/moonriver/src/weights/pallet_scheduler.rs
  runtime/moonriver/src/weights/pallet_timestamp.rs
  runtime/moonriver/src/weights/pallet_transaction_payment.rs
  runtime/moonriver/src/weights/pallet_treasury.rs
  runtime/moonriver/src/weights/pallet_utility.rs
  runtime/moonriver/src/weights/pallet_whitelist.rs
  runtime/moonriver/src/weights/pallet_xcm.rs
  runtime/moonriver/src/weights/pallet_xcm_transactor.rs
  runtime/moonriver/src/weights/pallet_xcm_weight_trader.rs
  runtime/moonriver/tests/integration_test.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking, weights-updates

#3434 Update runtime spec version to 4000
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial

#3436 Bump @moonbeam-network/api-augment to version 0.4000.0
  typescript-api/package.json
Labels: B0-silent, D2-notlive

#3438 Upgrade deprecated CI actions
  .github/workflows/publish-binary.yml
  .github/workflows/publish-runtime.yml
Labels: B0-silent, ci, D2-notlive

#3423 Remove `pallet-assets` from all runtimes
  Cargo.lock
  Cargo.toml
  precompiles/assets-erc20/Cargo.toml
  precompiles/assets-erc20/ERC20.sol
  precompiles/assets-erc20/Permit.sol
  precompiles/assets-erc20/Roles.sol
  precompiles/assets-erc20/src/eip2612.rs
  precompiles/assets-erc20/src/lib.rs
  precompiles/assets-erc20/src/mock.rs
  precompiles/assets-erc20/src/tests.rs
  primitives/xcm/src/get_by_key.rs
  primitives/xcm/src/lib.rs
  runtime/moonbase/Cargo.toml
  runtime/moonbase/src/asset_config.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/precompiles.rs
  runtime/moonbase/src/weights/mod.rs
  runtime/moonbase/src/weights/pallet_assets.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/Cargo.toml
  runtime/moonbeam/src/asset_config.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/precompiles.rs
  runtime/moonbeam/src/weights/mod.rs
  runtime/moonbeam/src/weights/pallet_assets.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/Cargo.toml
  runtime/moonriver/src/asset_config.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/precompiles.rs
  runtime/moonriver/src/weights/mod.rs
  runtime/moonriver/src/weights/pallet_assets.rs
  runtime/moonriver/tests/integration_test.rs
  test/contracts/src/ERC20Instance.sol
  test/contracts/src/ERC20WithInitialSupply.sol
  test/suites/dev/moonbase/test-pov/test-precompile-over-pov2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery4.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery5.ts
  test/suites/dev/moonbase/test-storage-growth/test-precompile-storage-growth.ts
  test/suites/dev/moonbeam/test-precompile/test-precompile-assets-erc20-local-assets-removal.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#3443 Update GitHub Actions setup-node to v5
  .github/workflows/build.yml
  .github/workflows/client-release-issue.yml
  .github/workflows/publish-binary.yml
  .github/workflows/publish-types-bundle.yml
  .github/workflows/publish-typescript-api.yml
  .github/workflows/runtime-release-issue.yml
  .github/workflows/update-typescript-api.yml
  .github/workflows/version-bump.yml
Labels: B0-silent, ci, D2-notlive

#3446 Fix zombienet test flakiness
  test/suites/zombie/test_para.ts
Labels: B0-silent, ci, D2-notlive

#3451 Properly await Vitest assertions
  test/suites/dev/common/test-block/test-block-gas.ts
  test/suites/dev/common/test-precompile/test-precompile-proxy.ts
  test/suites/dev/moonbase/test-contract/test-contract-methods.ts
  test/suites/dev/moonbase/test-eth-pool/test-eth-pool-discard.ts
  test/suites/dev/moonbase/test-eth-pool/test-eth-pool-error.ts
  test/suites/dev/moonbase/test-eth-rpc/test-eth-rpc-deprecated.ts
  test/suites/dev/moonbase/test-eth-rpc/test-eth-rpc-tx-index.ts
  test/suites/dev/moonbase/test-eth-tx/test-eth-tx-size.ts
  test/suites/dev/moonbase/test-gas/test-gas-estimation-contracts.ts
  test/suites/dev/moonbase/test-gas/test-gas-estimation-multiply.ts
  test/suites/dev/moonbase/test-maintenance/test-maintenance-filter.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-ecrecover.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-erc20-overflow.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-preimage.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-referenda.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-revert-attack.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-smart-contract-call.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-smart-contract-call3.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-smart-contract-call4.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-smart-contract-call5.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-xcm-utils.ts
  test/suites/dev/moonbase/test-staking/test-delegate-with-auto-compound.ts
  test/suites/dev/moonbase/test-staking/test-set-auto-compound3.ts
  test/suites/dev/moonbase/test-sudo/test-sudo.ts
  test/suites/tracing-tests/test-trace-1.ts
  test/suites/tracing-tests/test-trace-7.ts
Labels: B0-silent, D2-notlive

#3454 Upgrade `moonwall` to 5.15.0
  pnpm-lock.yaml
  test/package.json
Labels: B0-silent, D2-notlive

#3456 Fix smoke tests
  test/helpers/assets.ts
  test/suites/smoke/test-staking-rewards.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive, not-breaking

#3457 Fix flaky test
  test/suites/dev/moonbase/test-contract/test-contract-fibonacci.ts
Labels: B0-silent, I4-tests 🎯, D2-notlive

#3459 Update storage benchmarks
  runtime/moonbase/src/weights/db/rocksdb.rs
  runtime/moonbase/tests/integration_test.rs
  runtime/moonbeam/src/weights/db/rocksdb.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonriver/src/weights/db/rocksdb.rs
  runtime/moonriver/tests/integration_test.rs
  test/helpers/constants.ts
  test/suites/dev/common/test-xcm-v5/test-mock-hrmp-transact-ethereum-6.ts
  test/suites/dev/moonbase/test-assets/test-foreign-assets-xcm-costs.ts
  test/suites/dev/moonbase/test-crowdloan/test-crowdloan-democracy.ts
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-max.ts
  test/suites/dev/moonbase/test-fees/test-length-fees2.ts
  test/suites/dev/moonbase/test-pov/test-precompile-over-pov2.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-modexp.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery4.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery5.ts
  test/suites/dev/moonbase/test-staking/test-rewards-auto-compound-pov.ts
  test/suites/dev/moonbase/test-storage-growth/test-precompile-storage-growth.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-12.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-7.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-8.ts
Labels: B7-runtimenoteworthy, D3-trivial, breaking

#3464 Mute Equilibrium & Composable foreign chains check
  test/helpers/foreign-chains.ts
Labels: B0-silent, D2-notlive
