Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-07, with the labels that each got.

#3349 Update the client docker image to moonbeamfoundation/moonbeam:v0.46.0
  README.md
Labels: B0-silent, D3-trivial

#3353 Fix Typos in Documentation and Comments Across Multiple Modules
  node/service/src/lib.rs
  pallets/moonbeam-foreign-assets/src/lib.rs
  pallets/xcm-weight-trader/src/tests.rs
Labels: B0-silent, D2-notlive

#3301 Test that we can reach 7.5 MB in PoV.
  test/helpers/block.ts
  test/suites/dev/moonbase/test-pov/test-pov-limit.ts
Labels: B0-silent, D2-notlive, not-breaking
