Repository moonbeam-foundation/moonbeam, pull requests merged in 2025-03, with the labels that each got.

#3204 Default to new block import strategy
  node/cli/src/cli.rs
  node/cli/src/command.rs
  node/service/src/lib.rs
Labels: B5-clientnoteworthy, D2-notlive, breaking

#3203 fix(moonbeam, moonriver): support evm native foreign assets in xcm transactor
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/xcm_config.rs
  runtime/moonbeam/tests/common/mod.rs
  runtime/moonbeam/tests/integration_test.rs
  runtime/moonbeam/tests/xcm_mock/parachain.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/common/mod.rs
  runtime/moonriver/tests/integration_test.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking, evm-native-foreign-assets

#3210 Fix weight limits in evm tracing runtimes
  Cargo.lock
  client/evm-tracing/Cargo.toml
  client/evm-tracing/src/formatters/call_tracer.rs
  client/evm-tracing/src/formatters/trace_filter.rs
  client/rpc/trace/src/lib.rs
  runtime/common/src/apis.rs
  test/suites/tracing-tests/test-trace-filter-weight-limits.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3208 Add pallet-collective instances benchmarks to all runtimes
  .github/workflows/check-benchmarks.yml
  runtime/moonbase/src/governance/councils.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/weights/mod.rs
  runtime/moonbase/src/weights/pallet_collective.rs
  runtime/moonbase/src/weights/pallet_collective_open_tech_committee.rs
  runtime/moonbase/src/weights/pallet_collective_treasury_council.rs
  runtime/moonbeam/src/governance/councils.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/weights/mod.rs
  runtime/moonbeam/src/weights/pallet_collective.rs
  runtime/moonbeam/src/weights/pallet_collective_open_tech_committee.rs
  runtime/moonbeam/src/weights/pallet_collective_treasury_council.rs
  runtime/moonriver/src/governance/councils.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/weights/mod.rs
  runtime/moonriver/src/weights/pallet_collective.rs
  runtime/moonriver/src/weights/pallet_collective_open_tech_committee.rs
  runtime/moonriver/src/weights/pallet_collective_treasury_council.rs
  scripts/run-benches-for-runtime.sh
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3212 Apply frontier optimization to the Pending storage of pallet-ethereum
  Cargo.lock
  pallets/ethereum-xcm/src/tests/v1/eip1559.rs
  pallets/ethereum-xcm/src/tests/v1/eip2930.rs
  pallets/ethereum-xcm/src/tests/v1/legacy.rs
  pallets/ethereum-xcm/src/tests/v2.rs
  pallets/moonbeam-foreign-assets/src/benchmarks.rs
  runtime/moonbase/src/weights/pallet_moonbeam_foreign_assets.rs
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3216 Update publish-binary.yml
  .github/workflows/publish-binary.yml
Labels: B0-silent, ci, D2-notlive

#3219 temporarily disable lazy-loading tests
  .github/workflows/build.yml
  test/moonwall.config.json
  test/suites/lazy-loading/test-runtime-upgrade.ts
Labels: B0-silent, D2-notlive

#3221 Updated bug bounty MD file to reference immunefi
  bug-bounty.md
Labels: B0-silent, D2-notlive, not-breaking

#3218 Replace `TxPool` RPC with Frontier implementation
  Cargo.lock
  Cargo.toml
  client/rpc-core/txpool/Cargo.toml
  client/rpc-core/txpool/src/lib.rs
  client/rpc-core/txpool/src/types/content.rs
  client/rpc-core/txpool/src/types/inspect.rs
  client/rpc-core/txpool/src/types/mod.rs
  client/rpc/txpool/Cargo.toml
  client/rpc/txpool/src/lib.rs
  node/service/Cargo.toml
  node/service/src/rpc.rs
  test/suites/dev/moonbase/test-txpool/test-txpool-future.ts
  test/suites/dev/moonbase/test-txpool/test-txpool-pending.ts
  test/suites/dev/moonbase/test-txpool/test-txpool-pending2.ts
Labels: B5-clientnoteworthy, D2-notlive, breaking

#3217 Add frame system pallet benchmarking to all runtimes
  runtime/common/src/apis.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/weights/frame_system.rs
  runtime/moonbase/src/weights/mod.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonbeam/src/weights/frame_system.rs
  runtime/moonbeam/src/weights/mod.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/weights/frame_system.rs
  runtime/moonriver/src/weights/mod.rs
  test/suites/dev/moonbase/test-fees/test-fee-multiplier-max.ts
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3225 Deprecate `--experimental-block-import-strategy`
  node/cli/src/cli.rs
Labels: B0-silent, D2-notlive, not-breaking

#3226 Update frontier pin to include `eth_pendingTransactions` RPC
  Cargo.lock
  test/suites/dev/moonbase/test-eth-rpc/test-eth-rpc-pending-transactions.ts
  test/suites/dev/moonbase/test-eth-rpc/test-eth-rpc-transaction-receipt.ts
  test/suites/dev/moonbase/test-eth-rpc/test-eth-rpc-tx-index.ts
  test/suites/dev/moonbase/test-eth-rpc/test-eth-rpc-version.ts
Labels: B5-clientnoteworthy, D2-notlive, not-breaking

#3228 Enable 10 Mb PoV for moonbase and moonriver
  Cargo.lock
  precompiles/proxy/src/lib.rs
  runtime/moonbase/src/lib.rs
  runtime/moonbase/src/xcm_config.rs
  runtime/moonbase/tests/xcm_mock/parachain.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
  runtime/moonriver/src/xcm_config.rs
  runtime/moonriver/tests/xcm_mock/parachain.rs
  test/helpers/constants.ts
  test/helpers/xcm.ts
  test/suites/dev/moonbase/test-fees/test-length-fees2.ts
  test/suites/dev/moonbase/test-pov/test-evm-over-pov.ts
  test/suites/dev/moonbase/test-pov/test-evm-over-pov2.ts
  test/suites/dev/moonbase/test-pov/test-precompile-over-pov2.ts
  test/suites/dev/moonbase/test-pov/test-xcm-to-evm-pov.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-assets-erc20d.ts
  test/suites/dev/moonbase/test-precompile/test-precompile-proxy.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery2.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-babe-lottery3.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery4.ts
  test/suites/dev/moonbase/test-randomness/test-randomness-vrf-lottery5.ts
  test/suites/dev/moonbase/test-storage-growth/test-precompile-storage-growth.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-1.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-10.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-11.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-12.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-2.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-3.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-4.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-5.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-6.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-7.ts
  test/suites/dev/moonbase/test-xcm-v3/test-mock-hrmp-transact-ethereum-8.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-1.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-4.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-6.ts
  test/suites/dev/moonbase/test-xcm-v4/test-mock-hrmp-transact-ethereum-8.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-evm-with-dot.ts
  test/suites/dev/moonbase/test-xcm-v4/test-xcm-payment-api-transact-foreign.ts
Labels: B7-runtimenoteworthy, D5-nicetohaveaudit⚠️, breaking

#3230 Update frontier pins to enable using full gas limit when limit is reached
  Cargo.lock
Labels: B7-runtimenoteworthy, D3-trivial, not-breaking

#3234 Update the client docker image to moonbeamfoundation/moonbeam:v0.44.0
  README.md
Labels: B0-silent, D3-trivial

#3235 Update client version to 0.45.0
  Cargo.lock
  node/cli-opt/Cargo.toml
  node/cli/Cargo.toml
  node/service/Cargo.toml
Labels: B0-silent, D3-trivial

#3236 Update version to 0.45.0 in node/Cargo.toml
  Cargo.lock
  node/Cargo.toml
Labels: B0-silent, D2-notlive

#3240 Update runtime spec version to 3700
  runtime/moonbase/src/lib.rs
  runtime/moonbeam/src/lib.rs
  runtime/moonriver/src/lib.rs
Labels: B0-silent, D3-trivial
